(()=>{
const {table,flow}=CS.helpers;
CS.lessons['ch04-l01']={
 lead:'컴퓨터 안에는 0과 1만 있다는데, 어떻게 숫자 5와 글자 ‘가’와 사진을 서로 구별할까요?',
 goals:['비트·바이트와 이진수 자리값을 연결해요.','문자·코드 포인트·UTF-8 바이트를 구별해요.','정수·실수·이미지·소리의 표현 규칙과 한계를 설명해요.'],prerequisites:['ch01-l01'],sections:[
 {id:'b01',title:'한 칸은 두 상태, 여덟 칸은 256가지',html:`<p><strong>비트(bit)</strong>는 두 상태 중 하나를 나타내는 정보 단위예요. 흔히 0과 1로 적지만, 실제 장치에서는 전압·전하·자기 상태처럼 구별 가능한 물리 상태로 구현해요. <strong>바이트(byte)</strong>는 오늘날 거의 모든 범용 컴퓨터에서 8비트예요. 8개의 자리에 각각 두 선택이 있으니 <code>2⁸ = 256</code>가지 조합을 만들 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="bit-visual" aria-label="8비트 자리값 그림"><span data-on="true">128</span><span>64</span><span>32</span><span>16</span><span data-on="true">8</span><span>4</span><span data-on="true">2</span><span>1</span></div><figcaption><strong>비트열은 자리마다 무게가 달라요</strong><ul class="picture-key"><li><b>여덟 칸</b>한 바이트를 나타내요.</li><li><b>오른쪽부터 1·2·4…</b>왼쪽으로 갈수록 자리값이 두 배예요.</li><li><b>켜진 칸</b>자리값을 합해 숫자를 읽어요. 그림은 138이에요.</li></ul></figcaption></figure><p>표기는 소문자 <strong>b</strong>가 bit, 대문자 <strong>B</strong>가 byte인 경우가 많아요. 8 Mb와 8 MB는 여덟 배 차이예요. KB·MB·GB는 보통 1000배 단위이고, KiB·MiB·GiB는 1024배 단위예요.</p>`},
 {id:'b02',title:'이진수는 켜진 자리값을 더해 읽어요',html:`<p>8비트 부호 없는 정수의 자리값은 왼쪽부터 128, 64, 32, 16, 8, 4, 2, 1이에요. <code>00000101</code>은 4와 1이 켜져 있으므로 5예요. 아래 스위치는 표시만 바꾸는 그림이 아니라 브라우저가 합과 UTF-8 바이트를 실제로 계산해요.</p>`,lab:'bit-byte'},
 {id:'b03',title:'같은 비트열도 해석 규칙이 필요해요',html:`<p><code>01000001</code>은 부호 없는 수로 읽으면 65예요. ASCII라는 문자 부호화 규칙으로 읽으면 대문자 A예요. 비트열 자체에 ‘나는 숫자’ 또는 ‘나는 문자’라는 꼬리표가 붙는 것은 아니에요. 프로그램과 파일 형식이 어떤 규칙으로 읽을지 정해요.</p><figure class="teaching-figure concept-figure"><div class="encoding-visual" aria-label="문자에서 UTF-8 바이트로 가는 과정"><span class="char-card">가</span><span class="flow-arrow">→</span><span class="code-card">U+AC00</span><span class="flow-arrow">→</span><span class="byte-card">EA</span><span class="byte-card">B0</span><span class="byte-card">80</span></div><figcaption><strong>문자·코드 포인트·바이트는 서로 다른 단계예요</strong><ul class="picture-key"><li><b>가</b>사람이 읽는 문자예요.</li><li><b>U+AC00</b>유니코드가 정한 코드 포인트예요.</li><li><b>EA B0 80</b>UTF-8로 저장·전송하는 세 바이트예요.</li></ul></figcaption></figure><p><strong>유니코드</strong>는 문자에 코드 포인트를 정하고, <strong>UTF-8</strong>은 그 코드 포인트를 1~4바이트로 바꾸는 인코딩 형식이에요. A는 UTF-8에서 1바이트, ‘가’는 3바이트예요. 한글이 ‘차별적으로 더 큰 칸을 배정받았다’기보다 코드 포인트 범위에 따라 같은 가변 길이 규칙을 적용한 결과예요.</p><div class="info">화면에서 보이는 글자 하나, 유니코드 코드 포인트 하나, JavaScript 문자열 길이, UTF-8 바이트 수는 서로 다를 수 있어요. 결합 문자나 가족 이모지처럼 여러 코드 포인트가 한 글자처럼 보이는 예도 있어요.</div>`},
 {id:'b04',title:'정수와 실수는 범위와 정밀도를 맞바꿔요',html:`<p>8비트 부호 없는 정수는 0~255를 표현해요. 같은 8비트를 보통의 2의 보수 부호 있는 정수로 해석하면 -128~127이에요. 음수는 단순히 맨 앞 비트만 떼어 읽는 방식보다 전체 비트열의 2의 보수 규칙으로 이해하는 편이 정확해요.</p>${table(['표현','같은 8비트 예','읽는 값'],[['부호 없는 정수','11111111','255'],['2의 보수 부호 있는 정수','11111111','-1'],['문자 인코딩의 한 바이트','11111111','ASCII 문자가 아니며 UTF-8 단독 바이트로도 유효하지 않음']])}<p>JavaScript의 일반 <code>Number</code>는 IEEE 754 배정밀도 형식의 값을 표현해요. 0.1과 0.2는 이진 유한 소수로 정확히 담기지 않아 <code>0.1 + 0.2</code>가 정확한 0.3과 같지 않을 수 있어요. 컴퓨터가 계산을 ‘틀린’ 것이 아니라 선택한 유한 정밀도 표현에서 가장 가까운 값을 사용한 결과예요.</p><details class="more"><summary>더 알아보기 · 오버플로와 정확한 계산</summary><div class="more-body"><p>고정된 비트 수의 범위를 넘는 계산은 언어와 자료형 규칙에 따라 되감기, 오류, 더 큰 형식 사용 등으로 처리할 수 있어요. JavaScript의 Number와 이 단원의 8비트 스위치 모형을 같은 범위로 생각하면 안 돼요.</p><p>돈처럼 십진 소수의 정확한 규칙이 중요한 값은 가장 작은 화폐 단위의 정수로 저장하거나, 해당 언어의 십진 자료형·라이브러리를 검토해요.</p></div></details>`},
 {id:'b05',title:'사진은 픽셀, 소리는 시간별 표본으로 바꿔요',html:`<p>비트맵 이미지는 화면을 작은 <strong>픽셀</strong>로 나누고 각 픽셀의 색을 숫자로 표현해요. RGB라면 빨강·초록·파랑 성분을 각각 저장해요. 벡터 이미지는 점·선·곡선 같은 도형 명령을 저장해 확대할 때 다른 방식으로 그려요.</p><figure class="teaching-figure concept-figure"><div class="media-visual" aria-label="이미지와 오디오를 표본으로 나누는 그림"><div class="mini-pixels">${Array.from({length:36},(_,i)=>`<span style="--i:${i}"></span>`).join('')}</div><div class="sample-wave">${[20,42,64,38,18,50,72,44,26,58,35,16].map(v=>`<i style="height:${v}%"></i>`).join('')}</div></div><figcaption><strong>연속된 대상을 작은 표본들의 수로 바꿔요</strong><ul class="picture-key"><li><b>왼쪽 격자</b>위치별 색 숫자를 가진 픽셀이에요.</li><li><b>오른쪽 막대</b>일정한 시간 간격으로 잰 소리의 크기를 떠올려요.</li><li><b>표본 수와 정밀도</b>늘리면 더 많은 정보를 담지만 데이터도 커져요.</li></ul></figcaption></figure><p>동영상은 시간에 따른 여러 영상 프레임과 소리 등을 컨테이너에 담아요. MP4 같은 컨테이너와 H.264·AV1 같은 영상 코덱은 같은 분류가 아니에요. 압축은 반복이나 사람이 덜 민감한 정보를 이용하지만, 결과 크기는 내용과 설정에 따라 달라져요.</p>`,lab:'pixel-size'},
 {id:'b06',title:'파일 형식은 바이트를 읽는 약속이에요',html:`<p>파일 확장자는 사람이 형식을 짐작하게 돕지만, 실제로는 바이트 배열의 구조·헤더·메타데이터·인코딩 규칙을 함께 읽어야 해요. 이름만 <code>.png</code>로 바꾼다고 JPEG 바이트가 PNG로 변환되지는 않아요.</p>${flow(['현실의 문자·빛·소리','표본과 코드 포인트','숫자','비트와 바이트','파일 형식이 구조를 설명'])}<p>이제 같은 데이터를 어떤 순서와 연결 규칙으로 놓아야 빠르게 찾고 바꿀 수 있는지 살펴볼 거예요. 다음 소단원의 자료구조가 그 역할을 맡아요.</p>`}
 ],questions:[
 {q:'8비트 부호 없는 수 00000101을 십진수로 읽으면?',options:['3','5','101'],answer:1,feedback:['켜진 자리값은 4와 1이에요.','맞아요. 4 + 1 = 5예요.','이진수 표기를 십진수 글자 101로 읽지 않아요.'],review:'b02'},
 {q:'UTF-8에서 A는 1바이트, ‘가’는 3바이트예요. 가장 정확한 설명은?',options:['유니코드가 모든 문자를 언제나 3바이트로 저장해요.','UTF-8이 코드 포인트 범위에 따라 1~4바이트 규칙을 적용해요.','한글은 컴퓨터에서 비트로 표현할 수 없어요.'],answer:1,feedback:['유니코드의 코드 포인트와 UTF-8 바이트를 구별해요.','맞아요. 같은 UTF-8 가변 길이 규칙을 적용한 결과예요.','‘가’도 EA B0 80이라는 비트·바이트로 표현할 수 있어요.'],review:'b03'},
 {q:'8×8 RGB 그림의 압축 전 색상 데이터는 몇 바이트일까요? 픽셀당 3바이트로 가정해요.',options:['24바이트','64바이트','192바이트'],answer:2,feedback:['가로×세로×픽셀당 바이트를 모두 곱해요.','64는 픽셀 수예요.','맞아요. 8×8×3 = 192바이트예요.'],review:'b05'}
 ],summary:['비트열의 의미는 자리값·자료형·인코딩·파일 형식 같은 해석 규칙이 정해요.','유니코드 코드 포인트와 UTF-8 바이트, 보이는 글자 수를 구별해요.','멀티미디어는 표본을 숫자로 표현하며 원시 데이터 크기와 압축 파일 크기는 달라요.'],nextQuestion:'같은 값들을 빠르게 찾고 순서대로 꺼내려면 어떤 구조로 놓아야 할까요?',sources:[['Unicode Consortium · UTF 인코딩 FAQ','https://www.unicode.org/faq/utf_bom.html'],['Unicode Consortium · 문자와 결합 문자 FAQ','https://www.unicode.org/faq/char_combmark.html'],['ECMAScript 2024 · Number 타입','https://tc39.es/ecma262/2024/#sec-ecmascript-language-types-number-type']]
};
CS.lessons['ch04-l02']={
 lead:'같은 A·B·C를 저장해도, 놓는 방법이 달라지면 찾고 넣고 꺼내는 방법이 달라져요.',
 goals:['배열·연결 리스트·동적 배열의 저장과 접근을 비교해요.','스택·큐·덱의 허용 연산과 출력 순서를 예측해요.','해시 테이블의 충돌과 Set의 중복 규칙을 설명해요.'],prerequisites:['ch04-l01'],sections:[
 {id:'b01',title:'자료구조는 값을 놓고 꺼내는 규칙이에요',html:`<p><strong>자료구조</strong>는 데이터를 저장하고 관계를 표현하며 접근·추가·제거하는 규칙의 묶음이에요. 같은 값도 어떤 연산을 자주 하는지에 따라 알맞은 구조가 달라져요. ‘항상 가장 빠른 자료구조’는 없어요.</p><figure class="teaching-figure concept-figure"><div class="array-list-visual" aria-label="배열과 연결 리스트의 구조 비교"><div><strong>배열</strong><span>A</span><span>B</span><span>C</span><span>D</span></div><div><strong>연결 리스트</strong><span>A</span><i>→</i><span>B</span><i>→</i><span>C</span><i>→</i><span>D</span></div></div><figcaption><strong>순서가 있어도 저장·이동 규칙은 달라요</strong><ul class="picture-key"><li><b>붙어 있는 배열 칸</b>인덱스로 원하는 위치를 바로 계산해요.</li><li><b>연결된 노드</b>다음 참조를 따라 순서대로 이동해요.</li><li><b>공통점</b>둘 다 논리적인 순서를 유지할 수 있어요.</li></ul></figcaption></figure><p>선형 자료구조는 항목을 한 줄의 순서로 다루는 관점이고, 트리·그래프는 계층이나 여러 연결을 표현하는 비선형 구조예요. 메모리 주소가 물리적으로 붙어 있는지와 ‘선형’이라는 분류는 같은 질문이 아니에요.</p>`},
 {id:'b02',title:'배열은 인덱스로, 연결 리스트는 링크를 따라가요',html:`<p>배열은 같은 크기의 칸을 연속된 영역에 놓아 <code>시작 위치 + 인덱스 × 칸 크기</code>로 원하는 칸을 계산할 수 있어요. 가운데에 새 값을 넣으려면 뒤 항목을 옮길 수 있어요. 연결 리스트는 각 노드가 다음 노드의 참조를 저장하므로, 중간 노드를 이미 알고 있을 때 연결만 바꿔 삽입할 수 있어요.</p>${table(['연산','배열','단일 연결 리스트'],[['인덱스 i 읽기','O(1)','머리부터 따라가면 O(n)'],['끝에 추가','빈 용량이 있으면 O(1)','꼬리 참조가 있으면 O(1)'],['가운데 삽입','뒤 항목 이동 때문에 O(n)','위치를 찾는 데 O(n), 위치를 이미 알면 연결 변경 O(1)'],['앞에서 제거','뒤 항목 이동 때문에 O(n)','머리 참조 변경 O(1)']])}<div class="info">연결 리스트도 순서를 유지해요. ‘메모리에서 연속 배치가 아니다’를 ‘순서가 없다’로 바꾸어 말하면 안 돼요. 실제 속도는 캐시 지역성·할당 비용·구현과 입력 크기에도 영향을 받아요.</div>`},
 {id:'b03',title:'동적 배열은 여유 용량을 두고 커져요',html:`<p>동적 배열은 내부에 배열을 사용하되, 항목 수(<strong>size</strong>)와 현재 배열의 칸 수(<strong>capacity</strong>)를 따로 관리해요. 빈 칸이 있으면 끝에 바로 추가하고, 가득 차면 더 큰 배열을 만들고 기존 항목을 복사해요.</p><figure class="teaching-figure concept-figure"><div class="capacity-visual" aria-label="동적 배열이 더 큰 배열로 확장되는 그림"><div><span>A</span><span>B</span><span>C</span><span>D</span></div><b>복사</b><div class="grown"><span>A</span><span>B</span><span>C</span><span>D</span><span class="empty">·</span><span class="empty">·</span><span class="empty">·</span><span class="empty">·</span></div></div><figcaption><strong>매번 늘리지 않고 가끔 크게 복사해요</strong><ul class="picture-key"><li><b>위 4칸</b>size와 capacity가 모두 4인 가득 찬 상태예요.</li><li><b>아래 8칸</b>더 큰 저장 공간의 예예요.</li><li><b>빈 네 칸</b>앞으로 여러 번의 끝 추가를 빠르게 만들 여유예요.</li></ul></figcaption></figure><p>가끔 O(n) 복사가 생겨도 여러 번의 끝 추가에 비용을 나누어 보면 평균적으로 <strong>상각 O(1)</strong>이 될 수 있어요. 성장 배율은 구현 세부사항이에요. Java의 ArrayList를 언제나 1.5배, 모든 언어의 vector를 언제나 2배라고 일반화하지 않아요. Java의 Vector는 ArrayList와 ‘차이가 전혀 없는’ 클래스도 아니며 동기화 정책이 달라요.</p>`},
 {id:'b04',title:'스택·큐·덱은 사용할 수 있는 끝을 정해요',html:`<p><strong>스택</strong>은 마지막에 넣은 값을 먼저 꺼내는 LIFO, <strong>큐</strong>는 먼저 넣은 값을 먼저 꺼내는 FIFO 규칙이에요. <strong>덱(deque)</strong>은 양쪽 끝에서 넣고 뺄 수 있어요. 이것들은 내부 저장 방식과 별개인 <strong>추상 자료형</strong>으로 볼 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="ends-visual" aria-label="스택과 큐의 입출력 끝 비교"><div><strong>스택</strong><span>A</span><span>B</span><span>C</span><i>↕</i></div><div><strong>큐</strong><i>출력 ←</i><span>A</span><span>B</span><span>C</span><i>← 입력</i></div></div><figcaption><strong>같은 세 값에서 다음 출력이 달라요</strong><ul class="picture-key"><li><b>스택의 한쪽 끝</b>C를 먼저 꺼내요.</li><li><b>큐의 서로 다른 끝</b>A를 먼저 꺼내요.</li><li><b>덱</b>왼쪽 또는 오른쪽을 연산마다 고를 수 있어요.</li></ul></figcaption></figure>`,lab:'stack-queue'},
 {id:'b05',title:'해시는 키를 버킷 후보로 보내요',html:`<p><strong>해시 함수</strong>는 키를 계산해 해시 값을 만들고, 해시 테이블은 그 값으로 저장할 버킷 후보를 정해요. 서로 다른 키가 같은 버킷 후보를 얻는 <strong>충돌</strong>은 오류가 아니라 반드시 처리해야 하는 정상 상황이에요.</p><figure class="teaching-figure concept-figure"><div class="hash-visual" aria-label="서로 다른 키가 같은 버킷에 충돌하는 그림"><span>A</span><span>E</span><i>→ 해시 →</i><div><b>0</b><b>1 · A · E</b><b>2</b><b>3</b></div></div><figcaption><strong>버킷이 같아도 원래 키를 다시 비교해요</strong><ul class="picture-key"><li><b>A와 E</b>서로 다른 키예요.</li><li><b>같은 버킷 1</b>교육용 함수에서 충돌했어요.</li><li><b>둘 다 보관</b>체이닝 같은 충돌 해결 규칙이 필요해요.</li></ul></figcaption></figure><p>체이닝은 버킷마다 여러 항목을 연결하고, 개방 주소 방식은 다른 빈 버킷을 찾아요. 좋은 분산과 적절한 용량에서 평균 조회가 O(1)에 가까울 수 있지만, 충돌이 몰린 최악의 경우까지 언제나 O(1)이라는 뜻은 아니에요.</p>`,lab:'hash-buckets'},
 {id:'b06',title:'Set은 중복 없음이라는 약속이에요',html:`<p><strong>Set</strong>은 같은 값을 하나만 유지하는 추상 자료형이에요. HashSet은 해시 테이블을, TreeSet은 정렬 트리를 사용하는 식으로 구현에 따라 순서와 비용이 달라질 수 있어요. 그래서 ‘Set은 언제나 순서가 없다’보다 <strong>일반 Set 인터페이스만으로 특정 순서를 기대하지 않는다</strong>고 이해하는 편이 안전해요.</p>${table(['필요','어울리는 시작점','확인할 점'],[['인덱스로 자주 읽기','배열·동적 배열','가운데 삽입·삭제 비용'],['최근 작업 되돌리기','스택','마지막 값만 먼저 꺼내도 되는지'],['도착 순서대로 처리','큐','과부하 때 큐 한도와 거절 정책'],['양쪽 끝에서 처리','덱','중간 임의 접근이 필요한지'],['키로 값 찾기','Map·해시 테이블','충돌·메모리·최악 성능'],['중복 없는 포함 여부','Set','순서가 필요한지와 구현 종류']])}<p>자료구조 이름부터 고르기보다 자주 하는 연산, 데이터 크기, 필요한 순서와 중복 규칙을 먼저 적어 보세요. 다음 대단원에서는 이 선택이 시간과 공간을 얼마나 사용하는지 계산해요.</p>`}
 ],questions:[
 {q:'A, B, C를 차례로 넣은 뒤 하나를 꺼낼 때 스택과 큐의 결과는?',options:['스택 A · 큐 C','스택 C · 큐 A','둘 다 B'],answer:1,feedback:['스택은 마지막, 큐는 첫 항목을 꺼내요.','맞아요. LIFO와 FIFO의 차이예요.','가운데 B를 직접 꺼내는 것은 이 두 규칙의 기본 연산이 아니에요.'],review:'b04'},
 {q:'동적 배열의 size가 4, capacity가 8이라는 뜻은?',options:['항목 8개가 모두 들어 있어요.','항목 4개와 아직 쓸 수 있는 내부 칸 4개가 있어요.','연결 리스트 노드가 8개예요.'],answer:1,feedback:['capacity는 실제 항목 수와 구별해요.','맞아요. 여유 용량 덕분에 다음 끝 추가는 복사 없이 가능할 수 있어요.','동적 배열은 내부 배열을 사용해요.'],review:'b03'},
 {q:'서로 다른 키가 같은 해시 버킷 후보를 얻었어요. 가장 알맞은 처리는?',options:['항상 먼저 넣은 키를 삭제해요.','충돌 해결 규칙으로 둘을 보관하고 원래 키도 비교해요.','두 키가 같은 값이라고 선언해요.'],answer:1,feedback:['기존 값을 조용히 잃으면 Map이 올바르게 동작하지 않아요.','맞아요. 충돌은 예상하고 처리하는 상황이에요.','같은 해시 값이 같은 키를 뜻하지 않아요.'],review:'b05'}
 ],summary:['자료구조는 저장 모양과 허용 연산을 함께 정하며, 연산 요구에 따라 선택해요.','배열·연결 리스트·동적 배열의 접근과 삽입 비용은 조건에 따라 달라져요.','스택·큐·덱의 끝 규칙과 해시 충돌·Set 중복 규칙을 구별해요.'],nextQuestion:'자료구조가 쓰는 칸 수와 작업 횟수는 입력이 커질 때 어떻게 늘어날까요?',sources:[['Oracle Java · ArrayList API','https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/util/ArrayList.html'],['Oracle Java · List 구현 비교','https://docs.oracle.com/javase/tutorial/collections/implementations/list.html'],['Python 문서 · deque','https://docs.python.org/3/library/collections.html#collections.deque'],['Python 문서 · Set','https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset']]
};
})();

