(()=>{
const {table,flow}=CS.helpers;
CS.lessons['ch05-l01']={
 lead:'재료가 열 배로 늘면 그릇도 열 배가 필요할까요? 프로그램도 무엇을 보관하느냐에 따라 필요한 공간의 증가가 달라져요.',
 goals:['저장장치의 용량과 알고리즘의 공간 사용을 구별해요.','입력 공간과 추가 작업 공간을 나누어 계산해요.','O(1)·O(n)·O(n²) 공간 증가와 실제 바이트 계산을 연결해요.'],prerequisites:['ch04-l02'],sections:[
 {id:'b01',title:'공간 자원은 서로 다른 층에 있어요',html:`<p>컴퓨터는 레지스터·캐시·주 기억장치·보조 기억장치처럼 성질이 다른 저장 공간을 사용해요. 앞 단원에서 배운 계층을 이번에는 <strong>용량과 사용량</strong>의 관점으로 다시 봐요. 저장장치를 더 크게 사는 일과, 같은 문제를 더 적은 작업 공간으로 푸는 일은 서로 다른 해결책이에요.</p><figure class="teaching-figure concept-figure"><div class="space-hierarchy-visual" aria-label="작고 가까운 저장 공간부터 크고 먼 저장 공간까지의 계층"><span class="cpu-dot"></span><span class="shelf tiny"></span><span class="shelf small"></span><span class="shelf medium"></span><span class="shelf large"></span></div><figcaption><strong>CPU에 가까운 작은 공간부터 큰 저장 공간까지</strong><ul class="picture-key"><li><b>안쪽의 작은 칸</b>레지스터와 캐시를 떠올려요.</li><li><b>가운데 선반</b>실행 중인 데이터가 놓이는 주 기억장치예요.</li><li><b>바깥 큰 선반</b>전원이 꺼져도 파일을 보관하는 저장장치예요.</li></ul></figcaption></figure><p>프로그램 파일은 저장장치에 있다가 실행할 때 필요한 코드와 데이터가 메모리에 올라와요. 실제 시스템에서는 계층 사이로 데이터가 이동하며, 모든 종류의 메모리를 한 숫자의 ‘공간’으로 합치면 병목과 한계를 놓치기 쉬워요.</p>`},
 {id:'b02',title:'값의 개수에 칸의 크기를 곱해요',html:`<p>먼저 크기가 고정된 단순 모형으로 계산해 봅시다. 정수 하나를 4B로 정하면 10개는 <code>10 × 4B = 40B</code>, 100개는 400B예요. 이 계산은 값이 놓인 칸만 세며 배열의 부가 정보와 실행 환경의 비용을 생략해요.</p><figure class="teaching-figure concept-figure"><div class="array-space-visual" aria-label="같은 크기의 값 칸이 입력 수에 따라 늘어나는 그림"><div class="short-row">${Array.from({length:5},()=>'<span></span>').join('')}</div><div class="long-row">${Array.from({length:10},()=>'<span></span>').join('')}</div></div><figcaption><strong>같은 크기의 값은 개수가 두 배면 값 저장 공간도 두 배예요</strong><ul class="picture-key"><li><b>윗줄 다섯 칸</b>고정 폭 값 다섯 개예요.</li><li><b>아랫줄 열 칸</b>같은 값 형식을 두 배 담아요.</li><li><b>주의</b>실제 객체 전체 크기를 재는 그림은 아니에요.</li></ul></figcaption></figure>`,lab:'space-growth'},
 {id:'b03',title:'입력 공간과 보조 공간을 따로 세어요',html:`<p>이미 주어진 배열의 합계를 구한다고 해 볼게요. 입력 배열은 문제를 표현하는 공간이에요. 배열 전체를 하나 더 복사하면 입력 크기 n에 비례하는 <strong>보조 공간 O(n)</strong>이 필요하지만, 합계 변수 하나만 유지하면 추가 공간은 <strong>O(1)</strong>이에요.</p><figure class="teaching-figure concept-figure"><div class="copy-space-visual" aria-label="전체 복사본과 한 개의 누산 변수 비교"><div class="copy-pair"><span>${Array.from({length:7},()=>'<i></i>').join('')}</span><span>${Array.from({length:7},()=>'<i></i>').join('')}</span></div><div class="sum-token"><b></b></div></div><figcaption><strong>같은 입력도 처리 방법에 따라 추가 공간이 달라져요</strong><ul class="picture-key"><li><b>두 줄의 같은 블록</b>입력과 전체 복사본이에요.</li><li><b>작은 금색 한 칸</b>합계 변수 하나만 쓰는 방법이에요.</li><li><b>비교 기준</b>입력 자체와 새로 만든 공간을 구별해요.</li></ul></figcaption></figure><p>‘이 알고리즘의 공간 복잡도는 O(n)’이라고만 쓰면 입력까지 센 것인지, 입력 외의 보조 공간만 센 것인지 애매할 수 있어요. 분석에서 무엇을 포함했는지 먼저 밝혀야 해요. 출력 크기를 반드시 만들어야 하는 문제라면 출력 공간을 별도로 적기도 해요.</p>`},
 {id:'b04',title:'Big-O는 큰 입력에서 증가하는 모양을 말해요',html:`<p>점근 표기법은 n이 커질 때 필요한 자원이 어떤 함수의 비율로 증가하는지 설명해요. 상수 여러 개를 쓰는 반복문은 O(1) 추가 공간, 길이 n 배열 하나는 O(n), n×n 격자는 O(n²)이에요. <code>4n + 20</code>칸과 <code>100n + 3</code>칸은 모두 선형으로 자라므로 O(n)으로 묶을 수 있어요.</p>${table(['추가로 만드는 것','n=10의 단순 칸 수','증가 분류'],[['변수 3개','3','O(1)'],['n개짜리 복사 배열','10','O(n)'],['n×n 표','100','O(n²)'],['깊이 n의 재귀 호출 스택','호출당 일정한 프레임 × 10','O(n)']])}<div class="info"><strong>Big-O·Ω·Θ와 최악·평균·최선은 같은 구분이 아니에요.</strong> O는 점근적 상한, Ω는 하한, Θ는 위아래가 같은 차수인 경계를 말해요. 어떤 입력 경우를 분석했는지는 별도로 밝혀요.</div>`},
 {id:'b05',title:'보이지 않게 하는 것과 저장하지 않는 것은 달라요',html:`<p>채팅 화면에서 오래된 메시지를 숨겨도 목록에 계속 보관하면 저장 공간은 계속 늘 수 있어요. 최근 20개만 필요하다면 새 항목을 넣을 때 가장 오래된 항목의 참조를 목록에서 실제로 제거해야 저장한 항목 수에 상한을 둘 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="ring-buffer-visual" aria-label="고정된 원형 보관함에서 가장 오래된 항목이 나가고 새 항목이 들어오는 그림">${Array.from({length:8},(_,i)=>`<span style="--slot:${i}"></span>`).join('')}<i class="old-slot"></i><b class="new-slot"></b></div><figcaption><strong>용량이 찬 뒤에는 새 항목과 가장 오래된 항목을 교대해요</strong><ul class="picture-key"><li><b>고정된 여덟 자리</b>보관할 수 있는 상한을 뜻해요.</li><li><b>바깥으로 나온 회색 칸</b>가장 오래되어 제거된 항목이에요.</li><li><b>새 파란 칸</b>비워진 자리를 이어서 사용해요.</li></ul></figcaption></figure>`,lab:'bounded-buffer'},
 {id:'b06',title:'실제 한계에서는 바이트와 표현 범위를 함께 봐요',html:`<p>Big-O가 같아도 실제 필요한 메모리는 자료형·배치·객체 머리 정보·참조 크기·정렬·런타임에 따라 달라져요. <code>boolean</code> 하나가 논리적으로 한 비트이면 충분하다는 사실만으로, 어떤 언어의 배열 원소가 실제로 정확히 한 비트를 쓴다고 단정할 수는 없어요.</p>${table(['질문','확인할 것'],[['값 하나가 표현 가능한가?','부호·범위·정밀도·오버플로'],['값 n개가 공간에 들어가는가?','원소 크기×개수와 부가 비용'],['재귀가 너무 깊지 않은가?','호출마다 쌓이는 스택 프레임과 실행 환경의 한도'],['객체가 계속 남는가?','더는 필요하지 않은 참조를 유지하는지'],['메모리 제한을 지키는가?','문제·서비스·장치가 실제로 허용한 수치']])}<p>‘512MB면 언제나 정수 몇 개’ 같은 고정 암기보다, 그 환경의 자료형 크기와 제한을 확인하고 여유를 두어 계산하세요. 쓰지 않는 객체에 도달하는 참조를 제거해도 자동 메모리 회수 시점은 런타임이 정할 수 있어요.</p>`}
 ],questions:[
 {q:'4B 정수 10개가 이미 입력으로 있고, 같은 크기의 복사본을 하나 만들어요. 이 모형에서 입력과 보조 공간은?',options:['입력 40B · 보조 40B','입력 10B · 보조 4B','입력 40B · 보조 4B'],answer:0,feedback:['맞아요. 10×4B를 입력과 복사본에 각각 계산해요.','원소 수와 바이트를 구별해요.','4B 보조 공간은 합계 변수 하나만 쓰는 방법이에요.'],review:'b02'},
 {q:'입력 배열은 이미 있고 합계 변수 하나만 추가로 사용해요. 보조 공간의 증가 분류는?',options:['O(1)','O(n)','O(n²)'],answer:0,feedback:['맞아요. 입력 n과 상관없이 추가 변수 수가 일정해요.','입력 배열까지 세는 기준과 추가 공간만 세는 기준을 구별해요.','n×n개의 새 칸을 만들지 않아요.'],review:'b03'},
 {q:'최근 20개만 화면에 보이지만 저장 목록에는 모든 메시지가 남아 있어요. 공간 사용은?',options:['항상 20개로 제한돼요.','메시지가 늘수록 계속 증가할 수 있어요.','화면이 작으면 자동으로 O(1)이 돼요.'],answer:1,feedback:['보이는 개수와 저장한 개수는 달라요.','맞아요. 목록에서 오래된 항목을 실제로 제거해야 상한을 둘 수 있어요.','화면 크기가 저장 목록의 참조를 없애 주지는 않아요.'],review:'b05'}
 ],summary:['공간 계층의 용량과 알고리즘의 공간 증가는 서로 다른 질문이에요.','입력·출력·보조 공간 중 무엇을 세었는지 밝히고, 실제 바이트와 증가 차수를 함께 봐요.','보이지 않게 숨기는 것과 더는 저장하지 않는 것을 구별해요.'],nextQuestion:'같은 문제를 풀 때 작업 횟수는 입력이 커질수록 어떻게 달라질까요?',sources:[['MIT OpenCourseWare · 점근적 복잡도','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/c6d8f06c6f11e3342633dec85498f551_MIT6_006S20_r01.pdf'],['MDN · JavaScript 메모리 관리','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Memory_management'],['OSTEP · 메모리 가상화와 관리','https://pages.cs.wisc.edu/~remzi/OSTEP/']]
};

CS.lessons['ch05-l02']={
 lead:'같은 값을 찾아도 왼쪽부터 하나씩 볼 수도 있고, 가운데를 골라 후보를 절반씩 줄일 수도 있어요.',
 goals:['측정한 실행 시간과 연산 횟수의 증가를 구별해요.','순차 탐색과 이진 탐색을 한 단계씩 비교해요.','시간·공간의 교환과 네트워크 지연을 계산해요.'],prerequisites:['ch05-l01'],sections:[
 {id:'b01',title:'느리다는 말부터 구간으로 나누어요',html:`<p>웹 요청이 늦을 때 CPU 계산, 메모리·저장장치 접근, 네트워크 왕복, 서버 대기 중 어디에서 시간을 썼는지 나누어 봐야 해요. 하나의 ‘컴퓨터 속도’만으로 전체 지연을 설명하기는 어려워요.</p><figure class="teaching-figure concept-figure"><div class="latency-path-visual" aria-label="계산과 메모리 접근과 네트워크 대기가 이어지는 시간 구간"><span class="compute"></span><i></i><span class="memory"></span><i></i><span class="network"></span><i></i><span class="response"></span></div><figcaption><strong>응답 시간에는 서로 다른 종류의 기다림이 이어져요</strong><ul class="picture-key"><li><b>첫 구간</b>CPU가 계산하는 시간이에요.</li><li><b>가운데 구간</b>메모리·저장장치와 네트워크를 기다려요.</li><li><b>마지막 구간</b>결과가 사용자에게 도착해요.</li></ul></figcaption></figure><p><strong>지연 시간(latency)</strong>은 한 요청이나 데이터가 완료되기까지 걸린 시간이고, <strong>처리량(throughput)</strong>은 단위 시간에 처리한 양이에요. 처리량이 커져도 개별 요청의 왕복 지연이 자동으로 0이 되지는 않아요.</p>`},
 {id:'b02',title:'초시계와 작업 횟수는 다른 질문이에요',html:`<p>실제 실행 시간은 CPU·언어·컴파일러·다른 작업·캐시 상태·입력 내용에 영향을 받아요. 그래서 알고리즘을 비교할 때는 먼저 입력 크기 n에 따라 핵심 연산의 횟수가 어떻게 증가하는지 세어요. 이번 탐색에서는 <strong>목표값과 비교한 사건</strong>을 한 번으로 정해요.</p>${table(['증가 모양','n이 두 배가 될 때의 대표 변화','예'],[['O(1)','일정한 상한 안에 머묾','배열의 유효한 인덱스 한 곳 읽기'],['O(log n)','대략 일정한 단계만 추가','정렬된 배열의 이진 탐색'],['O(n)','대략 두 배','끝까지 가는 순차 탐색'],['O(n log n)','두 배보다 조금 더 증가','비교 기반 정렬의 흔한 효율 범위'],['O(n²)','대략 네 배','n×n쌍을 모두 비교']])}<p>상수와 낮은 차수 항을 생략하는 것은 실제 차이가 없다는 뜻이 아니에요. 작은 입력에서는 초기 준비 비용이나 구현 차이가 더 클 수 있어요. Big-O만으로 특정 컴퓨터에서 몇 초가 걸릴지 계산할 수도 없어요.</p>`},
 {id:'b03',title:'순차 탐색은 앞에서부터 비교해요',html:`<p>순차 탐색은 현재 항목이 목표인지 확인하고, 다르면 다음 항목으로 이동해요. 정렬되지 않은 목록에서도 사용할 수 있지만, 목표가 마지막에 있거나 없다면 n개를 모두 확인할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="linear-search-visual" aria-label="왼쪽부터 마지막까지 차례로 상자를 확인하는 순차 탐색">${Array.from({length:12},(_,i)=>`<span class="${i<11?'visited':'target'}"></span>`).join('')}<b></b></div><figcaption><strong>왼쪽부터 한 칸씩 확인해 마지막에 도착했어요</strong><ul class="picture-key"><li><b>회색으로 지난 칸</b>이미 목표와 비교한 항목이에요.</li><li><b>마지막 파란 칸</b>이번 예시의 목표예요.</li><li><b>검사 막대</b>한 단계에 한 항목을 비교해요.</li></ul></figcaption></figure>`,lab:'search-compare'},
 {id:'b04',title:'이진 탐색은 정렬된 후보를 절반씩 줄여요',html:`<p>이진 탐색은 남은 구간의 가운데 값을 목표와 비교해요. 목표가 더 크면 왼쪽 절반을, 더 작으면 오른쪽 절반을 제외해요. <strong>값이 순서대로 정렬되어 있어야</strong> 비교 결과로 어느 절반을 버릴지 알 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="binary-search-visual" aria-label="후보 구간이 절반씩 줄어드는 이진 탐색"><div>${Array.from({length:16},()=>'<span></span>').join('')}</div><div>${Array.from({length:8},()=>'<span></span>').join('')}</div><div>${Array.from({length:4},()=>'<span></span>').join('')}</div><div>${Array.from({length:2},()=>'<span></span>').join('')}</div><div><span class="found"></span></div></div><figcaption><strong>한 번 비교할 때마다 남은 구간이 절반 가까이 줄어요</strong><ul class="picture-key"><li><b>첫 줄 열여섯 칸</b>처음 후보 전체예요.</li><li><b>아래로 갈수록</b>비교 결과로 한쪽 절반을 제외해요.</li><li><b>마지막 한 칸</b>목표를 찾거나 후보가 없어지면 끝나요.</li></ul></figcaption></figure><p>기본 실습의 1~16에서 16을 찾으면 순차 탐색은 16회, 이진 탐색은 5회 비교해요. 목록을 새로 정렬해야 한다면 그 정렬 비용도 전체 작업에 포함해야 해요.</p>`},
 {id:'b05',title:'자료구조의 비용에는 조건이 붙어요',html:`<p>앞 단원의 표에 시간 비용을 붙일 때는 어떤 연산인지와 어떤 조건인지 함께 적어야 해요. ‘연결 리스트 삽입 O(1)’은 삽입할 위치의 노드를 이미 알고 연결만 바꾸는 경우예요. 머리부터 그 위치를 찾아야 한다면 탐색에 O(n)이 들 수 있어요.</p>${table(['작업','대표 비용','필요한 조건'],[['배열 인덱스 읽기','O(1)','유효한 인덱스와 고정 폭 위치 계산'],['동적 배열 끝 추가','상각 O(1)','가끔 생기는 전체 복사 비용을 여러 추가에 나눔'],['연결 리스트 중간 삽입','연결 변경 O(1)','삽입 위치 노드를 이미 알고 있음'],['해시 테이블 조회','평균 O(1)','좋은 분산·적절한 용량·충돌 처리'],['균형 탐색 트리 조회','O(log n)','균형을 유지하는 구현']])}<details class="more"><summary>더 알아보기 · 최악·평균·상각</summary><div class="more-body"><p><strong>최악·평균·최선</strong>은 어떤 입력이나 실행 경우를 보는지의 구분이에요. <strong>상각 분석</strong>은 연속된 여러 연산의 총비용을 연산당으로 나누어 봐요. <strong>점근 표기 O·Ω·Θ</strong>는 선택한 비용 함수의 성장 경계를 표현해요. 세 구분을 서로 바꾸어 부르면 안 돼요.</p></div></details>`},
 {id:'b06',title:'공간을 더 써서 시간을 줄일 수도 있어요',html:`<p>계산 결과를 캐시에 저장하면 같은 질문이 다시 왔을 때 계산을 건너뛸 수 있어요. 대신 저장 공간과 갱신 규칙이 필요해요. 오래된 결과를 계속 쓰면 빠르지만 틀릴 수 있으므로, 언제 버리거나 다시 계산할지도 설계해야 해요.</p><figure class="teaching-figure concept-figure"><div class="cache-tradeoff-visual" aria-label="가까운 작은 캐시와 먼 큰 저장 공간 사이의 시간 공간 교환"><div class="near-cache">${Array.from({length:4},()=>'<span></span>').join('')}</div><i></i><div class="far-store">${Array.from({length:18},()=>'<span></span>').join('')}</div></div><figcaption><strong>자주 쓰는 결과를 가까운 작은 공간에 미리 두어요</strong><ul class="picture-key"><li><b>왼쪽 네 칸</b>추가 공간을 쓰는 작은 캐시예요.</li><li><b>가운데 거리</b>매번 먼 저장소를 찾는 시간을 떠올려요.</li><li><b>오른쪽 큰 창고</b>원본과 전체 결과가 있는 저장 공간이에요.</li></ul></figcaption></figure><p>네트워크에서도 전송률과 왕복 지연을 나누어 계산하면 어느 부분을 개선해야 하는지 더 잘 보여요. 아래 모형에서 10MB를 10Mbps로 보내는 순수 전송 시간은 <code>10×8÷10 = 8초</code>예요.</p>`,lab:'network-delay'}
 ],questions:[
 {q:'정렬된 1~16에서 16을 찾는 기본 실습의 실제 비교 횟수는?',options:['순차 16회 · 이진 5회','둘 다 1회','순차 5회 · 이진 16회'],answer:0,feedback:['맞아요. 실습의 실제 비교 사건을 센 결과예요.','배열에 접근할 수 있다는 사실과 목표를 찾기 위한 비교 횟수는 달라요.','두 탐색의 결과를 바꾸어 적었어요.'],review:'b03'},
 {q:'정렬되지 않은 목록에서 이진 탐색을 그대로 적용하면?',options:['항상 O(1)로 찾아요.','절반을 버릴 근거가 없어 올바름을 보장할 수 없어요.','자동으로 먼저 정렬되며 비용은 0이에요.'],answer:1,feedback:['정렬 조건이 필요해요.','맞아요. 가운데 값과 비교해 어느 절반을 제외할지는 정렬 순서에 의존해요.','정렬은 별도 작업이며 비용을 고려해야 해요.'],review:'b04'},
 {q:'10MB를 10Mbps로 보내고 RTT가 100ms인 단순 모형의 합계는?',options:['약 1.1초','약 8.1초','정확히 100초'],answer:1,feedback:['MB를 Mb로 바꾸려면 8을 곱해요.','맞아요. 순수 전송 8초와 RTT 0.1초를 더해요.','전송률과 왕복 지연의 단위를 구별해요.'],review:'b06'}
 ],summary:['측정한 초와 입력 크기에 따른 연산 횟수 증가는 서로 다른 성능 정보예요.','이진 탐색은 정렬 조건 아래 후보를 절반씩 줄이고, 순차 탐색은 한 항목씩 비교해요.','시간을 줄이기 위해 캐시 공간을 쓸 수 있고, 네트워크에서는 전송 시간과 지연을 나누어 봐요.'],nextQuestion:'다른 컴퓨터와 데이터를 주고받을 때는 어떤 역할과 약속이 필요할까요?',sources:[['NIST DADS · Binary Search','https://xlinux.nist.gov/dads/HTML/binarySearch.html'],['MIT OpenCourseWare · Introduction to Algorithms','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/'],['OSTEP · CPU와 메모리 자원','https://pages.cs.wisc.edu/~remzi/OSTEP/']]
};
})();

