(()=>{
const {table,flow}=CS.helpers;
CS.lessons['ch06-l01']={
 lead:'휴대폰에서 보낸 짧은 메시지가 다른 컴퓨터의 알맞은 프로그램까지 가려면 어떤 역할들이 이어져야 할까요?',
 goals:['클라이언트와 서버를 장비 종류가 아닌 통신 역할로 설명해요.','OSI 7계층의 역할과 TCP/IP 계층을 연결하되 일대일로 외우지 않아요.','캡슐화와 수신 과정을 따라 메시지가 복원되는 모습을 확인해요.'],prerequisites:['ch01-l01','ch02-l01'],sections:[
 {id:'b01',title:'네트워크는 장치와 규칙과 경로가 함께 만들어요',html:`<p><strong>네트워크</strong>는 여러 장치가 데이터를 주고받을 수 있도록 연결한 체계예요. 케이블이나 무선 신호 같은 매체, 스위치·라우터 같은 장비, 주소와 통신 규칙이 함께 필요해요. 가까운 범위의 LAN과 멀리 떨어진 네트워크를 잇는 WAN은 범위와 운영 관점의 구분이며, 인터넷은 수많은 네트워크가 연결된 네트워크예요.</p><figure class="teaching-figure concept-figure"><div class="network-role-visual" aria-label="여러 장치가 공유기와 라우터를 거쳐 서버에 연결된 네트워크"><div class="clients"><span></span><span></span><span></span></div><i></i><b></b><i></i><div class="server-node"></div></div><figcaption><strong>한 줄의 케이블이 아니라 여러 장비와 경로를 거쳐요</strong><ul class="picture-key"><li><b>왼쪽 여러 장치</b>같은 LAN에 연결된 클라이언트의 예예요.</li><li><b>가운데 연결 장비</b>다음 구간으로 데이터를 전달해요.</li><li><b>오른쪽 서버</b>요청받은 서비스를 제공하는 역할이에요.</li></ul></figcaption></figure><p><strong>클라이언트</strong>는 서비스를 요청하는 역할, <strong>서버</strong>는 그 요청을 받아 서비스를 제공하는 역할이에요. 휴대폰과 고성능 컴퓨터라는 외형으로 고정되는 이름이 아니며, 한 프로그램이 상황에 따라 두 역할을 맡을 수도 있어요.</p>`},
 {id:'b02',title:'계층은 복잡한 통신을 역할별 질문으로 나눠요',html:`<p>OSI 7계층은 통신 기능을 역할별로 설명하는 <strong>참조 모델</strong>이에요. 어떤 계층에서 문제가 생겼는지 말하고, 서로 다른 시스템이 맞춰야 할 인터페이스를 생각하기 쉬워져요. 실제 인터넷 구현이 항상 일곱 프로그램으로 나뉘거나 프로토콜 하나가 한 계층에만 깔끔하게 들어맞는 것은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="osi-tower-visual" aria-label="응용부터 물리까지 일곱 역할을 쌓은 계층 도해"><span>응용<small>서비스</small></span><span>표현<small>형식</small></span><span>세션<small>대화</small></span><span>전송<small>프로그램</small></span><span>네트워크<small>경로</small></span><span>링크<small>한 구간</small></span><span>물리<small>신호</small></span></div><figcaption><strong>위에서는 앱의 의미를, 아래에서는 실제 전달을 다뤄요</strong><ul class="picture-key"><li><b>응용·표현·세션</b>서비스와 데이터 형식, 대화 관리를 설명해요.</li><li><b>전송</b>종단 프로그램 사이 전달의 성질을 다뤄요.</li><li><b>네트워크·링크·물리</b>경로, 한 구간, 신호 전달을 맡아요.</li></ul></figcaption></figure>${table(['계층','초심자가 붙잡을 질문'],[['7 응용','어떤 네트워크 서비스를 이용하는가?'],['6 표현','데이터를 어떤 형식으로 표현·해석하는가?'],['5 세션','대화의 시작·진행·끝을 어떻게 관리하는가?'],['4 전송','어느 프로그램 사이에 어떤 전달 성질이 필요한가?'],['3 네트워크','여러 네트워크를 지나 목적지까지 어떻게 가는가?'],['2 데이터 링크','현재 연결 구간에서 다음 장치까지 어떻게 전달하는가?'],['1 물리','비트를 전기·빛·무선 신호로 어떻게 보내는가?']])}`},
 {id:'b03',title:'보낼 때 정보를 붙이고, 받을 때 읽어 내려가요',html:`<p>앱의 데이터가 아래 역할로 내려가면서 전달에 필요한 제어 정보가 더해지는 과정을 <strong>캡슐화</strong>, 수신 측에서 그 정보를 확인하고 원래 데이터를 위로 넘기는 과정을 <strong>디캡슐화</strong>라고 해요. 모든 계층이 같은 모양의 헤더를 하나씩 붙이는 것은 아니므로, 아래 실습은 TCP/IP의 핵심 역할만 단순화해요.</p><figure class="teaching-figure concept-figure"><div class="encapsulation-visual" aria-label="내용 주위에 전송 네트워크 링크 정보가 차례로 둘러지는 그림"><div class="app-data">HI</div><div class="transport-wrap"><span>HI</span></div><div class="network-wrap"><span>HI</span></div><div class="link-wrap"><span>HI</span></div></div><figcaption><strong>원래 내용은 안쪽에 있고 전달 정보가 바깥에 더해져요</strong><ul class="picture-key"><li><b>가운데 내용</b>응용 프로그램이 보내려는 데이터예요.</li><li><b>전송·네트워크 정보</b>프로그램과 목적지 네트워크를 찾는 데 써요.</li><li><b>가장 바깥 링크 정보</b>현재 구간을 건널 때 사용해요.</li></ul></figcaption></figure>`,lab:'layer-message'},
 {id:'b04',title:'각 계층은 서로 다른 주소와 단위를 봐요',html:`<p>한 컴퓨터 안의 프로그램을 구별하는 데는 포트가, 여러 네트워크를 지나 목적지 호스트로 가는 데는 IP 주소가, 현재 링크의 다음 장치로 전달하는 데는 링크 계층 주소가 사용될 수 있어요. 라우터를 지날 때 링크 계층의 다음 구간 정보는 바뀔 수 있지만, IP 목적지는 보통 종단을 향해 유지돼요.</p>${table(['관점','대표 이름','주의할 점'],[['응용 데이터','message·data','앱이 이해하는 내용과 형식'],['TCP 전송 단위','segment','TCP는 신뢰성 있는 순서화된 바이트 스트림을 제공'],['UDP 전송 단위','datagram','전달·순서·중복 제거를 TCP처럼 보장하지 않음'],['IP 네트워크 단위','packet·IP datagram','목적지까지의 최선형 전달, 종단 신뢰성은 별도'],['링크 단위','frame','한 링크 구간에서 쓰며 형식은 링크 기술에 따라 다름'],['물리 표현','bit·signal','비트를 매체에 맞는 신호로 보냄']])}<div class="info">PDU 이름은 문맥과 교재에 따라 조금씩 달리 쓰여요. 중요한 것은 이름만 외우는 것보다 그 단계가 어떤 전달 정보를 다루는지 설명하는 일이에요.</div>`},
 {id:'b05',title:'IP의 전달과 TCP의 순서·재전송 역할을 구별해요',html:`<p>IP는 패킷을 목적지 쪽으로 전달하지만 도착, 순서, 중복 제거를 보장하지 않아요. TCP는 IP 위에서 순서 번호·확인 응답·재전송·흐름 제어·혼잡 제어 등을 사용해 애플리케이션에 신뢰성 있는 순서화된 바이트 스트림을 제공해요.</p><figure class="teaching-figure concept-figure"><div class="packet-order-visual" aria-label="세 조각이 다른 순서로 도착한 뒤 원래 순서로 다시 정렬되는 그림"><div><span>2</span><span>1</span><span>3</span></div><i></i><div><span>1</span><span>2</span><span>3</span></div></div><figcaption><strong>도착 순서와 앱에 넘기는 순서를 구별해요</strong><ul class="picture-key"><li><b>왼쪽 2·1·3</b>네트워크에서 관찰할 수 있는 뒤섞인 도착 예예요.</li><li><b>가운데 확인</b>순서 번호와 빠진 범위를 살펴요.</li><li><b>오른쪽 1·2·3</b>모두 받은 뒤 올바른 순서로 넘겨요.</li></ul></figcaption></figure>`,lab:'segment-order'},
 {id:'b06',title:'OSI와 TCP/IP는 역할을 보는 해상도가 달라요',html:`<p>인터넷 프로토콜 묶음을 설명할 때는 보통 응용·전송·인터넷·링크의 네 계층 모델이나, 링크를 데이터 링크와 물리로 나눈 다섯 계층 설명을 자주 써요. OSI의 표현·세션 역할은 사라진 것이 아니라 응용 계층과 라이브러리·프로토콜 구현 속에서 다뤄질 수 있어요.</p>${table(['OSI 역할','TCP/IP에서 함께 보는 시작점'],[['응용·표현·세션','응용 · HTTP, DNS, TLS 등 여러 기능이 걸침'],['전송','TCP, UDP, QUIC 등의 전송 기능'],['네트워크','인터넷 · IP와 라우팅'],['데이터 링크·물리','링크 · Ethernet, Wi-Fi와 매체']])}<p>“TCP/IP는 TCP와 IP 두 개만”이라는 뜻이 아니에요. IP, TCP, UDP, HTTP, DNS처럼 인터넷에서 함께 쓰는 여러 프로토콜과 규칙의 묶음을 가리키는 이름이에요. 다음 소단원에서는 웹 주소를 해석하고 HTTP 요청·응답과 TLS 보호를 한 흐름으로 연결해요.</p>`}
 ],questions:[
 {q:'송신 앱의 HI가 수신 앱에서 HI로 복원되기까지 가장 알맞은 흐름은?',options:['송신에서 전달 정보를 붙이고, 수신에서 확인하며 내용을 꺼내요.','모든 라우터가 HI를 새 문장으로 다시 써요.','IP가 모든 계층의 신뢰성과 순서를 혼자 보장해요.'],answer:0,feedback:['맞아요. 전달용 정보와 원래 내용을 구별하며 반대 순서로 처리해요.','라우터는 응용 메시지를 새로 쓰는 역할이 아니에요.','IP의 전달과 TCP 같은 전송 프로토콜의 보장을 구별해요.'],review:'b03'},
 {q:'클라이언트와 서버를 가장 정확히 설명한 것은?',options:['휴대폰은 항상 클라이언트이고 큰 컴퓨터는 항상 서버예요.','요청하는 역할과 서비스를 제공하는 역할이며 상황에 따라 달라질 수 있어요.','둘은 같은 네트워크에서 절대 함께 있을 수 없어요.'],answer:1,feedback:['장비 크기나 종류로 고정되는 이름이 아니에요.','맞아요. 역할을 가리키는 말이에요.','같은 LAN에서도 클라이언트와 서버가 통신할 수 있어요.'],review:'b01'},
 {q:'세 조각 중 2번이 오지 않았는데 1번과 3번만 받았어요. 수신 측은?',options:['완성했다고 앱에 바로 넘겨요.','빠진 범위를 확인하고 필요한 재전송 등을 기다려요.','IP 주소를 MAC 주소로 바꾸면 내용이 자동 완성돼요.'],answer:1,feedback:['중간 조각이 빠져 원래 바이트 흐름이 완성되지 않았어요.','맞아요. 실습에서 빠진 조각을 다시 요청해 확인할 수 있어요.','주소 변환과 전송 내용의 누락 복구는 다른 문제예요.'],review:'b05'}
 ],summary:['클라이언트와 서버는 요청·제공 역할이며 네트워크는 장비·경로·규칙이 함께 만들어요.','OSI는 역할을 나누어 이해하는 참조 모델이고 실제 TCP/IP 구현과 일대일 대응하지 않아요.','IP 전달과 TCP의 순서·재전송 역할을 구별하고 캡슐화의 방향을 설명해요.'],nextQuestion:'웹 주소를 입력하면 이름 찾기부터 HTTP 응답과 화면 표시까지 어떤 일이 이어질까요?',sources:[['ISO/IEC 7498-1 · OSI Basic Reference Model','https://www.iso.org/standard/14256.html'],['IETF RFC 1122 · Internet Host Requirements','https://www.rfc-editor.org/rfc/rfc1122'],['IETF RFC 9293 · Transmission Control Protocol','https://www.rfc-editor.org/rfc/rfc9293']]
};

CS.lessons['ch06-l02']={
 lead:'주소창에 URL을 입력했을 뿐인데, 이름을 찾고 요청을 만들고 안전한 연결을 확인하는 여러 단계가 이어져요.',
 goals:['URL·DNS·IP·포트·경로의 역할을 한 흐름으로 연결해요.','HTTP 요청과 응답, 상태코드와 본문의 차이를 설명해요.','HTTPS의 TLS 인증서 검증과 키 합의의 역할을 구별해요.'],prerequisites:['ch06-l01'],sections:[
 {id:'b01',title:'URL은 프로토콜과 대상과 자원 위치를 나눠 적어요',html:`<p><code>https://library.example/books?id=B01</code>을 봅시다. <code>https</code>는 사용할 스킴, <code>library.example</code>은 호스트 이름, <code>/books</code>는 경로, <code>id=B01</code>은 질의 문자열이에요. URL에는 포트를 직접 적을 수도 있고, 생략하면 스킴의 기본 포트를 사용하는 경우가 있어요.</p><figure class="teaching-figure concept-figure"><div class="url-anatomy-visual" aria-label="URL을 스킴 호스트 경로 질의 문자열로 나눈 그림"><span class="scheme">https</span><i>:</i><span class="host">library.example</span><span class="path">/books</span><span class="query">?id=B01</span></div><figcaption><strong>한 줄의 주소 안에도 역할이 다른 조각이 있어요</strong><ul class="picture-key"><li><b>스킴</b>어떤 방식으로 접근할지 나타내요.</li><li><b>호스트</b>DNS가 찾을 네트워크 이름이에요.</li><li><b>경로와 질의</b>서버 안에서 요청할 자원을 구별해요.</li></ul></figcaption></figure><p>IP 주소는 네트워크의 인터페이스를 식별하고 라우팅에 쓰여요. 같은 장치가 여러 IP를 가질 수 있고, 사설 주소와 NAT가 있을 수 있으므로 ‘세상의 모든 컴퓨터에 영원히 하나씩 붙은 번호’로 외우지 않아요. 포트는 한 호스트 안에서 전송 종단의 프로그램·서비스를 구별하는 데 사용해요.</p>`},
 {id:'b02',title:'DNS는 사람이 쓰는 이름을 주소 정보로 찾게 도와요',html:`<p>DNS는 계층적으로 분산된 이름 시스템이에요. 브라우저와 운영체제의 캐시, 재귀 해석기, 여러 권한 서버가 관여할 수 있어요. 이름 하나가 항상 IP 하나에 영구 고정되는 것은 아니며, 레코드 종류와 시점에 따라 여러 결과가 나올 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="dns-lookup-visual" aria-label="브라우저가 DNS 해석기를 통해 예시 IP 주소를 찾는 그림"><div class="browser-box"></div><i></i><div class="resolver-box"><span></span><span></span><span></span></div><i></i><div class="address-card"></div></div><figcaption><strong>이름을 물어 네트워크에서 쓸 주소 정보를 얻어요</strong><ul class="picture-key"><li><b>왼쪽 브라우저</b>호스트 이름의 주소를 요청해요.</li><li><b>가운데 해석기</b>캐시와 DNS 계층을 이용해 답을 찾아요.</li><li><b>오른쪽 주소 카드</b>연결할 IP 후보 정보를 돌려줘요.</li></ul></figcaption></figure><p>DNS 답을 받은 뒤에도 연결 설정과 TLS, HTTP 요청이 남아 있어요. DNS가 웹페이지의 HTML을 직접 전달하거나 URL의 경로에 맞는 도서를 고르는 것은 아니에요.</p>`,lab:'http-library'},
 {id:'b03',title:'HTTP는 요청과 응답 메시지의 의미를 정해요',html:`<p>HTTP 클라이언트는 메서드와 대상, 헤더, 필요하면 본문을 담아 요청해요. 서버는 상태코드와 헤더, 필요하면 본문을 담아 응답해요. HTTP는 응용 계층의 의미를 정하고, 실제 전송은 HTTP 버전에 따라 TCP 또는 QUIC 같은 아래 계층 기능을 이용할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="request-response-visual" aria-label="클라이언트의 요청 카드와 서버의 응답 카드가 오가는 그림"><div class="request-card"><b>GET</b><span></span><span></span></div><i class="to-server"></i><div class="server-slab"></div><i class="to-client"></i><div class="response-card"><b>200</b><span></span><span></span></div></div><figcaption><strong>요청과 응답은 방향과 내용이 달라요</strong><ul class="picture-key"><li><b>GET 요청</b>어떤 자원을 원하는지 서버에 말해요.</li><li><b>서버 처리</b>메서드와 대상에 맞는 결과를 만들어요.</li><li><b>200 응답</b>처리 상태와 결과 본문을 돌려줘요.</li></ul></figcaption></figure>${table(['메서드','대표 의미','성질을 읽을 때'],[['GET','현재 자원의 표현 조회','안전하고 멱등으로 정의됨'],['POST','대상 자원이 정한 처리를 요청','같은 요청 반복 결과가 같다고 일반 보장하지 않음'],['PUT','대상 자원의 상태를 요청 본문으로 만들거나 대체','멱등으로 정의됨'],['PATCH','자원 일부 변경을 기술','패치 문서와 서버 의미에 따라 반복 효과를 주의'],['DELETE','대상 자원을 제거하도록 요청','멱등은 응답 코드가 늘 같다는 뜻이 아님']])}`},
 {id:'b04',title:'상태코드와 응답 본문은 따로 읽어요',html:`<p>상태코드는 서버가 요청을 어떻게 처리했는지 알려 주는 세 자리 수예요. 2xx는 성공, 3xx는 추가 동작이나 다른 위치, 4xx는 요청 측과 관련된 오류, 5xx는 서버가 요청 처리를 완료하지 못한 오류 범주예요.</p>${table(['상황','이 예시의 결과','해석'],[['도서 B01 조회','200 + 도서 JSON','요청을 처리했고 결과 본문이 있음'],['없는 B99 조회','404 + 오류 설명','대상 자원을 찾지 못함'],['정상 처리·보낼 본문 없음','204 + 본문 없음','성공과 본문 존재는 다른 정보'],['서버 내부 오류','500 + 오류 설명','HTTP 응답 자체는 받음'],['연결 실패','HTTP 상태코드 없음','서버의 HTTP 응답을 받지 못함']])}<div class="info">401의 이름은 Unauthorized이지만 보통 인증 자격이 필요함을 나타내고, 403은 서버가 요청을 이해했으나 허용하지 않는 상황에 사용해요. 상태코드는 앱의 자세한 오류 원인을 모두 대신하지 않아요.</div>`},
 {id:'b05',title:'HTTP는 상태를 자동 기억하지 않아요',html:`<p>HTTP 요청은 각각 필요한 정보를 담아 처리돼요. 로그인 상태처럼 이전 요청과 연결할 정보가 필요하면 쿠키, 세션 식별자, 토큰 같은 별도 방식을 설계해요. 브라우저는 도메인·경로·보안 속성 등 조건에 맞는 쿠키를 요청에 포함할 수 있어요.</p>${flow(['첫 로그인 요청','서버가 세션 상태와 식별자 준비','브라우저가 조건에 맞는 쿠키 저장','다음 요청에 식별자 포함','서버가 관련 상태 조회'])}<p>HTTP가 항상 요청마다 TCP 연결을 새로 만들고 즉시 끊는 것도 아니에요. HTTP/1.1은 지속 연결을 지원하고, HTTP/2는 한 연결에서 여러 스트림을 다중화하며, HTTP/3는 QUIC 위에서 동작해요. ‘HTTP는 단방향이라 서버가 데이터를 보낼 수 없다’ 같은 한 문장 대신 버전과 사용 방식, 웹소켓·서버 전송 기술을 구분해야 해요.</p>`},
 {id:'b06',title:'HTTPS는 TLS로 전송을 보호하고 서버를 확인해요',html:`<p>HTTPS는 HTTP를 TLS로 보호해 전송 중 기밀성·무결성을 제공하고, 인증서를 검증해 접속한 서버 이름의 인증을 도와요. 최신 TLS의 키 합의는 단순히 브라우저가 대칭키 하나를 서버 공개키로 감싸 보내는 고정 절차로 설명할 수 없어요. TLS 1.3에서는 보통 임시 키 교환으로 함께 통신 키를 만들고 인증서 서명으로 서버의 신원을 검증해요.</p><figure class="teaching-figure concept-figure"><div class="tls-channel-visual" aria-label="인증서를 확인한 뒤 보호된 통로로 요청과 응답이 오가는 그림"><div class="client-lock"></div><div class="certificate-sheet"><span></span><span></span><b></b></div><div class="secure-tunnel"><i></i><i></i><i></i></div><div class="server-lock"></div></div><figcaption><strong>인증서를 확인하고 합의한 키로 통신을 보호해요</strong><ul class="picture-key"><li><b>인증서 문서</b>신뢰 경로·기간·접속 이름 등을 확인해요.</li><li><b>파란 통로</b>합의한 키로 보호되는 연결을 나타내요.</li><li><b>양쪽 끝</b>HTTP 요청과 응답을 암호화해 주고받아요.</li></ul></figcaption></figure>`,lab:'tls-handshake'},
 ],questions:[
 {q:'B99를 요청해 서버에서 HTTP 404 응답을 받았어요. 이것은?',options:['HTTP 응답을 받았고 대상 자원을 찾지 못한 상황','네트워크 연결이 없어 상태코드도 없는 상황','TLS 인증서가 반드시 만료된 상황'],answer:0,feedback:['맞아요. 연결 실패와 서버의 404 응답을 구별했어요.','404는 실제 HTTP 응답 안의 상태코드예요.','404만으로 인증서 상태를 알 수 없어요.'],review:'b04'},
 {q:'204 No Content의 가장 알맞은 설명은?',options:['실패했으므로 HTTP 응답이 없어요.','요청은 성공했지만 응답 본문에 보낼 내용이 없어요.','DNS가 IP를 찾지 못했어요.'],answer:1,feedback:['204는 성공 범주인 2xx예요.','맞아요. 성공 여부와 본문 존재를 구별해요.','DNS 실패라면 HTTP 204 응답을 받지 못해요.'],review:'b04'},
 {q:'HTTPS 자물쇠가 뜻하는 범위는?',options:['그 사이트의 모든 글과 판매 상품이 항상 믿을 만해요.','전송을 보호하고 접속한 서버 이름의 인증을 돕지만 사이트 내용 전체를 보증하지는 않아요.','HTTP 응답 상태코드가 언제나 200이에요.'],answer:1,feedback:['TLS 인증과 사이트 내용의 진실성을 구별해요.','맞아요. 보호하는 범위를 정확히 설명했어요.','HTTPS 연결에서도 404·500 같은 응답이 올 수 있어요.'],review:'b06'}
 ],summary:['URL의 호스트는 DNS로 주소 정보를 찾고, 경로와 질의는 서버의 요청 대상을 구별해요.','HTTP 응답의 상태코드·본문과 네트워크 연결 실패를 서로 구별해요.','HTTPS는 TLS로 전송을 보호하고 서버 인증을 돕지만 사이트 내용 전체를 보증하지 않아요.'],nextQuestion:'같은 데이터를 더 빠르게 찾거나 정렬하려면 어떤 알고리즘 전략을 선택해야 할까요?',sources:[['WHATWG · URL Standard','https://url.spec.whatwg.org/'],['IETF RFC 9110 · HTTP Semantics','https://www.rfc-editor.org/rfc/rfc9110'],['IETF RFC 8446 · TLS 1.3','https://www.rfc-editor.org/rfc/rfc8446'],['MDN · HTTP Overview','https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview']]
};
})();

