(()=>{
const {table,flow}=CS.helpers;
CS.lessons['ch07-l01']={
 lead:'숫자를 작은 순서로 놓는 일은 쉬워 보여도, 컴퓨터에게는 “무엇이 올바른 결과인지”와 “얼마나 일했는지”를 함께 설명해야 해요.',
 goals:['탐색 전에 필요한 조건과 정렬의 정답 조건을 설명해요.','삽입·버블·병합·퀵 정렬이 입력을 다루는 방식을 비교해요.','같은 값의 식별자를 추적해 안정 정렬을 직접 확인해요.'],prerequisites:['ch05-l02'],sections:[
 {id:'b01',title:'알고리즘은 입력을 답으로 바꾸는 정확한 절차예요',html:`<p><strong>알고리즘</strong>은 정해진 입력을 받아 유한한 단계로 원하는 출력을 만드는 절차예요. 정렬이라면 “대충 작은 값이 앞”으로는 부족해요. 결과가 <strong>비내림차순</strong>이고, 입력에 있던 항목이 빠지거나 새로 생기지 않았다는 두 조건을 모두 만족해야 해요.</p><figure class="teaching-figure concept-figure"><div class="algorithm-contract-visual" aria-label="섞인 네 항목이 정렬된 뒤 값의 순서와 항목 보존 검사를 통과하는 그림"><div class="contract-input"><span>3A</span><span>1B</span><span>2C</span><span>1D</span></div><i></i><div class="contract-output"><span>1B</span><span>1D</span><span>2C</span><span>3A</span></div><div class="contract-check"><b>순서 ✓</b><b>항목 보존 ✓</b></div></div><figcaption><strong>정렬 결과에는 두 가지 약속이 있어요</strong><ul class="picture-key"><li><b>순서 검사</b>왼쪽 값이 오른쪽 값보다 크지 않아야 해요.</li><li><b>항목 보존</b>A·B·C·D가 하나씩 그대로 남아야 해요.</li><li><b>식별자</b>값이 같은 항목의 원래 순서도 관찰하게 해 줘요.</li></ul></figcaption></figure><p>좋은 알고리즘 설명은 정상 입력뿐 아니라 빈 입력, 항목 하나, 이미 정렬된 입력에서도 약속을 지키는지 살펴요. 실행 시간과 메모리 사용량은 정답을 낸 뒤 서로 다른 방법을 비교하는 기준이에요.</p>`},
 {id:'b02',title:'탐색 방법은 데이터가 어떤 상태인지에 따라 달라져요',html:`<p>순차 탐색은 처음부터 하나씩 비교하므로 정렬되지 않은 자료에도 쓸 수 있어요. 이진 탐색은 가운데 값과 비교해 후보 범위를 절반씩 줄이지만, 비교 기준에 따라 <strong>정렬된 자료</strong>라는 전제가 필요해요. 자료가 자주 바뀐다면 정렬을 유지하는 비용도 함께 계산해야 해요.</p><figure class="teaching-figure concept-figure"><div class="search-branches-visual" aria-label="순차 탐색은 한 칸씩 보고 이진 탐색은 후보 범위를 절반씩 줄이는 그림"><div class="scan-line"><b>순차</b><span class="seen"></span><span class="seen"></span><span class="seen"></span><span class="seen"></span><span class="found"></span><span></span><span></span></div><div class="halve-lines"><b>이진</b><p><span></span><span></span><span></span><span class="pivot"></span><span></span><span></span><span></span></p><p><span></span><span></span><span class="pivot"></span></p><p><span class="found"></span></p></div></div><figcaption><strong>빠른 방법에는 사용할 수 있는 조건이 붙어요</strong><ul class="picture-key"><li><b>위쪽 순차 탐색</b>앞에서부터 차례로 확인해요.</li><li><b>아래쪽 이진 탐색</b>정렬된 범위의 가운데를 비교해 절반을 버려요.</li><li><b>준비 비용</b>한 번만 찾는지, 계속 찾는지도 선택에 영향을 줘요.</li></ul></figcaption></figure>${table(['방법','필요한 상태','최악의 비교 규모'],[['순차 탐색','특별한 정렬 조건 없음','n개'],['이진 탐색','비교 기준에 따라 정렬됨','약 log₂n번'],['해시 탐색','적절한 해시 구조와 충돌 처리','평균은 빠르지만 최악은 구현·입력에 따라 커짐']])}`},
 {id:'b03',title:'삽입 정렬은 앞쪽의 정렬된 부분을 한 칸씩 키워요',html:`<p>삽입 정렬은 다음 항목 하나를 꺼내 이미 정렬된 앞부분의 알맞은 자리에 넣어요. 앞의 큰 항목을 오른쪽으로 밀고, 같거나 작은 항목 뒤에 놓으면 같은 값의 원래 순서를 유지할 수 있어요. 거의 정렬된 입력에서는 이동이 적지만, 역순 입력에서는 비교와 이동이 많이 생겨요.</p><figure class="teaching-figure concept-figure"><div class="insertion-tray-visual" aria-label="정렬된 앞부분에 1D 항목을 삽입하는 세 단계"><div><span class="fixed">1B</span><span class="fixed">2C</span><span class="fixed">3A</span><span class="key">1D</span></div><i></i><div><span>1B</span><span class="gap"></span><span>2C</span><span>3A</span></div><i></i><div><span>1B</span><span class="key">1D</span><span>2C</span><span>3A</span></div></div><figcaption><strong>같은 값 1에서는 먼저 온 B 뒤에 D를 놓아요</strong><ul class="picture-key"><li><b>고른 항목</b>1D를 따로 기억해요.</li><li><b>이동</b>더 큰 3A와 2C를 오른쪽으로 밀어요.</li><li><b>삽입</b>같은 값 1B의 뒤에 놓아 순서를 보존해요.</li></ul></figcaption></figure>`,lab:'stable-sort'},
 {id:'b04',title:'버블 정렬은 이웃을 비교해 큰 값을 끝으로 보내요',html:`<p>버블 정렬은 이웃한 두 항목의 순서가 거꾸로일 때 교환해요. 한 번 끝까지 지나가면 가장 큰 항목 하나가 뒤쪽의 제자리를 찾아요. 기본 구현은 많은 비교를 하지만, 한 패스에서 교환이 없으면 이미 정렬됐다고 조기 종료하도록 개선할 수 있어요.</p>${table(['입력 상태','삽입 정렬의 관찰','조기 종료 버블 정렬의 관찰'],[['이미 정렬됨','항목마다 앞의 바로 한 번 정도만 확인','첫 패스에서 교환 없이 종료 가능'],['거의 정렬됨','어긋난 만큼만 주로 이동','여러 패스가 필요할 수 있음'],['역순','비교와 이동이 Θ(n²) 규모','비교와 교환이 Θ(n²) 규모']])}<div class="info">시간 복잡도는 실제 초 수가 아니라 입력 크기가 커질 때 일이 늘어나는 모양을 나타내요. 같은 Θ(n²)이라도 구현, 입력 상태, 자료 크기에 따라 실제 횟수는 달라져요.</div>`},
 {id:'b05',title:'병합 정렬과 퀵 정렬은 큰 문제를 작은 문제로 나눠요',html:`<p><strong>병합 정렬</strong>은 목록을 절반으로 나누어 각각 정렬한 뒤 두 정렬 결과를 합쳐요. 배열에서는 보통 Θ(n log n) 시간과 합칠 임시 공간을 사용하며, 같은 값에서 왼쪽 항목을 먼저 고르면 안정적으로 만들 수 있어요. <strong>퀵 정렬</strong>은 피벗을 기준으로 작은 쪽과 큰 쪽을 나누고 각 부분을 다시 처리해요. 평균적으로 빠르지만 분할이 계속 한쪽으로 치우치면 Θ(n²)이 될 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="merge-quick-visual" aria-label="병합 정렬의 균등 분할과 퀵 정렬의 피벗 분할 비교"><div class="merge-tree"><b>병합</b><span class="root"></span><p><span></span><span></span></p><p><i></i><i></i><i></i><i></i></p></div><div class="quick-pivot"><b>퀵</b><p><span></span><strong>피벗</strong><span></span></p><p><i>작음</i><i>큼</i></p></div></div><figcaption><strong>둘 다 나누지만 나누는 기준과 합치는 일이 달라요</strong><ul class="picture-key"><li><b>병합 정렬</b>크기를 절반씩 나누고 정렬된 두 결과를 합쳐요.</li><li><b>퀵 정렬</b>피벗과의 비교 결과로 두 구역을 만들어요.</li><li><b>분할의 균형</b>퀵 정렬의 실행 깊이에 큰 영향을 줘요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'정렬 이름보다 자료와 필요한 성질을 먼저 확인해요',html:`<p><strong>안정 정렬</strong>은 키가 같은 항목의 상대적인 순서를 유지해요. 학생을 먼저 이름순, 그다음 반 번호순으로 안정 정렬하면 같은 반 안의 이름순을 보존할 수 있어요. 숫자만 표시하면 같은 숫자끼리 바뀌어도 보이지 않으므로 실습처럼 식별자를 붙여 확인해야 해요.</p>${table(['질문','선택에 미치는 영향'],[['항목 수가 얼마나 큰가?','작은 자료에서는 단순한 방법도 충분할 수 있음'],['거의 정렬돼 있는가?','삽입 정렬의 이동량이 작아질 수 있음'],['같은 키의 순서를 보존해야 하는가?','안정 정렬 또는 안정적으로 구현한 방법이 필요'],['추가 메모리를 얼마나 쓸 수 있는가?','배열 병합 정렬의 임시 공간 등을 고려'],['최악의 실행 시간 보장이 필요한가?','평균 성능만으로 결정하지 않음']])}<p>라이브러리 정렬을 사용할 때도 언어와 버전의 안정성 보장, 비교 함수의 규칙, 원본 변경 여부를 문서에서 확인해야 해요.</p>`}
 ],questions:[
 {q:'정렬 결과가 올바르다고 말하려면 무엇을 함께 확인해야 할까요?',options:['값이 비내림차순이고 입력 항목이 모두 그대로 남았는지','첫 번째 값만 가장 작은지','실행 시간이 항상 1초보다 짧은지'],answer:0,feedback:['맞아요. 순서와 항목 보존이 정답 조건이에요.','첫 항목만으로 전체 순서를 보장할 수 없어요.','속도는 비교 기준이지만 정답 조건을 대신하지 않아요.'],review:'b01'},
 {q:'이진 탐색을 바로 적용하기 전에 가장 먼저 확인할 것은?',options:['자료가 탐색의 비교 기준에 맞게 정렬돼 있는지','값마다 색이 다른지','항목 수가 짝수인지'],answer:0,feedback:['맞아요. 후보 절반을 버려도 되는 전제가 필요해요.','색은 일반적인 이진 탐색 조건이 아니에요.','홀수 항목에서도 가운데를 정해 탐색할 수 있어요.'],review:'b02'},
 {q:'안정 정렬의 의미는?',options:['어떤 입력에서도 O(1) 시간에 끝나요.','같은 키를 가진 항목의 상대적인 순서를 보존해요.','추가 메모리를 전혀 쓰지 않아요.'],answer:1,feedback:['안정성은 실행 시간의 이름이 아니에요.','맞아요. 값과 식별자를 함께 보면 확인할 수 있어요.','안정성과 추가 메모리 사용은 서로 다른 성질이에요.'],review:'b06'}
 ],summary:['정렬의 정답은 비내림차순과 입력 항목 보존을 함께 만족해야 해요.','탐색·정렬 방법은 데이터 상태, 안정성, 시간과 공간 요구에 맞춰 골라요.','삽입·버블 정렬은 작은 단계를 관찰하기 쉽고, 병합·퀵 정렬은 분할 방식과 보장이 달라요.'],nextQuestion:'문제의 모든 선택을 살펴볼지, 작은 답을 저장할지, 당장 좋아 보이는 선택을 할지는 어떻게 결정할까요?',sources:[['NIST DADS · Sort','https://xlinux.nist.gov/dads/HTML/sort.html'],['NIST DADS · Insertion sort','https://xlinux.nist.gov/dads/HTML/insertionSort.html'],['MIT OpenCourseWare · Insertion sort and merge sort','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/resources/mit6_006f11_lec03/']]
};

CS.lessons['ch07-l02']={
 lead:'같은 문제도 모든 경우를 살펴보거나, 쪼개거나, 지금 좋아 보이는 것을 고르거나, 작은 답을 저장하는 방식으로 다르게 풀 수 있어요.',
 goals:['완전 탐색과 가지치기가 정답 후보를 다루는 방식을 설명해요.','분할 정복·탐욕법·동적 계획법의 성립 조건을 구별해요.','동전 교환에서 탐욕 선택과 최적 답이 달라지는 사례를 실행해요.'],prerequisites:['ch07-l01'],sections:[
 {id:'b01',title:'완전 탐색은 가능한 후보를 빠짐없이 확인해요',html:`<p><strong>완전 탐색</strong>은 문제에서 허용한 모든 후보를 만들거나 방문해 정답을 찾아요. 작은 입력의 기준 답을 만들기 좋지만 선택지가 늘면 후보 수가 매우 빠르게 커질 수 있어요. <strong>가지치기</strong>는 지금까지의 선택이 제약을 이미 어겼거나 최선의 답을 이길 수 없다는 사실을 증명할 때 그 아래를 생략해요.</p><figure class="teaching-figure concept-figure"><div class="choice-tree-visual" aria-label="선택 트리에서 불가능한 가지를 잘라 내고 남은 후보를 조사하는 그림"><span class="tree-root">시작</span><div><i></i><i></i><i></i></div><div class="tree-level"><span>선택 A</span><span class="pruned">불가능</span><span>선택 C</span></div><div class="tree-leaves"><b>후보</b><b>후보</b><b>후보</b></div></div><figcaption><strong>가지를 자르려면 그 아래에 답이 없다는 근거가 필요해요</strong><ul class="picture-key"><li><b>선택 트리</b>한 단계의 선택마다 다음 후보가 갈라져요.</li><li><b>회색 가지</b>제약을 어겨 더 볼 필요가 없어요.</li><li><b>남은 잎</b>가능한 답을 빠짐없이 비교해요.</li></ul></figcaption></figure><p>“왠지 나쁠 것 같다”는 이유로 가지를 버리면 정답까지 잘라낼 수 있어요. 안전한 상한·하한이나 문제의 제약으로 생략의 타당성을 설명해야 해요.</p>`},
 {id:'b02',title:'분할 정복은 나누고 풀고 합쳐요',html:`<p><strong>분할 정복</strong>은 큰 문제를 더 작은 부분 문제로 나누고, 각 부분을 재귀적으로 푼 뒤 결과를 합쳐요. 종료 조건이 없으면 계속 나뉘므로 더 나누지 않고 바로 답을 낼 <strong>기본 사례</strong>가 필요해요. 병합 정렬은 이 구조를 뚜렷하게 보여 줘요.</p><figure class="teaching-figure concept-figure"><div class="divide-combine-visual" aria-label="큰 문제가 네 부분으로 나뉘어 해결된 뒤 하나의 답으로 합쳐지는 그림"><div class="big-problem">8개 문제</div><div class="split-arrows"><i></i><i></i></div><div class="small-problems"><span>2개</span><span>2개</span><span>2개</span><span>2개</span></div><div class="combine-arrows"><i></i><i></i></div><div class="big-answer">정렬된 답</div></div><figcaption><strong>문제 크기가 줄어드는지와 결과를 합칠 수 있는지가 핵심이에요</strong><ul class="picture-key"><li><b>분할</b>같은 모양의 더 작은 문제로 만들어요.</li><li><b>기본 사례</b>아주 작은 문제는 바로 해결해 재귀를 끝내요.</li><li><b>결합</b>부분 답을 전체 문제의 답으로 만들어요.</li></ul></figcaption></figure>${flow(['문제 정의','기본 사례','부분 문제로 분할','부분 답 계산','전체 답으로 결합'])}`},
 {id:'b03',title:'탐욕법은 지금 가장 좋아 보이는 선택을 확정해요',html:`<p><strong>탐욕법</strong>은 매 단계에서 정한 기준으로 가장 좋아 보이는 선택을 하고 보통 되돌리지 않아요. 빠르고 단순한 경우가 많지만, 그 선택을 포함하는 최적해가 항상 존재한다는 <strong>탐욕 선택 성질</strong>과 남은 문제가 같은 구조의 최적 부분을 갖는다는 근거가 필요해요.</p><figure class="teaching-figure concept-figure"><div class="greedy-path-visual" aria-label="여러 갈림길 중 매번 가장 커 보이는 값만 따라간 경로가 전체 최대 경로와 달라지는 그림"><span class="start-dot"></span><div><i class="chosen"></i><i></i></div><div class="path-values"><b class="chosen">4</b><b>3</b></div><div><i class="chosen"></i><i></i><i></i></div><div class="path-values bottom"><b class="chosen">1+1</b><b>3</b><b>1+1+1</b></div></div><figcaption><strong>당장의 큰 값 4가 전체 동전 수를 최소로 만들지는 않아요</strong><ul class="picture-key"><li><b>파란 경로</b>6에서 가장 큰 동전 4를 먼저 골라요.</li><li><b>남은 2</b>1을 두 번 더 골라 총 3개가 돼요.</li><li><b>다른 경로</b>3을 두 번 고르면 총 2개로 더 좋아요.</li></ul></figcaption></figure><p>어떤 동전 체계에서는 큰 동전부터 고르는 방법이 맞지만, 모든 동전 체계에 자동으로 적용되지는 않아요. 반례 하나만 찾으면 일반적인 최적성 주장을 깨뜨릴 수 있어요.</p>`},
 {id:'b04',title:'같은 동전 문제를 탐욕법과 DP로 나란히 풀어요',html:`<p>동전 <code>1, 3, 4</code>로 금액 <code>6</code>을 만들 때 큰 동전부터 고르면 <code>4+1+1</code>로 3개를 써요. 아래 DP는 0원부터 각 금액의 최소 동전 수를 쌓아 <code>3+3</code>, 2개를 찾아요. 동전 구성을 바꿔 도달할 수 없는 금액도 확인해 보세요.</p>`,lab:'coin-strategies'},
 {id:'b05',title:'동적 계획법은 반복되는 작은 문제의 답을 저장해요',html:`<p><strong>동적 계획법</strong>은 겹치는 부분 문제의 답을 한 번 계산해 저장하고 다시 사용해요. 먼저 상태가 무엇을 뜻하는지, 이전 상태에서 새 상태를 만드는 점화식, 가장 작은 기본값, 계산 순서를 정해야 해요. 위 실습의 <code>DP[x]</code>는 “금액 x를 만드는 최소 동전 개수”예요.</p><figure class="teaching-figure concept-figure"><div class="overlap-dp-visual" aria-label="재귀 트리에서 같은 부분 문제가 반복되고 표에서는 한 칸씩 한 번만 계산되는 그림"><div class="repeat-tree"><b>F(5)</b><p><span>F(4)</span><span>F(3)</span></p><p><i>F(3)</i><i>F(2)</i><i>F(2)</i><i>F(1)</i></p></div><div class="memo-arrow">→</div><div class="memo-cells"><span><b>1</b><i>저장</i></span><span><b>2</b><i>저장</i></span><span class="shared"><b>3</b><i>한 번</i></span><span><b>4</b><i>저장</i></span><span><b>5</b><i>답</i></span></div></div><figcaption><strong>같은 F(3)과 F(2)를 여러 번 풀지 않고 결과를 재사용해요</strong><ul class="picture-key"><li><b>왼쪽 재귀 트리</b>같은 이름의 부분 문제가 반복돼요.</li><li><b>오른쪽 표</b>각 상태를 한 번 계산해 저장해요.</li><li><b>대가</b>반복 계산은 줄지만 상태를 보관할 메모리가 필요해요.</li></ul></figcaption></figure><p>위에서 아래로 재귀 호출하며 저장하면 메모이제이션, 작은 상태부터 반복문으로 채우면 타뷸레이션이라고 불러요. 둘 다 같은 상태 정의와 점화식을 사용할 수 있지만 방문 순서와 호출 비용이 달라요.</p>`},
 {id:'b06',title:'전략은 이름이 아니라 성립 조건과 비용으로 골라요',html:`${table(['전략','잘 맞는 구조','확인할 점'],[['완전 탐색·백트래킹','후보를 모두 생성할 수 있고 입력이 작음','후보 누락 없이 종료하는가, 가지치기가 안전한가'],['분할 정복','부분 문제가 작아지고 비교적 독립적임','기본 사례와 결합 비용은 무엇인가'],['탐욕법','지역 최선 선택을 포함한 최적해가 보장됨','교환 논증·귀류법 등으로 최적성을 증명할 수 있는가'],['동적 계획법','부분 문제가 겹치고 최적 부분 구조가 있음','상태·점화식·기본값·순서가 정확한가']])}<p>시간을 줄이면 메모리를 더 쓸 수 있고, 메모리를 아끼면 계산을 반복할 수도 있어요. 먼저 작은 입력을 손으로 풀어 기준 답을 만들고, 불변 조건과 반례를 찾고, 그 뒤 복잡도를 비교하면 전략을 더 안전하게 선택할 수 있어요.</p><div class="info"><strong>문제 풀이 점검 순서</strong><br>입력·출력과 예외를 적기 → 작은 예를 완전 탐색으로 풀기 → 반복되는 구조 찾기 → 선택을 버려도 되는 근거 세우기 → 시간·공간을 계산하기</div>`}
 ],questions:[
 {q:'가지치기로 어떤 선택 아래를 전부 생략해도 되는 때는?',options:['그 아래에 더 나은 정답이 없음을 제약이나 경계값으로 설명할 수 있을 때','첫눈에 복잡해 보일 때','그 선택이 목록의 마지막일 때'],answer:0,feedback:['맞아요. 정답을 잘라내지 않는다는 근거가 필요해요.','복잡해 보인다는 느낌만으로는 안전하지 않아요.','목록 위치만으로 후보 전체를 버릴 수 없어요.'],review:'b01'},
 {q:'동전 1, 3, 4로 6을 만들 때 큰 동전부터 고르는 탐욕법과 최적 답은?',options:['탐욕 3개, 최적 2개','탐욕 2개, 최적 3개','둘 다 항상 1개'],answer:0,feedback:['맞아요. 4+1+1과 3+3을 비교했어요.','탐욕 결과가 오히려 더 많은 동전을 써요.','6짜리 동전은 입력에 없어요.'],review:'b04'},
 {q:'동적 계획법을 설계할 때 먼저 분명히 해야 하는 것은?',options:['상태의 뜻과 점화식, 기본값과 계산 순서','버튼의 색과 글꼴','항상 가장 큰 숫자를 고르는 규칙'],answer:0,feedback:['맞아요. 저장할 작은 문제와 연결 관계를 정의해야 해요.','화면 모양은 알고리즘의 정답을 결정하지 않아요.','그 규칙은 특정 탐욕법이며 일반적인 DP 정의가 아니에요.'],review:'b05'}
 ],summary:['완전 탐색은 후보를 빠짐없이 보고, 가지치기는 답이 없다는 근거가 있을 때만 사용해요.','분할 정복은 작은 독립 문제를 합치고, DP는 겹치는 부분 문제의 답을 저장해요.','탐욕법의 지역 선택이 항상 전체 최적을 보장하지 않으므로 증명이나 반례가 필요해요.'],nextQuestion:'프로그램이 여러 작업을 동시에 처리하는 것처럼 보일 때 운영체제는 CPU와 메모리를 어떻게 나눌까요?',sources:[['MIT OpenCourseWare · Introduction to Algorithms lecture notes','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2008/pages/lecture-notes/'],['MIT OpenCourseWare · Dynamic Programming I','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/resources/mit6_006f11_lec19/'],['MIT OpenCourseWare · Dynamic Programming II','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/resources/mit6_006f11_lec20/']]
};
})();
