(()=>{
const {table,flow}=CS.helpers;
CS.lessons['ch08-l01']={
 lead:'폴더와 댓글처럼 위아래 관계가 있는 자료는 한 줄보다 가지가 뻗는 트리로 표현하면 구조와 탐색 과정을 보기 쉬워져요.',
 goals:['루트·부모·자식·깊이·높이를 간선 수로 설명해요.','전위·중위·후위 순회의 방문 시점과 BST 탐색 경로를 구별해요.','BST의 균형과 힙의 우선순위 규칙이 필요한 이유를 비교해요.'],prerequisites:['ch04-l02','ch07-l01'],sections:[
 {id:'b01',title:'트리는 한 루트에서 가지가 뻗는 계층 구조예요',html:`<p><strong>트리</strong>는 정점인 노드와 연결인 간선으로 계층을 표현해요. 루트 트리에서는 시작 노드가 <strong>루트</strong>이고, 바로 아래 연결은 부모·자식 관계예요. 자식이 없는 노드는 리프라고 해요. 한 자식으로 내려갈 때마다 깊이가 1씩 늘어요.</p><figure class="teaching-figure concept-figure"><div class="tree-family-visual" aria-label="루트 A 아래 B와 C, B 아래 D와 E가 연결된 트리"><div class="tf-node root">A<small>깊이 0</small></div><div class="tf-lines top"><i></i><i></i></div><div class="tf-level"><span>B<small>부모</small></span><span>C<small>리프</small></span></div><div class="tf-lines bottom"><i></i><i></i></div><div class="tf-level leaves"><span>D</span><span>E</span></div></div><figcaption><strong>관계는 노드 하나가 아니라 연결을 따라 정해져요</strong><ul class="picture-key"><li><b>A</b>부모가 없는 루트이며 깊이는 0이에요.</li><li><b>B와 C</b>A의 자식이고 서로 형제예요.</li><li><b>D와 E</b>자식이 없는 리프이며 깊이는 2예요.</li></ul></figcaption></figure><p>이 교안에서 노드의 깊이는 루트부터 그 노드까지의 간선 수, 트리의 높이는 루트부터 가장 먼 리프까지의 최대 간선 수로 정의해요. 교재에 따라 높이를 노드 수로 세거나 빈 트리의 높이를 다르게 정할 수 있으므로 기준을 함께 적어야 해요.</p>`},
 {id:'b02',title:'순회는 자신을 언제 방문하느냐로 나뉘어요',html:`<p>트리의 모든 노드를 한 번씩 처리하려면 방문 순서를 정해야 해요. 이진 트리에서 <strong>전위</strong>는 자신-왼쪽-오른쪽, <strong>중위</strong>는 왼쪽-자신-오른쪽, <strong>후위</strong>는 왼쪽-오른쪽-자신 순서예요. 재귀 호출은 같은 규칙을 작은 서브트리에 반복해요.</p><figure class="teaching-figure concept-figure"><div class="traversal-orders-visual" aria-label="같은 세 노드 트리의 전위 중위 후위 방문 순서를 비교"><div class="tiny-tree"><span>2</span><b>1</b><b>3</b></div><div class="order-lines"><p><strong>전위</strong><i>2</i><i>1</i><i>3</i></p><p><strong>중위</strong><i>1</i><i>2</i><i>3</i></p><p><strong>후위</strong><i>1</i><i>3</i><i>2</i></p></div></div><figcaption><strong>트리 모양은 같고 자신을 기록하는 시점만 달라요</strong><ul class="picture-key"><li><b>전위</b>서브트리에 들어가자마자 자신을 처리해요.</li><li><b>중위</b>왼쪽을 마친 뒤 자신을 처리해요.</li><li><b>후위</b>두 자식을 모두 마친 뒤 자신을 처리해요.</li></ul></figcaption></figure><p>중위 순회라는 이름은 왼쪽·오른쪽 두 자식의 사이에 자신을 방문한다는 뜻이므로 주로 이진 트리에서 사용해요. 순회 순서만으로는 트리가 균형인지, 값이 BST 규칙을 지키는지 알 수 없어요.</p>`},
 {id:'b03',title:'BST는 비교 결과로 왼쪽이나 오른쪽을 골라요',html:`<p>중복 키가 없는 <strong>이진 탐색 트리(BST)</strong>에서는 각 노드보다 작은 키가 왼쪽 서브트리, 큰 키가 오른쪽 서브트리에 있어요. 찾는 값과 현재 키를 비교할 때 한쪽 서브트리는 후보에서 제외할 수 있어요. 아래에서 입력 순서가 트리 모양을 어떻게 바꾸는지도 확인해 보세요.</p>`,lab:'bst-traversal'},
 {id:'b04',title:'같은 키도 넣는 순서에 따라 높이가 달라져요',html:`<p><code>1,2,3,4,5</code>를 단순 BST에 차례로 넣으면 모든 노드가 오른쪽으로 이어질 수 있어요. 이때 탐색 경로는 연결 리스트처럼 길어져 최악에는 Θ(n)이 돼요. 균형 BST는 회전 같은 규칙으로 높이를 Θ(log n) 규모로 유지해 탐색·삽입·삭제의 최악 시간을 제한하려고 해요.</p><figure class="teaching-figure concept-figure"><div class="balance-compare-visual" aria-label="같은 다섯 키가 균형 트리와 오른쪽으로 편향된 트리를 이루는 비교"><div class="balanced-shape"><b>균형에 가까움</b><span class="top"></span><p><span></span><span></span></p><p><i></i><i></i></p></div><div class="skewed-shape"><b>편향됨</b><span></span><span></span><span></span><span></span><span></span></div></div><figcaption><strong>노드 수보다 실제로 지나야 할 높이가 탐색 비용을 좌우해요</strong><ul class="picture-key"><li><b>왼쪽</b>분기가 나뉘어 한 번 비교할 때 후보가 크게 줄어요.</li><li><b>오른쪽</b>한 방향으로 이어져 여러 노드를 차례로 방문해요.</li><li><b>입력 순서</b>단순 BST의 모양과 높이를 바꿀 수 있어요.</li></ul></figcaption></figure><div class="info">“BST 탐색은 항상 O(log n)”이라고 외우면 편향된 경우를 놓쳐요. 높이가 h일 때 기본 연산은 보통 O(h)이며, 균형을 보장할 때 h=O(log n)을 기대할 수 있어요.</div>`},
 {id:'b05',title:'힙은 전체 정렬보다 가장 높은 우선순위를 빠르게 꺼내요',html:`<p><strong>최소 힙</strong>은 완전 이진 트리 모양을 유지하고 부모 키가 자식 키보다 작거나 같다는 규칙을 지켜요. 그래서 루트가 전체 최소지만, 형제나 서로 다른 서브트리 사이의 전체 순서는 정해지지 않아요. 새 값을 끝에 넣고 위로 올리거나, 루트를 제거한 뒤 마지막 값을 내려 보내 규칙을 회복해요.</p><figure class="teaching-figure concept-figure"><div class="heap-priority-visual" aria-label="최소 힙에 2를 끝에 넣은 뒤 부모와 바꾸어 위로 올리는 과정"><div class="heap-before"><b>3</b><p><span>5</span><span>7</span></p><p><i>9</i><i class="incoming">2</i></p></div><div class="heap-rise">↑</div><div class="heap-after"><b>2</b><p><span>3</span><span>7</span></p><p><i>9</i><i>5</i></p></div></div><figcaption><strong>2는 부모보다 작을 동안 위로 올라가 루트가 돼요</strong><ul class="picture-key"><li><b>완전한 모양</b>마지막 층을 왼쪽부터 채워 배열로 표현하기 좋아요.</li><li><b>힙 규칙</b>각 부모와 자식 사이의 우선순위만 보장해요.</li><li><b>우선순위 큐</b>최소 확인은 보통 O(1), 삽입·제거는 O(log n)이에요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'트리 종류마다 지키는 약속과 빠른 연산이 달라요',html:`${table(['구조','핵심 약속','잘 맞는 질문'],[['일반 루트 트리','부모·자식의 계층 관계','폴더·문서 구조를 어떻게 표현할까?'],['이진 트리','한 노드의 자식이 최대 둘','재귀 분기와 표현을 어떻게 단순화할까?'],['이진 탐색 트리','왼쪽 키 < 자신 < 오른쪽 키','정렬된 키를 비교하며 찾을까?'],['균형 탐색 트리','BST 조건과 제한된 높이','최악 탐색 비용도 제한할까?'],['최소·최대 힙','완전한 모양과 부모-자식 우선순위','가장 급한 항목을 반복해서 꺼낼까?']])}<p>자료구조의 이름보다 필요한 연산을 먼저 적어 보세요. 정렬 순서대로 모두 훑을지, 특정 키를 찾을지, 최소 하나만 반복해서 꺼낼지에 따라 알맞은 트리가 달라져요.</p>`}
 ],questions:[
 {q:'4,2,6,1,3을 중복 없는 BST에 넣고 중위 순회한 결과는?',options:['1,2,3,4,6','4,2,1,3,6','1,3,2,6,4'],answer:0,feedback:['맞아요. BST의 왼쪽-자신-오른쪽을 따르면 키가 오름차순이에요.','이 순서는 전위 순회 결과예요.','이 순서는 후위 순회 결과예요.'],review:'b02'},
 {q:'1,2,3,4,5를 단순 BST에 순서대로 넣었을 때 탐색이 느려질 수 있는 이유는?',options:['모든 값이 자동으로 같은 키가 되어서','트리가 한 방향으로 편향되어 높이가 커질 수 있어서','중위 순회가 금지되어서'],answer:1,feedback:['서로 다른 다섯 키예요.','맞아요. 기본 연산 비용은 트리 높이의 영향을 받아요.','순회 가능 여부와 트리의 편향은 다른 문제예요.'],review:'b04'},
 {q:'최소 힙이 직접 보장하는 것은?',options:['배열 전체가 오름차순임','각 부모가 자식보다 작거나 같고 루트가 최소임','중위 순회가 언제나 입력 순서임'],answer:1,feedback:['힙 배열 전체가 정렬됐다는 뜻은 아니에요.','맞아요. 부모-자식 우선순위 규칙으로 루트 최소를 보장해요.','힙은 BST의 중위 정렬 규칙을 보장하지 않아요.'],review:'b05'}
 ],summary:['트리의 깊이와 높이는 어떤 기준으로 세는지 함께 밝히고 부모·자식 관계를 간선으로 읽어요.','전위·중위·후위는 자신을 방문하는 시점이 다르고 BST 탐색은 키 비교로 한쪽 후보를 버려요.','BST의 속도는 높이에 달렸고, 힙은 전체 정렬 대신 루트의 우선순위를 빠르게 제공해요.'],nextQuestion:'도시가 여러 길로 연결된 그래프에서는 가장 가까운 길과 비용이 가장 적은 길이 언제 달라질까요?',sources:[['MIT OpenCourseWare · Binary Trees, Part 1','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/376714cc85c6c784d90eec9c575ec027_MIT6_006S20_lec6.pdf'],['MIT OpenCourseWare · 6.006 Lecture Notes','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-notes/'],['NIST · Dictionary of Algorithms and Data Structures','https://www.nist.gov/publications/dictionary-algorithms-and-data-structures']]
};

CS.lessons['ch08-l02']={
 lead:'친구 관계와 도로망처럼 한 대상이 여러 대상과 연결되면 트리의 부모·자식만으로는 부족해요. 그래프는 연결과 비용을 그대로 표현해요.',
 goals:['정점·간선·방향·가중치와 두 그래프 표현의 비용을 설명해요.','방문 기록을 사용해 BFS와 DFS가 순환 그래프에서 끝나는 과정을 구별해요.','최소 간선 경로와 최소 비용 경로, 위상 정렬의 조건을 비교해요.'],prerequisites:['ch08-l01','ch07-l02'],sections:[
 {id:'b01',title:'그래프는 정점과 간선으로 여러 연결을 표현해요',html:`<p><strong>그래프</strong> G=(V,E)는 대상인 정점 집합 V와 관계인 간선 집합 E로 표현해요. 무방향 간선 A-B는 양쪽 연결, 방향 간선 A→B는 정해진 방향의 연결이에요. 간선에는 거리·시간·가격 같은 가중치를 붙일 수 있어요. 그래프에는 여러 경로와 사이클, 연결되지 않은 정점이 있을 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="graph-kinds-visual" aria-label="무방향 그래프와 방향 가중 그래프 비교"><div><b>무방향</b><span>A</span><i></i><span>B</span><i></i><span>C</span></div><div><b>방향·가중치</b><span>A</span><i class="arrow"><small>4</small></i><span>B</span><i class="arrow"><small>2</small></i><span>C</span></div></div><figcaption><strong>선의 방향과 숫자가 관계의 의미를 바꿔요</strong><ul class="picture-key"><li><b>정점</b>A·B·C처럼 관계의 대상이에요.</li><li><b>간선</b>두 정점이 직접 연결됐는지 나타내요.</li><li><b>가중치</b>간선 하나를 이용하는 비용이며 음수 여부도 알고리즘에 영향을 줘요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'인접 리스트와 행렬은 연결을 저장하는 비용이 달라요',html:`<p><strong>인접 리스트</strong>는 각 정점에서 직접 이어진 이웃 목록을 저장해 공간이 보통 O(V+E)예요. <strong>인접 행렬</strong>은 모든 정점 쌍의 연결 여부를 V×V 칸에 저장해 O(V²) 공간을 쓰지만 특정 두 정점의 연결을 한 칸에서 확인하기 쉬워요. 무방향 그래프에서는 한 간선을 양쪽 이웃 목록에 기록할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="graph-storage-visual" aria-label="같은 세 정점 그래프의 인접 리스트와 인접 행렬 표현"><div class="adj-list"><b>리스트</b><p>A <span>B</span><span>C</span></p><p>B <span>A</span></p><p>C <span>A</span></p></div><div class="adj-matrix"><b>행렬</b><p><i>0</i><i>1</i><i>1</i></p><p><i>1</i><i>0</i><i>0</i></p><p><i>1</i><i>0</i><i>0</i></p></div></div><figcaption><strong>같은 연결도 자주 묻는 질문에 맞춰 다르게 저장해요</strong><ul class="picture-key"><li><b>리스트</b>실제로 있는 이웃을 따라 탐색하기 좋아요.</li><li><b>행렬</b>A-B처럼 특정 쌍의 연결을 바로 확인하기 좋아요.</li><li><b>희소 그래프</b>가능한 간선보다 실제 간선이 적으면 리스트의 공간 이점이 커져요.</li></ul></figcaption></figure>${table(['질문','인접 리스트','인접 행렬'],[['공간','O(V+E)','O(V²)'],['정점 v의 모든 이웃','v의 차수에 비례','행 한 줄 V칸 확인'],['u-v 직접 연결 확인','u의 목록에서 찾기','행렬 한 칸 확인']])}`},
 {id:'b03',title:'BFS는 층별로, DFS는 한 갈래를 깊게 방문해요',html:`<p><strong>BFS</strong>는 큐를 사용해 시작점과 가까운 층부터 방문하므로 가중치 없는 그래프에서 최소 간선 수 경로를 찾아요. <strong>DFS</strong>는 재귀 호출이나 스택으로 한 갈래를 깊게 간 뒤 돌아와 다른 갈래를 봐요. 연결 요소·사이클·선후 관계를 분석하는 데 쓰이지만 일반적으로 최단 경로를 보장하지 않아요.</p><figure class="teaching-figure concept-figure"><div class="bfs-dfs-visual" aria-label="같은 분기 그래프에서 BFS는 층별, DFS는 한 가지를 깊게 방문하는 비교"><div class="bfs-rings"><b>BFS</b><span>A</span><p><i>B</i><i>C</i></p><p><em>D</em><em>E</em><em>F</em></p></div><div class="dfs-branch"><b>DFS</b><span>A</span><i>B</i><em>D</em><small>↩ C → F</small></div></div><figcaption><strong>다음에 꺼낼 정점을 큐에 둘지 스택에 둘지가 순서를 바꿔요</strong><ul class="picture-key"><li><b>BFS</b>A에서 간선 1개인 B·C를 먼저 처리해요.</li><li><b>DFS</b>A-B-D처럼 한 갈래를 먼저 끝까지 따라가요.</li><li><b>방문 기록</b>사이클에서 같은 정점을 끝없이 다시 넣지 않게 해요.</li></ul></figcaption></figure><p>방문 표시를 큐나 스택에 넣을 때 할지, 꺼낼 때 할지에 따라 중복 등록 횟수가 달라질 수 있어요. 어느 방식을 택하든 각 정점을 처리하는 규칙과 부모 기록을 일관되게 유지해야 경로를 복원할 수 있어요.</p>`},
 {id:'b04',title:'같은 지도에서 최소 간선과 최소 비용을 비교해요',html:`<p>A-C 직접 길은 간선 하나지만 비용이 5예요. A-B-C는 간선 둘이지만 비용 합이 2예요. BFS와 다익스트라를 번갈아 실행해 “가까운”이라는 말이 간선 수인지 비용 합인지 확인해 보세요.</p>`,lab:'graph-paths'},
 {id:'b05',title:'다익스트라는 확정된 최소 비용을 바깥으로 넓혀요',html:`<p>다익스트라 알고리즘은 시작점 비용을 0, 나머지를 ∞로 두고 아직 확정하지 않은 정점 중 현재 비용이 가장 작은 정점을 선택해요. 그 정점을 거쳐 이웃으로 가는 비용이 더 작으면 거리와 부모를 갱신해요. 간선 가중치가 모두 음이 아닐 때 선택한 거리가 뒤에서 더 작아지지 않는다는 성질을 사용해요.</p><figure class="teaching-figure concept-figure"><div class="dijkstra-wave-visual" aria-label="A에서 B 비용1과 C 비용5를 기록한 뒤 B를 거쳐 C 비용2로 줄이는 그림"><div class="dj-nodes"><span>A<small>0 확정</small></span><span>B<small>1 확정</small></span><span>C<small><del>5</del> 2</small></span></div><div class="dj-edges"><i>1</i><i>1</i><i class="direct">5</i></div><p>A → B → C <strong>비용 2</strong></p></div><figcaption><strong>직접 경로 5보다 B를 거친 1+1이 작아 C의 값을 갱신해요</strong><ul class="picture-key"><li><b>임시 거리</b>지금까지 발견한 경로 중 가장 작은 비용이에요.</li><li><b>확정</b>가장 작은 임시 거리의 정점을 하나 선택해요.</li><li><b>음수 간선</b>확정 뒤 더 작은 경로가 나타날 수 있어 이 절차의 전제가 깨져요.</li></ul></figcaption></figure><div class="info">음수 간선이 있다고 최단 경로 문제가 모두 불가능한 것은 아니에요. 다익스트라 대신 Bellman-Ford처럼 음수 간선을 다루는 다른 알고리즘과 음수 사이클 검사를 고려해야 해요.</div>`},
 {id:'b06',title:'위상 정렬은 선행 관계를 지키는 순서를 찾아요',html:`<p><strong>위상 정렬</strong>은 방향 그래프에서 모든 간선 u→v에 대해 u가 v보다 먼저 오도록 정점을 나열해요. 선수 과목·빌드 작업처럼 선행 관계를 표현하는 데 쓰며, 결과가 하나뿐일 필요는 없어요. 방향 사이클이 있으면 모든 간선의 앞뒤 조건을 동시에 만족하는 순서가 없어요.</p>${flow(['요구사항 확정','설계','구현','테스트','배포'])}${table(['상황','가능한 처리'],[['진입 차수 0인 정점이 있음','그 정점을 결과에 넣고 나가는 간선을 제거'],['여러 정점의 진입 차수가 0','그중 어떤 것을 먼저 골라도 서로 다른 유효 순서 가능'],['정점을 모두 처리하기 전에 후보가 사라짐','남은 부분에 방향 사이클이 있어 위상 순서 없음']])}<p>BFS·DFS·다익스트라·위상 정렬은 모두 그래프를 보지만 답의 질문이 달라요. “간선 수가 적은 경로”, “깊게 조사”, “비용 합이 작은 경로”, “선행 조건을 지키는 순서” 중 무엇이 필요한지 먼저 정해야 해요.</p>`}
 ],questions:[
 {q:'기본 그래프에서 A에서 C까지 BFS가 고르는 최소 간선 경로는?',options:['A → C','A → B → C','A → D → C'],answer:0,feedback:['맞아요. 직접 간선 하나가 최소 간선 수예요.','비용은 작지만 간선은 두 개예요.','D는 연결되지 않아 경로가 없어요.'],review:'b04'},
 {q:'A-B 비용1, B-C 비용1, A-C 비용5일 때 다익스트라의 최소 비용 경로는?',options:['A → C, 비용5','A → B → C, 비용2','A → D → C, 비용0'],answer:1,feedback:['직접 길보다 비용 합이 작은 우회 경로가 있어요.','맞아요. 1+1=2가 5보다 작아요.','D는 떨어져 있어 유효한 간선 경로가 아니에요.'],review:'b05'},
 {q:'방향 그래프에 A→B→C→A 사이클이 있으면 위상 정렬은?',options:['항상 A,B,C 순서로 가능해요.','모든 선행 관계를 만족하는 순서가 없어요.','간선 비용을 0으로 바꾸면 자동 해결돼요.'],answer:1,feedback:['C→A는 C가 A보다 먼저여야 하므로 모순이에요.','맞아요. 방향 사이클은 위상 순서를 막아요.','위상 정렬은 가중치보다 방향 선행 관계를 봐요.'],review:'b06'}
 ],summary:['그래프는 방향·가중치·연결되지 않은 정점을 표현하며 인접 리스트와 행렬은 공간·조회 비용이 달라요.','BFS는 최소 간선 수 경로를 찾고 DFS는 한 갈래를 깊게 보며, 둘 다 방문 기록이 필요해요.','다익스트라는 음이 아닌 가중치에서 최소 비용을 찾고, 위상 정렬은 사이클 없는 방향 그래프의 선행 순서를 찾아요.'],nextQuestion:'프로그램이 파일이나 장치 기능을 요청할 때 운영체제 커널은 어떤 경계를 통과시킬까요?',sources:[['MIT OpenCourseWare · Breadth-First Search','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/196a95604877d326c6586e60477b59d4_MIT6_006S20_lec9.pdf'],['MIT OpenCourseWare · Graph and shortest-path lecture notes','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/resources/lecture-notes/'],['MIT OpenCourseWare · BFS, DFS and Dijkstra recitations','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2008/pages/recitations/']]
};
})();
