(()=>{
const {table,flow}=CS.helpers;
CS.lessons['ch09-l01']={
 lead:'앱이 파일을 읽고 화면에 그릴 수 있는 것은 하드웨어를 마음대로 조작해서가 아니라, 커널이 정한 안전한 입구로 요청하기 때문이에요.',
 goals:['운영체제와 커널의 관계, 사용자 모드와 커널 모드의 권한 차이를 설명해요.','시스템 콜의 진입·검사·대기·복귀 흐름을 상태 변화와 함께 따라가요.','시스템 콜·인터럽트·예외를 발생 원인과 현재 명령과의 관계로 구별해요.'],prerequisites:['ch06-l01','ch06-l02'],sections:[
 {id:'b01',title:'커널은 프로그램과 하드웨어 사이에서 자원을 관리해요',html:`<p><strong>운영체제</strong>는 프로그램이 컴퓨터를 쓰게 해 주는 소프트웨어 전체를 가리키고, <strong>커널</strong>은 그중 CPU·메모리·장치 같은 핵심 자원을 보호하고 배분하는 중심부예요. 셸과 시스템 도구처럼 사용자 공간에서 실행되는 구성 요소까지 커널이라고 부르지는 않아요.</p><figure class="teaching-figure concept-figure"><div class="kernel-core-visual" aria-label="앱에서 라이브러리와 커널을 거쳐 CPU 메모리 장치에 이르는 층"><div class="kc-apps"><span>그림 앱</span><span>브라우저</span><span>게임</span></div><i>요청</i><div class="kc-kernel"><b>커널</b><small>보호 · 배분 · 공통 규칙</small></div><i>제어</i><div class="kc-hardware"><span>CPU</span><span>메모리</span><span>장치</span></div></div><figcaption><strong>커널은 여러 프로그램의 요청을 한정된 하드웨어에 안전하게 연결해요</strong><ul class="picture-key"><li><b>추상화</b>앱은 장치별 신호보다 파일·프로세스 같은 공통 개념을 사용해요.</li><li><b>보호</b>한 앱이 다른 앱의 메모리나 장치를 함부로 바꾸지 못하게 해요.</li><li><b>배분</b>CPU 시간과 메모리, 입출력 순서를 여러 작업에 나눠 줘요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'CPU의 실행 모드는 할 수 있는 명령의 범위를 나눠요',html:`<p>CPU는 현재 코드의 권한 수준을 나타내는 실행 모드를 지원해요. 보통 앱은 제한된 <strong>사용자 모드</strong>에서 실행되고, 커널은 장치 제어와 주소 공간 관리 같은 특권 연산을 수행할 수 있는 <strong>커널 모드</strong>에서 실행돼요. 이름과 단계 수는 CPU 구조마다 다르지만 보호 경계의 목적은 같아요.</p><figure class="teaching-figure concept-figure"><div class="mode-rings-visual" aria-label="바깥 사용자 모드에서 보호된 입구를 통해 안쪽 커널 모드로 들어가는 그림"><div class="mode-user"><b>USER</b><span>계산 · 일반 메모리 접근</span><div class="mode-gate">시스템 콜 입구 ↓</div><div class="mode-kernel"><b>KERNEL</b><span>장치 · 주소 공간 · 스케줄러</span></div></div></div><figcaption><strong>경계는 앱의 기능을 막는 벽이 아니라 검사 가능한 입구를 만들어요</strong><ul class="picture-key"><li><b>USER</b>자신에게 허용된 코드와 메모리 안에서 실행해요.</li><li><b>진입점</b>CPU가 정한 방식으로 모드를 바꾸고 커널의 지정된 코드로 이동해요.</li><li><b>KERNEL</b>요청을 곧바로 믿지 않고 번호·인자·주소·권한을 검사해요.</li></ul></figcaption></figure><div class="info">“커널 함수를 호출한다”는 설명만으로는 보호 경계를 놓쳐요. 앱은 보통 라이브러리 함수에서 시작하지만, 실제 커널 진입에는 아키텍처가 제공하는 시스템 콜 명령과 정해진 진입 절차가 필요해요.</div>`},
 {id:'b03',title:'파일 읽기는 요청한 자리로 돌아올 경로까지 보관해요',html:`<p><code>read()</code>를 요청하면 CPU는 사용자 코드의 다음 실행 위치와 레지스터 문맥을 보관하고 커널 진입점으로 이동해요. 커널은 파일 설명자와 사용자 버퍼, 권한을 검사해요. 장치 응답을 기다려야 하면 프로세스는 WAITING이 되고, 완료 후 READY가 되어 스케줄될 때 비로소 다시 실행돼요.</p><figure class="teaching-figure concept-figure"><div class="syscall-route-visual" aria-label="USER 요청, KERNEL 검사, 장치 대기, 준비, USER 복귀의 시스템 콜 흐름"><span>USER<br><small>read 요청</small></span><i>진입</i><span>KERNEL<br><small>검사</small></span><i>요청</i><span>장치<br><small>완료 알림</small></span><i>준비</i><span>USER<br><small>다음 명령</small></span></div><figcaption><strong>READY는 실행할 수 있다는 뜻이며 즉시 실행 중이라는 뜻은 아니에요</strong><ul class="picture-key"><li><b>복귀 문맥</b>요청이 끝난 뒤 이어갈 사용자 코드 위치를 기억해요.</li><li><b>WAITING</b>입출력을 기다리는 동안 다른 준비된 프로세스가 CPU를 쓸 수 있어요.</li><li><b>반환</b>성공 값이나 오류를 사용자 모드의 요청 다음 위치로 전달해요.</li></ul></figcaption></figure>`,lab:'system-call-boundary'},
 {id:'b04',title:'커널 모드 진입과 문맥 교환은 같은 말이 아니에요',html:`<p>시스템 콜을 처리하려고 USER에서 KERNEL로 바뀌어도 같은 프로세스의 요청을 계속 처리할 수 있어요. <strong>문맥 교환</strong>은 CPU가 실행할 프로세스나 스레드를 바꾸며 레지스터와 실행 위치를 저장·복원하는 일이에요. 입출력 대기나 타이머 인터럽트 뒤 스케줄러가 다른 작업을 고르면 문맥 교환이 일어날 수 있어요.</p>${table(['변화','무엇이 바뀌나','항상 함께 일어나나'],[['모드 전환','CPU 권한 수준과 실행 코드 영역','시스템 콜 진입에는 필요'],['프로세스 상태 전환','RUNNING·WAITING·READY','요청이 바로 끝나면 대기가 없을 수 있음'],['문맥 교환','CPU를 쓰는 프로세스·스레드','모드 전환마다 일어나는 것은 아님']])}`},
 {id:'b05',title:'인터럽트와 예외는 발생 원인을 보면 구별하기 쉬워요',html:`<p><strong>인터럽트</strong>는 타이머나 장치 완료처럼 현재 실행 명령 바깥에서 비동기적으로 도착하는 알림이에요. <strong>예외</strong>는 0으로 나누기나 페이지 폴트처럼 현재 명령을 실행하다 동기적으로 생겨요. 시스템 콜도 프로그램이 의도적으로 실행한 명령으로 커널에 들어가므로 넓은 의미에서 동기적 트랩·예외 경로를 사용할 수 있지만 용어와 구현은 CPU마다 달라요.</p><figure class="teaching-figure concept-figure"><div class="event-sources-visual" aria-label="타이머와 장치 인터럽트, 현재 명령의 예외, 의도적인 시스템 콜 비교"><div><b>인터럽트</b><span>타이머</span><span>장치 완료</span><small>현재 명령 바깥에서 도착</small></div><div><b>예외</b><span>0으로 나누기</span><span>페이지 폴트</span><small>현재 명령 때문에 발생</small></div><div><b>시스템 콜</b><span>read</span><span>write</span><small>프로그램이 의도해 진입</small></div></div><figcaption><strong>세 경로 모두 커널 처리로 이어질 수 있지만 시작 원인이 달라요</strong><ul class="picture-key"><li><b>비동기</b>장치의 완료 시점은 실행 중인 명령과 직접 맞지 않을 수 있어요.</li><li><b>동기</b>같은 명령과 상태라면 같은 지점에서 예외가 생겨요.</li><li><b>복귀 판단</b>커널은 원인을 처리한 뒤 재시도·오류 전달·다른 작업 실행을 결정해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'보호된 입구는 검사와 되돌아갈 위치를 함께 만든다',html:`${flow(['USER에서 요청','KERNEL 진입','인자·권한 검사','작업 또는 오류','복귀 문맥 복원','USER에서 계속'])}<p>정상 흐름만 외우지 말고 검사 실패를 함께 생각해 보세요. 권한이 없으면 커널은 장치에서 내용을 가져오지 않고 오류를 반환해야 해요. 장치를 기다린다면 요청한 프로세스가 쉬는 동안 다른 작업이 CPU를 쓸 수 있고, 완료 알림을 받아도 스케줄되기 전까지는 READY 상태일 수 있어요.</p>`}
 ],questions:[
 {q:'사용자 프로그램이 파일을 읽기 위해 커널 기능을 요청하는 보호된 입구는?',options:['시스템 콜','일반 배열 인덱스','화면 새로 고침'],answer:0,feedback:['맞아요. 시스템 콜은 정해진 커널 진입 경로예요.','배열 연산은 일반 사용자 코드에서도 실행할 수 있어요.','화면 갱신은 보호 모드 전환의 이름이 아니에요.'],review:'b02'},
 {q:'장치 완료 후 프로세스가 READY가 되었다는 뜻은?',options:['CPU에서 이미 실행 중이다','실행할 수 있으며 스케줄되기를 기다린다','반드시 종료되었다'],answer:1,feedback:['RUNNING과 READY는 구별해야 해요.','맞아요. 준비됐지만 CPU를 배정받기 전일 수 있어요.','완료된 것은 장치 요청이며 프로세스 전체가 아니에요.'],review:'b03'},
 {q:'현재 명령의 0으로 나누기 때문에 동기적으로 발생하는 것은?',options:['장치 완료 인터럽트','예외','파이프 EOF'],answer:1,feedback:['장치 완료는 현재 명령과 비동기적으로 도착할 수 있어요.','맞아요. 현재 명령 수행 자체가 원인이에요.','EOF는 스트림 읽기의 결과예요.'],review:'b05'}
 ],summary:['커널은 운영체제의 핵심으로 자원을 보호·배분하며 앱은 보통 사용자 모드에서 실행해요.','시스템 콜은 복귀 문맥을 보관하고 커널에서 인자와 권한을 검사한 뒤 성공 값이나 오류를 USER로 돌려줘요.','인터럽트는 외부에서 비동기적으로, 예외와 의도한 시스템 콜은 현재 명령에 맞춰 동기적으로 커널 경로를 시작할 수 있어요.'],nextQuestion:'장치가 느리거나 두 프로세스가 데이터를 주고받을 때 기다림과 버퍼는 어떻게 동작할까요?',sources:[['OSTEP 한국어판 · 제한적 직접 실행 원리','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/06-cpu-mechanisms.pdf'],['Linux man-pages · read(2)','https://man7.org/linux/man-pages/man2/read.2.html'],['Intel · 시스템 프로그래밍 가이드','https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html']]
};

CS.lessons['ch09-l02']={
 lead:'CPU보다 느리고 제각각인 장치를 효율적으로 다루고, 서로 분리된 프로세스가 안전하게 데이터를 주고받으려면 드라이버·알림·버퍼 규칙이 필요해요.',
 goals:['드라이버의 역할과 폴링·인터럽트·DMA의 CPU 참여 방식을 비교해요.','블로킹·논블로킹과 동기·비동기를 서로 다른 관점으로 설명해요.','파이프의 유한 버퍼, FIFO 전달, 닫힘·EOF·쓰기 실패 규칙을 실습해요.'],prerequisites:['ch09-l01','ch07-l02'],sections:[
 {id:'b01',title:'장치 드라이버는 운영체제 요청을 장치 언어로 바꿔요',html:`<p>키보드·SSD·네트워크 카드는 제어 레지스터와 명령 형식이 서로 달라요. <strong>장치 드라이버</strong>는 운영체제의 공통 입출력 요청을 특정 장치가 이해하는 명령으로 바꾸고, 완료 상태와 오류를 다시 운영체제에 알려요. 드라이버가 모든 차이를 없애는 것은 아니지만 상위 코드가 장치 세부 규칙에 덜 의존하게 해요.</p><figure class="teaching-figure concept-figure"><div class="driver-bridge-visual" aria-label="공통 읽기 쓰기 요청을 드라이버가 SSD 네트워크 키보드 명령으로 변환"><div><span>read</span><span>write</span><span>status</span></div><i>공통 요청</i><b>장치 드라이버<small>번역 · 순서 · 오류</small></b><i>장치별 명령</i><div><span>SSD</span><span>네트워크</span><span>키보드</span></div></div><figcaption><strong>상위의 공통 규칙과 아래의 장치별 규칙을 드라이버가 연결해요</strong><ul class="picture-key"><li><b>명령</b>읽기 위치와 크기 같은 요청을 장치 형식에 맞춰요.</li><li><b>상태</b>바쁨·완료·오류를 읽어 커널에 전달해요.</li><li><b>보호</b>보통 커널 안의 검증된 코드가 장치 제어 권한을 사용해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'폴링·인터럽트·DMA는 CPU가 참여하는 때가 달라요',html:`<p><strong>폴링</strong>은 CPU가 장치 상태를 반복해서 확인하고, <strong>인터럽트</strong>는 다른 일을 하다가 장치의 완료 알림을 받아 처리해요. <strong>DMA</strong>는 CPU가 전송 조건을 설정한 뒤 장치와 메모리 사이의 큰 데이터 이동을 DMA 엔진이 맡도록 해 CPU의 바이트별 복사 부담을 줄여요. DMA도 설정·동기화·완료 처리가 필요하므로 CPU 작업이 0이 되는 것은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="io-notify-visual" aria-label="폴링 인터럽트 DMA에서 CPU 장치 메모리의 역할 비교"><div><b>폴링</b><p>CPU ↔ 장치 ↔ 장치</p><small>계속 상태 확인</small></div><div><b>인터럽트</b><p>CPU ··· 장치 → CPU</p><small>완료 때 알림</small></div><div><b>DMA</b><p>장치 ⇄ 메모리</p><small>CPU는 설정·완료 처리</small></div></div><figcaption><strong>무조건 하나가 최고가 아니라 지연·빈도·전송량에 따라 비용이 달라져요</strong><ul class="picture-key"><li><b>폴링</b>짧게 끝날 작업은 전환 비용을 줄일 수 있지만 오래 기다리면 CPU 시간을 써요.</li><li><b>인터럽트</b>기다리는 동안 다른 일을 할 수 있지만 알림 처리 비용이 있어요.</li><li><b>DMA</b>큰 블록 전송에 유리하며 캐시·주소 매핑과 동기화 규칙을 지켜야 해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'블로킹과 동기라는 말은 서로 다른 질문에 답해요',html:`<p><strong>블로킹/논블로킹</strong>은 호출이 지금 결과를 낼 수 없을 때 호출한 실행 흐름을 기다리게 할지, 즉시 “아직 없음”을 반환할지를 봐요. <strong>동기/비동기</strong>는 완료를 누가 언제 확인하고 후속 작업을 이어 가는지에 초점을 둬요. API와 문맥마다 용어 사용이 조금씩 다르므로 반환 시점과 완료 알림 방식을 구체적으로 적는 편이 정확해요.</p><figure class="teaching-figure concept-figure"><div class="io-axes-visual" aria-label="즉시 반환 여부와 완료 통지 방식을 두 축으로 비교"><div class="axis-y"><span>호출 흐름 기다림</span><b>블로킹</b><b>논블로킹</b></div><div class="axis-grid"><span>기다렸다 결과</span><span>즉시 아직 없음</span><span>후속 호출로 확인</span><span>완료 알림·콜백</span></div><div class="axis-x"><b>동기적 확인</b><b>비동기 완료 통지</b></div></div><figcaption><strong>이름만 외우지 말고 “언제 반환하고, 누가 완료를 아는가”를 물어요</strong><ul class="picture-key"><li><b>블로킹 read</b>데이터·EOF·오류 중 하나가 결정될 때까지 호출 흐름이 쉴 수 있어요.</li><li><b>논블로킹 read</b>지금 데이터가 없으면 기다리지 않고 상태를 돌려줘요.</li><li><b>비동기 작업</b>요청 접수와 실제 완료가 분리되고 이벤트·콜백 등으로 완료를 알려요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'IPC 방법은 복사·주소 공간·연결 범위가 달라요',html:`<p>서로 다른 프로세스는 기본적으로 주소 공간이 분리돼 있어 통신 수단이 필요해요. <strong>파이프</strong>는 커널 버퍼의 바이트 스트림, <strong>소켓</strong>은 같은 컴퓨터나 네트워크의 양 끝 통신, <strong>공유 메모리</strong>는 여러 프로세스가 같은 메모리 영역을 매핑하는 방식이에요. 공유 메모리는 데이터 복사를 줄일 수 있지만 동시에 접근하는 순서를 락이나 원자 연산으로 맞춰야 해요.</p><figure class="teaching-figure concept-figure"><div class="ipc-methods-visual" aria-label="파이프 소켓 공유 메모리의 데이터 경로 비교"><div><b>파이프</b><p>P1 → <span>커널 버퍼</span> → P2</p></div><div><b>소켓</b><p>P1 → <span>통신 끝점</span> ⇢ P2</p></div><div><b>공유 메모리</b><p>P1 ⇄ <span>같은 영역</span> ⇄ P2</p></div></div><figcaption><strong>데이터 길뿐 아니라 동기화와 종료 규칙까지 함께 골라야 해요</strong><ul class="picture-key"><li><b>파이프</b>단방향 스트림으로 단순한 생산자·소비자 흐름에 잘 맞아요.</li><li><b>소켓</b>양방향과 네트워크 통신을 지원하지만 프로토콜 경계를 설계해야 해요.</li><li><b>공유 메모리</b>공통 영역을 빠르게 쓰지만 데이터 경합을 자동으로 해결하지 않아요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'두 칸 버퍼에서 기다림과 닫힘을 직접 확인해요',html:`<p>아래 모형에서 A와 B를 쓰면 버퍼가 가득 차 C는 기다려요. A를 하나 읽은 뒤 C를 쓰면 수신 순서는 A-B-C로 유지돼요. 버퍼를 모두 비우고 모든 쓰기 끝을 닫은 다음 읽어야 EOF가 도착해요. 반대로 읽기 끝이 모두 닫힌 뒤 쓰면 실패해요.</p>`,lab:'pipe-buffer'},
 {id:'b06',title:'파이프는 메시지 상자가 아니라 끝이 있는 바이트 흐름이에요',html:`${table(['상태','블로킹 읽기·쓰기의 결과'],[['빈 버퍼 + 쓰기 끝 열림','읽기는 새 데이터가 올 때까지 기다릴 수 있음'],['가득 찬 유한 버퍼','쓰기는 읽을 공간이 생길 때까지 기다릴 수 있음'],['버퍼 비움 + 모든 쓰기 끝 닫힘','읽기는 EOF를 반환'],['모든 읽기 끝 닫힘','쓰기는 실패하며 POSIX에서는 SIGPIPE/EPIPE가 관련됨']])}<p>실습의 A·B·C는 순서를 보기 위한 작은 쓰기 단위예요. 실제 POSIX 파이프는 바이트 스트림이므로 일반적으로 “한 번 쓴 메시지 하나”라는 경계를 읽는 쪽이 그대로 받는다고 가정하면 안 돼요. 응용 프로그램이 길이·구분자 같은 프레이밍 규칙을 따로 정해야 할 수 있어요.</p>`}
 ],questions:[
 {q:'CPU가 장치 상태를 반복해서 직접 확인하는 방식은?',options:['폴링','DMA','공유 메모리'],answer:0,feedback:['맞아요. 폴링은 상태 레지스터 등을 되풀이해 확인해요.','DMA는 설정 후 큰 데이터 이동 부담을 덜어 주는 방식이에요.','공유 메모리는 프로세스 간 통신 방법이에요.'],review:'b02'},
 {q:'빈 파이프의 모든 쓰기 끝이 닫힌 뒤 읽으면?',options:['새 데이터가 올 때까지 영원히 기다린다','EOF를 받는다','읽은 A가 다시 생긴다'],answer:1,feedback:['작성자가 없으므로 새 데이터가 올 수 없어요.','맞아요. 버퍼가 비고 모든 작성 끝이 닫혀야 EOF를 관찰해요.','읽은 데이터가 자동 복제되지는 않아요.'],review:'b06'},
 {q:'공유 메모리를 사용할 때에도 따로 필요한 것은?',options:['동시 접근 순서를 맞추는 동기화','항상 네트워크 연결','파이프의 메시지 경계'],answer:0,feedback:['맞아요. 같은 영역을 동시에 읽고 쓸 때 경합을 제어해야 해요.','같은 컴퓨터의 공유 메모리는 네트워크가 필수는 아니에요.','공유 메모리는 파이프가 아니며 자체 데이터 규약을 정해요.'],review:'b04'}
 ],summary:['드라이버는 공통 입출력 요청을 장치별 명령으로 연결하고 폴링·인터럽트·DMA는 CPU 참여 시점과 비용이 달라요.','블로킹 여부는 호출 흐름의 기다림, 동기·비동기는 완료를 확인하고 전달하는 방식에 초점을 둬요.','파이프는 유한 커널 버퍼의 바이트 스트림이며 공간 대기, FIFO 전달, 모든 쓰기 끝 닫힘 뒤 EOF, 읽기 끝 닫힘 뒤 쓰기 실패 규칙이 있어요.'],nextQuestion:'여러 프로세스와 스레드가 CPU를 나눠 쓸 때 운영체제는 어떤 순서와 기준으로 실행할까요?',sources:[['OSTEP 한국어판 · 입출력 장치','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/36_file-devices.pdf'],['Linux man-pages · pipe(7)','https://man7.org/linux/man-pages/man7/pipe.7.html'],['Linux Kernel · Dynamic DMA mapping Guide','https://docs.kernel.org/core-api/dma-api-howto.html']]
};
})();
