(()=>{
const {table,flow}=CS.helpers;
CS.lessons['ch10-l01']={
 lead:'프로그램이 보는 넓고 연속적인 주소와 실제 RAM의 흩어진 자리는 페이지 테이블이라는 대응표로 연결돼요.',
 goals:['가상 주소를 페이지 번호와 오프셋으로 나누고 물리 주소를 계산해요.','TLB 미스와 페이지 폴트가 서로 다른 상황임을 설명해요.','같은 참조열에서 FIFO와 LRU의 교체 결과를 비교하고 스래싱의 원리를 이해해요.'],prerequisites:['ch05-l01','ch09-l01'],sections:[
 {id:'b01',title:'가상 주소는 프로세스마다 독립된 주소 공간을 만들어요',html:`<p>프로그램의 명령과 포인터는 <strong>가상 주소</strong>를 사용해요. 메모리 관리 장치(MMU)와 운영체제가 만든 매핑은 이 주소를 RAM의 <strong>물리 주소</strong>로 바꿔요. 그래서 서로 다른 프로세스가 같은 가상 주소를 사용해도 다른 물리 프레임을 가리킬 수 있고, 허용되지 않은 영역은 접근을 막을 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="virtual-spaces-visual" aria-label="프로세스 A와 B의 같은 가상 주소가 서로 다른 물리 프레임에 연결"><div><b>프로세스 A</b><span>가상 페이지 2</span></div><div><b>프로세스 B</b><span>가상 페이지 2</span></div><i>주소 변환</i><div class="physical-stack"><b>RAM</b><span>프레임 7 · A</span><span>프레임 3 · B</span></div></div><figcaption><strong>주소 공간을 분리하면 같은 숫자의 포인터도 프로세스마다 다른 곳을 가리킬 수 있어요</strong><ul class="picture-key"><li><b>가상 주소</b>CPU가 프로그램 명령을 실행하며 내는 주소예요.</li><li><b>물리 주소</b>RAM에서 실제로 접근할 위치를 나타내요.</li><li><b>보호</b>페이지별 읽기·쓰기·실행 권한도 변환 정보와 함께 검사할 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'페이징은 주소와 메모리를 같은 크기의 조각으로 나눠요',html:`<p><strong>페이지</strong>는 가상 주소 공간의 고정 크기 조각, <strong>프레임</strong>은 물리 메모리의 같은 크기 조각이에요. 페이지 크기가 1024B라면 가상 주소 2053은 페이지 번호 ⌊2053÷1024⌋=2, 오프셋 5예요. 페이지 테이블에서 페이지2→프레임7을 찾으면 물리 주소는 7×1024+5=<strong>7173</strong>이에요.</p><figure class="teaching-figure concept-figure"><div class="address-split-visual" aria-label="가상 주소 2053을 페이지2와 오프셋5로 나누어 프레임7의 물리 주소7173 계산"><div><small>가상 주소</small><b>2053</b></div><i>÷ 1024</i><div class="split-parts"><span>페이지<strong>2</strong></span><span>오프셋<strong>5</strong></span></div><i>페이지표</i><div><small>프레임 7</small><b>7173</b></div></div><figcaption><strong>변환 때 오프셋은 그대로 두고 페이지 번호만 프레임 번호로 바꿔요</strong><ul class="picture-key"><li><b>경계</b>주소 1024는 페이지1의 첫 바이트라 오프셋이 0이에요.</li><li><b>페이지 테이블</b>가상 페이지의 프레임·현재 존재 여부·권한 같은 정보를 담아요.</li><li><b>재조합</b>프레임 번호×페이지 크기+오프셋으로 물리 주소를 만들어요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'TLB 미스와 페이지 폴트는 확인하는 단계가 달라요',html:`<p><strong>TLB</strong>는 최근 페이지 변환을 저장하는 작은 하드웨어 캐시예요. TLB에서 변환을 못 찾은 <strong>TLB 미스</strong>가 나도 페이지 테이블에 유효한 매핑이 있으면 RAM 접근을 계속할 수 있어요. 페이지 테이블이 해당 페이지가 현재 메모리에 없다고 표시할 때 <strong>페이지 폴트</strong>가 발생해 운영체제의 처리 코드로 넘어가요.</p><figure class="teaching-figure concept-figure"><div class="tlb-fault-visual" aria-label="TLB 미스 뒤 페이지 테이블 현재 존재면 계속, 부재면 페이지 폴트로 나뉨"><span>가상 페이지</span><i>TLB 확인</i><div><b>HIT</b><small>바로 프레임</small></div><div><b>MISS</b><small>페이지표 확인</small><p><em>PRESENT</em> 계속</p><p><em>ABSENT</em> 페이지 폴트</p></div></div><figcaption><strong>빠른 변환표에 없음과 RAM에 페이지가 없음은 같은 사건이 아니에요</strong><ul class="picture-key"><li><b>TLB 미스</b>느린 페이지 테이블 확인이 더 필요하다는 뜻이에요.</li><li><b>페이지 폴트</b>운영체제가 매핑을 만들거나 페이지를 준비하거나 잘못된 접근을 처리해요.</li><li><b>디스크</b>스왑된 파일 페이지는 읽을 수 있지만, 처음 쓰는 0 채움 페이지처럼 디스크 읽기가 없는 폴트도 있어요.</li></ul></figcaption></figure><p>아래 실습은 TLB를 빈 상태로 시작해 두 사건을 분리해서 표시해요. 페이지2는 페이지 테이블에 있으므로 TLB 미스 뒤 변환되고, 다른 페이지는 이 작은 모형에서 PRESENT=0으로 표시돼요.</p>`,lab:'virtual-memory'},
 {id:'b04',title:'요구 페이징은 필요해진 페이지를 그때 준비해요',html:`<p><strong>요구 페이징</strong>은 모든 페이지를 미리 RAM에 올리지 않고 실제 접근에서 필요해질 때 준비해요. 폴트 처리기는 접근이 허용되는지 확인하고, 빈 프레임을 찾거나 희생 페이지를 고르고, 필요한 내용을 준비해 페이지 테이블과 TLB 상태를 갱신한 뒤 명령을 다시 시도할 수 있어요.</p>${flow(['페이지 접근','PRESENT=0 폴트','접근 유효성 검사','프레임 확보','내용 준비','매핑 갱신·재시도'])}<div class="info">모든 페이지 폴트가 정상 복구되는 것은 아니에요. 매핑되지 않은 주소나 권한을 어긴 접근은 프로세스에 오류나 신호로 전달될 수 있어요.</div>`},
 {id:'b05',title:'프레임이 가득 차면 내보낼 페이지를 골라야 해요',html:`<p><strong>FIFO</strong>는 가장 먼저 들어온 페이지를, <strong>LRU</strong>는 가장 오래 참조하지 않은 페이지를 내보내려는 정책이에요. 프레임3개와 요청 1,2,3,1,4에서 마지막 4는 FIFO라면 1을, 정확한 LRU라면 2를 내보내요. 실제 시스템은 정확한 LRU 기록 비용 때문에 참조 비트와 Clock 같은 근사 정책을 사용할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="replacement-compare-visual" aria-label="요청1 2 3 1 4에서 FIFO는1, LRU는2를 교체"><div><b>요청</b><p><span>1</span><span>2</span><span>3</span><span>1</span><span>4</span></p></div><div><b>FIFO</b><p>1 · 2 · 3</p><strong>1 내보냄</strong></div><div><b>LRU</b><p>2 · 3 · 1</p><strong>2 내보냄</strong></div></div><figcaption><strong>들어온 시각과 마지막으로 쓴 시각은 다른 기록이에요</strong><ul class="picture-key"><li><b>FIFO 히트</b>페이지1을 다시 봐도 들어온 순서는 바뀌지 않아요.</li><li><b>LRU 히트</b>페이지1이 가장 최근 사용 위치로 이동해요.</li><li><b>정책 결과</b>참조 패턴과 프레임 수에 따라 폴트 수가 달라져요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'스래싱은 계산보다 페이지를 옮기는 데 시간을 쓰는 상태예요',html:`<p>프로세스들이 자주 쓰는 페이지 집합보다 사용 가능한 프레임이 너무 적으면 폴트가 연달아 생길 수 있어요. 운영체제가 페이지를 내보내고 다시 가져오는 일을 반복해 CPU 이용률과 실제 진행이 크게 떨어지는 현상을 <strong>스래싱</strong>이라고 해요. 단순히 RAM 사용률이 높다는 뜻이 아니라 작업 집합과 할당량이 맞지 않아 빈번한 교체가 일어나는 상황이에요.</p>${table(['확인할 신호','해석'],[['페이지 폴트 빈도 급증','필요한 페이지가 프레임에 함께 머물지 못할 수 있음'],['교체 입출력 증가·CPU 진행 감소','메모리 이동이 실제 계산을 방해할 수 있음'],['프레임 추가·작업 수 조절 뒤 개선','작업 집합과 물리 메모리 압력의 관계를 의심']])}`}
 ],questions:[
 {q:'페이지 크기1024B, 페이지2→프레임7일 때 가상 주소2053의 물리 주소는?',options:['2053','7173','2048'],answer:1,feedback:['가상 주소를 그대로 쓰지 않고 페이지 번호를 변환해야 해요.','맞아요. 7×1024+5=7173이에요.','2048은 가상 페이지2의 시작 주소예요.'],review:'b02'},
 {q:'TLB에서 변환을 찾지 못했지만 페이지 테이블에는 PRESENT 매핑이 있다면?',options:['반드시 디스크에서 페이지를 읽는다','페이지 테이블 변환으로 계속할 수 있다','프로세스가 반드시 종료된다'],answer:1,feedback:['TLB 미스와 페이지 폴트는 달라요.','맞아요. 매핑을 찾아 TLB를 채우고 계속할 수 있어요.','유효한 페이지 매핑이 있으므로 종료 이유가 아니에요.'],review:'b03'},
 {q:'프레임3개, 요청1·2·3·1·4에서 LRU가 4를 넣으며 내보내는 페이지는?',options:['1','2','3'],answer:1,feedback:['1은 방금 다시 사용되어 가장 최근 쪽이에요.','맞아요. 2가 가장 오래 사용되지 않았어요.','3은 2보다 뒤에 사용됐어요.'],review:'b05'}
 ],summary:['가상 주소는 페이지 번호와 오프셋으로 나뉘고 페이지 테이블이 페이지를 물리 프레임에 대응시켜요.','TLB 미스는 빠른 변환 캐시에 없음, 페이지 폴트는 현재 사용할 페이지 매핑이 준비되지 않은 사건이에요.','FIFO와 LRU는 다른 기록으로 희생 페이지를 고르며 빈번한 교체가 실제 진행을 막으면 스래싱이 생길 수 있어요.'],nextQuestion:'메모리에서 바뀐 파일 데이터가 저장장치에 안전하게 남으려면 어떤 순서와 기록이 필요할까요?',sources:[['OSTEP 한국어판 · 페이징 개요','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/18-vm-paging.pdf'],['OSTEP 한국어판 · TLB','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/19_vm-tlbs.pdf'],['Linux Kernel · Page Tables','https://docs.kernel.org/mm/page_tables.html']]
};

CS.lessons['ch10-l02']={
 lead:'파일 이름, 내용, 저장 블록은 한곳에 붙어 있지 않아요. 파일 시스템은 여러 자료구조와 쓰기 순서를 연결해 이름을 찾고 장애 뒤에도 일관된 상태를 복구해요.',
 goals:['디렉터리 항목·inode 같은 메타데이터·데이터 블록의 관계를 설명해요.','블록 할당과 빈 공간 표시, 버퍼링과 영구 저장 완료를 구별해요.','단순화한 전체 데이터 저널에서 커밋 전후 장애 복구 결과를 예측해요.'],prerequisites:['ch09-l02','ch10-l01'],sections:[
 {id:'b01',title:'파일 이름은 디렉터리에서 관리 구조를 찾아가는 열쇠예요',html:`<p>유닉스 계열 파일 시스템을 단순화하면 디렉터리는 <strong>이름→inode 번호</strong>의 대응을 담고, inode는 파일 종류·권한·크기·시간과 데이터 블록 위치 같은 메타데이터를 담아요. 보통 파일 이름 자체는 inode 안에 있지 않아요. 한 inode에 여러 이름을 연결하는 하드 링크가 가능한 이유도 이 분리에서 볼 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="file-lookup-visual" aria-label="경로의 디렉터리에서 note.txt 이름으로 inode41을 찾아 데이터 블록12와14로 연결"><div><b>디렉터리</b><span>note.txt → 41</span></div><i>→</i><div><b>inode 41</b><span>크기 · 권한 · 블록</span></div><i>→</i><div><b>데이터</b><span>블록 12</span><span>블록 14</span></div></div><figcaption><strong>경로 탐색은 이름을 차례로 해석해 마지막 파일의 관리 구조를 찾아요</strong><ul class="picture-key"><li><b>디렉터리 항목</b>사람이 쓰는 이름을 파일 식별 번호에 연결해요.</li><li><b>inode 예</b>파일의 메타데이터와 데이터 위치를 관리해요.</li><li><b>데이터 블록</b>파일 내용이 저장되는 고정 크기 공간이에요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'0바이트 파일도 이름과 메타데이터를 가질 수 있어요',html:`<p>파일 크기가 0이면 내용 데이터 블록이 아직 필요 없을 수 있지만, 디렉터리의 이름과 inode 같은 메타데이터는 존재할 수 있어요. 반대로 파일을 삭제해 이름 연결이 사라져도 열린 파일 설명자나 다른 하드 링크가 남아 있으면 inode와 데이터가 즉시 회수되지 않을 수 있어요. 구체적인 수명 규칙은 파일 시스템과 운영체제 인터페이스를 함께 봐야 해요.</p>${table(['구성','empty.txt 0B 예'],[['디렉터리 항목','empty.txt → inode 52'],['메타데이터','종류·권한·크기0·시간 정보'],['파일 데이터 블록','내용이 없어 0개일 수 있음']])}`},
 {id:'b03',title:'블록 할당기는 빈 공간과 파일의 블록 목록을 함께 바꿔요',html:`<p>파일이 커지면 파일 시스템은 비어 있는 데이터 블록을 골라 사용 중으로 표시하고 파일의 관리 구조가 그 블록을 가리키게 해요. 비트맵이나 빈 공간 목록을 사용할 수 있어요. 저장 공간이 없으면 기존 파일을 손상시키지 않고 쓰기 실패를 알리는 경로가 필요해요.</p><figure class="teaching-figure concept-figure"><div class="block-allocation-visual" aria-label="빈 공간 비트맵에서 블록18을 고르고 inode 블록 목록에 연결"><div><b>빈 공간 비트맵</b><p><span>1</span><span>1</span><span>0</span><span class="chosen">0</span><span>1</span></p><small>0 = 비어 있음</small></div><i>블록 18 선택</i><div><b>inode 블록 목록</b><p><span>12</span><span>14</span><span class="chosen">18</span></p></div></div><figcaption><strong>내용·메타데이터·빈 공간 정보는 서로 맞는 순서로 바뀌어야 해요</strong><ul class="picture-key"><li><b>할당</b>같은 블록을 두 파일에 실수로 배정하지 않게 사용 상태를 바꿔요.</li><li><b>연결</b>inode가 새 데이터 블록을 찾아갈 수 있게 주소를 기록해요.</li><li><b>공간 부족</b>새 블록을 얻지 못하면 부분 변경을 남기지 않는 처리가 필요해요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'write 반환과 영구 저장 완료는 항상 같은 순간이 아니에요',html:`<p>운영체제는 작은 쓰기를 모아 효율적으로 처리하려고 변경 내용을 메모리의 페이지 캐시·버퍼에 먼저 둘 수 있어요. 따라서 <code>write()</code>가 성공해도 전원 손실 뒤 복구 가능한 저장장치까지 모든 관련 정보가 도달했다는 뜻은 아닐 수 있어요. POSIX 계열의 <code>fsync()</code>는 해당 파일의 수정된 데이터와 관련 메타데이터를 저장장치로 동기화하도록 요청하지만, 새 디렉터리 항목의 지속성에는 그 디렉터리를 별도로 동기화해야 하는 경우가 있어요.</p><figure class="teaching-figure concept-figure"><div class="write-path-visual" aria-label="앱 write가 페이지 캐시를 거쳐 장치 큐와 영구 저장장치로 내려가는 단계"><span>앱<br><small>write</small></span><i>반환 가능</i><span>페이지 캐시<br><small>dirty</small></span><i>writeback</i><span>장치 큐<br><small>전송</small></span><i>완료</i><span>저장장치<br><small>영구 상태</small></span></div><figcaption><strong>각 단계의 “완료”가 무엇을 보장하는지 API와 장치 경계를 확인해야 해요</strong><ul class="picture-key"><li><b>버퍼링</b>여러 쓰기를 묶고 순서를 조정해 효율을 높일 수 있어요.</li><li><b>dirty</b>메모리 사본이 저장된 사본보다 새롭다는 뜻이에요.</li><li><b>동기화</b>요청이 어떤 데이터·메타데이터·디렉터리까지 포함하는지 구체적으로 봐야 해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'저널은 변경 의도를 먼저 확정해 장애 뒤 다시 적용할 수 있게 해요',html:`<p>저널링 파일 시스템은 여러 블록에 걸친 변경을 기록 영역에 먼저 남기고 <strong>커밋 경계</strong>를 만든 뒤 최종 위치에 반영할 수 있어요. 장애 뒤에는 커밋된 작업을 다시 적용하고, 커밋되지 않은 불완전한 기록은 무시해 메타데이터 일관성을 빠르게 회복해요. 아래는 데이터와 관련 메타데이터를 함께 기록하는 작은 교육 모형이에요.</p><figure class="teaching-figure concept-figure"><div class="journal-timeline-visual" aria-label="저널 기록 커밋 최종 위치 반영과 장애 복구 경계"><span>변경 기록</span><i></i><span class="commit">COMMIT</span><i></i><span>최종 반영</span><p><b>커밋 전 장애</b>A 유지</p><p><b>커밋 후 장애</b>저널로 B 재실행</p></div><figcaption><strong>커밋 표식이 복구 때 적용할 변경과 버릴 변경의 경계가 돼요</strong><ul class="picture-key"><li><b>커밋 전</b>완전한 작업으로 확정되지 않아 기존 A로 돌아가요.</li><li><b>커밋 후</b>최종 위치 반영 전 멈춰도 저널의 B를 다시 적용할 수 있어요.</li><li><b>모형 범위</b>실제 파일 시스템은 메타데이터만 저널링하거나 ordered 모드 등 다른 규칙을 쓸 수 있어요.</li></ul></figcaption></figure>`,lab:'journal-recovery'},
 {id:'b06',title:'장애 일관성은 최신 값 하나보다 관련 구조의 약속이에요',html:`${flow(['변경할 블록 모음','저널에 쓰기','커밋 확정','최종 위치 반영','저널 공간 재사용'])}<p>저널은 모든 데이터 손실을 자동으로 막는 마법 상자가 아니에요. 어떤 내용을 저널링하는지, 장치가 쓰기 완료와 순서를 어떻게 보장하는지, 응용 프로그램이 언제 동기화하는지에 따라 결과가 달라져요. 이 실습은 커밋된 전체 데이터 변경은 복구하고 미커밋 변경은 버린다는 명시된 약속만 사용해요.</p>`}
 ],questions:[
 {q:'유닉스 계열 파일 시스템의 단순 모형에서 파일 이름과 inode 번호의 대응을 담는 곳은?',options:['디렉터리 항목','CPU 레지스터','TLB'],answer:0,feedback:['맞아요. 디렉터리가 이름을 inode 번호에 연결해요.','CPU 레지스터는 파일 이름 목록을 영구 관리하지 않아요.','TLB는 가상 페이지 주소 변환 캐시예요.'],review:'b01'},
 {q:'저널 커밋 뒤 최종 위치 반영 전에 장애가 난 교육 모형의 복구 결과는?',options:['항상 A만 유지','커밋된 저널을 다시 적용해 B','파일 이름이 반드시 사라짐'],answer:1,feedback:['커밋 표식이 있는 변경은 복구 대상이에요.','맞아요. 저널의 B를 최종 위치에 다시 반영해요.','이 모형은 디렉터리 이름 삭제를 수행하지 않아요.'],review:'b05'},
 {q:'0바이트 파일에 대한 올바른 설명은?',options:['이름과 메타데이터도 존재할 수 없다','내용 블록이 없어도 이름과 메타데이터는 존재할 수 있다','반드시 저장 공간 부족 오류다'],answer:1,feedback:['파일 크기0과 파일 자체의 부재는 달라요.','맞아요. 디렉터리 항목과 inode 정보는 존재할 수 있어요.','0바이트는 정상적인 파일 상태예요.'],review:'b02'}
 ],summary:['디렉터리의 이름은 inode 같은 관리 구조를 찾게 하고, 메타데이터는 데이터 블록 위치와 크기·권한 등을 연결해요.','버퍼링된 write의 반환과 저장장치에 대한 영구 반영 완료를 구별하고 동기화 범위를 확인해야 해요.','저널의 커밋 경계는 장애 뒤 다시 적용할 변경과 버릴 미완료 변경을 구별하지만 실제 보장은 파일 시스템의 모드와 장치 규칙에 따라 달라요.'],nextQuestion:'여러 실행 흐름이 같은 메모리와 파일을 동시에 바꾸면 어떤 순서 문제와 경쟁이 생길까요?',sources:[['OSTEP 한국어판 · 파일과 디렉터리','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/39_interlude-file-directory.pdf'],['OSTEP · Crash Consistency and Journaling','https://pages.cs.wisc.edu/~remzi/OSTEP/file-journaling.pdf'],['Linux man-pages · fsync(2)','https://man7.org/linux/man-pages/man2/fsync.2.html']]
};
})();
