(()=>{
const {table,flow}=CS.helpers;
CS.lessons['ch11-l01']={
 lead:'두 작업이 각각 올바른 코드를 실행해도 공유 값을 읽고 쓰는 순서가 겹치면 한 번의 변경이 사라질 수 있어요.',
 goals:['경쟁 상태와 임계 구역을 실행 순서와 결과로 설명해요.','원자적 연산·CAS·뮤텍스가 해결하는 범위와 실패 조건을 구별해요.','세마포어와 조건 변수의 역할을 제한된 버퍼 문제에 연결해요.'],prerequisites:['ch02-l02','ch09-l02'],sections:[
 {id:'b01',title:'공유 자원은 실행 흐름 여러 개가 같은 상태를 보는 곳이에요',html:`<p>여러 스레드나 프로세스가 같은 메모리·파일·장치 상태를 읽고 바꾸면 그 상태가 <strong>공유 자원</strong>이에요. 실행 순서에 따라 결과가 달라지고 그중 일부가 잘못된 결과라면 <strong>경쟁 상태</strong>가 있어요. 단순히 작업이 동시에 존재한다는 사실보다 공유 접근의 순서가 정확성에 영향을 주는지가 핵심이에요.</p><figure class="teaching-figure concept-figure"><div class="shared-race-visual" aria-label="작업 A와 B가 같은 공유 카운터100을 읽고 쓰는 그림"><div><b>작업 A</b><span>읽기</span><span>쓰기</span></div><i>↘</i><div class="race-counter"><small>공유 counter</small><strong>100</strong></div><i>↗</i><div><b>작업 B</b><span>읽기</span><span>쓰기</span></div></div><figcaption><strong>같은 값을 읽는 두 작업 사이의 순서가 최종 결과를 바꿀 수 있어요</strong><ul class="picture-key"><li><b>공유 상태</b>A와 B가 모두 접근할 수 있는 counter예요.</li><li><b>실행 사이 끼어들기</b>한 작업이 읽은 뒤 쓰기 전에 다른 작업이 읽을 수 있어요.</li><li><b>결정성</b>동기화가 없으면 실행할 때마다 순서와 결과가 달라질 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'counter++도 읽기·계산·쓰기로 나뉠 수 있어요',html:`<p>A와 B가 모두 100을 읽고 각자 101을 계산한 뒤 차례로 쓰면 최종 값은 101이에요. 두 번 증가했지만 하나가 사라지는 <strong>갱신 손실</strong>이에요. 소스 코드 한 줄이나 고수준 연산 하나가 자동으로 원자적이라는 뜻은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="lost-update-visual" aria-label="A와 B가100을 읽고 둘 다101을 써서 한 증가가 사라지는 타임라인"><div><b>A</b><span>100 읽기</span><span>101 계산</span><span>101 쓰기</span></div><div><b>B</b><span>100 읽기</span><span>101 계산</span><span>101 쓰기</span></div><p>기대 102 <i>→</i> 실제 101</p></div><figcaption><strong>각 작업의 계산은 맞지만 둘이 같은 오래된 값을 바탕으로 썼어요</strong><ul class="picture-key"><li><b>읽기</b>각 작업의 로컬 값에 100이 복사돼요.</li><li><b>쓰기</b>나중에 쓴 101이 먼저 쓴 101을 덮어요.</li><li><b>재현</b>실행 순서를 명시하면 같은 갱신 손실을 반복해 확인할 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'임계 구역은 함께 실행되면 안 되는 공유 접근 묶음이에요',html:`<p>공유 값을 읽고 새 값을 쓰는 전체 구간을 <strong>임계 구역</strong>으로 정하고 뮤텍스로 한 작업만 들어가게 하면 A가 101을 쓴 뒤 B가 101을 읽어 102를 쓸 수 있어요. 아래에서 보호 없는 순서와 잠금 순서를 실행해 보세요. 잠금 모드에서는 읽기 전 소유권을 얻고 자신이 가진 잠금만 해제해야 해요.</p>`,lab:'counter-race'},
 {id:'b04',title:'원자적 연산과 CAS는 중간 상태를 함부로 끼워 넣지 못하게 해요',html:`<p><strong>원자적 연산</strong>은 다른 실행 흐름이 관찰하는 관점에서 더 작은 중간 단계로 나뉘지 않는 것처럼 동작해요. <strong>CAS</strong>(compare-and-swap)는 메모리 값이 예상값과 같을 때만 새 값으로 바꾸고 성공 여부를 돌려줘요. 실패하면 최신 값을 다시 읽고 재시도할 수 있지만, 반복 경쟁과 ABA 같은 별도 문제도 고려해야 해요.</p><figure class="teaching-figure concept-figure"><div class="cas-gate-visual" aria-label="예상100과 현재100을 비교해101로 바꾸거나 현재101이면 실패하는 CAS"><div><small>예상값</small><b>100</b></div><i>현재값과 비교</i><div class="cas-memory"><small>공유 값</small><b>100</b></div><div class="cas-results"><span class="success">같음 → 101 · 성공</span><span>다름 → 변경 없음 · 재시도</span></div></div><figcaption><strong>CAS는 비교와 조건부 쓰기를 하나의 원자적 약속으로 묶어요</strong><ul class="picture-key"><li><b>성공</b>현재 값이 예상값과 같을 때만 새 값을 써요.</li><li><b>실패</b>다른 작업이 먼저 바꿨으면 공유 값을 덮지 않아요.</li><li><b>범위</b>복잡한 여러 불변식은 CAS 한 번만으로 충분하지 않을 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'뮤텍스·세마포어·조건 변수는 질문이 달라요',html:`<p><strong>뮤텍스</strong>는 임계 구역에 한 소유자만 들어가게 하고 보통 소유자가 해제해요. <strong>세마포어</strong>는 정수 허용량과 wait/post 연산으로 여러 자원 수나 사건 순서를 표현할 수 있어요. <strong>조건 변수</strong>는 특정 상태가 될 때까지 잠들고 상태를 바꾼 작업의 신호를 받아 깨어나는 데 쓰며, 조건을 보호하는 뮤텍스와 반복 검사 규칙이 필요해요.</p><figure class="teaching-figure concept-figure"><div class="sync-tools-visual" aria-label="뮤텍스 세마포어 조건 변수의 서로 다른 역할"><div><b>뮤텍스</b><span>문 1개</span><small>소유자만 임계 구역</small></div><div><b>세마포어</b><span>허용표 N개</span><small>자원 수·순서 신호</small></div><div><b>조건 변수</b><span>대기 줄</span><small>조건 변화까지 잠들기</small></div></div><figcaption><strong>세 도구는 이름만 다른 같은 잠금이 아니에요</strong><ul class="picture-key"><li><b>상호 배제</b>동시에 한 실행만 허용하려면 뮤텍스가 직접적인 도구예요.</li><li><b>개수</b>동시 사용 가능한 자원 수는 세마포어 값으로 나타낼 수 있어요.</li><li><b>조건 대기</b>버퍼가 비지 않음·가득 차지 않음 같은 상태를 기다릴 때 조건 변수를 사용해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'잠금은 정확성을 주지만 범위와 경합 비용을 설계해야 해요',html:`${table(['생산자·소비자 상태','필요한 조정'],[['버퍼 배열과 인덱스 변경','뮤텍스로 같은 임계 구역을 동시에 바꾸지 않게 함'],['버퍼가 가득 참','생산자가 not-full 조건을 기다림'],['버퍼가 비어 있음','소비자가 not-empty 조건을 기다림'],['공간·데이터가 생김','상태를 바꾼 쪽이 관련 대기자를 깨움']])}<p>잠금 범위가 너무 좁으면 하나의 불변식을 보호하지 못하고, 너무 넓으면 관련 없는 작업까지 기다려 병렬성이 줄어요. 잠든 채 기다릴 수 있는 상황에서 무조건 반복 확인만 하면 CPU 시간을 낭비할 수 있어요. 정확한 조건과 보호할 데이터, 잠금 순서, 대기 방식을 함께 정해야 해요.</p>`}
 ],questions:[
 {q:'A와 B가 모두100을 읽고 각각101을 쓴 뒤 최종 값이101인 현상은?',options:['갱신 손실','페이지 폴트','저널 재실행'],answer:0,feedback:['맞아요. 두 증가 중 하나가 결과에 반영되지 않았어요.','메모리 주소 매핑 부재와는 다른 문제예요.','파일 시스템 복구 절차가 아니에요.'],review:'b02'},
 {q:'CAS가 공유 값을 바꾸는 조건은?',options:['현재 값이 예상값과 같을 때','다른 작업이 잠들었을 때만','언제나 무조건'],answer:0,feedback:['맞아요. 비교가 성공할 때만 조건부로 새 값을 써요.','잠듦은 CAS의 필수 조건이 아니에요.','다르면 변경하지 않고 실패를 알려요.'],review:'b04'},
 {q:'빈 버퍼에서 소비자가 데이터가 생기기를 효율적으로 기다릴 때 알맞은 설명은?',options:['조건 변수를 뮤텍스와 함께 사용해 조건을 반복 확인한다','공유 값을 보호하지 않고 계속 쓴다','잠금을 영원히 가진 채 생산자를 막는다'],answer:0,feedback:['맞아요. wait가 잠금을 놓고 잠든 뒤 깨어나 조건을 다시 확인하는 방식이 일반적이에요.','경쟁 상태가 생길 수 있어요.','생산자가 버퍼 상태를 바꿀 수 없어 진행하지 못해요.'],review:'b05'}
 ],summary:['경쟁 상태는 공유 접근 순서에 따라 정확성이 달라지는 문제이고, 읽기·계산·쓰기가 겹치면 갱신 손실이 생길 수 있어요.','임계 구역을 뮤텍스로 보호하거나 적절한 원자 연산을 사용하되 도구의 보장 범위와 실패·재시도 조건을 알아야 해요.','세마포어는 허용량과 순서를, 조건 변수는 상태가 바뀔 때까지의 대기를 표현하며 잠금 범위와 경합 비용도 함께 설계해요.'],nextQuestion:'잠금을 여러 개 사용하면 작업들이 서로 가진 자원을 기다리며 멈추는 상황을 어떻게 판별하고 막을까요?',sources:[['OSTEP 한국어판 · 락','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/28_threads-locks.pdf'],['OSTEP 한국어판 · 조건 변수','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/30_threads-cv.pdf'],['OSTEP 한국어판 · 세마포어','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/31_threads-sema.pdf']]
};

CS.lessons['ch11-l02']={
 lead:'작업들이 실행 중이라는 사실만으로 진행이 보장되지는 않아요. 누가 어떤 자원을 가지고 무엇을 기다리는지 그려야 멈춤의 종류를 구별할 수 있어요.',
 goals:['교착 상태의 네 필요 조건과 대기 순환을 실제 소유 관계로 판별해요.','공통 자원 획득 순서가 순환 대기를 끊는 원리를 설명해요.','교착·기아·라이브락을 상태 변화와 작업 완료 여부로 구별해요.'],prerequisites:['ch11-l01','ch09-l01'],sections:[
 {id:'b01',title:'교착은 네 조건이 함께 가능할 때 생길 수 있어요',html:`<p><strong>교착 상태</strong>는 작업 집합이 서로가 일으킬 사건을 기다려 누구도 진행하지 못하는 상태예요. 자원 교착에는 보통 상호 배제, 보유하며 대기, 강제 회수 불가, 순환 대기라는 네 조건이 필요해요. 네 조건이 가능하다는 사실만으로 현재 교착이라고 단정하지 않고 실제 할당과 대기를 확인해야 해요.</p><figure class="teaching-figure concept-figure"><div class="deadlock-four-visual" aria-label="교착의 네 필요 조건인 상호 배제 보유 대기 비선점 순환 대기"><span><b>1</b>상호 배제<small>자원 하나에 소유자 하나</small></span><span><b>2</b>보유하며 대기<small>하나는 잡고 다음을 기다림</small></span><span><b>3</b>강제 회수 없음<small>소유자가 직접 놓음</small></span><span><b>4</b>순환 대기<small>A→B→A</small></span></div><figcaption><strong>네 조건 중 하나를 구조적으로 없애면 해당 자원 교착을 예방할 수 있어요</strong><ul class="picture-key"><li><b>필요 조건</b>전형적인 자원 교착이 성립하려면 함께 존재해야 해요.</li><li><b>충분 조건 아님</b>조건이 가능한 시스템이라도 실행마다 교착이 생기는 것은 아니에요.</li><li><b>판별</b>현재 소유자와 대기 대상을 연결한 그래프를 확인해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'대기 그래프의 순환은 서로가 가진 자원을 기다림을 보여줘요',html:`<p>A가 X를 가진 채 Y를 기다리고, B가 Y를 가진 채 X를 기다리면 A→Y→B→X→A의 순환이 생겨요. 각 자원이 하나뿐인 이 모형에서는 두 작업 모두 상대가 놓아야만 진행하므로 교착이에요. 단순히 오래 기다렸다는 시간만으로 판정하지 않아요.</p><figure class="teaching-figure concept-figure"><div class="wait-cycle-visual" aria-label="A가X를 소유하고Y를 기다리며 B가Y를 소유하고X를 기다리는 순환"><span class="worker">A</span><i>보유</i><span>X</span><b>대기</b><span class="worker">B</span><i>보유</i><span>Y</span><b>대기</b><em>↺ A</em></div><figcaption><strong>소유 화살표와 요청 화살표를 함께 읽으면 진행을 막는 고리가 보여요</strong><ul class="picture-key"><li><b>A</b>X를 놓지 않은 채 B의 Y를 기다려요.</li><li><b>B</b>Y를 놓지 않은 채 A의 X를 기다려요.</li><li><b>순환</b>누구도 스스로 다음 자원을 얻을 수 없어요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'획득 순서를 직접 바꿔 대기 순환을 만들고 끊어요',html:`<p>기본 규칙에서는 A가 X→Y, B가 Y→X로 얻어 순환을 만들 수 있어요. 순서 통일에서는 모두 X→Y를 따르므로 B가 X 앞에서 기다리는 동안 A가 Y까지 얻어 끝내고 자원을 돌려줄 수 있어요. 한 작업자만 있으면 이 두 작업의 상호 대기 순환은 생기지 않아요.</p>`,lab:'deadlock-progress'},
 {id:'b04',title:'모든 작업이 같은 전역 순서로 자원을 얻으면 순환을 막을 수 있어요',html:`<p>자원에 X&lt;Y 같은 전역 순서를 정하고 모든 코드가 작은 자원부터 얻도록 하면 Y를 가진 채 X를 기다리는 역방향 간선을 만들지 않아요. 이 방식은 순환 대기 조건을 제거해 해당 잠금 집합의 교착을 예방해요. 모든 획득 경로가 규칙을 지켜야 하며, 외부 호출이나 숨은 잠금까지 포함해 순서를 관리해야 해요.</p><figure class="teaching-figure concept-figure"><div class="ordered-locks-visual" aria-label="A와 B 모두 X 뒤 Y 순서로 자원을 얻어 차례로 완료"><div><b>A</b><span>X</span><i>→</i><span>Y</span><strong>완료·반환</strong></div><div><b>B</b><em>X 앞 대기</em><span>X</span><i>→</i><span>Y</span><strong>완료</strong></div></div><figcaption><strong>한 방향으로만 자원을 얻으면 대기 간선이 원으로 돌아오기 어려워져요</strong><ul class="picture-key"><li><b>일관성</b>A와 B뿐 아니라 관련된 모든 경로가 같은 순서를 따라야 해요.</li><li><b>대기 가능</b>B가 잠시 기다리는 것은 교착과 달리 A의 완료로 풀려요.</li><li><b>다른 전략</b>한꺼번에 요청·타임아웃·try-lock 뒤 반환 등도 조건을 바꿀 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'교착·기아·라이브락은 모두 진행 문제지만 움직임이 달라요',html:`<p><strong>기아</strong>는 특정 작업이 계속 자원이나 CPU 기회를 얻지 못해 진행하지 못하는 상태예요. 다른 작업은 계속 끝날 수 있어요. <strong>라이브락</strong>은 관련 작업들이 충돌을 피하려고 계속 상태를 바꾸지만 서로 반응만 반복해 유용한 완료를 만들지 못하는 상태예요. 공정한 대기열과 무작위·지수 백오프 같은 규칙은 상황에 따라 진행 가능성을 높여요.</p><figure class="teaching-figure concept-figure"><div class="liveness-compare-visual" aria-label="교착 기아 라이브락의 상태 변화와 완료 비교"><div><b>교착</b><span>상태 멈춤</span><small>A완료0 · B완료0</small></div><div><b>기아</b><span>A 계속 완료</span><small>B만 오래 대기</small></div><div><b>라이브락</b><span>양보 ↔ 재시도</span><small>상태 변화 · 완료0</small></div></div><figcaption><strong>상태가 움직이는지와 어떤 작업이 실제로 완료되는지를 함께 봐요</strong><ul class="picture-key"><li><b>교착</b>대기 순환 속 작업들이 멈춰 있어요.</li><li><b>기아</b>시스템 전체는 움직이지만 특정 작업의 기회가 보장되지 않아요.</li><li><b>라이브락</b>코드는 실행되지만 반복 반응 때문에 유용한 진행이 없어요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'안전성은 나쁜 일이 없음, 진행성은 좋은 일이 결국 일어남이에요',html:`${table(['관점','묻는 질문','예'],[['안전성','절대 일어나면 안 되는 일이 없는가?','두 작업이 임계 구역에 동시에 들어가지 않음'],['교착 없음','대기 집합 전체가 서로를 영원히 기다리지 않는가?','자원 순서로 순환 대기 제거'],['기아 없음·공정성','요청한 각 작업이 결국 기회를 얻는가?','FIFO 대기열·공정한 스케줄 정책'],['완료 진행','상태 변화가 실제 작업 완료로 이어지는가?','라이브락의 반복 양보를 백오프로 분산']])}<p>상호 배제를 지켰다고 모든 작업이 언젠가 끝나는 것은 아니에요. 반대로 계속 실행 중이라고 유용한 결과가 생기는 것도 아니에요. 정확성 조건과 완료·공정성 조건을 별도로 적고 실행 기록으로 확인해야 해요.</p>`}
 ],questions:[
 {q:'A는 X를 보유하고 Y를 기다리며, B는 Y를 보유하고 X를 기다린다면?',options:['자원 대기 순환의 교착 상태','B만의 기아','페이지 교체'],answer:0,feedback:['맞아요. 각 자원이 하나이고 상대가 놓아야 진행하는 순환이에요.','두 작업 모두 순환에 묶였으므로 특정 B만의 기아로 보지 않아요.','가상 메모리 정책이 아니에요.'],review:'b02'},
 {q:'모든 작업이 X 다음 Y 순서로 잠금을 얻는 규칙이 제거하는 조건은?',options:['상호 배제','순환 대기','파일 메타데이터'],answer:1,feedback:['자원 하나의 상호 배제는 그대로 유지해요.','맞아요. 역방향 획득을 막아 대기 고리를 만들지 않아요.','파일 시스템 구조와 관계없는 조건이에요.'],review:'b04'},
 {q:'두 작업이 계속 양보하고 다시 시도해 상태는 바뀌지만 아무도 완료하지 못하는 것은?',options:['라이브락','안전한 완료','TLB 히트'],answer:0,feedback:['맞아요. 실행은 계속되지만 유용한 진행이 없어요.','완료된 작업이 없어요.','주소 변환 캐시 사건이 아니에요.'],review:'b05'}
 ],summary:['교착은 상호 배제·보유 대기·강제 회수 불가·순환 대기 조건 아래 실제 소유·대기 고리가 생겨 작업들이 진행하지 못하는 상태예요.','자원 획득 순서를 전역으로 통일하면 순환 대기를 끊을 수 있지만 모든 경로가 같은 규칙을 지켜야 해요.','기아는 특정 작업의 기회 부족, 라이브락은 계속 반응하지만 완료하지 못하는 상태이며 안전성과 진행성을 별도로 확인해야 해요.'],nextQuestion:'서비스 정보를 표로 나눌 때 중복을 줄이면서도 회원·도서·대출의 연결을 어떻게 보존할까요?',sources:[['OSTEP · Common Concurrency Problems','https://pages.cs.wisc.edu/~remzi/OSTEP/threads-deadlock.pdf'],['OSTEP 한국어판 · 세마포어와 순환 대기','https://pages.cs.wisc.edu/~remzi/OSTEP/Korean/31_threads-sema.pdf'],['Oracle Java Tutorials · Starvation and Livelock','https://docs.oracle.com/javase/tutorial/essential/concurrency/starvelive.html']]
};
})();
