(()=>{
const {table}=CS.helpers;
CS.lessons['ch12-l01']={
 lead:'서비스의 정보를 한 표에 모두 복사하면 처음에는 편해 보여도 같은 사실을 여러 곳에서 고쳐야 해요. 식별자와 관계를 설계하면 연결은 유지하고 중복 위험은 줄일 수 있어요.',
 goals:['엔터티·속성·관계를 도서관 예로 구별해요.','기본키·외래키와 관계의 수를 실제 행 연결로 설명해요.','수정 이상을 재현하고 정규화와 비정규화의 판단 기준을 말해요.'],prerequisites:['ch03-l01','ch03-l02'],sections:[
 {id:'b01',title:'엔터티는 관리할 대상, 속성은 그 대상을 설명하는 값이에요',html:`<p>도서관이 회원과 도서를 따로 관리한다면 <strong>회원</strong>과 <strong>도서</strong>는 엔터티가 될 수 있어요. 회원ID·이름은 회원의 속성이고, 도서ID·제목은 도서의 속성이에요. 현실의 모든 특징을 담는 것이 아니라 서비스가 구별하고 기록해야 할 사실을 골라 모델로 만들어요.</p><figure class="teaching-figure concept-figure"><div class="entity-attribute-visual" aria-label="회원과 도서 엔터티 안에 각각의 속성이 들어 있는 그림"><div><b>회원 엔터티</b><span>회원ID</span><span>이름</span></div><i>대출 관계</i><div><b>도서 엔터티</b><span>도서ID</span><span>제목</span></div></div><figcaption><strong>대상·특징·연결을 나누면 어떤 사실을 어디에 저장할지 보여요</strong><ul class="picture-key"><li><b>엔터티</b>독립적으로 식별하고 관리할 대상이에요.</li><li><b>속성</b>그 대상에 속한 값을 표현해요.</li><li><b>관계</b>대상 사이의 업무 연결을 표현해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'키는 같은 이름을 가진 행도 정확히 구별해요',html:`<p><strong>기본키</strong>는 표 안에서 행을 유일하게 식별하고 NULL이 될 수 없어요. <strong>외래키</strong>는 다른 표의 후보키를 참조해 존재하는 행과 연결되도록 해요. 이름이 같은 두 회원이 있어도 S1과 S2로 구별하면 대출이 어느 회원의 것인지 잃지 않아요.</p><figure class="teaching-figure concept-figure"><div class="key-link-visual" aria-label="동명이인 S1과 S2 중 대출 T1이 S1을 참조하는 그림"><div><b>members</b><span><strong>S1</strong> 민지</span><span><strong>S2</strong> 민지</span></div><div class="key-arrow">T1.member_id<br><b>S1</b> →</div><div><b>loans</b><span>T1 · S1 · B01</span></div></div><figcaption><strong>화면에 보이는 이름보다 안정적인 식별값으로 연결해요</strong><ul class="picture-key"><li><b>고유성</b>S1과 S2는 겹치지 않아요.</li><li><b>참조</b>대출의 S1은 실제 회원 S1과 연결돼요.</li><li><b>변경</b>이름이 바뀌어도 같은 ID의 연결은 유지돼요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'표를 연결하고 중복 수정 문제를 직접 비교해요',html:`<p>정규화한 표에서는 회원 이름을 members 한 곳에서 바꾸고, loans는 회원ID만 참조해요. 반대로 대출마다 이름과 제목을 복사한 표에서는 한 행만 고치면 같은 회원이 서로 다른 이름으로 보일 수 있어요. 아래에서 정상 연결과 수정 이상을 차례로 확인하세요.</p>`,lab:'relation-designer'},
 {id:'b04',title:'관계의 수는 한 행이 몇 행과 연결될 수 있는지 말해요',html:`<p><strong>카디널리티</strong>는 일대일·일대다·다대다처럼 연결 가능한 수를 나타내요. 회원 한 명은 대출 여러 건을 가질 수 있으므로 회원→대출은 일대다예요. 회원과 도서는 시간이 지나며 서로 여러 번 연결될 수 있어 다대다이고, 대출 같은 연결 엔터티를 두어 두 개의 일대다 관계로 풀 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="cardinality-visual" aria-label="회원과 도서의 다대다 관계를 대출 표로 푸는 그림"><div><b>회원</b><span>1</span></div><i>1 : N</i><div class="bridge-table"><b>대출</b><span>S1 · B01</span><span>S1 · B02</span></div><i>N : 1</i><div><b>도서</b><span>1</span></div></div><figcaption><strong>다대다 연결에 관계 자체의 정보를 담을 표를 둘 수 있어요</strong><ul class="picture-key"><li><b>일대일</b>각 행이 상대 한 행과 연결돼요.</li><li><b>일대다</b>한 회원에 대출 여러 건이 연결돼요.</li><li><b>다대다</b>대출일·반납일 같은 관계 속성은 연결 표에 담아요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'정규화는 한 사실이 여러 곳에서 어긋나는 위험을 줄여요',html:`<p>회원 이름과 도서 제목을 대출 행마다 복사하면 새 대출이 없을 때 회원만 넣기 어렵거나, 한 행만 수정해 값이 어긋나거나, 마지막 대출을 지우며 회원 정보까지 잃을 수 있어요. 이를 삽입·수정·삭제 이상이라고 해요. <strong>정규화</strong>는 함수 종속을 살펴 한 사실을 알맞은 관계에 두어 이런 위험을 줄이는 과정이에요.</p><figure class="teaching-figure concept-figure"><div class="normalization-visual" aria-label="중복된 한 표를 회원 도서 대출 세 표로 나누는 그림"><div class="wide-row"><b>대출 한 표</b><span>S1·민지·B01·책A</span><span>S1·민지·B02·책B</span></div><i>사실별로 분해</i><div class="normal-rows"><span>회원 S1·민지</span><span>도서 B01·책A</span><span>대출 S1·B01</span></div></div><figcaption><strong>분해 뒤에도 원래 사실을 올바르게 다시 연결할 수 있어야 해요</strong><ul class="picture-key"><li><b>중복 감소</b>회원 이름은 회원 표 한 곳에서 관리해요.</li><li><b>무손실 연결</b>키로 조인해 원래 대출 사실을 복원해요.</li><li><b>종속성</b>회원ID가 회원 이름을 결정하는 관계를 보존해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'정규화와 비정규화는 목적과 비용을 함께 보고 결정해요',html:`${table(['선택','얻는 점','확인할 비용'],[['정규화','중복과 변경 이상을 줄이고 제약을 명확히 함','조회 때 조인이 늘 수 있음'],['의도적 비정규화','반복 조회를 단순화하거나 계산 결과를 빠르게 제공','중복 동기화·갱신·검증 규칙이 필요'],['캐시·집계 테이블','원본을 유지한 채 읽기용 결과를 준비','갱신 지연과 원본 기준 복구 절차가 필요']])}<p>정규화가 언제나 가장 빠르거나 표를 많이 나눌수록 좋은 것은 아니에요. 먼저 정확한 원본 모델과 제약을 만들고, 측정한 조회 요구가 있을 때 중복된 값의 갱신 책임까지 설계해 비정규화를 선택해요.</p>`}
 ],questions:[
 {q:'이름이 같은 회원 S1과 S2를 대출 기록에서 정확히 구별하려면?',options:['회원 이름만 저장한다','회원ID를 외래키로 참조한다','화면의 행 번호를 기억한다'],answer:1,feedback:['동명이인을 구별할 수 없어요.','맞아요. 안정적인 식별자를 참조해요.','정렬과 삭제로 행 위치가 바뀔 수 있어요.'],review:'b02'},
 {q:'대출 표의 첫 행에 있는 회원 이름만 바꿔 같은 회원이 두 이름으로 보이는 현상은?',options:['수정 이상','올바른 정규화','카디널리티 증가'],answer:0,feedback:['맞아요. 같은 사실의 중복 사본이 어긋났어요.','정규화는 이런 불일치 위험을 줄여요.','연결 가능한 수의 정의가 바뀐 것은 아니에요.'],review:'b05'},
 {q:'대출 기록이 0건인 회원을 저장할 수 있어야 한다면 알맞은 설계는?',options:['회원과 대출을 분리한다','대출 행이 생길 때까지 회원을 저장하지 않는다','모든 회원에게 가짜 대출을 만든다'],answer:0,feedback:['맞아요. 회원의 존재를 대출의 존재와 분리해요.','삽입 이상 때문에 회원 정보를 잃어요.','가짜 업무 사실을 만들면 데이터가 틀려요.'],review:'b05'}
 ],summary:['엔터티·속성·관계는 서비스가 관리할 대상과 사실, 연결을 표현해요.','기본키는 행을 구별하고 외래키는 존재하는 행을 참조하며 카디널리티는 관계의 수를 나타내요.','정규화는 변경 이상을 줄이고, 비정규화는 측정된 필요와 중복 갱신 책임을 함께 설계할 때 선택해요.'],nextQuestion:'키로 나눈 표에서 원하는 회원 이름과 대출 수를 SQL 한 문장으로 어떻게 가져올까요?',sources:[['PostgreSQL · 제약 조건','https://www.postgresql.org/docs/current/ddl-constraints.html'],['PostgreSQL · 테이블 기본','https://www.postgresql.org/docs/current/tutorial-table.html'],['CMU 15-445 · Database Design','https://15445.courses.cs.cmu.edu/fall2025/notes/01-relationalmodel.pdf']]
};

CS.lessons['ch12-l02']={
 lead:'SQL은 저장된 표에 무엇을 원하는지 선언하는 언어예요. 열 선택부터 연결·그룹 집계까지 한 단계씩 쌓으면 결과 행이 왜 그렇게 나오는지 설명할 수 있어요.',
 goals:['SELECT·WHERE·ORDER BY의 역할과 논리적 처리 흐름을 구별해요.','JOIN 조건이 행 수와 의미를 바꾸는 이유를 실제 결과로 확인해요.','GROUP BY·HAVING·NULL과 변경 제약을 적용해요.'],prerequisites:['ch12-l01','ch03-l02'],sections:[
 {id:'b01',title:'SELECT는 열을 고르고 WHERE는 행을 거르며 ORDER BY는 결과를 정렬해요',html:`<p><code>SELECT</code>는 결과에 보여 줄 표현을, <code>FROM</code>은 입력 관계를, <code>WHERE</code>는 남길 행의 조건을 정해요. <code>ORDER BY</code>가 없으면 결과 순서를 기대하면 안 돼요. SQL을 적는 순서와 개념적으로 처리되는 흐름은 다를 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="select-pipeline-visual" aria-label="FROM WHERE SELECT ORDER BY로 데이터가 처리되는 흐름"><span><b>FROM</b>입력 행</span><i>→</i><span><b>WHERE</b>조건 통과</span><i>→</i><span><b>SELECT</b>열 계산</span><i>→</i><span><b>ORDER BY</b>결과 정렬</span></div><figcaption><strong>질문을 입력·필터·표현·순서로 나누면 SQL을 읽기 쉬워요</strong><ul class="picture-key"><li><b>0행</b>조건을 만족하는 행이 없을 뿐 원본 삭제가 아니에요.</li><li><b>순서</b>필요한 경우 ORDER BY로 명시해요.</li><li><b>별칭</b>AS로 결과 열과 표를 읽기 쉽게 이름 붙여요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'JOIN은 두 표의 행을 어떤 조건으로 연결할지 정해요',html:`<p>대출의 member_id와 회원의 id가 같은 행을 연결하면 회원 이름을 가져올 수 있어요. <code>ON</code> 조건을 빠뜨리거나 항상 참인 조건을 쓰면 모든 조합에 가까운 행이 생겨 결과가 부풀 수 있어요. INNER JOIN은 일치하는 행을, LEFT JOIN은 왼쪽의 일치하지 않는 행도 NULL을 채워 남겨요.</p><figure class="teaching-figure concept-figure"><div class="join-match-visual" aria-label="loans의 M1과 members의 M1이 같은 키로 연결되는 그림"><div><b>loans</b><span>M1 · B1</span><span>M1 · B2</span><span>M2 · B3</span></div><div class="join-rule"><strong>ON</strong><br>l.member_id<br>= m.id</div><div><b>members</b><span>M1 · 민지</span><span>M2 · 준호</span></div></div><figcaption><strong>JOIN의 핵심은 표 이름보다 행을 짝짓는 조건이에요</strong><ul class="picture-key"><li><b>올바른 조건</b>3개 대출은3개 결과 행이 돼요.</li><li><b>조건 누락</b>대출3×회원2로6행이 될 수 있어요.</li><li><b>LEFT JOIN</b>대출0건 회원도 집계에 포함할 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'실제 SQLite에서 조인과 집계 결과를 확인해요',html:`<p>기본 SQL은 회원을 기준으로 대출을 LEFT JOIN하고 회원별로 묶어 개수를 계산해요. M1은2건, M2는1건이 나와야 해요. 올바른 JOIN 3행과 조건이 빠진 JOIN 6행도 비교하고, 0행·NULL·문법 오류 뒤 재실행까지 확인하세요.</p>`,lab:'sql-analytics'},
 {id:'b04',title:'GROUP BY는 행을 그룹으로 묶고 HAVING은 그룹 결과를 걸러요',html:`<p><code>COUNT</code>·<code>SUM</code> 같은 집계 함수는 여러 입력 행을 요약해요. <code>GROUP BY member_id</code>는 회원별 그룹을 만들고, <code>HAVING COUNT(*) &gt;= 2</code>는 집계가 끝난 그룹을 걸러요. WHERE는 그룹을 만들기 전 개별 행을 거른다는 차이가 있어요.</p><figure class="teaching-figure concept-figure"><div class="group-aggregate-visual" aria-label="M1의 두 대출과 M2의 한 대출이 그룹별 개수로 집계되는 그림"><div><span>M1·B1</span><span>M1·B2</span><span>M2·B3</span></div><i>GROUP BY</i><div><b>M1 그룹</b><span>COUNT = 2</span><b>M2 그룹</b><span>COUNT = 1</span></div><i>HAVING ≥ 2</i><strong>M1만 남음</strong></div><figcaption><strong>WHERE는 행, HAVING은 만들어진 그룹을 대상으로 해요</strong><ul class="picture-key"><li><b>그룹 키</b>같은 회원ID의 행을 함께 묶어요.</li><li><b>집계</b>각 그룹마다 결과 한 행을 만들어요.</li><li><b>필터</b>집계값 조건은 HAVING에 적어요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'NULL은 빈 문자열이나 0이 아니라 모르는 값·해당 없음의 표시예요',html:`<p>NULL과 일반 값을 비교한 결과는 참·거짓 외에 <strong>UNKNOWN</strong>이 될 수 있어요. WHERE는 참인 행만 남기므로 <code>returned_at = NULL</code>이 아니라 <code>returned_at IS NULL</code>을 사용해요. <code>COUNT(column)</code>은 NULL을 제외하고, <code>COUNT(*)</code>는 행을 세는 차이도 있어요.</p><figure class="teaching-figure concept-figure"><div class="null-logic-visual" aria-label="SQL의 TRUE FALSE UNKNOWN 세 값 논리와 IS NULL 검사"><span class="truth">TRUE<br><small>행 유지</small></span><span>FALSE<br><small>행 제외</small></span><span class="unknown">UNKNOWN<br><small>행 제외</small></span><i>NULL 비교</i><strong>IS NULL로 검사</strong></div><figcaption><strong>값이 없다는 표시와 값이 무엇인지 모른다는 의미를 문맥으로 정해요</strong><ul class="picture-key"><li><b>비교</b>NULL = NULL도 TRUE가 아니에요.</li><li><b>검사</b>IS NULL과 IS NOT NULL을 사용해요.</li><li><b>집계</b>NULL 포함 여부를 함수별로 확인해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'INSERT·UPDATE·DELETE도 제약을 통과한 상태만 남겨야 해요',html:`${table(['문장','바꾸는 대상','대표 확인'],[['INSERT','새 행 추가','기본키 중복·NOT NULL·외래키 대상'],['UPDATE','조건에 맞는 기존 행','WHERE 범위·CHECK·참조 영향'],['DELETE','조건에 맞는 기존 행 제거','참조 중인 행·CASCADE 정책·삭제 범위']])}<p>변경 전에는 WHERE로 대상 행을 먼저 조회하고, 트랜잭션 안에서 제약 오류와 영향 행 수를 확인하는 습관이 좋아요. 외래키 검사는 DBMS와 설정에 따라 활성화 조건이 다를 수 있으며, 제품별 확장 문법과 동시성·복구 보장은 해당 문서를 확인해야 해요.</p>`}
 ],questions:[
 {q:'대출3행과 회원2행을 연결했는데 결과가6행이라면 먼저 확인할 것은?',options:['JOIN의 ON 조건','ORDER BY 방향','열 별칭의 글자 수'],answer:0,feedback:['맞아요. 모든 조합이 만들어지지 않았는지 연결 조건을 확인해요.','정렬은 행의 순서를 바꾸지만 행 수를 두 배로 만들지 않아요.','별칭 길이는 조인 행 수와 관계없어요.'],review:'b02'},
 {q:'회원별 대출 수를 구한 뒤 대출2건 이상인 회원 그룹만 남기려면?',options:['WHERE COUNT(*) >= 2','HAVING COUNT(*) >= 2','ORDER BY COUNT(*) >= 2'],answer:1,feedback:['WHERE는 그룹을 만들기 전 행을 대상으로 해요.','맞아요. 집계 뒤 그룹 조건은 HAVING으로 검사해요.','ORDER BY는 결과 순서를 정해요.'],review:'b04'},
 {q:'아직 반납하지 않아 returned_at이 NULL인 행을 찾는 조건은?',options:['returned_at = NULL','returned_at IS NULL','returned_at = 0'],answer:1,feedback:['일반 비교 결과가 UNKNOWN이 되어 WHERE에 남지 않아요.','맞아요. NULL 전용 검사식을 사용해요.','0은 NULL과 다른 실제 값이에요.'],review:'b05'}
 ],summary:['SELECT·FROM·WHERE·ORDER BY는 결과 열, 입력, 행 조건, 순서를 각각 표현해요.','JOIN 조건은 행의 짝을 정하고 GROUP BY·집계·HAVING은 그룹별 질문을 표현해요.','NULL은 세 값 논리로 다루며 변경 문장은 제약·대상 범위·트랜잭션을 함께 확인해요.'],nextQuestion:'행을 빠르게 찾기 위해 만드는 인덱스는 저장 구조와 쿼리 실행 비용을 어떻게 바꿀까요?',sources:[['SQLite · SELECT','https://www.sqlite.org/lang_select.html'],['SQLite · NULL 처리','https://www.sqlite.org/nulls.html'],['PostgreSQL · 테이블 조인','https://www.postgresql.org/docs/current/tutorial-join.html'],['PostgreSQL · 집계 함수','https://www.postgresql.org/docs/current/tutorial-agg.html']]
};
})();

