(()=>{
const {table}=CS.helpers;
CS.lessons['ch13-l01']={
 lead:'표의 행이 많아지면 원하는 행을 매번 처음부터 찾는 비용이 커져요. DBMS는 페이지 단위 저장과 인덱스를 이용해 필요한 위치를 좁혀요.',
 goals:['레코드·페이지·버퍼 풀의 관계를 설명해요.','B+트리의 검색·삽입·분할과 리프 연결을 실행해요.','해시·복합 인덱스의 조건과 읽기·쓰기 비용을 판단해요.'],prerequisites:['ch12-l01','ch08-l01','ch05-l02'],sections:[
 {id:'b01',title:'DBMS는 여러 레코드를 페이지에 담아 메모리와 저장장치 사이로 옮겨요',html:`<p><strong>레코드</strong>는 한 행의 물리적 표현이고, <strong>페이지</strong>는 DBMS가 저장장치에서 읽고 쓰는 고정 크기 블록 단위예요. <strong>버퍼 풀</strong>은 자주 쓰는 페이지를 메모리에 두고, 필요한 페이지가 없으면 가져오며 더티 페이지는 정책에 따라 저장장치에 반영해요.</p><figure class="teaching-figure concept-figure"><div class="page-buffer-visual" aria-label="저장장치의 페이지가 버퍼 풀에 올라오고 안에 여러 레코드가 있는 그림"><div><b>저장장치</b><span>Page 17</span><span>Page 18</span></div><i>읽기·쓰기</i><div class="buffer-frame"><b>버퍼 풀</b><span>Frame A · P17</span><span>Frame B · P42</span></div><i>페이지 안</i><div><b>레코드</b><span>R1</span><span>R2</span><span>R3</span></div></div><figcaption><strong>행 하나를 찾더라도 실제 I/O는 페이지 단위로 일어날 수 있어요</strong><ul class="picture-key"><li><b>페이지</b>레코드와 관리 정보를 함께 담아요.</li><li><b>버퍼 히트</b>메모리에 있으면 저장장치 읽기를 피할 수 있어요.</li><li><b>교체</b>빈 프레임이 없으면 내보낼 페이지를 골라요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'B+트리는 구분 키로 리프를 찾고 리프끼리 순서대로 연결해요',html:`<p>B+트리의 내부 노드는 어느 자식으로 갈지 알려 주는 구분 키를, 리프는 검색 키와 행 위치를 담아요. 노드가 페이지에 맞게 넓은 자식을 가지므로 높이가 낮아질 수 있고, 균형을 유지해 검색 경로 길이를 제한해요. 연결된 리프는 범위 결과를 순서대로 읽는 데 유리해요.</p><figure class="teaching-figure concept-figure"><div class="bplus-structure-visual" aria-label="루트 구분키30 아래 세 리프가 순서대로 연결된 B플러스트리"><div class="tree-root"><small>내부 페이지</small><b>30 · 60</b></div><div class="tree-leaves"><span>[10,20] →</span><span>[30,40,50] →</span><span>[60,70]</span></div></div><figcaption><strong>정확한 키는 한 경로로, 범위는 시작 리프부터 옆으로 찾아요</strong><ul class="picture-key"><li><b>균형</b>모든 리프는 같은 깊이에 있어요.</li><li><b>구분 키</b>검색할 자식 범위를 선택해요.</li><li><b>리프 연결</b>30~65 같은 범위를 이어서 읽어요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'네 번째 키를 넣어 리프 분할과 검색 경로를 확인해요',html:`<p>이 학습 모형의 리프는 키를 최대3개 담아요. 1·2·3 다음4를 넣으면 넘친 리프를 [1,2]와 [3,4]로 나누고 루트에 구분키3을 올려요. 분할 뒤에도 정렬·키 보존·구분 규칙이 유지되는지 확인하세요.</p>`,lab:'bplus-tree'},
 {id:'b04',title:'B+트리와 해시 인덱스는 잘하는 질문이 달라요',html:`<p>B+트리는 키 순서를 유지해 동등 비교와 범위·정렬 조건에 활용할 수 있어요. 해시 인덱스는 해시 함수를 거쳐 버킷 후보를 찾아 주로 동등 비교에 알맞고, 키 순서가 없어 범위 조회를 같은 방식으로 돕지 못해요. 실제 지원 연산은 DBMS와 인덱스 종류를 확인해야 해요.</p><figure class="teaching-figure concept-figure"><div class="index-kind-visual" aria-label="B플러스트리의 순서 탐색과 해시의 버킷 탐색 비교"><div><b>B+트리</b><span>10 → 20 → 30 → 40</span><small>= · &lt; · BETWEEN · 정렬</small></div><div><b>해시</b><span>hash(30) → bucket 2</span><small>주로 = 조건</small></div></div><figcaption><strong>인덱스 이름보다 연산과 정렬 보장을 조회 조건에 맞춰요</strong><ul class="picture-key"><li><b>점 조회</b>두 구조 모두 적합할 수 있어요.</li><li><b>범위 조회</b>정렬된 B+트리 리프가 유리해요.</li><li><b>충돌</b>해시는 같은 버킷의 후보를 다시 비교해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'복합 B-tree 인덱스는 앞쪽 열 조건이 탐색 범위를 크게 좌우해요',html:`<p><code>(category, published_at)</code> 복합 B-tree 인덱스는 category로 먼저 묶이고 그 안에서 날짜 순으로 정렬돼요. category 동등 조건과 날짜 범위는 잘 맞지만 날짜만 조건으로 주면 읽어야 할 인덱스 범위가 커질 수 있어요. 최신 DBMS의 skip scan 등 최적화가 있어도 앞쪽 열과 데이터 분포가 중요해요.</p><figure class="teaching-figure concept-figure"><div class="composite-index-visual" aria-label="카테고리와 날짜 순서의 복합 인덱스에서 앞 열 조건 유무 비교"><div><b>(category, date)</b><span>CS·01</span><span>CS·08</span><span>WEB·03</span></div><div><strong>category='CS'<br>AND date≥05</strong><small>CS 묶음 안을 좁힘</small></div><div><strong>date≥05</strong><small>여러 category 묶음을 확인</small></div></div><figcaption><strong>자주 함께 쓰는 조건과 정렬 순서를 보고 열 순서를 정해요</strong><ul class="picture-key"><li><b>선두 열</b>탐색 시작 범위를 정하는 데 큰 역할을 해요.</li><li><b>선택도</b>값 분포에 따라 후보 수가 달라져요.</li><li><b>과잉 인덱스</b>비슷한 인덱스를 무작정 늘리지 않아요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'인덱스는 읽기를 돕는 대신 저장 공간과 쓰기 작업을 더해요',html:`${table(['상황','도움이 될 수 있는 점','추가 비용·주의'],[['선택도 높은 검색','적은 후보 위치로 빠르게 좁힘','테이블 행을 다시 읽는 랜덤 접근 가능'],['범위·정렬 조회','정렬된 리프 순서를 활용','범위가 넓으면 전체 스캔이 나을 수 있음'],['INSERT·UPDATE·DELETE','이후 조회 경로 유지','관련 인덱스마다 키 삽입·삭제·분할'],['많은 인덱스','다양한 조회 조건 지원','저장 공간·캐시·쓰기·유지보수 비용 증가']])}<p>인덱스가 있다는 사실만으로 항상 사용되거나 빨라지는 것은 아니에요. 데이터 양·분포·캐시 상태·반환할 열·쓰기 비율을 고려해 실행 계획과 실제 측정을 함께 봐야 해요.</p>`}
 ],questions:[
 {q:'B+트리에서 30~60 같은 범위를 순서대로 찾을 때 도움이 되는 구조는?',options:['연결된 리프','해시값의 무작위 순서','모든 내부 노드 삭제'],answer:0,feedback:['맞아요. 시작 리프를 찾은 뒤 옆 리프로 이어가요.','해시는 일반적으로 키 순서를 보존하지 않아요.','내부 노드는 시작 위치를 좁히는 데 필요해요.'],review:'b02'},
 {q:'리프 최대3키 모형에서1·2·3 다음4를 넣은 결과는?',options:['리프 [1,2]·[3,4], 루트 구분키3','키4 삭제','루트에 모든 레코드 복사'],answer:0,feedback:['맞아요. 넘친 리프를 나누고 오른쪽 첫 키를 올려요.','삽입한 키는 보존해야 해요.','내부 노드는 여기서 탐색용 구분 키를 담아요.'],review:'b03'},
 {q:'인덱스를 추가할 때 함께 늘어나는 비용은?',options:['저장 공간과 쓰기 유지 작업','모든 조회 결과의 행 수','기본키의 중복 허용'],answer:0,feedback:['맞아요. 변경 때 인덱스 구조도 갱신해야 해요.','인덱스는 질문 결과의 의미를 바꾸지 않아야 해요.','기본키 제약은 그대로예요.'],review:'b06'}
 ],summary:['DBMS는 레코드를 페이지에 담고 버퍼 풀로 저장장치 I/O를 관리해요.','B+트리는 균형 검색과 연결 리프의 범위 조회를 지원하며 분할 뒤에도 정렬과 키를 보존해요.','인덱스 종류·복합 열 순서·데이터 분포를 조회와 쓰기 비용에 맞춰 선택해요.'],nextQuestion:'같은 SQL에도 여러 접근법이 있다면 DBMS는 어떤 실행 계획을 고르고 우리는 무엇을 확인해야 할까요?',sources:[['CMU 15-445 · B+Tree','https://15445.courses.cs.cmu.edu/spring2025/project2/'],['PostgreSQL · 인덱스','https://www.postgresql.org/docs/current/indexes.html'],['PostgreSQL · 복합 인덱스','https://www.postgresql.org/docs/current/indexes-multicolumn.html']]
};

CS.lessons['ch13-l02']={
 lead:'SQL은 원하는 결과를 말하고, 옵티마이저는 전체 스캔·인덱스·여러 조인 방식 중 실행 방법을 골라 물리 계획을 만들어요.',
 goals:['논리 연산과 물리 실행 계획을 구별해요.','전체 스캔과 인덱스 검색의 계획 표시를 실제 SQLite에서 비교해요.','조인 방식·통계·예상 비용과 실제 관측의 한계를 설명해요.'],prerequisites:['ch13-l01','ch12-l02','ch05-l02'],sections:[
 {id:'b01',title:'같은 논리적 질문도 여러 물리 연산으로 실행할 수 있어요',html:`<p>파서와 바인더가 SQL의 이름·구조를 확인하면 관계 대수에 가까운 <strong>논리 계획</strong>을 만들 수 있어요. 옵티마이저는 같은 결과를 내는 후보들을 비교해 스캔·조인 순서·조인 알고리즘 같은 <strong>물리 계획</strong>을 선택하고 실행기가 이를 처리해요.</p><figure class="teaching-figure concept-figure"><div class="query-stages-visual" aria-label="SQL이 논리 계획 후보 물리 계획 실행 결과로 변하는 흐름"><span><b>SQL</b>원하는 결과</span><i>→</i><span><b>논리 계획</b>필터·조인·집계</span><i>→</i><span><b>후보 비교</b>추정 비용</span><i>→</i><span><b>물리 계획</b>스캔·조인 방식</span><i>→</i><span><b>실행</b>실제 행</span></div><figcaption><strong>SQL 문장과 실제 실행 방법을 같은 것으로 보지 않아요</strong><ul class="picture-key"><li><b>동등성</b>후보 계획은 같은 결과를 내야 해요.</li><li><b>비용 모델</b>페이지·CPU·메모리 같은 사건을 추정해요.</li><li><b>선택</b>최저 추정 비용 계획이 실제 최저 시간과 항상 같지는 않아요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'전체 스캔은 넓게 읽고 인덱스 검색은 후보 위치를 좁혀요',html:`<p>전체 스캔은 테이블의 페이지와 레코드를 차례로 검사해요. 인덱스 검색은 트리 경로로 후보 위치를 찾고 필요하면 테이블 행을 읽어요. 1000행 중20행이 일치하는 고정 모형이라면 전체 스캔은1000레코드를 검사하고, 인덱스는 트리 노드3개와 후보20개처럼 서로 다른 사건을 보여줄 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="access-path-visual" aria-label="1000행 전체 스캔과 트리3노드 후보20행 인덱스 접근 비교"><div><b>전체 스캔</b><strong>1000</strong><span>레코드 검사</span></div><div><b>인덱스 접근</b><strong>3 + 20</strong><span>트리 노드 + 후보 행</span></div><div><b>모두 일치</b><strong>3 + 1000</strong><span>이점이 달라짐</span></div></div><figcaption><strong>단위가 다른 사건을 근거 없이 밀리초로 합치지 않아요</strong><ul class="picture-key"><li><b>선택도</b>전체 중 조건을 만족하는 비율이에요.</li><li><b>후보 수</b>낮은 선택도에서 인덱스 이점이 커질 수 있어요.</li><li><b>캐시</b>페이지가 이미 메모리에 있는지도 실제 시간에 영향을 줘요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'SQLite의 실제 실행 계획에서 SCAN과 SEARCH를 비교해요',html:`<p><code>EXPLAIN QUERY PLAN</code>의 detail 열에서 제목 인덱스가 없을 때의 SCAN과 만든 뒤의 SEARCH·USING INDEX를 비교하세요. 함수로 인덱스 열을 감싸면 단순 인덱스를 그대로 활용하지 못할 수 있고, 기본키와 조인은 또 다른 계획을 만들어요.</p>`,lab:'query-plan'},
 {id:'b04',title:'조인 알고리즘은 입력 크기·정렬·메모리·인덱스에 따라 달라져요',html:`<p><strong>중첩 루프 조인</strong>은 바깥 행마다 안쪽에서 일치를 찾고, 안쪽 키 인덱스가 있으면 효과적일 수 있어요. <strong>해시 조인</strong>은 한쪽으로 해시 테이블을 만들어 동등 조건을 찾고, <strong>정렬 병합 조인</strong>은 정렬된 양쪽을 순서대로 맞춰요. 제품마다 지원 방식은 달라요.</p><figure class="teaching-figure concept-figure"><div class="join-algorithms-visual" aria-label="중첩 루프 해시 정렬 병합 조인의 처리 방식"><div><b>중첩 루프</b><span>바깥 행 → 안쪽 탐색</span></div><div><b>해시 조인</b><span>build → hash probe</span></div><div><b>정렬 병합</b><span>정렬 → 양쪽 전진</span></div></div><figcaption><strong>JOIN이라는 논리 연산과 이를 수행하는 물리 알고리즘을 구별해요</strong><ul class="picture-key"><li><b>중첩 루프</b>작은 바깥쪽과 빠른 안쪽 탐색에 맞을 수 있어요.</li><li><b>해시</b>주로 동등 조인에 사용돼요.</li><li><b>병합</b>정렬 비용과 이미 정렬된 입력 여부를 고려해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'통계가 실제 분포와 다르면 예상 행 수와 계획 선택도 빗나갈 수 있어요',html:`<p>옵티마이저는 모든 후보를 실제로 끝까지 실행해 보지 않고 행 수·서로 다른 값 수·분포 같은 통계로 비용을 추정해요. 데이터가 크게 바뀌었거나 열 사이 상관관계를 단순하게 가정하면 <strong>예상 행 수</strong>가 실제와 달라지고 조인 순서와 접근법 선택에 영향을 줄 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="estimate-actual-visual" aria-label="통계 기반 예상20행과 실행에서 관측한 실제600행의 차이"><div><b>통계</b><span>값100종 · 균등 가정</span></div><i>비용 추정</i><div><b>예상</b><strong>20행</strong></div><i>실행 관측</i><div class="actual"><b>실제</b><strong>600행</strong></div></div><figcaption><strong>예상과 실제의 큰 차이는 통계·상관관계·조건식을 점검할 단서예요</strong><ul class="picture-key"><li><b>통계 갱신</b>데이터 변화 뒤 분포 정보를 새로 모아요.</li><li><b>추정 오차</b>상위 연산으로 누적될 수 있어요.</li><li><b>실제 관측</b>대표 데이터와 실제 실행 지표를 함께 봐요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'실행 계획은 예측이고 실제 관측은 그 예측을 검증하는 자료예요',html:`${table(['확인 순서','질문'],[['결과 의미','두 계획이 같은 행과 값을 반환하는가?'],['접근 경로','SCAN·SEARCH와 사용 인덱스는 무엇인가?'],['예상','예상 행 수와 비용의 근거는 무엇인가?'],['실제','실제 행·반복·시간·I/O가 예상과 얼마나 다른가?'],['전체 작업량','쿼리 한 번뿐 아니라 인덱스 유지와 동시 부하까지 어떤가?']])}<p>작은 예제에서 더 빨랐다는 결과를 운영 데이터 전체로 일반화하지 않아요. 콜드·웜 캐시, 파라미터, 통계 시점, 데이터 분포를 기록하고 여러 번 측정해야 해요. SQLite의 EXPLAIN QUERY PLAN 출력 형식은 버전 사이에 바뀔 수 있어 애플리케이션 로직의 고정 입력으로 사용하지 않는 편이 좋아요.</p>`}
 ],questions:[
 {q:'같은 SQL 결과를 내는 전체 스캔과 인덱스 검색은 무엇이 다른가요?',options:['물리 접근 방법','질문의 논리적 결과','테이블의 기본키 값'],answer:0,feedback:['맞아요. 결과 의미는 같아도 읽는 방법이 달라요.','후보 계획은 같은 결과를 내야 해요.','계획 비교가 기본키 값을 바꾸지 않아요.'],review:'b01'},
 {q:'1000행 대부분이 조건과 일치할 때 인덱스 이점이 작아질 수 있는 이유는?',options:['후보 행을 거의 모두 다시 읽을 수 있어서','인덱스가 SQL 결과를 삭제해서','COUNT가 항상 NULL이어서'],answer:0,feedback:['맞아요. 좁힐 후보가 적지 않으면 추가 인덱스 탐색 비용도 들어요.','인덱스는 올바른 결과 의미를 바꾸지 않아요.','집계 NULL 규칙과 다른 문제예요.'],review:'b02'},
 {q:'계획의 예상20행과 실제600행이 크게 다르면 먼저 살필 것은?',options:['통계와 데이터 분포','화면 글꼴','열 이름의 길이'],answer:0,feedback:['맞아요. 낡은 통계와 치우친 분포·상관관계를 확인해요.','글꼴은 행 수 추정과 관계없어요.','이름 길이가 선택도를 결정하지 않아요.'],review:'b05'}
 ],summary:['옵티마이저는 같은 논리 결과의 여러 물리 계획을 비용 모델로 비교해 선택해요.','전체 스캔과 인덱스 접근의 선택은 후보 비율·페이지·캐시·반환 열 등에 따라 달라져요.','실행 계획의 추정과 실제 행·반복·I/O를 비교해 통계와 성능 가정을 검증해요.'],nextQuestion:'여러 트랜잭션이 같은 행을 읽고 바꿀 때 격리 수준은 어떤 결과를 허용하고 막을까요?',sources:[['SQLite · EXPLAIN QUERY PLAN','https://www.sqlite.org/eqp.html'],['SQLite · Query Planning','https://www.sqlite.org/queryplanner.html'],['PostgreSQL · EXPLAIN','https://www.postgresql.org/docs/current/using-explain.html'],['CMU 15-445 · Query Processing','https://15445.courses.cs.cmu.edu/fall2018/notes/10-queryprocessing.pdf']]
};
})();
