(()=>{
const {table}=CS.helpers;
CS.lessons['ch14-l01']={
 lead:'각 트랜잭션이 혼자 실행하면 맞아도 서로의 중간에 끼어들면 관찰과 최종 결과가 달라질 수 있어요. 격리는 어떤 실행을 허용할지 정하는 약속이에요.',
 goals:['ACID의 네 성질과 서로 다른 읽기 이상을 구별해요.','문장·트랜잭션 스냅샷의 가시성을 직접 비교해요.','직렬화 가능성과 쓰기 편향을 충돌 관계로 설명해요.'],prerequisites:['ch03-l02','ch11-l01','ch12-l02'],sections:[
 {id:'b01',title:'ACID는 트랜잭션의 완료·규칙·동시 관찰·장애 결과를 나눠 묻는 관점이에요',html:`<p><strong>원자성</strong>은 관련 변경을 전부 반영하거나 전부 취소하고, <strong>일관성</strong>은 올바르게 정의한 제약을 지키는 상태 사이를 이동해요. <strong>격리성</strong>은 동시 실행의 관찰을 제어하고, <strong>지속성</strong>은 커밋 성공 뒤 장애가 나도 결과를 보존하는 성질이에요.</p><figure class="teaching-figure concept-figure"><div class="acid-visual" aria-label="원자성 일관성 격리성 지속성이 묻는 질문 네 가지"><span><b>A</b>전부 또는 전무<small>부분 변경 방지</small></span><span><b>C</b>정의한 규칙<small>제약 보존</small></span><span><b>I</b>동시 관찰<small>허용 실행 결정</small></span><span><b>D</b>커밋 뒤 보존<small>장애 복구</small></span></div><figcaption><strong>네 글자는 같은 보장을 반복한 것이 아니라 서로 다른 실패를 다뤄요</strong><ul class="picture-key"><li><b>업무 규칙</b>DB가 모르는 규칙은 애플리케이션도 올바르게 구현해야 해요.</li><li><b>격리 수준</b>성능과 동시성을 위해 허용 관찰이 달라질 수 있어요.</li><li><b>커밋</b>성공 응답과 내구화의 계약을 확인해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'더티 리드·반복 불가능 읽기·팬텀은 관찰 대상이 달라요',html:`<p><strong>더티 리드</strong>는 다른 거래의 미확정 값을 읽고, <strong>반복 불가능 읽기</strong>는 같은 행을 다시 읽었을 때 확정된 변경 때문에 값이 달라져요. <strong>팬텀</strong>은 같은 조건 조회를 반복했을 때 다른 거래의 삽입·삭제로 결과 행 집합이 달라지는 현상이에요.</p><figure class="teaching-figure concept-figure"><div class="read-anomalies-visual" aria-label="더티 리드 반복 불가능 읽기 팬텀의 실행 순서 비교"><div><b>더티 리드</b><span>T2: 120 쓰기</span><span>T1: 120 읽기</span><em>T2 ROLLBACK</em></div><div><b>반복 불가능</b><span>T1: 100 읽기</span><span>T2: 120 COMMIT</span><em>T1: 120 읽기</em></div><div><b>팬텀</b><span>T1: 조건 결과2행</span><span>T2: 새 행 COMMIT</span><em>T1: 결과3행</em></div></div><figcaption><strong>값 하나의 변화와 조건 결과 집합의 변화를 구별해요</strong><ul class="picture-key"><li><b>미확정</b>더티 리드는 취소될 값에 의존해요.</li><li><b>같은 행</b>반복 읽기의 값이 달라져요.</li><li><b>행 집합</b>팬텀은 조건을 만족하는 행 수·구성이 달라져요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'T1의 두 읽기가 어떤 확정 버전을 보는지 직접 비교해요',html:`<p>값100에서 T1이 읽고, T2가120을 써 커밋한 뒤 T1이 다시 읽어요. 문장마다 최신 확정 버전을 보는 규칙에서는100→120, T1 시작 스냅샷을 유지하면100→100이에요. T2가 커밋하기 전에는 두 규칙 모두 미확정120을 읽지 않아요.</p>`,lab:'isolation-snapshots'},
 {id:'b04',title:'직렬화 가능성은 동시 실행 결과가 어떤 직렬 순서와 같아야 한다는 기준이에요',html:`<p>직렬 실행은 T1 전체 뒤 T2 전체처럼 겹치지 않아요. <strong>직렬화 가능한</strong> 동시 실행은 섞여 실행돼도 충돌 관계가 어떤 직렬 순서와 같은 결과를 만들어요. 충돌 그래프에 순환이 있으면 충돌 직렬화 가능한 순서를 만들 수 없어요.</p><figure class="teaching-figure concept-figure"><div class="serializable-visual" aria-label="T1에서 T2로만 향하는 충돌 그래프와 양방향 순환 비교"><div><b>직렬 순서 가능</b><span>T1</span><i>→</i><span>T2</span><small>순환 없음</small></div><div><b>직렬 순서 불가</b><span>T1</span><i>⇄</i><span>T2</span><small>충돌 순환</small></div></div><figcaption><strong>실행이 겹쳤는지가 아니라 관찰 가능한 결과와 충돌 순서를 봐요</strong><ul class="picture-key"><li><b>선후 관계</b>같은 데이터를 읽고 쓰는 충돌이 방향을 만들어요.</li><li><b>비충돌 연산</b>순서를 바꿔도 결과가 같을 수 있어요.</li><li><b>직렬화 실패</b>DBMS가 한 거래를 중단하고 재시도를 요구할 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'같은 스냅샷을 유지해도 쓰기 편향 같은 이상이 남을 수 있어요',html:`<p>당직자가 최소 한 명 있어야 한다고 해요. T1과 T2가 같은 스냅샷에서 두 명 모두 근무 중임을 읽고 각자 자기 행만 휴무로 바꾸면, 서로 다른 행을 써도 최종적으로 당직0명이 될 수 있어요. 이것이 <strong>쓰기 편향</strong>의 전형적 모양이며 단순 반복 읽기만으로는 설명되지 않아요.</p><figure class="teaching-figure concept-figure"><div class="write-skew-visual" aria-label="두 거래가 같은 당직 스냅샷을 보고 서로 다른 행을 휴무로 바꾸는 그림"><div><b>시작</b><span>A 근무</span><span>B 근무</span></div><div><b>T1</b><span>둘 다 근무 확인</span><em>A 휴무</em></div><div><b>T2</b><span>둘 다 근무 확인</span><em>B 휴무</em></div><strong>최종 당직 0명</strong></div><figcaption><strong>각 행의 쓰기 충돌이 없어도 여러 행에 걸친 규칙이 깨질 수 있어요</strong><ul class="picture-key"><li><b>공통 읽기</b>두 거래가 같은 오래된 전제를 봐요.</li><li><b>다른 행 쓰기</b>단순 쓰기 충돌만으로 잡히지 않을 수 있어요.</li><li><b>대응</b>직렬화 격리·명시적 잠금·제약 모델을 검토해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'격리 수준 이름보다 제품이 실제로 허용하는 관찰과 실패를 확인해요',html:`${table(['관점','확인할 질문'],[['스냅샷 시점','문장마다 새로 보는가, 거래 전체가 같은 버전을 보는가?'],['읽기 이상','더티·반복 불가능·팬텀 중 무엇을 막는가?'],['쓰기 이상','갱신 손실·쓰기 편향·직렬화 순환을 어떻게 다루는가?'],['실패 방식','기다림·교착 중단·직렬화 실패 중 무엇이 가능한가?'],['재시도','전체 거래의 판단과 SQL을 다시 실행할 준비가 됐는가?']])}<p>SQL 표준의 격리 이름과 각 DBMS 구현은 완전히 같은 동작을 뜻하지 않을 수 있어요. 예를 들어 PostgreSQL의 Read Uncommitted는 Read Committed처럼 동작하고 Repeatable Read는 표준에서 허용한 팬텀도 허용하지 않아요. 사용하는 제품 문서를 기준으로 판단해야 해요.</p>`}
 ],questions:[
 {q:'T1이100을 읽은 뒤 T2가120을 커밋하고 T1이 같은 행에서120을 읽은 현상은?',options:['반복 불가능 읽기','더티 리드','팬텀만 발생'],answer:0,feedback:['맞아요. 같은 행의 두 확정 읽기 값이 달라졌어요.','T2가 이미 커밋했으므로 미확정 읽기가 아니에요.','행 집합의 추가·삭제 예제가 아니에요.'],review:'b02'},
 {q:'T1 시작 스냅샷 유지 모형에서 T2가120을 커밋한 뒤 T1의 둘째 읽기는?',options:['100','120','미확정 값'],answer:0,feedback:['맞아요. T1이 시작할 때 본 버전1을 계속 읽어요.','문장마다 최신 확정 버전을 볼 때의 결과예요.','T2는 이미 커밋했고 미확정 값은 읽지 않아요.'],review:'b03'},
 {q:'서로 다른 행을 수정했지만 당직 최소1명 규칙이 깨진 사례는?',options:['쓰기 편향','페이지 폴트','정상 직렬 실행'],answer:0,feedback:['맞아요. 같은 전제를 읽고 각자 다른 행을 바꿨어요.','가상 메모리 사건이 아니에요.','어떤 직렬 순서라면 두 번째 거래가 변경된 전제를 보게 돼요.'],review:'b05'}
 ],summary:['ACID는 원자성·일관성·격리성·지속성이라는 서로 다른 실패 관점을 다뤄요.','격리 규칙은 더티·반복 불가능·팬텀과 버전 가시성을 결정해요.','스냅샷만으로 쓰기 편향이 남을 수 있어 직렬화 가능성과 제품별 실패·재시도 규칙을 확인해요.'],nextQuestion:'커밋된 변경과 미완료 변경을 장애 뒤 구별하려면 잠금·버전·로그는 각각 어떤 역할을 할까요?',sources:[['PostgreSQL · Transaction Isolation','https://www.postgresql.org/docs/current/transaction-iso.html'],['PostgreSQL · MVCC 소개','https://www.postgresql.org/docs/current/mvcc-intro.html'],['CMU 15-445 · Concurrency Control','https://15445.courses.cs.cmu.edu/spring2023/notes/15-concurrencycontrol.pdf']]
};

CS.lessons['ch14-l02']={
 lead:'동시 실행 중에는 잘못된 충돌을 막고, 장애 뒤에는 커밋 여부에 맞는 상태를 복원해야 해요. 잠금·버전·검사와 WAL은 이 두 문제를 나눠 해결해요.',
 goals:['2단계 잠금·MVCC·낙관적 제어의 충돌 처리 방식을 비교해요.','WAL의 선행 기록 규칙과 체크포인트 역할을 설명해요.','커밋 전후 장애 복구와 안전한 재시도를 실행해요.'],prerequisites:['ch14-l01','ch11-l02','ch10-l02'],sections:[
 {id:'b01',title:'2단계 잠금은 잠금을 얻는 구간과 놓는 구간을 나눠 충돌 순서를 만들어요',html:`<p><strong>2단계 잠금</strong>(2PL)은 성장 단계에서 잠금을 얻고, 하나라도 놓기 시작한 축소 단계에서는 새 잠금을 얻지 않는 규칙이에요. 충돌 직렬화 가능성을 만들 수 있지만 교착이 생길 수 있어 탐지·예방·중단 정책이 필요해요. Strict 2PL은 쓰기 잠금을 커밋·롤백까지 유지해 복구를 단순하게 도울 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="two-phase-lock-visual" aria-label="잠금을 얻는 성장 단계와 놓는 축소 단계"><div><b>성장 단계</b><span>LOCK A</span><span>LOCK B</span><small>잠금 획득만</small></div><i>첫 해제</i><div><b>축소 단계</b><span>UNLOCK A</span><span>UNLOCK B</span><small>새 잠금 금지</small></div></div><figcaption><strong>2단계라는 이름은 거래의 작업 수가 아니라 잠금 획득·해제 규칙이에요</strong><ul class="picture-key"><li><b>상호 배제</b>충돌하는 접근을 기다리게 해요.</li><li><b>직렬화</b>충돌 순서를 한 방향으로 만들어요.</li><li><b>교착</b>여러 잠금의 대기 순환은 별도로 처리해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'MVCC는 새 값을 덮어쓰기보다 여러 버전과 가시성 정보를 관리해요',html:`<p><strong>MVCC</strong>는 행의 여러 버전을 유지하고 트랜잭션의 스냅샷에 보이는 버전을 골라요. 읽기와 쓰기가 항상 같은 잠금으로 서로를 막지 않게 할 수 있지만, 오래된 버전 정리·저장 공간·쓰기 충돌·직렬화 이상 처리가 필요해요.</p><figure class="teaching-figure concept-figure"><div class="mvcc-versions-visual" aria-label="값100 버전1과 값120 버전2를 서로 다른 스냅샷이 읽는 그림"><div><b>버전 사슬</b><span>v1 · 값100</span><i>→</i><span>v2 · 값120</span></div><div><b>T1 snapshot=1</b><strong>100 보임</strong></div><div><b>T3 snapshot=2</b><strong>120 보임</strong></div></div><figcaption><strong>같은 행에도 스냅샷마다 다른 확정 버전이 보일 수 있어요</strong><ul class="picture-key"><li><b>가시성</b>시작 시점과 커밋 정보를 계산해요.</li><li><b>정리</b>아무도 필요로 하지 않는 옛 버전을 회수해요.</li><li><b>한계</b>MVCC라는 이름만으로 직렬화 가능성이 자동 보장되지는 않아요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'낙관적 제어는 먼저 작업하고 커밋 전에 충돌을 검사해요',html:`<p>충돌이 드물다고 예상하면 읽기와 계산을 진행한 뒤 검증 단계에서 읽은 버전이 바뀌었는지 확인할 수 있어요. 충돌이 없으면 커밋하고, 있으면 중단한 뒤 최신 상태에서 전체 판단을 다시 해야 해요. 충돌이 잦으면 반복 재시도 비용이 커질 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="optimistic-visual" aria-label="읽기 계산 검증 뒤 커밋하거나 충돌 시 재시도하는 흐름"><span>읽기 v1</span><i>→</i><span>계산</span><i>→</i><span>검증</span><div><b>v1 유지</b>COMMIT</div><div><b>v2로 변경</b>ABORT → 재시도</div></div><figcaption><strong>낙관적이라는 말은 충돌을 무시한다는 뜻이 아니에요</strong><ul class="picture-key"><li><b>검증</b>읽은 전제가 아직 유효한지 확인해요.</li><li><b>중단</b>충돌한 결과를 확정하지 않아요.</li><li><b>재시도</b>새 스냅샷에서 비즈니스 판단부터 반복해요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'WAL에서 COMMIT 로그의 내구화 시점을 바꿔 장애 복구를 실행해요',html:`<p><strong>WAL</strong>은 데이터 페이지의 변경을 저장장치에 쓰기 전에 그 변경을 설명하는 로그를 먼저 내구화하는 규칙이에요. 이 모형에서 UPDATE만 내구화되고 COMMIT은 사라지면 값100을 유지하고, UPDATE와 COMMIT이 모두 내구화되면 데이터 페이지가 아직100이어도 복구가120을 재실행해요.</p>`,lab:'wal-recovery'},
 {id:'b05',title:'체크포인트는 복구가 살펴볼 로그 시작 범위를 줄이는 기준점이에요',html:`<p>로그가 끝없이 쌓이면 시작부터 모두 재생하는 복구는 오래 걸려요. <strong>체크포인트</strong>는 복구에 필요한 상태와 진행 위치를 기록하고, 관련 더티 페이지와 로그 보존 범위를 관리해 다시 살펴볼 양을 줄여요. 체크포인트 순간에 모든 서비스를 멈추고 모든 페이지를 한꺼번에 쓰는 방식만 있는 것은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="checkpoint-visual" aria-label="오래된 로그 체크포인트 이후 복구 시작점과 최신 로그"><span>오래된 로그</span><span class="checkpoint">CHECKPOINT</span><span>UPDATE T7</span><span>COMMIT T7</span><i>복구 탐색 시작 범위 축소</i></div><figcaption><strong>체크포인트는 로그를 없애는 버튼이 아니라 안전한 복구 기준을 만드는 절차예요</strong><ul class="picture-key"><li><b>위치</b>복구가 어디서부터 분석할지 도와요.</li><li><b>더티 페이지</b>메모리 변경의 저장 상태를 추적해요.</li><li><b>로그 보존</b>활성 거래와 백업·복제 요구도 고려해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'커밋 응답을 잃으면 성공 여부를 모를 수 있어 중복 방지 재시도가 필요해요',html:`${table(['상황','안전한 처리 질문'],[['직렬화 실패','전체 거래의 읽기·판단·쓰기를 새 상태에서 다시 실행하는가?'],['응답 전 장애','서버가 커밋하지 않았음을 확인할 수 있는가?'],['커밋 뒤 응답 유실','같은 요청을 다시 보내도 결과가 한 번만 적용되는가?'],['외부 부작용','DB 커밋과 메시지·결제 호출 사이의 중복을 어떻게 막는가?']])}<p>요청ID 같은 <strong>멱등성 키</strong>를 저장해 이미 처리한 요청의 결과를 돌려주면 중복 생성을 막을 수 있어요. 단순히 네트워크 오류가 날 때마다 같은 INSERT를 반복하거나, 오류 종류를 확인하지 않고 무한 재시도하면 안 돼요.</p>`}
 ],questions:[
 {q:'2단계 잠금의 축소 단계가 시작된 뒤 허용되는 것은?',options:['보유 잠금 해제','새 잠금 획득','과거 로그 삭제만'],answer:0,feedback:['맞아요. 첫 해제 뒤에는 잠금을 놓기만 해요.','새 잠금을 얻으면 성장 단계로 되돌아가 규칙을 깨요.','로그 관리는2PL 단계 정의가 아니에요.'],review:'b01'},
 {q:'UPDATE 로그는 내구화됐지만 COMMIT 로그가 내구화되기 전 장애가 났다면 이 모형의 복구 값은?',options:['100','120','둘 다 동시에'],answer:0,feedback:['맞아요. 미완료 거래를 확정 결과로 재실행하지 않아요.','내구화된 COMMIT까지 있을 때의 결과예요.','복구 뒤 확정 상태는 하나여야 해요.'],review:'b04'},
 {q:'커밋은 됐지만 응답을 잃은 요청을 안전하게 재시도하는 데 도움이 되는 것은?',options:['저장된 멱등성 요청ID','항상 새 요청ID 생성','제약을 모두 끄기'],answer:0,feedback:['맞아요. 이미 처리한 같은 요청인지 식별해 중복을 막아요.','매번 새 ID면 같은 작업인지 알기 어려워요.','제약을 끄면 중복과 불일치 위험이 커져요.'],review:'b06'}
 ],summary:['2PL은 잠금 획득·해제 단계를, MVCC는 버전 가시성을, 낙관적 제어는 커밋 전 충돌 검사를 사용해요.','WAL은 데이터 페이지보다 로그를 먼저 내구화하고 체크포인트는 복구 탐색 범위를 줄여요.','복구는 커밋된 변경만 보존해야 하며 불확실한 응답의 재시도에는 중복 방지 식별이 필요해요.'],nextQuestion:'트랜잭션 요청이 네트워크를 건너 다른 컴퓨터에 도착할 때 IP·TCP·라우팅은 각각 무엇을 보장할까요?',sources:[['PostgreSQL · Concurrency Control','https://www.postgresql.org/docs/current/mvcc.html'],['PostgreSQL · Serialization Failure Handling','https://www.postgresql.org/docs/current/mvcc-serialization-failure-handling.html'],['PostgreSQL · WAL Configuration','https://www.postgresql.org/docs/current/wal-configuration.html'],['CMU 15-445 · Recovery','https://15445.courses.cs.cmu.edu/fall2024/notes/21-recovery.pdf']]
};
})();
