(()=>{
const {table}=CS.helpers;
CS.lessons['ch15-l01']={
 lead:'IP 주소는 목적지를 표시하지만 패킷이 어느 다음 홉으로 갈지는 서브넷과 라우팅 표가 결정해요. 이름 해석·주소 변환·크기 제한도 서로 다른 역할이에요.',
 goals:['IPv4 주소와 prefix로 네트워크 범위를 계산해요.','라우팅 표의 최장 prefix 일치로 다음 홉을 선택해요.','NAT·DNS 캐시·MTU의 역할과 한계를 구별해요.'],prerequisites:['ch06-l01','ch08-l02','ch05-l02'],sections:[
 {id:'b01',title:'IP prefix는 주소의 앞부분 중 네트워크를 나타내는 비트 수예요',html:`<p>IPv4 주소는32비트이고 <code>192.0.2.128/25</code>의 /25는 앞25비트가 네트워크 부분이라는 뜻이에요. 남은7비트로 그 범위 안의 주소를 구별해요. 서브넷 마스크는 같은 경계를 다른 표기로 나타낼 수 있지만 prefix 길이가 곧 사용 가능한 호스트 수를 그대로 뜻하지는 않아요.</p><figure class="teaching-figure concept-figure"><div class="subnet-bits-visual" aria-label="192.0.2.130 주소의 앞25비트 네트워크와 뒤7비트 호스트 부분"><div><b>192.0.2.130</b><span>11000000.00000000.00000010.1</span><em>0000010</em></div><div><strong>앞25비트</strong><small>네트워크 192.0.2.128/25</small></div><div><strong>뒤7비트</strong><small>범위 안 주소 구별</small></div></div><figcaption><strong>같은 prefix를 공유하는 주소 집합을 하나의 경로로 표현할 수 있어요</strong><ul class="picture-key"><li><b>/25</b>/24보다 범위가 작고 더 구체적이에요.</li><li><b>주소 범위</b>192.0.2.128~255가 같은 prefix예요.</li><li><b>경계</b>prefix 비트에서 네트워크가 나뉘어요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'라우터는 목적지와 일치하는 경로 중 가장 긴 prefix를 선택해요',html:`<p>라우팅 표에는 목적지 prefix와 다음 홉 또는 출력 인터페이스가 있어요. 여러 경로가 일치하면 더 긴 prefix가 더 작은 주소 집합을 가리키므로 <strong>최장 prefix 일치</strong>를 사용해요. 아무 구체 경로도 없을 때 /0 기본 경로가 후보가 될 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="routing-table-visual" aria-label="목적지130이 24와25에 모두 일치해 더 긴25의 R2를 선택"><div><span>192.0.2.0/24 → R1</span><span class="chosen">192.0.2.128/25 → R2</span><span>0.0.0.0/0 → R3</span></div><i>목적지<br><b>192.0.2.130</b></i><strong>/25 · R2 선택</strong></div><figcaption><strong>목록에서 먼저 보이는 경로가 아니라 가장 구체적인 일치를 골라요</strong><ul class="picture-key"><li><b>후보</b>/24·/25·/0이 모두 일치해요.</li><li><b>선택</b>길이25가 가장 긴 prefix예요.</li><li><b>다음 홉</b>최종 목적지가 아니라 다음 전달 지점일 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'목적지를 바꿔 /25·/24·기본 경로를 직접 선택해요',html:`<p>192.0.2.130은 R2, 192.0.2.20은 /24의 R1, 203.0.113.7은 기본 경로 R3를 선택해요. 기본 경로까지 없으면 경로 없음으로 끝나야 하고 잘못된 IPv4 주소는 계산 전에 거부해야 해요.</p>`,lab:'ipv4-routing'},
 {id:'b04',title:'NAT는 경계에서 주소·포트 대응 상태를 바꿔 여러 내부 흐름을 구별해요',html:`<p>사설 IPv4 주소는 인터넷 전체에서 직접 라우팅되는 공인 주소와 범위가 달라요. NAPT/PAT 모형에서는 경계 장치가 내부 출발 주소·포트를 외부 주소·포트로 바꾸고 대응표로 돌아오는 흐름을 원래 호스트에 전달해요. NAT가 암호화나 방화벽 정책을 자동 제공하는 것은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="nat-map-visual" aria-label="두 사설 주소의 연결을 하나의 공인 주소와 다른 포트로 변환"><div><b>내부</b><span>10.0.0.2:5100</span><span>10.0.0.3:5100</span></div><i>NAT 대응표</i><div><b>외부 표현</b><span>203.0.113.5:40001</span><span>203.0.113.5:40002</span></div></div><figcaption><strong>같은 공인 주소도 변환된 포트로 내부 흐름을 구별할 수 있어요</strong><ul class="picture-key"><li><b>상태</b>응답을 되돌릴 주소·포트 대응을 기억해요.</li><li><b>주소 부족</b>여러 내부 주소가 한 외부 주소를 공유할 수 있어요.</li><li><b>종단 연결</b>외부에서 내부로 새 연결할 때 별도 매핑이 필요할 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'DNS는 계층적으로 이름을 찾고 TTL 동안 답을 캐시할 수 있어요',html:`<p>재귀 해석기는 캐시에 답이 없으면 루트·TLD·권한 서버의 위임을 따라 이름 정보를 얻을 수 있어요. 레코드의 <strong>TTL</strong>은 캐시가 그 답을 얼마나 오래 재사용할 수 있는지 나타내요. TTL이 끝났다고 원본 레코드가 삭제되는 것은 아니며, DNS가 실제 HTTP 연결까지 대신 만드는 것도 아니에요.</p><figure class="teaching-figure concept-figure"><div class="dns-hierarchy-visual" aria-label="재귀 해석기가 루트 TLD 권한 서버를 거쳐 답을 캐시"><span>브라우저</span><i>질문</i><span>재귀 해석기<br><b>캐시 TTL</b></span><i>위임</i><span>루트 → .kr → 권한 서버</span><strong>203.0.113.5</strong></div><figcaption><strong>이름을 주소로 해석하는 과정과 그 주소로 연결하는 과정은 나뉘어요</strong><ul class="picture-key"><li><b>계층</b>각 서버가 다음 권한 위치를 안내할 수 있어요.</li><li><b>캐시</b>TTL 안에서는 이전 답을 재사용해요.</li><li><b>변경 전파</b>캐시마다 남은 TTL이 달라 관측 시점이 다를 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'MTU는 한 링크가 나눔 없이 전달할 수 있는 IP 패킷 크기 제한이에요',html:`${table(['개념','의미','확인할 점'],[['링크 MTU','해당 링크가 전달하는 최대 IP 패킷 크기','경로 중 더 작은 MTU가 제약이 될 수 있음'],['IP 단편화','IPv4에서 패킷을 조각으로 나누는 방식','손실·재조립 비용 때문에 회피하는 경우가 많음'],['Path MTU Discovery','경로가 허용하는 크기를 알아내려는 절차','필요한 제어 메시지 차단 시 문제 가능'],['TCP MSS','TCP 데이터 구간의 최대 크기 협상 값','IP·TCP 헤더를 제외한 데이터 기준']])}<p>애플리케이션 메시지 크기와 한 IP 패킷 크기는 같지 않아요. 큰 데이터는 전송 계층에서 여러 세그먼트로 나뉠 수 있고 각 링크에서 프레임으로 전달돼요.</p>`}
 ],questions:[
 {q:'192.0.2.130이 /24와 /25 경로에 모두 일치할 때 선택하는 것은?',options:['더 긴 /25 경로','더 짧은 /24 경로','항상 기본 경로'],answer:0,feedback:['맞아요. 더 구체적인 최장 prefix 일치예요.','/24는 더 넓은 주소 범위를 나타내요.','구체 경로가 있으므로 /0보다 우선해요.'],review:'b02'},
 {q:'NAT가 자동으로 제공한다고 볼 수 없는 것은?',options:['종단 간 암호화','주소·포트 변환 대응','여러 내부 흐름의 외부 주소 공유'],answer:0,feedback:['맞아요. 암호화는 TLS·IPsec 같은 별도 기술이 필요해요.','NAT의 핵심 동작이에요.','포트 변환 모형에서 가능한 사용 방식이에요.'],review:'b04'},
 {q:'DNS 캐시의 TTL이 끝났다는 뜻은?',options:['캐시 답을 새로 확인할 시점','원본 도메인이 삭제됨','TCP 연결이 강제 종료됨'],answer:0,feedback:['맞아요. 이전 답을 계속 재사용하지 않고 다시 해석할 수 있어요.','권한 서버의 원본 삭제 의미가 아니에요.','전송 연결의 수명과 다른 값이에요.'],review:'b05'}
 ],summary:['IP prefix는 네트워크 범위를 표현하고 라우터는 일치 경로 중 가장 긴 prefix를 선택해요.','NAT는 주소·포트 대응, DNS는 계층적 이름 해석과 TTL 캐시를 담당해요.','MTU·MSS와 애플리케이션 메시지 크기를 구별하고 경로의 크기 제한을 고려해요.'],nextQuestion:'경로 중 일부 패킷이 사라지거나 순서가 뒤바뀌면 TCP는 어떤 번호와 확인 응답으로 복구할까요?',sources:[['RFC 1812 · IPv4 Router Requirements','https://www.rfc-editor.org/rfc/rfc1812.html'],['RFC 1918 · Private Address Space','https://www.rfc-editor.org/rfc/rfc1918.html'],['RFC 2663 · NAT Terminology','https://www.rfc-editor.org/rfc/rfc2663.html'],['RFC 1034 · DNS Concepts','https://www.rfc-editor.org/rfc/rfc1034.html']]
};

CS.lessons['ch15-l02']={
 lead:'IP가 패킷 전달을 시도해도 손실·중복·순서 변경은 생길 수 있어요. TCP는 바이트 순서와 확인 응답으로 신뢰성 있는 스트림을 만들어요.',
 goals:['TCP 연결과 바이트 순서 번호·누적 ACK를 설명해요.','중간 바이트 유실과 중복 도착을 재전송으로 복구해요.','흐름 제어·혼잡 제어·UDP와 성능 지표를 구별해요.'],prerequisites:['ch15-l01','ch06-l01','ch05-l02'],sections:[
 {id:'b01',title:'TCP 연결은 양쪽의 시작 순서 번호와 통신 준비 상태를 맞춰요',html:`<p>TCP의 3-way handshake는 SYN, SYN+ACK, ACK를 교환해 양쪽의 시작 순서 번호를 확인하고 연결 상태를 만들어요. 이 과정은 애플리케이션 사용자 인증이나 TLS 암호화와 다른 절차예요. 연결이 만들어진 뒤에도 데이터는 지연·손실될 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="handshake-visual" aria-label="클라이언트와 서버가 SYN SYNACK ACK를 교환"><div><b>클라이언트</b><span>SYN · seq=100</span><span class="back">ACK · ack=501</span></div><div><i>→</i><i>←</i><i>→</i></div><div><b>서버</b><span class="back">SYN+ACK · seq=500 · ack=101</span><span>ESTABLISHED</span></div></div><figcaption><strong>각 방향의 순서 번호 공간을 동기화해 데이터 전송을 시작해요</strong><ul class="picture-key"><li><b>SYN</b>연결 요청과 시작 번호를 알려요.</li><li><b>ACK</b>상대 시작 번호를 확인해요.</li><li><b>범위</b>서버가 누구인지 신뢰하는 인증 절차는 별도예요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'TCP는 바이트마다 순서 번호를 두고 다음 기대 번호를 누적 ACK로 알려요',html:`<p>TCP 순서 번호는 패킷 개수가 아니라 바이트 스트림의 위치를 나타내요. 이 교안의1바이트 예에서 A(seq1)를 받으면 다음 기대 번호인 ACK2를 보내요. C(seq3)가 먼저 와도 B(seq2)가 비어 있으므로 ACK2를 유지하고 C는 순서 대기 버퍼에 둘 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="seq-ack-visual" aria-label="A 도착 뒤 ACK2 B 유실 C 도착 뒤에도 ACK2인 흐름"><span>A<br><b>seq1</b></span><i>도착</i><strong>ACK2</strong><span class="lost">B<br><b>seq2 유실</b></span><span>C<br><b>seq3 보관</b></span><i>틈 존재</i><strong>ACK2 유지</strong></div><figcaption><strong>ACK2는1번까지 받았고2번을 다음에 기대한다는 뜻이에요</strong><ul class="picture-key"><li><b>누적 확인</b>ACK X는 X보다 앞선 바이트를 확인해요.</li><li><b>순서 대기</b>뒤 바이트가 와도 빈 구간을 기다려요.</li><li><b>중복 감지</b>이미 확인한 번호는 앱에 두 번 전달하지 않아요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'B 유실 뒤 C를 보관하고 재전송 B로 ABC를 완성해요',html:`<p>A 뒤 ACK2, B 유실, C 도착 뒤에도 ACK2, B 재전송 뒤 ACK4와 앱 내용ABC가 되는 순서를 실행하세요. 유실이 없는 흐름은 재전송0회이고, 이미 받은 B가 다시 와도 앱에 중복 전달하지 않아요.</p>`,lab:'tcp-recovery'},
 {id:'b04',title:'흐름 제어와 혼잡 제어는 보호하려는 대상이 달라요',html:`<p><strong>흐름 제어</strong>는 수신 버퍼가 넘치지 않도록 수신자가 광고한 윈도에 맞춰 보내요. <strong>혼잡 제어</strong>는 네트워크 경로에 과도한 패킷을 넣지 않도록 손실·지연 신호 등에 반응해 전송량을 조절해요. 실제 전송 가능량은 수신 윈도와 혼잡 윈도 모두의 제한을 받아요.</p><figure class="teaching-figure concept-figure"><div class="window-control-visual" aria-label="수신 윈도와 혼잡 윈도의 더 작은 값이 전송 한도를 정함"><div><b>수신 윈도 rwnd</b><strong>8 KB</strong><small>수신 버퍼 보호</small></div><div><b>혼잡 윈도 cwnd</b><strong>5 KB</strong><small>네트워크 경로 보호</small></div><i>min</i><div class="send-limit"><b>전송 한도</b><strong>5 KB</strong></div></div><figcaption><strong>두 윈도를 같은 값이나 같은 목적이라고 설명하지 않아요</strong><ul class="picture-key"><li><b>rwnd</b>수신자가 처리 가능한 여유와 관련돼요.</li><li><b>cwnd</b>송신자가 경로 상태에 따라 관리해요.</li><li><b>가변성</b>ACK·손실·알고리즘에 따라 시간에 따라 변해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'UDP는 작은 데이터그램 서비스를 제공하고 필요한 신뢰성은 앱이 선택해 보완해요',html:`<p>UDP는 연결 설정·바이트 스트림·TCP식 재전송·순서 복원을 기본 제공하지 않아요. 그래서 지연을 줄이거나 메시지 경계를 유지하려는 앱에 쓰일 수 있지만, 신뢰성이 필요하면 앱 프로토콜이 확인·재전송·순서·중복 제거·혼잡 대응을 설계해야 해요. UDP라고 항상 빠른 것은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="tcp-udp-visual" aria-label="TCP 기본 기능과 UDP에서 앱이 선택하는 기능 비교"><div><b>TCP</b><span>바이트 스트림</span><span>순서·재전송</span><span>흐름·혼잡 제어</span></div><div><b>UDP</b><span>데이터그램 경계</span><span>손실·순서 보장 없음</span><span>필요 기능은 앱 설계</span></div></div><figcaption><strong>프로토콜 선택은 속도라는 한 단어보다 앱의 요구와 실패 처리를 봐요</strong><ul class="picture-key"><li><b>메시지 경계</b>UDP 데이터그램은 개별 단위를 유지해요.</li><li><b>신뢰성</b>필요한 경우 앱이나 상위 프로토콜이 구현해요.</li><li><b>혼잡</b>UDP 기반 앱도 네트워크 공정성을 고려해야 해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'지연·처리량·손실률·지터는 서로 다른 통신 품질을 말해요',html:`${table(['지표','묻는 질문','예'],[['지연','한 데이터가 도착하기까지 얼마나 걸리는가?','왕복 시간 RTT, 단방향 지연'],['처리량','시간당 실제로 얼마나 전달되는가?','Mbps·요청/초'],['손실률','보낸 단위 중 사라진 비율은 얼마인가?','1000개 중10개=1%'],['지터','지연 시간이 얼마나 흔들리는가?','20ms, 80ms, 25ms'],['좋은put','앱에 유용한 데이터 전달량은 얼마인가?','재전송·헤더를 제외한 유효량']])}<p>대역폭이 커도 RTT가 길 수 있고 평균 지연이 같아도 지터가 다를 수 있어요. 실제 측정에서는 관찰 위치·시간 구간·표본 수와 재전송 여부를 함께 기록해야 해요.</p>`}
 ],questions:[
 {q:'A(seq1) 뒤 C(seq3)가 도착했지만 B(seq2)가 없을 때 누적 ACK는?',options:['ACK2','ACK4','ACK1로 감소'],answer:0,feedback:['맞아요. 다음 기대 바이트2가 비어 있어요.','B까지 채워져1~3을 모두 받은 뒤의 값이에요.','A를 확인했으므로 다음 기대 번호는2예요.'],review:'b02'},
 {q:'수신 버퍼가 넘치지 않도록 조절하는 것은?',options:['흐름 제어','DNS TTL','라우팅 prefix'],answer:0,feedback:['맞아요. 수신 윈도와 관련돼요.','이름 해석 캐시 수명이에요.','IP 다음 홉 선택 기준이에요.'],review:'b04'},
 {q:'UDP에서 순서 복원과 재전송이 필요하다면?',options:['애플리케이션 프로토콜이 설계한다','IP 주소가 자동 해결한다','아무 처리 없이 항상 보장된다'],answer:0,feedback:['맞아요. 요구에 맞게 상위 계층이 보완해야 해요.','IP는 UDP 데이터그램의 순서·재전송을 보장하지 않아요.','UDP 기본 보장이 아니에요.'],review:'b05'}
 ],summary:['TCP는 연결 상태와 바이트 순서 번호·누적 ACK·재전송으로 순서 있는 스트림을 제공해요.','흐름 제어는 수신 버퍼를, 혼잡 제어는 네트워크 경로를 보호해요.','UDP의 보장 범위를 확인하고 지연·처리량·손실률·지터를 따로 측정해요.'],nextQuestion:'TCP로 받은 HTML·CSS·JavaScript를 브라우저는 어떤 단계로 해석하고 화면에 그릴까요?',sources:[['RFC 9293 · TCP','https://www.rfc-editor.org/rfc/rfc9293.html'],['RFC 5681 · TCP Congestion Control','https://www.rfc-editor.org/rfc/rfc5681.html'],['RFC 768 · UDP','https://www.rfc-editor.org/rfc/rfc768.html'],['RFC 6298 · Retransmission Timer','https://www.rfc-editor.org/rfc/rfc6298.html']]
};
})();
