(()=>{
const {table}=CS.helpers;
CS.lessons['ch16-l01']={
 lead:'서버가 보낸 HTML·CSS·JavaScript는 곧바로 화면이 되지 않아요. 브라우저가 구조와 스타일을 만들고, 크기와 위치를 계산한 뒤 픽셀을 그리며 JavaScript 작업도 순서대로 처리해요.',
 goals:['HTML·CSS가 DOM·CSSOM과 렌더링 단계로 이어지는 흐름을 설명해요.','태스크·마이크로태스크와 화면 갱신의 실행 순서를 관찰해요.','긴 메인 스레드 작업이 입력과 화면 응답을 늦추는 이유를 설명해요.'],prerequisites:['ch06-l02','ch15-l02','ch02-l02'],sections:[
 {id:'b01',title:'HTML과 CSS는 서로 다른 구조로 해석된 뒤 화면에 필요한 정보를 만들어요',html:`<p>HTML 파서는 요소의 부모·자식 관계를 가진 <strong>DOM</strong>을 만들어요. CSS는 선택자와 선언을 다루는 <strong>CSSOM</strong>으로 해석돼요. 브라우저는 두 구조를 함께 살펴 각 요소에 적용할 스타일을 계산해요. DOM이 HTML 원문을 그대로 보관한 문자열이거나 CSSOM이 픽셀 그림이라는 뜻은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="parse-trees-visual" aria-label="HTML과 CSS가 DOM과 CSSOM으로 나뉘어 해석된 뒤 스타일 계산으로 만남"><div><b>HTML</b><span>&lt;main&gt;</span><span>└ &lt;h1&gt;</span><strong>DOM</strong></div><i>+</i><div><b>CSS</b><span>h1 { color: blue }</span><span>.card { padding: 16px }</span><strong>CSSOM</strong></div><em>→ 스타일 계산</em></div><figcaption><strong>구조와 스타일 규칙을 따로 해석한 뒤 어떤 요소에 어떤 규칙이 적용되는지 계산해요</strong><ul class="picture-key"><li><b>DOM</b>문서 요소와 관계를 나타내요.</li><li><b>CSSOM</b>스타일 규칙을 객체 구조로 다뤄요.</li><li><b>변경</b>JavaScript가 두 구조를 바꿀 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'스타일 계산·레이아웃·페인트·합성은 서로 다른 질문에 답해요',html:`<p><strong>스타일 계산</strong>은 적용할 속성을, <strong>레이아웃</strong>은 상자의 크기와 위치를 정해요. <strong>페인트</strong>는 글자·배경·테두리 같은 그리기 명령을 만들고, <strong>합성</strong>은 필요한 층을 화면에 조합해요. 실제 브라우저는 최적화에 따라 일부 단계를 건너뛰거나 묶을 수 있으므로 모든 변경이 항상 전체 과정을 다시 거치는 것은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="render-pipeline-visual" aria-label="스타일 계산 레이아웃 페인트 합성의 화면 생성 단계"><span><b>1</b>스타일<small>색·크기 규칙</small></span><i>→</i><span><b>2</b>레이아웃<small>위치·상자 크기</small></span><i>→</i><span><b>3</b>페인트<small>글자·배경 기록</small></span><i>→</i><span><b>4</b>합성<small>층을 화면에 조합</small></span></div><figcaption><strong>“무엇처럼 보일까, 어디에 놓일까, 무엇을 그릴까, 어떤 층을 합칠까”를 차례로 해결해요</strong><ul class="picture-key"><li><b>레이아웃</b>width 같은 기하 속성의 영향을 받아요.</li><li><b>페인트</b>색·그림자 변경과 관련될 수 있어요.</li><li><b>합성</b>transform 같은 변경을 별도 층에서 처리할 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'이벤트 루프는 실행할 작업을 고르고 한 태스크 뒤 마이크로태스크를 비워요',html:`<p>브라우저의 메인 스레드는 한 순간에 한 JavaScript 실행 흐름을 처리해요. 한 <strong>태스크</strong>가 끝나 실행 스택이 비면 준비된 <strong>마이크로태스크</strong>를 처리하고, 이후 브라우저가 화면을 갱신할 기회를 가질 수 있어요. <code>setTimeout(fn, 0)</code>도 즉시 실행 약속이 아니라 새 태스크가 실행 가능해지는 조건이에요.</p><figure class="teaching-figure concept-figure"><div class="event-loop-visual" aria-label="태스크 실행 뒤 마이크로태스크를 비우고 렌더링 기회를 거쳐 다음 태스크로 감"><span>태스크 A 실행</span><i>→</i><span class="micro">마이크로태스크<br>B 처리</span><i>→</i><span class="render">렌더링 기회</span><i>→</i><span>다음 태스크<br>C 처리</span></div><figcaption><strong>Promise 반응의 B가 타이머 태스크 C보다 먼저 실행되는 이유를 큐의 종류로 설명할 수 있어요</strong><ul class="picture-key"><li><b>실행 스택</b>현재 JavaScript가 끝나야 해요.</li><li><b>마이크로태스크</b>현재 태스크 뒤 checkpoint에서 처리해요.</li><li><b>렌더링</b>매 태스크마다 반드시 한 번 그린다는 뜻은 아니에요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'동기 A·Promise B·타이머 C의 실제 출력 순서를 확인해요',html:`<p><code>console.log('A')</code>, 이행된 Promise의 B, 0ms 타이머의 C를 준비된 코드로 실행해요. 먼저 예상하고 여러 번 실행해도 각 실행 로그가 섞이지 않는지 확인하세요.</p>`,lab:'event-loop-order'},
 {id:'b05',title:'긴 메인 스레드 작업은 입력 처리와 다음 화면 갱신을 함께 기다리게 해요',html:`<p>큰 계산이 메인 스레드를 오래 점유하면 클릭·키 입력을 처리할 태스크와 화면 갱신 기회가 뒤로 밀려요. 작업을 작은 단위로 나누거나 계산을 <strong>Web Worker</strong>로 옮길 수 있어요. Worker는 DOM을 직접 바꾸지 못하므로 결과를 메시지로 보내고 메인 스레드가 화면에 반영해요.</p><figure class="teaching-figure concept-figure"><div class="long-task-visual" aria-label="긴 메인 스레드 작업이 입력과 그리기를 막고 워커 계산은 메시지로 결과를 돌려줌"><div><b>메인 스레드만 사용</b><span class="long">긴 계산 120ms</span><span>클릭 대기</span><span>그리기 대기</span></div><div><b>Worker로 계산</b><span>메인: 입력 처리</span><i>⇄ 메시지</i><span class="worker">Worker: 계산</span></div></div><figcaption><strong>CPU 총 작업량뿐 아니라 메인 스레드가 사용자의 입력에 다시 답할 수 있는 시점이 중요해요</strong><ul class="picture-key"><li><b>긴 작업</b>다음 태스크가 시작될 기회를 늦춰요.</li><li><b>분할</b>중간에 제어권을 돌려줄 수 있어요.</li><li><b>Worker</b>계산과 DOM 변경의 책임을 나눠요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'변경한 속성에 따라 필요한 화면 갱신 비용이 달라질 수 있어요',html:`${table(['변경 예','관련될 수 있는 단계','초심자 점검'],[['텍스트·상자 너비','스타일 → 레이아웃 → 페인트 → 합성','주변 요소 위치도 바뀌는가?'],['배경색','스타일 → 페인트 → 합성','기하 구조는 그대로인가?'],['transform 이동','스타일 → 합성 가능','별도 층과 메모리 비용도 확인'],['DOM 대량 추가','파싱 이후 DOM 변경과 여러 갱신','읽기·쓰기를 불필요하게 교차하지 않는가?']])}<p>이 표는 이해를 위한 대표 경로예요. 실제 단계와 비용은 속성·브라우저·장치·레이어 구성에 따라 달라지므로 개발자 도구의 성능 기록으로 측정해야 해요.</p>`}
 ],questions:[
 {q:'동기 A, Promise 반응 B, 0ms 타이머 C의 일반적인 출력 순서는?',options:['A → B → C','A → C → B','B → A → C'],answer:0,feedback:['맞아요. 현재 실행 뒤 마이크로태스크 B, 다음 타이머 태스크 C예요.','타이머는 현재 태스크 뒤 새 태스크로 처리돼요.','동기 A가 먼저 현재 스택에서 실행돼요.'],review:'b04'},
 {q:'레이아웃 단계가 주로 결정하는 것은?',options:['요소 상자의 크기와 위치','서버의 IP 주소','쿠키의 만료 시간'],answer:0,feedback:['맞아요. 화면의 기하 구조를 계산해요.','DNS·네트워크 영역이에요.','웹 상태 관리 영역이에요.'],review:'b02'},
 {q:'Web Worker를 사용할 때 맞는 설명은?',options:['계산 결과를 메시지로 메인 스레드에 전달한다','Worker가 DOM을 직접 수정한다','모든 작업이 자동으로 빨라진다'],answer:0,feedback:['맞아요. 메인 스레드와 메시지로 데이터를 주고받아요.','Worker에는 일반적인 DOM 직접 접근이 없어요.','복사·통신 비용과 작업 성격을 함께 봐야 해요.'],review:'b05'}
 ],summary:['HTML·CSS는 DOM·CSSOM으로 해석되고 스타일·레이아웃·페인트·합성을 거쳐 화면에 반영돼요.','현재 태스크 뒤 마이크로태스크를 처리하며 타이머는 이후 태스크가 돼요.','긴 메인 스레드 작업은 입력과 그리기를 늦추므로 분할·Worker와 실제 측정을 고려해요.'],nextQuestion:'브라우저가 만든 화면에서 로그인 정보·설정·받은 자원을 새로고침 뒤에도 어떻게 구별해 유지할까요?',sources:[['WHATWG HTML · Parsing','https://html.spec.whatwg.org/multipage/parsing.html'],['WHATWG HTML · Web application APIs','https://html.spec.whatwg.org/multipage/webappapis.html'],['W3C CSSOM','https://www.w3.org/TR/cssom-1/'],['WHATWG HTML · Web Workers','https://html.spec.whatwg.org/multipage/workers.html']]
};

CS.lessons['ch16-l02']={
 lead:'웹의 상태는 한곳에만 저장되지 않아요. 요청에 실리는 쿠키, 서버 세션, 브라우저 저장소, 받은 응답을 재사용하는 HTTP 캐시는 목적·범위·수명이 서로 달라요.',
 goals:['쿠키·서버 세션·토큰의 저장 위치와 전달 범위를 구별해요.','메모리·sessionStorage·localStorage·IndexedDB의 수명을 비교해요.','동일 출처 정책·CORS와 HTTP 캐시 검증 과정을 설명해요.'],prerequisites:['ch16-l01','ch06-l02','ch15-l01'],sections:[
 {id:'b01',title:'쿠키·서버 세션·토큰은 같은 로그인 상태를 서로 다른 방식으로 이어가요',html:`<p><strong>쿠키</strong>는 브라우저가 조건에 맞는 HTTP 요청에 보낼 수 있는 이름·값과 속성이에요. 서버 세션 방식은 쿠키 등에 짧은 세션 식별자를 두고 실제 상태를 서버에 보관할 수 있어요. 토큰은 권한 주장과 서명을 담을 수 있지만 저장·전달·취소·만료 전략이 별도로 필요해요. 셋을 같은 저장 위치나 같은 보안 수준으로 보면 안 돼요.</p><figure class="teaching-figure concept-figure"><div class="web-state-roles-visual" aria-label="브라우저 쿠키의 세션 ID로 서버 세션을 찾고 토큰은 요청 자격 증명으로 전달"><div><b>브라우저</b><span>Cookie: sid=K7</span><span>또는 Authorization 토큰</span></div><i>요청 →</i><div><b>서버</b><span>세션 K7 → 사용자 상태</span><span>토큰 서명·만료 검증</span></div></div><figcaption><strong>브라우저에 무엇을 두고 서버가 무엇을 확인하는지 나누어 그리면 역할이 보여요</strong><ul class="picture-key"><li><b>HttpOnly</b>쿠키를 JavaScript에서 읽지 못하게 제한해요.</li><li><b>Secure</b>보안 연결에서만 보내도록 제한해요.</li><li><b>권한</b>저장 위치만으로 접근 권한이 증명되지는 않아요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'메모리·sessionStorage·localStorage·IndexedDB는 수명과 자료 구조가 달라요',html:`<p>JavaScript 변수는 현재 문서 메모리에 있고 새로고침하면 다시 만들어져요. <code>sessionStorage</code>는 출처와 탭의 페이지 세션 단위, <code>localStorage</code>는 출처 단위의 문자열 키·값 저장소예요. IndexedDB는 객체 저장소·키·인덱스·트랜잭션을 제공해 더 구조화된 데이터를 비동기로 다룰 수 있어요. 브라우저 정책과 사용자가 데이터를 지우는 상황도 수명에 영향을 줘요.</p><figure class="teaching-figure concept-figure"><div class="storage-layers-visual" aria-label="문서 메모리 세션 저장소 로컬 저장소 IndexedDB의 수명과 형태 비교"><span><b>변수</b><strong>현재 문서</strong><small>자유로운 JS 값</small></span><span><b>sessionStorage</b><strong>탭 세션</strong><small>문자열 키·값</small></span><span><b>localStorage</b><strong>명시적 삭제 전</strong><small>문자열 키·값</small></span><span><b>IndexedDB</b><strong>명시적 삭제 전</strong><small>객체·키·인덱스</small></span></div><figcaption><strong>“얼마나 오래 남나”와 “어떤 자료를 다루나”를 함께 비교해요</strong><ul class="picture-key"><li><b>동기 API</b>Web Storage는 메인 스레드에서 동기식이에요.</li><li><b>구조화 자료</b>IndexedDB는 객체 저장소와 트랜잭션을 제공해요.</li><li><b>민감 정보</b>스크립트 접근 가능 저장소의 위험을 따로 평가해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'세 저장 위치에 값을 남기고 새로고침 뒤 상태를 비교해요',html:`<p>글자 크기20을 문서 메모리·sessionStorage·localStorage에 저장해 보세요. 새로고침 모형에서는 문서 메모리만 기본18로 돌아가고 두 저장소의 교안 전용 값은 다시 읽어요. 저장 접근이 거부된 경우에도 본문은 계속 사용할 수 있어야 해요.</p>`,lab:'storage-lifetime'},
 {id:'b04',title:'동일 출처 정책은 출처가 다른 자원의 읽기 접근을 제한하고 CORS가 예외를 협의해요',html:`<p>출처는 보통 <strong>scheme·host·port</strong>의 조합으로 비교해요. 브라우저는 다른 출처의 자원을 보내거나 화면에 포함하는 모든 행위를 한 방식으로 막는 것이 아니라, API를 통한 응답 읽기 같은 접근을 정책별로 제한해요. CORS는 서버가 허용 출처와 방법·헤더를 응답으로 알려 브라우저가 교차 출처 읽기를 허용할지 판단하는 HTTP 기반 절차예요.</p><figure class="teaching-figure concept-figure"><div class="cors-gate-visual" aria-label="app example에서 api example로 요청하고 서버의 CORS 허용 응답을 브라우저가 검사"><span>https://app.example</span><i>fetch 요청</i><div><b>브라우저 정책 문</b><small>scheme · host · port 비교</small></div><i>Origin / 허용 응답</i><span>https://api.example</span><strong>허용 시 JS가 응답 읽기</strong></div><figcaption><strong>CORS는 서버 요청 자체를 모두 막는 방화벽이 아니라 브라우저가 응답 노출을 판단하는 절차예요</strong><ul class="picture-key"><li><b>출처</b>경로가 아니라 scheme·host·port를 봐요.</li><li><b>서버 응답</b>허용 정보를 명시해야 해요.</li><li><b>자격 증명</b>와일드카드와 쿠키 사용 규칙을 따로 확인해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'HTTP 캐시는 신선하면 재사용하고 오래되면 조건부 요청으로 검증할 수 있어요',html:`<p>캐시는 응답의 <code>Cache-Control</code> 같은 지시와 현재 나이를 보고 바로 재사용할 수 있는지 판단해요. 오래된 응답이라도 <code>ETag</code>를 <code>If-None-Match</code>로 보내 검증하고, 내용이 같으면 서버가 <strong>304 Not Modified</strong>로 본문 없이 재사용을 허용할 수 있어요. 캐시가 있다고 요청이 항상 사라지는 것은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="cache-validate-visual" aria-label="캐시가 신선하면 바로 사용하고 오래되면 ETag 조건부 요청 뒤304로 본문 재사용"><div><b>캐시 확인</b><span>fresh → 즉시 재사용</span><span>stale → 검증 필요</span></div><i>IF-NONE-MATCH: v7 →</i><div><b>원본 서버</b><span>같음 → 304</span><span>변경 → 200 + 새 본문</span></div><strong>304면 저장 본문 재사용</strong></div><figcaption><strong>신선도와 검증은 다른 판단이며 304는 저장된 본문과 함께 사용해요</strong><ul class="picture-key"><li><b>fresh</b>허용 기간 안이라 네트워크 없이 쓸 수 있어요.</li><li><b>validator</b>ETag·Last-Modified로 변경 여부를 물어요.</li><li><b>no-store</b>저장을 금지하는 지시와 매번 검증을 구별해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'HTTP/1.1·HTTP/2·HTTP/3은 같은 HTTP 의미를 서로 다른 전송 구조에 실어요',html:`${table(['버전','메시지·다중화 구조','전송 기반과 손실 영향'],[['HTTP/1.1','텍스트 기반 메시지, 연결 하나에 다중화 계층 없음','주로 TCP, 병렬 처리에 여러 연결을 쓰기도 함'],['HTTP/2','이진 프레임과 여러 스트림 다중화','TCP 한 연결의 패킷 손실이 여러 스트림 진행을 함께 늦출 수 있음'],['HTTP/3','HTTP 의미를 QUIC 스트림에 매핑','QUIC/UDP 기반, 한 스트림 손실이 다른 스트림 전달을 같은 방식으로 막지 않음']])}<p>버전이 높다고 모든 상황에서 반드시 빠르지는 않아요. 연결 재사용, 왕복 지연, 손실, 서버·브라우저 지원, 자원 크기와 우선순위를 함께 측정해야 해요.</p>`}
 ],questions:[
 {q:'메모리 변수에만 저장한20px 값을 새로고침하면 일반적으로 어떻게 되나요?',options:['문서가 다시 만들어져 기본값으로 돌아간다','localStorage에 자동 복사된다','서버 세션으로 자동 이동한다'],answer:0,feedback:['맞아요. 새 문서의 변수는 다시 초기화돼요.','명시적으로 저장해야 해요.','서버와 통신하는 별도 처리가 필요해요.'],review:'b03'},
 {q:'오래된 캐시 응답의 ETag가 서버 값과 같을 때 가능한 결과는?',options:['304 뒤 저장 본문 재사용','항상 새 본문 전체 다운로드','DNS 캐시 삭제'],answer:0,feedback:['맞아요. 조건부 요청 결과로 저장된 본문을 재사용할 수 있어요.','변경되지 않았다면 본문 전송을 생략할 수 있어요.','DNS와 HTTP 응답 캐시는 다른 층이에요.'],review:'b05'},
 {q:'CORS에 대한 맞는 설명은?',options:['브라우저가 교차 출처 응답을 JS에 노출할지 판단하는 절차','서버를 모든 인터넷 요청에서 숨기는 방화벽','쿠키를 자동 암호화하는 기능'],answer:0,feedback:['맞아요. 서버의 허용 응답과 브라우저 검사가 함께 작동해요.','요청이 서버에 도달하는 것과 응답 읽기 허용을 구별해야 해요.','쿠키 보호 속성과 전송 암호화는 별도예요.'],review:'b04'}
 ],summary:['쿠키·서버 세션·토큰은 저장 위치·전달·검증 책임이 다르므로 한 단어로 묶지 않아요.','문서 메모리·Web Storage·IndexedDB는 수명·자료형·API 성격이 달라요.','동일 출처·CORS와 HTTP 캐시 검증을 구별하고 HTTP 버전의 전송 구조를 비교해요.'],nextQuestion:'브라우저에 저장되고 네트워크를 지나는 데이터를 기밀성·무결성·신뢰 관점에서 어떻게 보호할까요?',sources:[['WHATWG HTML · Web Storage','https://html.spec.whatwg.org/multipage/webstorage.html'],['W3C Indexed Database API','https://www.w3.org/TR/IndexedDB/'],['WHATWG Fetch · CORS protocol','https://fetch.spec.whatwg.org/#http-cors-protocol'],['RFC 9111 · HTTP Caching','https://www.rfc-editor.org/rfc/rfc9111.html'],['RFC 9114 · HTTP/3','https://www.rfc-editor.org/rfc/rfc9114.html']]
};
})();
