(()=>{
const {table}=CS.helpers;
CS.lessons['ch17-l01']={
 lead:'보안 기술은 모두 데이터를 알아보기 어렵게 만드는 한 가지 기능이 아니에요. 표현을 바꾸는 인코딩, 변경을 요약하는 해시, 비밀키로 보호하는 암호화, 작성자를 확인하는 서명은 서로 다른 질문에 답해요.',
 goals:['인코딩·암호학적 해시·암호화의 목적과 되돌림 가능성을 구별해요.','대칭키·공개키와 전자서명·인증서의 역할을 연결해요.','TLS의 보호 범위와 비밀번호 저장에 필요한 salt·비용 요소를 설명해요.'],prerequisites:['ch04-l01','ch06-l02','ch16-l02'],sections:[
 {id:'b01',title:'인코딩·해시·암호화는 입력과 결과 사이의 약속이 달라요',html:`<p><strong>인코딩</strong>은 데이터를 전달 가능한 표현으로 바꾸며 규칙을 알면 되돌릴 수 있어요. <strong>암호학적 해시</strong>는 임의 길이 입력을 고정 길이 요약으로 바꾸고 일반적으로 원문 복원을 제공하지 않아요. <strong>암호화</strong>는 키를 가진 대상만 복호화하도록 기밀성을 보호해요. Base64는 비밀키가 없으므로 암호화가 아니에요.</p><figure class="teaching-figure concept-figure"><div class="security-transform-visual" aria-label="hello가 Base64로 복원되고 SHA256 고정 길이 해시가 되며 키를 사용한 암호문은 키로 복호화"><div><b>Base64</b><span>hello</span><i>⇄</i><strong>aGVsbG8=</strong><small>표현 변환</small></div><div><b>SHA-256</b><span>hello</span><i>→</i><strong>2cf24d…9824</strong><small>고정 길이 요약</small></div><div><b>암호화</b><span>평문 + 키</span><i>⇄</i><strong>암호문</strong><small>기밀성</small></div></div><figcaption><strong>결과가 읽기 어렵다는 겉모습보다 누가 어떤 조건으로 되돌리거나 검증하는지 봐요</strong><ul class="picture-key"><li><b>Base64</b>전송 표현이며 누구나 복원할 수 있어요.</li><li><b>해시</b>같은 입력은 같은 요약을 만들어요.</li><li><b>암호화</b>키·알고리즘·nonce 같은 조건이 필요해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'공개 예문의 Base64 복원과 실제 SHA-256을 직접 비교해요',html:`<p>실제 비밀번호나 개인 정보 대신 공개 예문 <code>hello</code>를 사용하세요. Base64는 원문으로 복원되고 SHA-256은 64자리 16진수로 표시돼요. 느낌표 한 글자를 붙였을 때 길이는 같지만 값이 얼마나 달라지는지도 확인해요.</p>`,lab:'crypto-compare'},
 {id:'b03',title:'대칭키와 공개키 방식은 키를 나누고 사용하는 방법이 달라요',html:`<p>대칭키 암호는 같은 비밀키 계열로 암호화와 복호화를 수행해 대량 데이터 처리에 적합할 수 있지만 키를 안전하게 공유해야 해요. 공개키 방식은 공개키와 개인키의 쌍을 사용해 키 합의·암호화·서명 같은 목적에 쓰여요. 공개키로 암호화하면 누구나 개인키 없이 풀 수 있다는 뜻은 아니며, 알고리즘마다 허용 용도가 달라요.</p><figure class="teaching-figure concept-figure"><div class="key-models-visual" aria-label="대칭키는 공유 비밀키를 양쪽이 사용하고 공개키 방식은 공개키와 개인키 역할을 나눔"><div><b>대칭키</b><span>앨리스 🔑</span><i>암호문</i><span>🔑 밥</span><small>같은 공유 비밀</small></div><div><b>공개키 쌍</b><span>공개키 · 배포 가능</span><i>+</i><span>개인키 · 소유자 보관</span><small>용도별 알고리즘 규칙</small></div></div><figcaption><strong>TLS 같은 실제 프로토콜은 공개키 기술과 대칭키 암호를 조합해 사용해요</strong><ul class="picture-key"><li><b>대칭키</b>빠른 데이터 보호에 널리 사용해요.</li><li><b>공개키</b>키 합의·서명 등에서 역할을 나눠요.</li><li><b>키 관리</b>좋은 알고리즘도 키가 노출되면 보호가 깨져요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'전자서명은 개인키로 만든 증거를 공개키로 검증하고 인증서는 공개키의 주인을 연결해요',html:`<p>서명자는 개인키로 메시지에 대한 서명을 만들고 검증자는 공개키로 메시지가 바뀌지 않았는지와 해당 키의 서명인지 확인해요. 인증서는 도메인 같은 주체 정보와 공개키를 발급자의 서명으로 연결해요. 인증서가 유효해도 사이트의 모든 내용·운영자가 선의임을 보증하는 것은 아니에요.</p><figure class="teaching-figure concept-figure"><div class="signature-trust-visual" aria-label="메시지 해시와 개인키로 서명하고 공개키 인증서 체인으로 검증"><span>메시지</span><i>해시</i><div><b>개인키</b><strong>서명 생성</strong></div><i>→</i><div><b>공개키</b><strong>서명 검증</strong></div><i>연결</i><span class="certificate">인증서<br>도메인 ↔ 공개키</span></div><figcaption><strong>서명 검증과 인증서 신뢰 경로가 함께 있어야 “어떤 키의 서명인가”를 의미 있게 판단해요</strong><ul class="picture-key"><li><b>무결성</b>메시지 변경을 검출할 수 있어요.</li><li><b>진위</b>대응 개인키 보유자가 만든 서명인지 봐요.</li><li><b>신뢰 경로</b>발급자·이름·기간·폐기 등을 검증해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'TLS는 전송 중 기밀성·무결성과 상대 인증을 제공하지만 끝점 이후까지 대신 보호하지 않아요',html:`<p>TLS는 핸드셰이크에서 버전·암호 매개변수와 키를 합의하고 인증서를 검증한 뒤 레코드 데이터를 보호해요. 네트워크 관찰자가 평문을 읽거나 몰래 바꾸기 어렵게 하지만 브라우저나 서버 자체가 침해됐거나 사용자가 악성 사이트에 직접 정보를 입력한 상황까지 해결하지는 못해요.</p><figure class="teaching-figure concept-figure"><div class="tls-boundary-visual" aria-label="브라우저와 서버 사이 TLS 터널은 보호되지만 양 끝의 앱과 저장 데이터는 별도 보호가 필요"><div><b>브라우저 앱</b><span>평문 사용</span></div><i>🔒 TLS 전송 구간<br>기밀성 · 무결성 · 서버 인증</i><div><b>서버 앱</b><span>평문 처리·저장</span></div><strong>끝점 보안은 별도</strong></div><figcaption><strong>자물쇠 표시는 연결 보호와 인증서 검증을 뜻하며 사이트 내용 전체의 안전 판정은 아니에요</strong><ul class="picture-key"><li><b>전송 중</b>도청·변조를 방어해요.</li><li><b>끝점</b>악성 코드·권한·저장은 별도예요.</li><li><b>이름 검증</b>접속한 호스트와 인증서 이름을 비교해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'비밀번호는 빠른 일반 해시 한 번보다 salt와 비용이 있는 전용 방식으로 저장해요',html:`${table(['요소','역할','주의'],[['사용자별 salt','같은 비밀번호도 다른 검증값을 만들게 도움','비밀일 필요는 없지만 충돌을 피할 충분한 무작위 값'],['비밀번호 해싱 방식','각 추측에 시간·메모리 비용을 부과','Argon2id·scrypt·PBKDF2 등 정책과 환경에 맞게 선택'],['비용 요소','공격자의 대량 추측 비용을 높임','서비스 응답성과 하드웨어 변화에 맞춰 조정'],['버전 정보','알고리즘·비용 변경과 점진적 이전 지원','salt·검증값과 함께 기록'],['온라인 방어','속도 제한·MFA·유출 비밀번호 차단 등','저장 해싱만으로 로그인 공격을 모두 막지 못함']])}<p>실습의 SHA-256은 해시 성질을 관찰하기 위한 것이며 비밀번호 저장 예제가 아니에요. 실제 설계는 검증된 라이브러리와 최신 조직 정책을 사용하고 직접 암호 방식을 만들지 않아요.</p>`}
 ],questions:[
 {q:'Base64에 대한 맞는 설명은?',options:['규칙을 알면 원문을 복원할 수 있는 표현 변환','비밀키 없이는 절대 풀 수 없는 암호화','비밀번호 저장용 느린 해시'],answer:0,feedback:['맞아요. 전송과 표현을 위한 인코딩이에요.','Base64에는 비밀키가 없어요.','비밀번호 저장용 기능이 아니에요.'],review:'b01'},
 {q:'전자서명의 일반적인 검증에 사용하는 것은?',options:['서명자의 공개키','서명자의 개인키를 모두에게 배포','Base64 문자열'],answer:0,feedback:['맞아요. 대응 공개키로 서명을 검증해요.','개인키는 서명자가 보호해야 해요.','표현 변환만으로 서명 진위를 검증할 수 없어요.'],review:'b04'},
 {q:'비밀번호 검증값 저장에 일반 SHA-256 한 번이 부족한 주된 이유는?',options:['대량 추측을 너무 빠르게 시도할 수 있어서','SHA-256 결과가 매번 무작위 길이라서','Base64로 자동 복원되기 때문에'],answer:0,feedback:['맞아요. salt와 비용 요소가 있는 전용 방식을 사용해 추측 비용을 높여요.','SHA-256 결과 길이는 고정이에요.','해시와 Base64는 다른 변환이에요.'],review:'b06'}
 ],summary:['인코딩은 표현, 해시는 고정 길이 요약, 암호화는 키를 이용한 기밀성 보호예요.','대칭키·공개키·전자서명·인증서는 서로 다른 키 역할과 신뢰 연결을 가져요.','TLS의 전송 보호 범위를 구별하고 비밀번호는 salt·비용이 있는 전용 방식으로 검증해요.'],nextQuestion:'사용자의 신원을 확인한 뒤에도 왜 서버가 요청마다 대상과 행동의 권한을 다시 검사해야 할까요?',sources:[['W3C Web Cryptography API','https://www.w3.org/TR/WebCryptoAPI/'],['NIST FIPS 180-4 · Secure Hash Standard','https://csrc.nist.gov/pubs/fips/180-4/upd1/final'],['NIST SP 800-63B · Authenticators','https://pages.nist.gov/800-63-4/sp800-63b/authenticators/'],['RFC 8446 · TLS 1.3','https://www.rfc-editor.org/rfc/rfc8446.html']]
};

CS.lessons['ch17-l02']={
 lead:'로그인에 성공했다는 사실과 모든 자원에 접근할 권한은 달라요. 서버는 요청마다 사용자·대상·행동·상황을 확인하고, 신뢰할 수 없는 입력이 코드나 명령으로 해석되지 않게 경계를 지켜야 해요.',
 goals:['인증과 인가를 구별하고 요청마다 권한을 검사해요.','세션 생성·갱신·만료·로그아웃과 탈취 방어를 연결해요.','XSS·SQL Injection·CSRF의 발생 경로와 핵심 방어를 비교해요.'],prerequisites:['ch17-l01','ch16-l02','ch12-l02'],sections:[
 {id:'b01',title:'인증은 누구인지 확인하고 인가는 그 사용자가 이 행동을 할 수 있는지 판단해요',html:`<p><strong>인증</strong>은 비밀번호·패스키·인증 장치 등으로 계정의 주체임을 확인하는 과정이에요. <strong>인가</strong>는 인증된 주체가 특정 자원에 읽기·수정 같은 행동을 해도 되는지 정책으로 판단해요. 로그인 화면에서 관리자 버튼을 숨겨도 직접 API 요청을 만들 수 있으므로 서버 검사를 대신할 수 없어요.</p><figure class="teaching-figure concept-figure"><div class="authn-authz-visual" aria-label="자격 증명으로 인증한 뒤 사용자 대상 행동을 인가 정책으로 판단"><span>자격 증명</span><i>→</i><div><b>인증 AuthN</b><strong>S1 확인</strong></div><i>→</i><div><b>인가 AuthZ</b><strong>S1 · A1 · 읽기?</strong></div><i>→</i><span class="decision">허용 또는 거부</span></div><figcaption><strong>“로그인했는가?”와 “이 자료에 이 행동을 해도 되는가?”는 별도 질문이에요</strong><ul class="picture-key"><li><b>주체</b>누가 요청했는지 확인해요.</li><li><b>대상·행동</b>무엇을 어떻게 하려는지 검사해요.</li><li><b>서버</b>모든 진입 경로에서 같은 정책을 적용해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'세션은 로그인 뒤에도 수명·갱신·종료와 탈취 대응을 관리해야 해요',html:`<p>로그인 성공 뒤 서버는 새 세션 식별자를 발급하고 인증 수준이 바뀔 때 다시 갱신할 수 있어요. 유휴·절대 만료를 두고 로그아웃 시 서버 상태를 무효화해야 해요. 쿠키에는 Secure·HttpOnly·SameSite 같은 범위 제한을 적용할 수 있지만, 속성 하나가 모든 공격을 막아 주지는 않아요.</p><figure class="teaching-figure concept-figure"><div class="session-life-visual" aria-label="로그인 세션 ID 갱신 사용 만료 로그아웃 무효화의 수명 주기"><span>로그인</span><i>→</i><span class="rotate">새 세션 ID</span><i>→</i><span>요청마다 검증</span><i>→</i><span>유휴·절대 만료</span><i>→</i><span class="ended">로그아웃·무효화</span></div><figcaption><strong>브라우저에서 쿠키를 지우는 것과 서버가 세션을 더 이상 인정하지 않는 것을 함께 처리해요</strong><ul class="picture-key"><li><b>갱신</b>로그인·권한 변화 때 식별자 고정을 막아요.</li><li><b>만료</b>무기한 재사용 가능성을 줄여요.</li><li><b>기록</b>생성·갱신·종료·이상 사용을 관찰해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'학생·교사·로그아웃 사용자의 요청을 서버 권한표로 판단해요',html:`<p>S1의 과제 A1을 S1이 읽으면 허용, S2가 읽으면 거부돼요. C1 담당 교사 T1은 읽을 수 있지만 다른 수업 교사 T2나 로그아웃 사용자는 거부돼요. 화면의 버튼을 숨긴 경로를 우회해도 서버 판단은 같아야 해요.</p>`,lab:'access-control'},
 {id:'b04',title:'입력 검증과 출력 인코딩은 서로 다른 시점과 목적을 가져요',html:`<p>입력 검증은 길이·범위·형식·업무 규칙에 맞는지 가능한 한 허용 목록으로 확인해요. 출력 인코딩은 신뢰할 수 없는 문자열이 들어가는 <strong>HTML·속성·URL·JavaScript 등 문맥</strong>에 맞게 데이터로 표시되도록 바꿔요. HTML을 허용해야 한다면 단순 문자열 인코딩 대신 검증된 정화 정책이 필요할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="input-output-visual" aria-label="신뢰할 수 없는 img 문자열을 검증하고 HTML 문맥에서 인코딩해 문자 그대로 표시"><span>&lt;img src=x onerror=…&gt;</span><i>입력 검증<br>길이·형식·업무 규칙</i><i>저장</i><i>HTML 문맥 출력 인코딩</i><strong>&amp;lt;img…&amp;gt;<br><small>글자로 표시</small></strong></div><figcaption><strong>입력을 한 번 걸렀다는 이유로 모든 출력 문맥에서 안전해지는 것은 아니에요</strong><ul class="picture-key"><li><b>검증</b>받을 데이터의 모양과 의미를 제한해요.</li><li><b>인코딩</b>출력될 문맥의 제어 문자를 처리해요.</li><li><b>안전한 sink</b>HTML 텍스트에는 textContent 같은 API를 써요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'XSS·SQL Injection·CSRF는 신뢰 경계를 넘는 방식이 서로 달라요',html:`<p>XSS는 신뢰하지 않은 값이 브라우저 코드·HTML로 해석되는 문제이고, SQL Injection은 데이터가 SQL 명령 구조에 섞이는 문제예요. CSRF는 로그인 쿠키가 자동 전송되는 브라우저를 속여 사용자가 의도하지 않은 상태 변경 요청을 보내게 해요. 이름이 비슷해도 방어 지점이 다르며 여러 방어를 함께 적용해요.</p><figure class="teaching-figure concept-figure"><div class="web-threats-visual" aria-label="XSS SQL Injection CSRF의 입력 경로와 핵심 방어 비교"><div><b>XSS</b><span>데이터 → 브라우저 코드</span><strong>문맥별 출력 인코딩·정화</strong></div><div><b>SQL Injection</b><span>데이터 → SQL 구조</span><strong>매개변수화 쿼리</strong></div><div><b>CSRF</b><span>다른 사이트 → 쿠키 동반 요청</span><strong>CSRF token·출처 신호·SameSite</strong></div></div><figcaption><strong>문자열을 막는 목록 하나보다 코드와 데이터를 구조적으로 분리하고 요청 의도를 검증해요</strong><ul class="picture-key"><li><b>XSS</b>출력 문맥마다 올바른 처리가 달라요.</li><li><b>SQLi</b>문자열 연결 대신 매개변수를 바인딩해요.</li><li><b>CSRF</b>상태 변경 요청에 위조 방지 검사를 해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'최소 권한과 기본 거부는 실수 하나가 미치는 범위를 줄여요',html:`${table(['원칙','서버에서 할 일','예'],[['최소 권한','업무에 필요한 자원·행동만 허용','담당 교사는 담당 수업 과제 읽기만'],['기본 거부','명시적으로 허용하지 않은 요청을 거부','새 API에 규칙이 없으면403'],['매 요청 검사','UI·HTTP 방법과 무관하게 중앙 정책 적용','숨긴 버튼·직접 URL도 같은 검사'],['객체 수준 검사','ID만 바꿔 다른 사용자의 자원에 접근하지 못하게 함','A1 요청 때 소유자·수업 관계 확인'],['심층 방어','세션·입력·출력·DB·CSRF 방어를 조합','한 제어 실패가 전체 침해로 이어지지 않게 함']])}<p>오류 응답과 로그에도 개인 정보와 내부 정책을 과도하게 노출하지 않도록 설계해요. 권한표는 기능이 바뀔 때 테스트하고 실제 정책과 구현의 차이를 점검해야 해요.</p>`}
 ],questions:[
 {q:'S2가 로그인했지만 S1의 과제 A1을 읽으려 할 때 필요한 판단은?',options:['인증 뒤에도 A1에 대한 인가 검사','로그인했으므로 항상 허용','버튼이 숨겨졌는지만 검사'],answer:0,feedback:['맞아요. 대상과 행동에 대한 권한을 서버가 검사해요.','인증은 모든 자원 권한을 뜻하지 않아요.','UI는 서버 권한 검사를 대신하지 못해요.'],review:'b03'},
 {q:'SQL Injection의 핵심 방어로 가장 알맞은 것은?',options:['값을 SQL 구조와 분리해 매개변수로 바인딩','모든 작은따옴표만 삭제','Base64로 입력을 바꿈'],answer:0,feedback:['맞아요. 준비된 문장과 매개변수로 코드·데이터를 분리해요.','우회와 정상 데이터 손상 가능성이 있어요.','인코딩은 SQL 명령 분리를 보장하지 않아요.'],review:'b05'},
 {q:'CSRF 방어에 대한 맞는 설명은?',options:['상태 변경 요청에 CSRF token·출처 신호 등을 검증','HttpOnly 하나로 모든 CSRF를 차단','GET으로 모든 상태 변경을 수행'],answer:0,feedback:['맞아요. 세션 방식과 위협에 맞는 검사를 조합해요.','HttpOnly는 스크립트 읽기를 제한하지만 요청 위조를 혼자 해결하지 않아요.','안전 메서드로 상태를 바꾸지 않아야 해요.'],review:'b05'}
 ],summary:['인증은 주체 확인, 인가는 특정 대상·행동의 권한 판단이며 서버가 요청마다 검사해요.','세션 식별자는 생성·갱신·만료·로그아웃과 탈취 방어를 함께 관리해요.','XSS·SQL Injection·CSRF의 경로를 구별하고 문맥별 출력·매개변수·요청 의도 검사를 적용해요.'],nextQuestion:'안전하게 작성한 소스 코드는 어떤 분석·변환 단계를 거쳐 실제 실행 가능한 명령이 될까요?',sources:[['OWASP Authorization Cheat Sheet','https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html'],['OWASP Session Management Cheat Sheet','https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html'],['OWASP XSS Prevention Cheat Sheet','https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html'],['OWASP SQL Injection Prevention Cheat Sheet','https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'],['OWASP CSRF Prevention Cheat Sheet','https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html']]
};
})();
