(()=>{
const {table}=CS.helpers;
CS.lessons['ch18-l01']={
 lead:'소스 코드는 곧바로 CPU 명령이 되지 않아요. 언어 처리기는 글자를 토큰으로 나누고, 문법 구조와 의미를 확인한 뒤 실행할 수 있는 형태로 바꿔요.',
 goals:['어휘 분석과 구문 분석이 만드는 토큰·AST를 구별해요.','이름 해석·스코프·타입 검사가 찾는 오류를 설명해요.','컴파일·인터프리트·JIT가 함께 사용될 수 있음을 이해해요.'],prerequisites:['ch04-l02','ch07-l02','ch16-l01'],sections:[
 {id:'b01',title:'어휘 분석은 문자 흐름을 의미 있는 토큰으로 나눠요',html:`<p><code>total + 12</code>라는 글자에서 공백은 건너뛰고 이름·연산자·정수 토큰을 만들어요. 토큰에는 종류와 값뿐 아니라 오류 위치를 알려 줄 줄·열 정보도 붙을 수 있어요. 따옴표가 닫히지 않거나 허용되지 않은 문자가 나오면 이 단계에서 멈춰요.</p><figure class="teaching-figure concept-figure"><div class="lexer-visual" aria-label="문자 흐름 total 더하기 12가 이름 연산자 정수 토큰으로 나뉨"><span>t o t a l &nbsp; + &nbsp; 1 2</span><i>어휘 분석</i><div><b>NAME</b><strong>total</strong></div><div><b>PLUS</b><strong>+</strong></div><div><b>NUMBER</b><strong>12</strong></div></div><figcaption><strong>토큰은 문법 분석기가 다루기 쉬운 최소 단위예요</strong><ul class="picture-key"><li><b>종류</b>이름·숫자·연산자처럼 역할을 나타내요.</li><li><b>값</b>total이나 12 같은 실제 내용을 담아요.</li><li><b>위치</b>오류가 난 문자를 정확히 가리켜요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'구문 분석은 문법에 맞춰 AST를 만들고 우선순위를 구조로 기록해요',html:`<p>문법은 어떤 토큰 배열이 올바른 프로그램인지 정해요. 곱셈을 덧셈보다 먼저 처리하는 문법에서 <code>2+3*4</code>의 루트는 <code>+</code>이고 오른쪽 자식이 <code>*</code>예요. 괄호를 사용한 <code>(2+3)*4</code>는 루트가 <code>*</code>로 바뀌어요. AST는 괄호 같은 표면 문자를 덜어 내고 실행에 필요한 구조를 남겨요.</p><figure class="teaching-figure concept-figure"><div class="ast-precedence-visual" aria-label="2 더하기 3 곱하기 4와 괄호식의 서로 다른 AST"><div><b>2 + 3 × 4</b><strong>+</strong><span>2</span><em>×<small>3 · 4</small></em></div><i>구조가 다르면</i><div><b>(2 + 3) × 4</b><strong>×</strong><em>+<small>2 · 3</small></em><span>4</span></div></div><figcaption><strong>계산 순서는 문자열의 모양이 아니라 AST의 부모·자식 관계에 담겨요</strong><ul class="picture-key"><li><b>우선순위</b>곱셈 노드가 덧셈보다 아래에 놓여 먼저 계산돼요.</li><li><b>결합 규칙</b>같은 우선순위 연산을 묶는 방향을 정해요.</li><li><b>완전 소비</b>끝까지 해석하지 못한 토큰도 오류예요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'작은 산술 언어를 실제로 토큰화하고 AST로 계산해요',html:`<p>입력을 바꾼 뒤 세 단계를 따로 실행해 보세요. <code>2+</code>는 오른쪽 피연산자가 없고, <code>2+a</code>는 이 언어가 이름을 허용하지 않아 위치가 포함된 오류를 내요. 각 단계가 성공해야 다음 단계로 넘어가요.</p>`,lab:'expression-parser'},
 {id:'b04',title:'문법이 맞아도 이름·스코프·타입의 의미가 틀릴 수 있어요',html:`<p><code>x + 1</code>의 모양은 올바르지만 x가 선언되지 않았다면 이름 해석에서 실패해요. 선언된 이름은 현재 블록과 바깥 스코프에서 찾고, 가장 가까운 선언에 연결해요. 그 뒤 연산이 허용되는 타입인지 확인해요. 언어에 따라 이 검사를 실행 전에 하거나 실행 중에 할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="semantic-check-visual" aria-label="AST의 이름 x를 스코프에서 찾고 숫자 타입을 검사하는 과정"><div><b>AST</b><span>+<small>x · 1</small></span></div><i>이름 해석</i><div><b>스코프</b><span>x → 바깥 블록의 number</span></div><i>타입 검사</i><div class="semantic-ok"><b>+</b><span>number + number ✓</span></div></div><figcaption><strong>구문은 문장의 모양, 의미 분석은 이름과 연산의 타당성을 확인해요</strong><ul class="picture-key"><li><b>이름 해석</b>사용한 이름을 선언과 연결해요.</li><li><b>스코프</b>이름을 볼 수 있는 범위를 정해요.</li><li><b>타입</b>연산이 허용되는 값의 종류인지 확인해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'중간 표현은 분석과 기계 코드 사이의 공통 작업 공간이에요',html:`<p>프런트엔드는 소스 언어를 분석해 중간 표현(IR)으로 바꾸고, 최적화 단계는 의미를 유지하면서 불필요한 계산을 줄일 수 있어요. 백엔드는 대상 CPU의 명령과 레지스터 규칙에 맞게 코드를 생성해요. 실제 컴파일러는 이 단계를 더 세분하거나 여러 번 반복해요.</p><figure class="teaching-figure concept-figure"><div class="compiler-pipeline-visual" aria-label="소스 코드가 프런트엔드와 IR 최적화 백엔드를 거쳐 기계 코드가 됨"><span><b>소스</b>언어 문법</span><i>→</i><span><b>프런트엔드</b>토큰·AST·의미</span><i>→</i><span class="ir"><b>IR</b>공통 표현·최적화</span><i>→</i><span><b>백엔드</b>명령 선택</span><i>→</i><strong>기계 코드</strong></div><figcaption><strong>IR을 사이에 두면 여러 소스 언어와 여러 CPU 대상을 조합하기 쉬워져요</strong><ul class="picture-key"><li><b>프런트엔드</b>소스 언어의 규칙을 알아요.</li><li><b>최적화</b>관찰되는 의미를 유지해야 해요.</li><li><b>백엔드</b>대상 기계의 제약을 반영해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'컴파일·인터프리트·JIT는 배타적인 이름이 아니라 실행 전략의 구성 요소예요',html:`${table(['방식','언제 무엇을 하나요','장점과 비용'],[['미리 컴파일','실행 전에 대상 코드나 바이트코드 생성','시작 뒤 빠를 수 있지만 대상별 빌드가 필요할 수 있어요.'],['인터프리트','표현을 읽으며 동작을 수행','시작이 단순하고 관찰하기 쉽지만 반복 해석 비용이 있어요.'],['JIT','실행 중 자주 쓰는 부분을 관측해 기계 코드 생성','실제 실행 정보로 최적화하지만 컴파일 시간과 메모리를 써요.'],['혼합 실행','바이트코드를 해석하다 뜨거운 부분을 JIT','현대 런타임에서 여러 전략을 함께 쓸 수 있어요.']])}<p>언어 하나가 항상 한 방식만 사용되는 것은 아니에요. 같은 언어도 구현체와 실행 환경에 따라 준비·실행 전략이 달라져요.</p>`}
 ],questions:[
 {q:'2+3*4의 AST에서 루트 연산자는?',options:['+','*','숫자 3'],answer:0,feedback:['맞아요. 오른쪽의 곱셈 하위 트리가 먼저 계산돼요.','괄호가 없는 이 식에서는 곱셈이 더 아래에 있어요.','숫자는 잎 노드예요.'],review:'b02'},
 {q:'문법은 맞지만 선언되지 않은 x를 사용한 오류는 주로 어느 단계에서 찾나요?',options:['이름 해석','어휘 분석','기계 코드 실행이 끝난 뒤만'],answer:0,feedback:['맞아요. 사용한 이름을 보이는 선언과 연결해요.','문자 x 자체는 이름 토큰이 될 수 있어요.','언어에 따라 시점은 다르지만 이름 연결은 의미 분석의 핵심이에요.'],review:'b04'},
 {q:'JIT에 대한 올바른 설명은?',options:['실행 중 관측을 이용해 일부 코드를 컴파일할 수 있어요.','모든 소스를 사람이 직접 기계어로 바꿔요.','토큰을 만들지 못하게 하는 보안 기능이에요.'],answer:0,feedback:['맞아요. 자주 실행되는 부분을 최적화할 수 있어요.','컴파일러가 변환을 수행해요.','언어 실행 전략이지 입력 보안 기능이 아니에요.'],review:'b06'}
 ],summary:['문자를 토큰으로, 토큰을 AST로 바꾸며 문법 구조를 확인해요.','이름·스코프·타입을 검사한 뒤 IR과 대상 코드로 이어져요.','컴파일·인터프리트·JIT는 한 실행 환경 안에서 조합될 수 있어요.'],nextQuestion:'함수를 호출하고 객체를 만들 때 실행 중인 프로그램은 값을 어디에 두고 언제 회수할까요?',sources:[['LLVM · My First Language Frontend','https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/'],['LLVM · Parser and AST','https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/LangImpl02.html'],['ECMAScript · Execution Contexts','https://tc39.es/ecma262/'],['Cornell CS 6120 · Advanced Compilers','https://www.cs.cornell.edu/courses/cs6120/2025fa/']]
};

CS.lessons['ch18-l02']={
 lead:'프로그램을 실행하면 함수마다 지역 상태가 생기고 객체들은 참조로 연결돼요. 런타임은 호출을 관리하고, 더는 도달할 수 없는 객체를 찾아 메모리를 다시 쓸 수 있게 해요.',
 goals:['호출 스택과 프레임이 함수 실행 상태를 나누는 이유를 설명해요.','클로저와 객체 참조를 도달 가능성으로 연결해요.','GC 전략의 처리량·정지 시간·메모리 비용을 비교해요.'],prerequisites:['ch02-l01','ch10-l01','ch18-l01'],sections:[
 {id:'b01',title:'함수를 호출할 때마다 그 호출을 위한 프레임이 쌓여요',html:`<p>프레임에는 인수·지역 변수·계산 중간값·돌아갈 위치처럼 호출을 계속하기 위한 정보가 들어가요. 함수가 다른 함수를 호출하면 새 프레임이 위에 놓이고, 반환하면 위 프레임이 제거되어 호출 지점으로 돌아가요. 실제 배치는 언어·VM·ABI·최적화에 따라 달라요.</p><figure class="teaching-figure concept-figure"><div class="call-stack-visual" aria-label="main 위에 total 위에 add 호출 프레임이 쌓이고 add 반환 뒤 제거됨"><div><span><b>add(2, 3)</b>인수 2, 3 · 복귀 위치</span><span><b>total()</b>지역 변수 sum</span><span><b>main()</b>프로그램 시작</span></div><i>add 반환<br>맨 위 제거</i><div><span class="gone">빈 자리</span><span><b>total()</b>sum = 5</span><span><b>main()</b>계속 실행</span></div></div><figcaption><strong>호출 스택은 지금 중단된 호출과 돌아갈 순서를 보존해요</strong><ul class="picture-key"><li><b>프레임</b>호출 한 번의 실행 상태예요.</li><li><b>반환</b>맨 위 호출부터 끝나는 LIFO 구조예요.</li><li><b>규약</b>인수·결과·보존 레지스터 약속이 필요해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'재귀는 프레임을 반복해 쌓고 클로저는 끝난 호출의 환경을 계속 가리킬 수 있어요',html:`<p>재귀 함수는 자기 자신을 다시 호출할 때마다 별도 프레임을 만들며 종료 조건이 없으면 스택 한계를 넘을 수 있어요. 클로저는 함수와 그 함수가 만들어질 때의 어휘 환경을 함께 기억해요. 바깥 함수가 반환해도 내부 함수가 변수를 참조하면 해당 환경은 계속 살아 있어야 해요.</p><figure class="teaching-figure concept-figure"><div class="closure-visual" aria-label="재귀 프레임 세 개와 반환 뒤에도 count 환경을 가리키는 클로저"><div><b>재귀 호출</b><span>fact(1)</span><span>fact(2)</span><span>fact(3)</span><small>종료 조건 뒤 역순 반환</small></div><i>실행 상태의 수명</i><div><b>클로저</b><span>counter 함수 → 환경 { count: 2 }</span><small>만든 호출이 끝나도 참조가 있으면 유지</small></div></div><figcaption><strong>스택의 반환 순서와 값의 실제 수명은 항상 같지 않아요</strong><ul class="picture-key"><li><b>재귀</b>호출마다 매개변수와 복귀 지점이 달라요.</li><li><b>클로저</b>어휘 환경에 대한 참조를 보존해요.</li><li><b>수명</b>도달 가능한 환경은 반환 뒤에도 필요해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'루트에서 참조를 따라가 회수 후보를 표시해요',html:`<p>C와 D는 서로 가리키므로 참조 횟수가 0은 아니지만 루트 R에서 닿지 않아요. 도달 가능성 기반 수집기는 이런 순환도 회수 후보로 찾을 수 있어요. 연결을 끊거나 C를 새 루트로 추가해 결과가 어떻게 바뀌는지 확인하세요.</p>`,lab:'gc-reachability'},
 {id:'b04',title:'표시와 쓸기 방식은 루트에서 살아 있는 객체를 먼저 찾아요',html:`<p>런타임은 스택·전역 변수·런타임 내부 참조 같은 루트에서 시작해 객체 그래프를 따라가며 표시해요. 표시되지 않은 객체는 프로그램이 다시 접근할 경로가 없으므로 회수할 수 있어요. 실제 구현은 메모리를 압축하거나 빈 공간 목록을 관리하는 작업을 더할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="mark-sweep-visual" aria-label="루트에서 A와 B는 표시되고 고립된 C D 순환은 쓸기 대상"><span class="root">ROOT</span><i>→</i><span class="live">A ✓</span><i>→</i><span class="live">B ✓</span><div><span class="dead">C</span><i>↔</i><span class="dead">D</span><strong>표시 없음 → 회수 후보</strong></div></div><figcaption><strong>객체가 다른 객체를 가리키는지만 보지 않고 루트에서 도달할 수 있는지 확인해요</strong><ul class="picture-key"><li><b>표시</b>루트에서 참조를 따라 살아 있는 객체를 찾아요.</li><li><b>순환</b>루트와 끊겼다면 함께 회수할 수 있어요.</li><li><b>쓸기·압축</b>빈 공간을 되찾고 필요하면 배치를 정리해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'세대·증분·동시 수집은 실제 프로그램의 멈춤과 처리량을 조절해요',html:`<p>많은 세대별 수집기는 새 객체 영역을 자주 작게 수집하고 오래 살아남은 객체를 이전해요. 증분 표시는 큰 표시 작업을 작은 조각으로 나누고, 동시 표시는 애플리케이션 실행과 일부 작업을 겹쳐요. 이때 참조가 바뀌어도 올바르게 추적하도록 쓰기 장벽 같은 협력이 필요해요.</p><figure class="teaching-figure concept-figure"><div class="gc-tradeoff-visual" aria-label="새 객체 영역의 짧고 잦은 수집, 오래된 객체 영역의 큰 수집, 동시 표시가 앱과 겹침"><div><b>새 객체 영역</b><span>● ● ● ● ●</span><strong>짧고 자주</strong></div><i>생존 객체 이동</i><div><b>오래된 객체 영역</b><span>● ● ●</span><strong>더 넓은 추적</strong></div><div class="concurrent"><b>동시·증분 작업</b><span>앱 ▮▮▮▮▮</span><span>GC ▮ ▮ ▮</span></div></div><figcaption><strong>GC는 메모리 회수뿐 아니라 응답 지연·CPU 사용·여유 메모리의 균형을 다뤄요</strong><ul class="picture-key"><li><b>세대</b>객체 수명 경향을 이용해 검사 범위를 줄여요.</li><li><b>증분</b>긴 작업을 나누어 정지 시간을 관리해요.</li><li><b>동시</b>앱과 겹치지만 추가 CPU와 동기화 비용이 들어요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'GC가 있어도 필요 없는 참조를 붙잡으면 논리적 메모리 누수가 생겨요',html:`${table(['상황','왜 메모리가 남나요','설계·관찰 방법'],[['전역 배열에 계속 추가','루트에서 모든 항목에 계속 도달','필요한 항목 제거·상한 설정·크기 지표 관찰'],['해제하지 않은 이벤트 리스너','리스너가 요소와 주변 환경을 참조','수명 종료 때 등록 해제·약한 참조는 용도 검토'],['무제한 캐시','다시 쓸 가능성 때문에 모두 보존','LRU·TTL·용량 제한과 적중률 측정'],['긴 정지 시간','큰 그래프·할당 압력·단편화 등','프로파일·GC 로그·지연 분포로 원인 확인']])}<p>GC는 “더는 도달할 수 없는” 메모리를 찾을 뿐, 프로그램이 계속 참조하는 값이 정말 필요한지는 알 수 없어요. 평균 메모리만 보지 말고 시간에 따른 증가와 사용자 지연을 함께 관찰해요.</p>`}
 ],questions:[
 {q:'함수가 다른 함수를 호출할 때 일반적으로 새로 생기는 것은?',options:['호출 한 번의 프레임','모든 객체의 즉시 삭제','소스 코드의 토큰 재작성'],answer:0,feedback:['맞아요. 인수·지역 상태·복귀 정보를 담아요.','도달 가능한 객체는 계속 필요할 수 있어요.','호출은 이미 준비된 코드를 실행하는 과정이에요.'],review:'b01'},
 {q:'C↔D가 서로 참조하지만 루트에서 닿지 않을 때 도달 가능성 기반 GC의 판단은?',options:['둘 다 회수 후보','서로 참조하므로 영원히 살아 있음','D만 무조건 보존'],answer:0,feedback:['맞아요. 루트 경로가 없으므로 순환 전체가 후보예요.','서로의 참조만으로 루트 도달 가능해지지 않아요.','두 객체를 다 같은 기준으로 추적해요.'],review:'b04'},
 {q:'GC가 있어도 무제한 캐시가 누수가 될 수 있는 이유는?',options:['캐시가 계속 객체를 참조해 도달 가능하게 만들기 때문에','GC가 순환 참조를 절대 처리하지 못해서','함수 프레임이 한 번도 제거되지 않아서'],answer:0,feedback:['맞아요. 필요 없어도 루트 경로가 남으면 회수할 수 없어요.','도달 가능성 방식은 고립된 순환을 찾을 수 있어요.','반환한 일반 호출의 프레임은 제거돼요.'],review:'b06'}
 ],summary:['함수 호출마다 프레임이 생기고 반환 순서와 실행 상태를 관리해요.','클로저와 객체의 수명은 루트에서 이어지는 참조 경로로 설명할 수 있어요.','GC 전략은 회수 정확성뿐 아니라 정지 시간·처리량·메모리 비용을 함께 조절해요.'],nextQuestion:'CPU가 여러 명령을 겹쳐 처리할 때 앞 명령의 결과가 아직 없다면 어떤 일이 생길까요?',sources:[['ECMAScript · Execution Contexts and Environment Records','https://tc39.es/ecma262/'],['Java Virtual Machine Specification · Runtime Data Areas','https://docs.oracle.com/javase/specs/jvms/se20/html/jvms-2.html'],['V8 · Trash talk: the Orinoco garbage collector','https://v8.dev/blog/trash-talk'],['V8 · Concurrent marking','https://v8.dev/blog/concurrent-marking']]
};
})();
