(()=>{
const {table}=CS.helpers;
CS.lessons['ch19-l01']={
 lead:'명령어 집합은 프로그램과 CPU가 공유하는 약속이고, 마이크로아키텍처는 그 약속을 실제 회로로 구현하는 방법이에요. 현대 CPU는 여러 명령의 단계를 겹치지만 의존성과 분기 때문에 언제나 한 사이클에 하나씩 끝나지는 않아요.',
 goals:['ISA와 마이크로아키텍처를 구별하고 명령 실행 단계를 설명해요.','데이터·구조·제어 위험이 파이프라인을 멈추는 이유를 찾아요.','지연 시간·처리량·IPC를 구별하고 분기 예측의 비용을 설명해요.'],prerequisites:['ch01-l01','ch05-l02','ch18-l01'],sections:[
 {id:'b01',title:'ISA는 보이는 약속이고 마이크로아키텍처는 그 약속을 구현하는 내부 구조예요',html:`<p>명령어 집합 구조(ISA)는 명령의 종류와 인코딩, 레지스터, 메모리 접근, 예외처럼 소프트웨어가 기대할 수 있는 규칙을 정의해요. 같은 ISA를 실행하는 CPU도 파이프라인 길이·캐시·실행 장치·예측기 같은 내부 구현은 다를 수 있어요. 따라서 같은 프로그램을 실행해도 성능과 전력 특성은 달라질 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="isa-layers-visual" aria-label="프로그램이 ISA 약속을 통해 서로 다른 CPU 구현에서 실행됨"><div><b>프로그램</b><span>ADD · LOAD · BRANCH</span></div><i>ISA 약속</i><div class="cpu-impl"><span><b>CPU A</b>짧은 파이프라인</span><span><b>CPU B</b>비순차·넓은 실행</span></div><strong>같은 결과<br>다른 구현 비용</strong></div><figcaption><strong>ISA 호환성은 내부 회로가 같다는 뜻이 아니에요</strong><ul class="picture-key"><li><b>ISA</b>소프트웨어가 볼 수 있는 동작을 정의해요.</li><li><b>구현</b>명령을 얼마나 겹치고 빠르게 처리할지 정해요.</li><li><b>성능</b>클럭뿐 아니라 작업·메모리·구현에 따라 달라져요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'파이프라인은 한 명령의 시간을 없애기보다 여러 명령의 단계를 겹쳐 처리량을 높여요',html:`<p>교육용 5단계 모형은 명령 가져오기(IF), 해독과 레지스터 읽기(ID), 연산(EX), 메모리 접근(MEM), 결과 기록(WB)으로 나눠요. 한 명령은 여전히 여러 단계를 지나지만 파이프라인이 찬 뒤에는 서로 다른 명령이 각 단계에 있을 수 있어요. 세탁기를 여러 대 이어 놓은 것처럼 첫 결과까지의 시간과 계속 나오는 결과의 간격은 다른 지표예요.</p><figure class="teaching-figure concept-figure"><div class="pipeline-stages-visual" aria-label="세 명령이 IF ID EX MEM WB 단계를 한 사이클씩 어긋나 겹쳐 실행됨"><span><b>I1</b><i>IF</i><i>ID</i><i>EX</i><i>MEM</i><i>WB</i></span><span><b>I2</b><em></em><i>IF</i><i>ID</i><i>EX</i><i>MEM</i><i>WB</i></span><span><b>I3</b><em></em><em></em><i>IF</i><i>ID</i><i>EX</i><i>MEM</i><i>WB</i></span></div><figcaption><strong>5단계 모형에서 독립 명령 3개는 15사이클이 아니라 채우고 비우는 7사이클에 끝날 수 있어요</strong><ul class="picture-key"><li><b>지연 시간</b>명령 하나가 시작해 끝날 때까지예요.</li><li><b>처리량</b>단위 시간에 끝내는 명령 수예요.</li><li><b>겹침</b>각 단계가 다른 명령을 동시에 맡아요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'다음 단계에 필요한 값이나 자원이 준비되지 않으면 위험이 생겨요',html:`<p><strong>데이터 위험</strong>은 앞 명령의 결과를 뒤 명령이 아직 받지 못한 경우예요. 전달(forwarding)은 결과를 레지스터 기록 전 다음 연산으로 바로 보내 일부 멈춤을 줄여요. <strong>구조 위험</strong>은 같은 하드웨어 자원을 동시에 원할 때, <strong>제어 위험</strong>은 분기할 다음 주소가 확정되지 않았을 때 생겨요.</p><figure class="teaching-figure concept-figure"><div class="hazards-visual" aria-label="데이터 구조 제어 위험과 각각의 대응"><div><b>데이터 위험</b><span>ADD R1 → SUB가 R1 사용</span><strong>전달 · 멈춤</strong></div><div><b>구조 위험</b><span>두 단계가 메모리 포트 요청</span><strong>자원 분리 · 대기</strong></div><div><b>제어 위험</b><span>분기 다음 주소가 미확정</span><strong>예측 · 잘못된 경로 폐기</strong></div></div><figcaption><strong>멈춤은 오류가 아니라 올바른 결과를 지키기 위한 빈 사이클이에요</strong><ul class="picture-key"><li><b>RAW</b>앞에서 쓸 값을 뒤에서 읽으려 해요.</li><li><b>LOAD-use</b>메모리 결과가 늦어 전달이 있어도 멈출 수 있어요.</li><li><b>제어</b>분기 결과 전 가져온 명령이 틀릴 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'전달 유무와 LOAD·분기 조건에 따라 파이프라인 시간표를 비교해요',html:`<p>서로 독립인 명령은 빈칸 없이 흐르고, ALU 결과 의존은 전달 회로가 없으면 기다려요. 전달이 있어도 LOAD의 값은 메모리 단계 뒤에 준비되므로 바로 다음 명령이 한 번 멈추는 단순 모형을 확인해 보세요.</p>`,lab:'pipeline-hazards'},
 {id:'b05',title:'분기 예측은 결과가 확정되기 전에 예상 경로의 명령을 준비해요',html:`<p>예측이 맞으면 파이프라인을 계속 채울 수 있어요. 틀리면 잘못 가져오거나 실행한 명령을 폐기하고 올바른 주소에서 다시 시작해요. 비순차 CPU는 내부 실행 순서를 바꾸더라도 명령이 확정(retire)될 때 프로그램이 허용한 결과처럼 보이도록 관리해요. 추측 실행의 세부 보안 문제는 별도의 위협 모델이 필요해요.</p><figure class="teaching-figure concept-figure"><div class="branch-retire-visual" aria-label="분기를 예측해 A 경로를 실행하다 오예측이면 폐기하고 B 경로를 확정"><span><b>분기</b>조건 계산 중</span><i>예측 A</i><div><span class="wrong">A1 · A2<br>폐기</span><span class="right">B1 · B2<br>실행</span></div><i>순서대로 확정</i><strong>RETIRE<br>올바른 결과</strong></div><figcaption><strong>실행을 시작한 명령 수와 프로그램 결과로 확정된 명령 수는 다를 수 있어요</strong><ul class="picture-key"><li><b>예측 성공</b>대기 시간을 숨겨 처리량을 지켜요.</li><li><b>오예측</b>잘못된 경로를 비우는 비용이 생겨요.</li><li><b>확정</b>예외와 프로그램 순서를 맞춰 결과를 공개해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'CPU 성능은 클럭 하나보다 작업량과 여러 지표를 함께 봐요',html:`${table(['지표','무엇을 재나요','해석할 때 주의'],[['클럭 주파수','초당 사이클 수','한 사이클의 작업량과 메모리 대기를 함께 봐야 해요.'],['CPI','명령 하나당 평균 사이클','명령 종류·캐시 미스·분기·의존성에 따라 변해요.'],['IPC','사이클당 완료 또는 확정 명령 수','측정 정의와 CPU 폭, 작업 특성을 확인해요.'],['지연 시간','한 작업의 시작부터 완료까지','사용자 응답성과 직접 연결될 수 있어요.'],['처리량','일정 시간에 끝낸 작업 수','개별 작업이 더 빨리 끝난다는 뜻은 아니에요.']])}<p>대표적인 단순 관계는 <code>CPU 시간 = 명령 수 × CPI × 사이클 시간</code>이에요. 실제 측정에서는 운영체제·메모리·입출력과 측정 구간도 함께 통제해야 해요.</p>`}
 ],questions:[
 {q:'같은 ISA를 구현한 두 CPU에 대해 맞는 설명은?',options:['프로그램 결과 약속은 같아도 내부 파이프라인은 다를 수 있어요.','캐시 크기와 소비 전력이 반드시 같아요.','모든 명령의 실행 시간도 반드시 같아요.'],answer:0,feedback:['맞아요. ISA는 보이는 동작, 마이크로아키텍처는 구현 방식이에요.','캐시는 구현 선택이에요.','호환성과 성능 동일성은 달라요.'],review:'b01'},
 {q:'앞 ADD가 쓸 R1을 바로 뒤 SUB가 읽는 상황은?',options:['데이터 위험','구조 위험만','입출력 인터럽트'],answer:0,feedback:['맞아요. RAW 데이터 의존이에요.','공유 하드웨어보다 값의 준비 시점 문제예요.','명령 사이의 레지스터 의존 문제예요.'],review:'b03'},
 {q:'파이프라인의 주된 목적을 가장 잘 설명한 것은?',options:['여러 명령 단계를 겹쳐 처리량을 높여요.','명령 하나의 모든 단계를 없애요.','분기 결과를 언제나 정확히 알아요.'],answer:0,feedback:['맞아요. 겹침으로 단위 시간당 완료 수를 높여요.','명령은 필요한 단계를 지나야 해요.','예측은 틀릴 수 있어요.'],review:'b02'}
 ],summary:['ISA의 보이는 약속과 CPU 내부 구현을 구별해요.','파이프라인은 단계를 겹치고 위험에서는 전달·멈춤·예측으로 정확성을 지켜요.','클럭·CPI·IPC·지연·처리량을 작업 특성과 함께 해석해요.'],nextQuestion:'코어를 두 배로 늘리면 프로그램도 언제나 두 배 빨라질까요?',sources:[['RISC-V Unprivileged ISA Specification','https://docs.riscv.org/reference/isa/unpriv/unpriv-index.html'],['Intel 64 and IA-32 Optimization Reference','https://www.intel.com/content/www/us/en/developer/articles/technical/intel64-and-ia32-architectures-optimization.html'],['Intel VTune · Instructions Retired Event','https://www.intel.com/content/www/us/en/docs/vtune-profiler/user-guide/2024-0/instructions-retired-event.html']]
};

CS.lessons['ch19-l02']={
 lead:'코어가 여러 개여도 작업의 일부는 순서대로 해야 하고, 코어들은 메모리와 캐시를 함께 사용해요. 병렬 성능은 코어 수보다 나눌 수 있는 일의 비율·데이터 배치·통신 비용에 크게 좌우돼요.',
 goals:['캐시 일관성과 메모리 순서가 서로 다른 약속임을 설명해요.','false sharing과 SIMD·GPU 분기 발산의 성능 영향을 찾아요.','암달의 법칙으로 고정 작업의 이상적 속도 향상 상한을 계산해요.'],prerequisites:['ch11-l01','ch15-l02','ch19-l01'],sections:[
 {id:'b01',title:'멀티코어의 캐시는 같은 주소의 값을 일관되게 보이도록 협력해야 해요',html:`<p>각 코어가 자기 캐시에 같은 메모리 블록의 복사본을 둘 수 있어요. 한 코어가 쓰면 일관성 프로토콜은 다른 복사본을 무효화하거나 갱신해 한 주소의 쓰기 순서를 관리해요. 하지만 캐시 일관성만으로 서로 다른 주소의 모든 접근 순서가 프로그래머가 쓴 순서와 같아지는 것은 아니므로 언어의 원자 연산과 동기화 규칙이 필요해요.</p><figure class="teaching-figure concept-figure"><div class="coherence-visual" aria-label="코어 두 개의 L1 캐시가 공유 메모리의 같은 캐시 라인에 대해 무효화 메시지를 교환"><div><b>Core 0</b><span>L1 · X=1</span><strong>WRITE X=2</strong></div><i>무효화</i><div><b>Core 1</b><span class="invalid">L1 · X=1 ✕</span><strong>다음 읽기 재요청</strong></div><em>공유 메모리 · X=2</em></div><figcaption><strong>일관성은 같은 위치의 값, 메모리 모델은 여러 접근의 관찰 가능한 순서를 다뤄요</strong><ul class="picture-key"><li><b>캐시 라인</b>주소 하나보다 큰 블록 단위로 이동해요.</li><li><b>일관성</b>같은 위치의 쓰기를 코어 사이에서 조정해요.</li><li><b>동기화</b>필요한 순서를 프로그램이 명시해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'서로 다른 변수도 같은 캐시 라인에 있으면 false sharing이 생길 수 있어요',html:`<p>Core 0은 변수 a만, Core 1은 b만 바꿔도 두 변수가 같은 캐시 라인에 있으면 라인 전체의 소유권이 오가요. 데이터 경쟁 없이 결과가 정확해도 일관성 트래픽 때문에 느려질 수 있어요. 자주 쓰는 스레드별 값을 라인 경계에 맞춰 분리하면 개선될 수 있지만 패딩으로 메모리가 늘고 실제 라인 크기와 접근 패턴을 측정해야 해요.</p><figure class="teaching-figure concept-figure"><div class="false-sharing-visual" aria-label="서로 다른 변수 a b가 한 캐시 라인에 있어 코어 쓰기마다 라인이 왕복"><div><b>같은 라인</b><span>Core0: a++</span><span>Core1: b++</span><i>라인 ↔ 라인</i><strong>결과는 맞아도 느림</strong></div><div><b>분리한 라인</b><span>Line A · a++</span><span>Line B · b++</span><i>독립 갱신</i><strong>패딩 비용 확인</strong></div></div><figcaption><strong>false sharing은 같은 변수를 동시에 쓰는 데이터 경쟁과 다른 성능 문제예요</strong><ul class="picture-key"><li><b>공유 단위</b>캐시는 라인 단위로 소유권을 관리해요.</li><li><b>증상</b>코어를 늘렸는데 처리량이 줄 수 있어요.</li><li><b>확인</b>프로파일과 배치 변경 전후를 측정해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'SIMD와 GPU는 같은 연산을 많은 데이터에 적용할 때 강해요',html:`<p>SIMD 명령은 한 명령으로 여러 데이터 원소를 계산해요. GPU는 많은 스레드를 그룹으로 실행해 대규모 데이터 병렬성을 제공해요. 같은 그룹의 스레드가 조건문에서 서로 다른 경로를 선택하면 경로를 나눠 실행해 효율이 떨어질 수 있어요. 작업 이동과 메모리 전송 비용도 포함해 판단해야 해요.</p><figure class="teaching-figure concept-figure"><div class="simd-gpu-visual" aria-label="하나의 더하기 명령이 여러 데이터에 적용되고 GPU 워프의 분기 발산은 경로를 나눠 실행"><div><b>SIMD</b><span>[1,2,3,4]</span><i>+ [10,10,10,10]</i><strong>[11,12,13,14]</strong></div><div><b>GPU 그룹</b><span class="same">✓ ✓ ✓ ✓ · 같은 경로</span><span class="split">A A · B B · 분기 발산</span><strong>경로별로 나눠 실행</strong></div></div><figcaption><strong>병렬 장치는 계산 모양이 규칙적이고 데이터가 충분할 때 효율을 내기 쉬워요</strong><ul class="picture-key"><li><b>SIMD</b>한 명령이 여러 원소를 처리해요.</li><li><b>GPU</b>많은 스레드로 지연을 숨기고 처리량을 높여요.</li><li><b>발산</b>그룹 안의 서로 다른 분기는 효율을 낮출 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'암달의 법칙으로 코어를 늘렸을 때의 이상적 상한을 계산해요',html:`<p>전체의 병렬화 가능 비율을 <code>p</code>, 코어 수를 <code>N</code>이라 하면 고정 크기 작업의 이상적 실행 시간은 <code>(1-p)+p/N</code>, 속도 향상은 그 역수예요. 90%를 8코어로 나눠도 약 4.71배이며 코어가 매우 많아져도 남은 10% 때문에 10배에 가까워질 뿐이에요.</p>`,lab:'amdahl-speedup'},
 {id:'b05',title:'코어가 늘수록 남은 직렬 구간이 전체 시간을 지배해요',html:`<p>병렬화 비율이 50%면 무한히 많은 코어를 가정해도 최대 2배예요. 90%면 최대 10배, 99%면 최대 100배지만 실제로는 통신과 동기화 비용 때문에 더 낮아요. 반대로 문제 크기를 코어와 함께 늘리는 상황은 고정 크기 암달 모형과 다른 확장 관점이 필요해요.</p><figure class="teaching-figure concept-figure"><div class="scaling-curves-visual" aria-label="코어 증가에 따라 병렬화 비율 50 90 99퍼센트의 속도 향상 곡선이 각각 상한에 가까워짐"><div class="axis"><i>속도 향상 ↑</i><span style="--h:22%">50%<b>최대 2×</b></span><span style="--h:58%">90%<b>최대 10×</b></span><span style="--h:92%">99%<b>최대 100×</b></span><em>코어 수 →</em></div><strong>증가 폭은 점점 작아짐</strong></div><figcaption><strong>“코어를 더 사면 얼마나 빨라지는가”보다 직렬 구간과 추가 비용을 먼저 찾아요</strong><ul class="picture-key"><li><b>상한</b>직렬 비율이 1%면 이상적 최대 100배예요.</li><li><b>한계 효용</b>코어 하나를 더할 때 얻는 개선이 작아져요.</li><li><b>측정</b>고정 크기와 증가한 문제 크기를 구별해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'병렬화 방법은 작업의 독립성·데이터 이동·정확성 요구로 선택해요',html:`${table(['방법','잘 맞는 작업','주요 비용·위험'],[['멀티코어 스레드','독립 작업과 공유 메모리 협력','잠금·메모리 순서·캐시 일관성·false sharing'],['SIMD','같은 연산을 연속 데이터에 반복','정렬·꼬리 원소·불규칙 분기'],['GPU','매우 많은 데이터 원소의 높은 처리량','호스트 전송·분기 발산·메모리 접근 패턴'],['작업 분할','요청·파일·구간을 독립 처리','부하 불균형·결과 병합·오류 처리']])}<p>먼저 정확한 직렬 기준 구현을 만들고, 실제 프로파일에서 큰 구간을 찾아 병렬화해요. 빨라진 구간만 보지 말고 전체 실행 시간과 결과 일치, 자원 사용을 함께 검증해요.</p>`}
 ],questions:[
 {q:'Core 0은 a만, Core 1은 b만 쓰지만 둘이 같은 캐시 라인에 있을 때 생길 수 있는 문제는?',options:['false sharing으로 인한 일관성 트래픽','반드시 데이터 값이 틀리는 경쟁 상태','ISA가 서로 달라지는 현상'],answer:0,feedback:['맞아요. 서로 다른 변수여도 라인 소유권이 오갈 수 있어요.','결과는 정확하면서 성능만 나빠질 수 있어요.','ISA와는 관계없는 데이터 배치 문제예요.'],review:'b02'},
 {q:'전체의 50%만 병렬화할 수 있을 때 코어가 무한히 많아지는 이상적 속도 향상 상한은?',options:['2배','50배','무한대'],answer:0,feedback:['맞아요. 남은 직렬 50% 때문에 1/0.5=2배예요.','병렬 비율의 숫자가 곧 배수는 아니에요.','직렬 구간이 남아 상한이 생겨요.'],review:'b05'},
 {q:'GPU의 같은 실행 그룹에서 데이터에 따라 서로 다른 분기를 선택하면?',options:['경로를 나눠 실행해 효율이 낮아질 수 있어요.','항상 두 경로가 완전히 동시에 무료로 실행돼요.','캐시 일관성이 자동으로 사라져요.'],answer:0,feedback:['맞아요. 분기 발산은 그룹의 실행 효율을 낮출 수 있어요.','비활성 스레드를 두고 경로별 실행이 필요할 수 있어요.','분기 발산과 캐시 일관성은 다른 문제예요.'],review:'b03'}
 ],summary:['캐시 일관성과 메모리 순서를 구별하고 공유 데이터에는 동기화 규칙을 적용해요.','false sharing·SIMD·GPU 분기 발산을 데이터 배치와 작업 모양으로 설명해요.','암달의 법칙은 병렬화되지 않는 구간이 전체 속도 향상을 제한함을 보여줘요.'],nextQuestion:'컴퓨터 여러 대가 메시지를 잃거나 늦게 받는 상황에서 같은 데이터를 어떻게 유지할까요?',sources:[['RISC-V · RVWMO Memory Consistency Model','https://docs.riscv.org/reference/isa/unpriv/rvwmo.html'],['OpenMP API Specifications','https://www.openmp.org/specifications/'],['NVIDIA CUDA Programming Guide','https://docs.nvidia.com/cuda/cuda-programming-guide/'],['Gene Amdahl · 1967 paper','https://doi.org/10.1145/1465482.1465560']]
};
})();
