(()=>{
const {table}=CS.helpers;
CS.lessons['ch20-l01']={
 lead:'여러 서버에 같은 데이터를 복제하면 한 대가 멈춰도 서비스를 계속할 수 있지만, 메시지가 늦거나 끊기면 복제본마다 다른 값을 잠시 볼 수 있어요. 분산 시스템은 실패가 전체가 아닌 일부에서만 나타나는 상황을 다뤄야 해요.',
 goals:['부분 장애와 불확실한 응답이 생기는 이유를 설명해요.','동기·비동기 복제의 응답 시간과 데이터 위험을 비교해요.','선형화 가능성·최종 일관성·네트워크 분할의 관계를 구별해요.'],prerequisites:['ch14-l01','ch15-l02','ch19-l02'],sections:[
 {id:'b01',title:'분산 시스템에서는 일부 서버와 메시지만 실패할 수 있어요',html:`<p>한 프로세스 안에서는 함수 호출이 끝났는지 비교적 직접 알 수 있지만, 네트워크 요청은 서버가 처리한 뒤 응답만 사라질 수도 있어요. 느린 응답이 장애인지 지연인지 즉시 구별할 수 없고, 서로 다른 서버가 서로 다른 정보를 가진 시간이 생겨요. 이를 <strong>부분 장애</strong>와 <strong>불확실성</strong>으로 생각해요.</p><figure class="teaching-figure concept-figure"><div class="partial-failure-visual" aria-label="클라이언트 요청을 서버 A가 처리했지만 응답 메시지만 유실되어 성공 여부가 불확실"><span><b>클라이언트</b>쓰기 요청</span><i>→</i><div><b>Server A</b><strong>저장 완료</strong></div><i class="lost">응답 ✕</i><span class="uncertain"><b>클라이언트</b>성공? 실패?</span><em>Server B는 정상 · Server C만 느림</em></div><figcaption><strong>타임아웃은 기다림을 끝내는 판단이며 원격 작업이 실패했다는 증거는 아니에요</strong><ul class="picture-key"><li><b>부분 장애</b>일부 구성 요소만 멈추거나 느려져요.</li><li><b>메시지 유실</b>요청과 응답은 각각 사라질 수 있어요.</li><li><b>불확실성</b>클라이언트가 결과를 즉시 확정하지 못할 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'리더 기반 복제는 쓰기 순서를 정하고 팔로워에 로그나 상태를 전달해요',html:`<p>클라이언트는 쓰기를 리더에 보내고 리더는 순서를 정해 복제본에 전달해요. 비동기 복제는 리더 저장 뒤 빨리 응답할 수 있지만 리더 장애 전 전달되지 않은 쓰기를 잃을 수 있어요. 동기 복제는 필요한 복제본의 확인을 기다려 위험을 줄이지만 느리거나 분리된 복제본 때문에 응답이 늦거나 불가능할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="replication-path-visual" aria-label="비동기 복제는 리더 저장 뒤 먼저 응답하고 동기 복제는 팔로워 확인 뒤 응답"><div><b>비동기</b><span>Client → Leader 저장</span><strong>먼저 응답</strong><i>나중에 B · C 전달</i></div><div><b>동기·쿼럼</b><span>Client → Leader → B 확인</span><strong>필요한 복제 후 응답</strong><i>C는 뒤따를 수 있음</i></div></div><figcaption><strong>동기와 비동기는 단순히 빠름과 느림의 이름이 아니라 응답 전에 무엇을 보장하는지의 차이예요</strong><ul class="picture-key"><li><b>리더</b>쓰기 순서와 복제 흐름을 조정해요.</li><li><b>비동기</b>응답 지연을 줄이는 대신 미복제 구간이 생겨요.</li><li><b>동기</b>확인을 기다리는 범위와 장애 허용 조건을 정해야 해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'일관성 모델은 사용자가 허용되는 읽기 결과를 판단하는 규칙이에요',html:`<p><strong>선형화 가능성</strong>은 완료된 작업의 실제 시간 순서를 존중하면서 모든 작업이 한 순간에 일어난 것처럼 설명할 수 있어야 해요. <strong>최종 일관성</strong>은 새 쓰기가 멈추고 메시지가 전달되면 복제본이 수렴함을 목표로 하지만 수렴 전 어떤 값을 읽는지는 별도 규칙이 필요해요. 세션 보장은 한 사용자의 읽기 경험을 보완할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="consistency-timeline-visual" aria-label="선형화 가능 읽기는 완료된 v1 쓰기 뒤 v1을 보지만 최종 일관성 복제본은 잠시 old를 읽고 나중에 v1로 수렴"><div><b>선형화 가능</b><span>WRITE v1 완료</span><i>→</i><strong>READ v1</strong></div><div><b>최종 일관성</b><span>Leader v1</span><i>→</i><strong>Replica old</strong><i>전달 뒤</i><strong>Replica v1</strong></div></div><figcaption><strong>“일관적”이라는 말만으로는 부족하며 어떤 읽기 결과가 허용되는지 구체적으로 정의해야 해요</strong><ul class="picture-key"><li><b>선형화</b>완료된 최신 쓰기보다 과거 값을 보여주지 않아요.</li><li><b>최종 수렴</b>복제 지연 중 오래된 값이 가능해요.</li><li><b>세션</b>read-your-writes 같은 사용자별 규칙을 둘 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'복제 메시지를 늦추고 어느 서버에서 어떤 버전을 읽는지 확인해요',html:`<p>A만 저장한 뒤 응답하고 B에서 읽으면 old가 보여요. 복제 메시지를 전달하면 같은 B가 v1을 보여요. B를 분리한 상태에서는 모두 전달을 눌러도 B가 갱신되지 않으며, 연결 복구 뒤 밀린 메시지를 다시 전달해야 수렴해요.</p>`,lab:'replica-consistency'},
 {id:'b05',title:'네트워크 분할 중에는 모든 요청에 최신 응답을 제공할 수 없어요',html:`<p>서버 집합이 서로 통신하지 못하는 분할이 생기면 양쪽 모두 쓰기를 허용할 경우 서로 충돌하는 상태가 만들어질 수 있어요. 하나의 최신 순서를 지키려면 과반수나 리더에 닿지 못한 쪽의 일부 요청을 거부하거나 기다리게 해야 해요. 반대로 응답 가능성을 우선하면 충돌 해결과 더 약한 일관성 규칙이 필요해요.</p><figure class="teaching-figure concept-figure"><div class="partition-choice-visual" aria-label="네트워크 분할로 A B 쪽과 C 쪽이 나뉘며 최신 순서를 지키는 쪽은 과반수 A B에서만 쓰기 허용"><div><span>A</span><span>B</span><b>과반수 · 쓰기 진행</b></div><i>네트워크 분할</i><div><span>C</span><b>최신 순서 보장 시 대기</b></div><strong>분할 허용 상황에서 일관성·응답 가능성 선택</strong></div><figcaption><strong>CAP의 분할 허용은 네트워크가 절대 끊기지 않는다는 가정 대신 끊긴 동안의 동작을 정하는 문제예요</strong><ul class="picture-key"><li><b>과반수</b>겹치는 집합으로 두 리더의 동시 확정을 막는 데 도움을 줘요.</li><li><b>일관성 우선</b>확신할 수 없는 요청을 거부할 수 있어요.</li><li><b>가용성 우선</b>충돌·오래된 읽기 처리 규칙이 필요해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'읽기 경로는 필요한 일관성과 지연 목표에 맞춰 선택해요',html:`${table(['읽기 방법','관찰 가능한 결과','비용·조건'],[['리더 읽기','리더가 최신 상태를 확인하면 강한 읽기 구성 가능','리더 병목과 원거리 지연, 임기 확인 필요'],['팔로워 읽기','가까운 복제본으로 낮은 지연 가능','복제 지연으로 오래된 값 가능'],['쿼럼 읽기','여러 복제본의 버전을 비교','추가 메시지와 충돌·버전 판정 규칙 필요'],['세션 고정·토큰','한 사용자의 이전 쓰기 이상 버전 요구','세션 메타데이터와 장애 시 우회 규칙 필요']])}<p>“항상 최신”이 필요한 잔액과 잠시 늦어도 되는 조회 통계는 같은 선택을 하지 않을 수 있어요. 요구사항을 작업별로 정하고 장애 중 응답도 검증해요.</p>`}
 ],questions:[
 {q:'클라이언트가 타임아웃을 받았을 때 반드시 알 수 있는 것은?',options:['기다리기로 정한 시간이 지났다는 사실','서버가 요청을 절대 처리하지 않았다는 사실','모든 복제본이 같은 값을 저장했다는 사실'],answer:0,feedback:['맞아요. 원격 결과는 여전히 불확실할 수 있어요.','처리 뒤 응답만 사라졌을 수도 있어요.','복제 완료 여부는 별도 프로토콜로 확인해야 해요.'],review:'b01'},
 {q:'비동기 복제 직후 팔로워 읽기에서 가능한 결과는?',options:['아직 이전 버전','항상 리더와 동일한 최신 버전','읽기 자체가 물리적으로 불가능'],answer:0,feedback:['맞아요. 복제 메시지가 도착하기 전일 수 있어요.','비동기 응답은 팔로워 반영을 기다리지 않을 수 있어요.','온라인 팔로워는 오래된 값을 반환할 수 있어요.'],review:'b04'},
 {q:'선형화 가능한 읽기에 대한 설명은?',options:['완료된 작업의 실제 시간 순서를 존중하는 단일 순서로 설명돼요.','언젠가 수렴하기만 하면 현재 어떤 값도 허용해요.','복제본 수가 두 개면 자동으로 보장돼요.'],answer:0,feedback:['맞아요. 각 작업이 한 순간에 일어난 것처럼 설명할 수 있어야 해요.','그 설명은 최종 수렴만 강조해요.','복제 개수보다 프로토콜과 읽기 경로가 중요해요.'],review:'b03'}
 ],summary:['분산 시스템은 일부 서버와 메시지만 실패하는 부분 장애와 불확실성을 다뤄요.','동기·비동기 복제는 응답 전 확인 범위와 지연·데이터 위험이 달라요.','일관성 모델은 허용되는 읽기 결과를 정의하며 분할 중 선택을 명시해야 해요.'],nextQuestion:'서버들이 서로 다른 로그를 가진 상태에서 어떤 값을 확정하고 새 리더를 안전하게 고를까요?',sources:[['MIT 6.5840 · Distributed Systems','https://pdos.csail.mit.edu/6.824/'],['Herlihy & Wing · Linearizability','https://cs.brown.edu/~mph/HerlihyW90/p463-herlihy.pdf'],['Raft Consensus Algorithm','https://raft.github.io/']]
};

CS.lessons['ch20-l02']={
 lead:'합의 알고리즘은 장애와 지연이 있어도 서버들이 같은 명령 순서에 동의하도록 해요. Raft는 리더 선출, 로그 복제, 안전 규칙을 나누어 설명하며 과반수를 이용해 확정된 로그가 새 리더에 이어지게 해요.',
 goals:['Raft의 follower·candidate·leader와 term의 역할을 설명해요.','과반수 로그 복제와 확정의 차이를 실습으로 확인해요.','타임아웃 재시도에서 멱등 키가 중복 효과를 막는 원리를 설명해요.'],prerequisites:['ch11-l02','ch14-l02','ch20-l01'],sections:[
 {id:'b01',title:'Raft는 임기마다 하나의 리더를 선출하고 리더가 로그 복제를 조정해요',html:`<p>서버는 보통 follower로 시작하고 리더의 연락이 일정 시간 없으면 candidate가 되어 새 term에서 표를 요청해요. 과반수 표를 얻은 후보가 leader가 되고 클라이언트 명령을 로그에 추가해 팔로워에 복제해요. 무작위화된 선거 타임아웃은 후보들이 계속 동시에 출마할 가능성을 줄여요.</p><figure class="teaching-figure concept-figure"><div class="raft-roles-visual" aria-label="term 4의 follower가 타임아웃 뒤 term 5 candidate가 되어 과반수 표를 얻고 leader가 됨"><span><b>Follower</b>term 4</span><i>선거 타임아웃</i><span><b>Candidate</b>term 5 · 표 요청</span><i>A+B 과반수</i><strong>Leader<br>로그 복제</strong></div><figcaption><strong>term은 리더 시대를 구분하는 논리적 번호이며 더 높은 term을 보면 이전 리더는 물러나요</strong><ul class="picture-key"><li><b>Follower</b>리더의 로그와 연락을 따라요.</li><li><b>Candidate</b>새 임기에 한 표를 요청해요.</li><li><b>Leader</b>명령 순서와 복제를 조정해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'세 서버에서는 두 서버의 과반수에 저장되어야 한 서버 장애 뒤에도 겹침이 생겨요',html:`<p>3노드의 과반수는 2개예요. A에만 있는 로그는 A가 멈추면 다른 서버들이 알지 못하지만 A와 B에 있는 로그는 B와 C가 새 선거를 할 때 B를 통해 이어질 수 있어요. 실제 Raft의 확정 규칙에는 현재 term의 로그와 로그 최신성 조건이 더 포함돼요.</p><figure class="teaching-figure concept-figure"><div class="quorum-overlap-visual" aria-label="세 서버에서 A B 과반수와 B C 과반수가 B에서 겹침"><div><span>A</span><span class="overlap">B</span><b>쓰기 과반수 A+B</b></div><i>겹치는 B</i><div><span class="overlap">B</span><span>C</span><b>선거 과반수 B+C</b></div><strong>확정 로그가 다음 리더 후보 집합과 만남</strong></div><figcaption><strong>과반수 집합은 서로 적어도 한 서버에서 겹치지만 로그 최신성 규칙도 함께 지켜야 해요</strong><ul class="picture-key"><li><b>3노드</b>2개가 과반수예요.</li><li><b>5노드</b>3개가 과반수예요.</li><li><b>진행</b>과반수와 통신할 수 없으면 새 확정을 멈춰요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'리더 로그를 복제하고 과반수 확정·리더 교체·재시도를 실행해요',html:`<p>req-1을 제안하면 처음에는 A에만 있어 미확정이에요. B에 복제하면 A+B 과반수로 확정되고 효과가 한 번 적용돼요. 그 뒤 A를 분리하고 B를 새 리더로 선출해 보세요. 같은 req-1 재시도는 새 로그를 만들지 않지만 새 req-2는 별도 요청이에요.</p>`,lab:'raft-quorum'},
 {id:'b04',title:'로그 항목은 리더에 추가된 것과 클러스터에서 확정된 것을 구별해요',html:`<p>리더는 명령과 term을 로그에 추가해 팔로워에 보냅니다. 과반수 복제와 안전 조건을 충족한 항목은 commit index 안으로 들어오고 상태 머신이 같은 순서로 적용해요. 팔로워의 충돌하는 미확정 꼬리는 새 리더의 로그와 맞추는 과정에서 바뀔 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="raft-log-visual" aria-label="A B 로그의 index 1과 2는 확정되고 A만 가진 index 3은 미확정"><div><b>A · Leader</b><span class="commit">1 t1</span><span class="commit">2 t1</span><span>3 t2</span></div><div><b>B · Follower</b><span class="commit">1 t1</span><span class="commit">2 t1</span><em>비어 있음</em></div><div><b>C · Follower</b><span class="commit">1 t1</span><em>지연</em><em>지연</em></div><strong>commit index = 2<br>상태 머신은 1 → 2 적용</strong></div><figcaption><strong>로그에 보인다는 사실만으로 클라이언트에 확정됐다고 답하면 안 돼요</strong><ul class="picture-key"><li><b>append</b>리더 로컬 로그에 먼저 들어갈 수 있어요.</li><li><b>replicate</b>팔로워가 순서와 이전 항목을 확인해요.</li><li><b>commit</b>안전 조건 뒤 같은 순서로 적용해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'응답이 사라진 요청은 같은 멱등 키로 재시도해 중복 효과를 막아요',html:`<p>서버가 주문을 만들고 응답만 잃으면 클라이언트는 성공 여부를 몰라요. 새 요청처럼 다시 보내면 주문이 두 개 생길 수 있어요. 클라이언트가 같은 의도를 나타내는 고유 키를 재사용하면 서버는 이미 처리한 결과를 찾아 의미가 같은 응답을 돌려줄 수 있어요. 같은 키에 다른 내용을 보내면 오류로 다루는 편이 안전해요.</p><figure class="teaching-figure concept-figure"><div class="idempotent-retry-visual" aria-label="req-7 주문 생성 응답이 유실된 뒤 같은 req-7 재시도는 기존 주문을 반환해 효과가 한 번"><span><b>Client</b>req-7 · 주문 생성</span><i>→</i><div><b>Server</b><strong>req-7 기록 + 주문 #42</strong></div><i class="lost">응답 유실</i><span><b>재시도</b>req-7 · 같은 내용</span><i>→</i><strong>기존 #42 반환<br>효과 1회</strong></div><figcaption><strong>멱등 키 기록과 실제 변경은 원자적으로 묶고 키의 범위·보존 기간·내용 비교를 정해야 해요</strong><ul class="picture-key"><li><b>같은 의도</b>같은 호출자와 키를 재사용해요.</li><li><b>중복 억제</b>새 효과 대신 기존 결과를 연결해요.</li><li><b>다른 내용</b>같은 키 재사용을 검증 오류로 처리해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'분산 시간은 하나의 완벽한 시계보다 사건 사이의 순서 관계를 먼저 봐요',html:`${table(['도구·개념','알 수 있는 것','한계·주의'],[['물리 시계','대략적인 실제 시간·만료 시점','시계 오차·조정·네트워크 지연을 고려해야 해요.'],['논리 시계·term','사건 또는 리더 시대의 순서','실제 몇 초 차이인지는 알려주지 않아요.'],['인과 관계','한 사건이 다른 사건에 영향을 줄 수 있었는지','동시 사건에는 하나의 자연스러운 순서가 없을 수 있어요.'],['쿼럼·합의 로그','복제 명령의 안전한 단일 순서 구성','과반수 장애 중에는 진행이 멈출 수 있어요.'],['멱등 키','재시도 요청의 같은 의도 식별','키 저장 수명·범위와 매개변수 일치 검사가 필요해요.']])}<p>합의는 모든 서버의 시계를 완벽히 맞추는 기술이 아니에요. 메시지와 표, 로그 규칙으로 어떤 사건을 먼저 확정할지 결정해요.</p>`}
 ],questions:[
 {q:'3노드 Raft 클러스터에서 과반수는?',options:['2노드','1노드','항상 3노드 전부'],answer:0,feedback:['맞아요. 두 과반수 집합은 적어도 한 노드에서 겹쳐요.','한 노드만으로 두 리더가 동시에 확정할 수 있어요.','모든 노드를 기다리면 한 대 장애에도 진행하지 못해요.'],review:'b02'},
 {q:'리더 A에만 추가되고 팔로워에는 복제되지 않은 로그는?',options:['아직 미확정일 수 있어요.','항상 과반수 확정이에요.','모든 상태 머신에 이미 적용됐어요.'],answer:0,feedback:['맞아요. 로컬 추가와 클러스터 확정을 구별해요.','A 하나는 3노드의 과반수가 아니에요.','확정 순서 뒤 적용돼요.'],review:'b04'},
 {q:'응답 유실 뒤 중복 효과를 줄이는 재시도 방법은?',options:['같은 의도에 같은 멱등 키를 사용해요.','매번 무조건 새 키를 만들어요.','타임아웃이면 첫 요청이 실패했다고 가정해요.'],answer:0,feedback:['맞아요. 서버가 이전 처리와 재시도를 연결할 수 있어요.','새 키는 새 요청으로 처리될 수 있어요.','서버는 이미 처리했을 수 있어요.'],review:'b05'}
 ],summary:['Raft는 term과 역할을 사용해 리더를 선출하고 리더가 로그 순서를 조정해요.','과반수 복제와 로그 최신성 규칙으로 확정된 명령이 새 리더에 이어지게 해요.','타임아웃 재시도는 같은 멱등 키와 원자적 결과 기록으로 중복 효과를 제어해요.'],nextQuestion:'사용자가 늘어날 때 서버·캐시·데이터를 어떻게 나누고 과부하를 제어할까요?',sources:[['Ongaro & Ousterhout · Raft paper','https://raft.github.io/raft.pdf'],['MIT 6.5840 · Raft Lab','https://pdos.csail.mit.edu/6.824/labs/lab-raft1.html'],['MIT 6.5840 · Fault-tolerant KV Lab','https://pdos.csail.mit.edu/6.5840/labs/lab-kvraft1.html'],['AWS Builders’ Library · Making retries safe','https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/']]
};
})();
