(()=>{
const {table}=CS.helpers;
CS.lessons['ch21-l01']={
 lead:'확장성은 서버 수를 늘리는 기술 하나가 아니라 목표 처리량과 지연을 정하고, 요청과 데이터를 병목 없이 나누며, 쏠림과 장애를 측정하는 과정이에요.',
 goals:['처리량·지연·동시 요청을 서로 다른 요구사항으로 설명해요.','수직·수평 확장과 로드 밸런서·세션 배치의 관계를 설명해요.','캐시와 샤딩이 부하를 줄이는 조건과 핫키 위험을 실습해요.'],prerequisites:['ch09-l02','ch12-l02','ch20-l01'],sections:[
 {id:'b01',title:'먼저 처리량·지연·동시 요청과 장애 목표를 숫자로 적어요',html:`<p><strong>처리량</strong>은 초당 완료한 요청 수, <strong>지연 시간</strong>은 요청 하나가 끝날 때까지 걸린 시간이에요. 동시 요청 수는 서비스 시간과 도착률에 함께 영향을 받아요. 평균만 보면 느린 일부 사용자를 놓칠 수 있어 p95·p99 같은 백분위 지연과 오류율, 장애 중 목표도 정해요.</p><figure class="teaching-figure concept-figure"><div class="scale-requirements-visual" aria-label="초당 요청 처리량과 개별 요청 지연 시간 및 동시에 처리 중인 요청 수를 구별"><div><b>처리량</b><strong>1,000 req/s</strong><span>단위 시간 완료 수</span></div><div><b>지연</b><strong>p95 200 ms</strong><span>95퍼센트가 이내</span></div><div><b>동시성</b><strong>200 in-flight</strong><span>현재 처리 중</span></div></div><figcaption><strong>“빠르게” 대신 부하 수준과 측정 구간을 포함한 목표를 세워요</strong><ul class="picture-key"><li><b>처리량</b>시스템이 감당하는 작업량이에요.</li><li><b>지연</b>사용자 한 명이 기다리는 시간이에요.</li><li><b>꼬리 지연</b>느린 일부 요청도 드러내요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'수직 확장은 한 대를 키우고 수평 확장은 여러 대로 요청을 나눠요',html:`<p>수직 확장은 CPU·메모리·디스크가 더 큰 장비로 바꾸기 쉬운 대신 한 장비의 상한과 장애 영향이 남아요. 수평 확장은 서버를 추가해 처리량과 장애 격리를 개선할 수 있지만 상태 공유, 분산, 배포, 관측이 복잡해져요. 실제 서비스는 두 방법을 함께 사용하기도 해요.</p><figure class="teaching-figure concept-figure"><div class="vertical-horizontal-visual" aria-label="작은 서버 한 대를 큰 서버로 바꾸는 수직 확장과 작은 서버를 여러 대 추가하는 수평 확장"><div><b>수직 확장</b><span class="small-server">4 CPU</span><i>→</i><strong>16 CPU</strong><em>단순하지만 한계 존재</em></div><div><b>수평 확장</b><span class="server-row"><i>4</i><i>4</i><i>4</i><i>4</i></span><strong>요청 분산</strong><em>상태·장애 조정 필요</em></div></div><figcaption><strong>서버 수만 늘려도 병목이 데이터베이스나 공유 잠금에 남으면 전체 처리량은 늘지 않아요</strong><ul class="picture-key"><li><b>Scale up</b>한 노드의 자원을 늘려요.</li><li><b>Scale out</b>노드 수를 늘려 일을 나눠요.</li><li><b>병목</b>요청 경로 전체를 측정해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'로드 밸런서는 건강한 서버를 고르고 세션 상태는 분산을 막지 않게 배치해요',html:`<p>로드 밸런서는 라운드 로빈, 최소 연결, 가중치처럼 정한 정책으로 요청을 건강한 서버에 전달해요. 로그인 세션을 서버 한 대의 메모리에만 두고 세션 고정을 사용하면 특정 사용자가 많은 서버에 부하가 몰리고 장애 시 상태를 잃기 쉬워요. 서명된 토큰이나 공유 저장소 등 요구사항에 맞는 상태 배치를 선택해요.</p><figure class="teaching-figure concept-figure"><div class="load-balance-visual" aria-label="클라이언트 요청을 로드 밸런서가 세 서버로 분산하되 세션 고정은 한 서버에 쏠림을 만듦"><span><b>Clients</b>요청 요청 요청</span><i>→</i><strong>Load<br>Balancer</strong><i>→</i><div><span>Server A · 40</span><span>Server B · 40</span><span>Server C · 40</span></div><em>세션 고정 시 60 · 40 · 20</em></div><figcaption><strong>총 용량이 충분해도 분산 정책이 고르지 않으면 한 서버부터 포화돼요</strong><ul class="picture-key"><li><b>건강 확인</b>실패한 대상에는 새 요청을 보내지 않아요.</li><li><b>정책</b>요청 비용과 연결 특성에 맞춰요.</li><li><b>상태</b>서버 교체와 재분산을 고려해요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'서버 수·캐시·세션 고정·핫키를 바꾸며 초과 요청을 비교해요',html:`<p>기준은 120개 요청, 서버 2대, 한 대당 40개 처리예요. 서버 성능을 높이거나 한 대를 추가하면 총 용량이 맞아져요. 하지만 세션 고정이나 핫키는 같은 총 용량에서도 한 곳을 먼저 넘치게 해요. 핫키 분할과 캐시가 결과를 어떻게 바꾸는지 실행해 보세요.</p>`,lab:'scaling-distribution'},
 {id:'b05',title:'캐시는 가까운 곳에서 재사용 가능한 응답을 제공해 원본 부하와 지연을 줄여요',html:`<p>브라우저·CDN·리버스 프록시·애플리케이션·데이터 저장소 앞에 서로 다른 캐시를 둘 수 있어요. 캐시 키, 신선도, 무효화, 개인정보 범위를 잘못 정하면 빠르게 오래되거나 다른 사용자의 값을 보여줄 수 있어요. HTTP 캐시는 응답 지시자와 검증 요청을 이용해 재사용 가능성을 판단해요.</p><figure class="teaching-figure concept-figure"><div class="cache-cdn-visual" aria-label="사용자 요청이 브라우저 캐시와 CDN을 거쳐 원본 서버와 데이터베이스로 가며 앞단 적중일수록 뒤 부하가 줄어듦"><span><b>Browser</b>개인 캐시</span><i>→</i><span><b>CDN</b>지역 엣지</span><i>→</i><span><b>Origin</b>앱 서버</span><i>→</i><strong>DB</strong><em>앞에서 적중하면 뒤 경로 생략</em></div><figcaption><strong>캐시는 복사본이므로 언제 만들고 버리고 검증할지까지 설계해야 해요</strong><ul class="picture-key"><li><b>적중률</b>원본까지 가지 않은 비율이에요.</li><li><b>신선도</b>얼마 동안 재사용할지 정해요.</li><li><b>무효화</b>변경된 값을 언제 반영할지 정해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'샤드 키는 데이터를 고르게 나누면서 자주 함께 쓰는 요청을 효율적으로 찾아야 해요',html:`${table(['분할 방법','장점','주의할 점'],[['수평 분할·샤딩','행을 여러 저장소로 나눠 용량과 처리량 확장','샤드 키·재분배·교차 샤드 질의'],['수직 분할','열이나 큰 필드를 분리해 접근 패턴 최적화','조인·일관성·추가 네트워크 호출'],['기능 분할','사용자·주문처럼 도메인별 저장소 분리','서비스 경계와 분산 트랜잭션'],['가상 샤드·해시','물리 노드보다 많은 논리 구간으로 재배치 용이','키 분포와 범위 조회 비용'],['핫키 분할','인기 키에 접미사·버킷을 두어 쓰기 분산','읽을 때 병합하고 순서·중복 처리']])}<p>시간순 ID나 유명 사용자 하나처럼 트래픽이 한 키에 몰리면 평균 분포가 좋아도 핫 파티션이 생겨요. 실제 키 분포와 가장 바쁜 구간을 관측하고 가상 샤드, 키 분할, 캐시, 전용 처리 등을 선택해요.</p>`}
 ],questions:[
 {q:'한 서버의 CPU와 메모리를 더 큰 것으로 바꾸는 확장 방법은?',options:['수직 확장','수평 확장','샤드 재분배'],answer:0,feedback:['맞아요. 한 노드의 자원을 키워요.','수평 확장은 노드 수를 늘려요.','샤드 재분배는 데이터 배치를 바꿔요.'],review:'b02'},
 {q:'서버 총 용량이 충분한데도 세션 고정으로 한 서버만 포화될 수 있는 이유는?',options:['요청이 고르게 분산되지 않기 때문이에요.','캐시가 언제나 모든 요청을 처리하기 때문이에요.','처리량과 지연이 같은 단위이기 때문이에요.'],answer:0,feedback:['맞아요. 평균 용량보다 노드별 최대 부하를 봐야 해요.','캐시 적중은 별도 조건이에요.','두 지표는 서로 다른 것을 재요.'],review:'b03'},
 {q:'샤딩에서 핫키 문제를 가장 잘 설명한 것은?',options:['특정 키 요청이 한 파티션에 몰리는 현상','모든 키가 완전히 균등한 현상','브라우저 캐시가 비어 있는 현상'],answer:0,feedback:['맞아요. 특정 샤드가 먼저 병목이 돼요.','균등하면 핫키가 아니에요.','캐시 미스와 샤드 쏠림은 다른 층의 문제예요.'],review:'b06'}
 ],summary:['확장 전 처리량·지연·동시성과 장애 목표를 숫자로 정의해요.','수직·수평 확장, 로드 밸런서와 상태 배치를 요청 경로 전체의 병목으로 판단해요.','캐시와 샤딩은 부하를 줄이지만 신선도·재분배·핫키를 함께 관리해요.'],nextQuestion:'도착하는 작업이 소비자가 처리하는 속도보다 많으면 어디에 쌓이고 어떻게 안전하게 줄일까요?',sources:[['Google SRE · Load Balancing at the Frontend','https://sre.google/sre-book/load-balancing-frontend/'],['RFC 9111 · HTTP Caching','https://www.rfc-editor.org/rfc/rfc9111.html'],['Azure Architecture · Sharding Pattern','https://learn.microsoft.com/en-ca/azure/architecture/patterns/sharding'],['Azure Well-Architected · Data Partitioning','https://learn.microsoft.com/en-us/azure/well-architected/design-guides/partition-data']]
};

CS.lessons['ch21-l02']={
 lead:'비동기 구조는 생산자와 소비자의 시간을 분리하지만 작업을 없애지는 않아요. 도착률이 처리율을 넘으면 적체가 생기므로 큐 한도, 백프레셔, 시간 제한과 안전한 재시도를 함께 설계해야 해요.',
 goals:['큐·브로커·이벤트가 생산자와 소비자를 분리하는 방법을 설명해요.','도착률과 처리율로 적체를 예측하고 제한 큐·백프레셔를 실습해요.','타임아웃·백오프·회로 차단기·멱등 키를 함께 설명해요.'],prerequisites:['ch11-l02','ch20-l02','ch21-l01'],sections:[
 {id:'b01',title:'메시지 큐는 생산자가 작업을 맡기고 소비자가 자기 속도로 가져가게 해요',html:`<p>생산자는 작업 메시지를 브로커에 보내고, 브로커는 저장·전달 정책에 따라 소비자에게 넘겨요. 소비자는 성공을 확인하고 실패한 작업은 정책에 따라 다시 처리해요. 이 분리는 순간 부하를 흡수하고 독립 배포를 돕지만 중복 전달, 순서, 지연, 보존과 실패 격리 규칙이 필요해요.</p><figure class="teaching-figure concept-figure"><div class="queue-flow-visual" aria-label="생산자가 브로커 큐에 작업을 넣고 여러 소비자가 가져가 처리하며 실패 작업은 재전달 큐로 이동"><span><b>Producer</b>주문 이벤트</span><i>→</i><div><b>Broker</b><em></em><em></em><em></em><em></em></div><i>→</i><div class="consumers"><span>Consumer A</span><span>Consumer B</span></div><strong>실패 → 재시도·격리</strong></div><figcaption><strong>비동기 응답은 작업이 완료됐다는 뜻이 아니라 안전하게 접수됐다는 약속일 수 있어요</strong><ul class="picture-key"><li><b>생산자</b>작업을 메시지로 발행해요.</li><li><b>브로커</b>전달 전 작업을 보관해요.</li><li><b>소비자</b>처리 후 성공 여부를 확인해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'도착률이 처리율보다 크면 차이만큼 대기열과 지연이 계속 늘어요',html:`<p>초당 8개가 도착하고 3개만 처리하면 한 초마다 5개가 남아요. 5초 뒤에는 25개예요. 평균 처리율이 같아도 순간 폭주를 흡수할 여유가 필요하고, 오래 쌓인 작업은 사용자가 이미 취소했거나 가치가 사라졌을 수 있어요. 큐 길이뿐 아니라 가장 오래된 작업 나이와 완료 지연을 봐요.</p><figure class="teaching-figure concept-figure"><div class="backlog-rate-visual" aria-label="초당 8개 도착하고 3개 처리되어 1초마다 대기열이 5개씩 증가"><div><b>도착 8/s</b><span>■■■■■■■■</span></div><i>−</i><div><b>처리 3/s</b><span>■■■</span></div><i>=</i><strong>적체 +5/s<br>5초 뒤 25개</strong></div><figcaption><strong>큐는 순간 차이를 시간으로 바꾸지만 지속적인 용량 부족을 해결하지는 않아요</strong><ul class="picture-key"><li><b>안정 조건</b>장기 평균 처리율이 도착률 이상이어야 해요.</li><li><b>작업 나이</b>사용자가 겪는 대기 시간을 드러내요.</li><li><b>폭주</b>버퍼와 증설이 반응할 시간을 줘요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'무제한·제한 큐와 백프레셔를 같은 도착률에서 비교해요',html:`<p>무제한 큐는 작업을 받아 적체와 메모리·지연을 늘려요. 제한 큐는 한도 밖 작업을 즉시 거부해 과부하를 드러내고, 백프레셔는 생산자를 늦춰 상류에 압력을 전달해요. 8개 도착·3개 처리로 5초를 진행한 뒤 소비자를 늘려 보세요.</p>`,lab:'bounded-queue'},
 {id:'b04',title:'제한 큐와 부하 차단은 시스템이 감당할 수 없는 일을 일찍 줄여요',html:`<p>과부하에서 모든 요청을 받아 늦게 실패하면 CPU·메모리·연결을 더 소비해 연쇄 장애가 커질 수 있어요. 큐 한도, 동시 실행 제한, 우선순위, 기한이 지난 작업 취소, 부하 차단으로 핵심 요청의 자원을 남겨요. 백프레셔가 전파되지 않는 경계에서는 명시적 거부와 재시도 가능 시간을 알려야 해요.</p><figure class="teaching-figure concept-figure"><div class="backpressure-visual" aria-label="용량 5인 제한 큐가 가득 차면 추가 요청을 거부하거나 생산자에게 천천히 보내라는 신호를 전달"><span><b>Producer</b>8/s</span><i class="back">← 천천히</i><div><b>BOUND 5</b><em class="on"></em><em class="on"></em><em class="on"></em><em class="on"></em><em class="on"></em></div><i>→</i><span><b>Consumer</b>3/s</span><strong>초과: 거부 또는 상류 지연</strong></div><figcaption><strong>용량 한도는 실패를 없애지 않고 어디서 어떤 형태로 보일지 정해요</strong><ul class="picture-key"><li><b>Bound</b>메모리와 대기 시간의 상한을 만들어요.</li><li><b>Load shedding</b>처리 가능성이 낮은 일을 일찍 거부해요.</li><li><b>Backpressure</b>생산 속도를 소비 속도에 맞추게 해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'타임아웃과 재시도는 백오프·지터·회로 차단기와 함께 써요',html:`<p>타임아웃은 영원히 기다리지 않게 하지만 서버가 처리했는지는 확정하지 못해요. 즉시 같은 간격으로 재시도하면 이미 과부하인 서버에 요청이 동기화되어 더 큰 폭주를 만들 수 있어요. 지수 백오프는 간격을 늘리고 지터는 클라이언트 시점을 흩어요. 회로 차단기는 실패가 많은 의존성 호출을 잠시 막고 회복을 시험해요.</p><figure class="teaching-figure concept-figure"><div class="retry-breaker-visual" aria-label="즉시 재시도는 한 시점에 몰리지만 지수 백오프와 지터는 요청을 1 2 4초 주변으로 흩고 회로 차단기는 실패 호출을 잠시 중단"><div><b>즉시 재시도</b><span>||||||||</span><strong>동기화된 폭주</strong></div><div><b>백오프 + 지터</b><span>| · | ·· | ···· |</span><strong>1s · 2s · 4s 주변</strong></div><em>회로 열림 → 빠른 실패 → 시험 호출</em></div><figcaption><strong>재시도는 성공 기회인 동시에 추가 부하이므로 횟수와 전체 기한을 제한해요</strong><ul class="picture-key"><li><b>Timeout</b>호출별 대기 상한을 정해요.</li><li><b>Backoff</b>실패할수록 간격을 늘려요.</li><li><b>Jitter</b>여러 클라이언트의 재시도를 흩어요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'중복 가능성을 인정하고 처리 결과를 멱등하게 만들어요',html:`${table(['장치','막거나 드러내는 문제','설계 확인'],[['확인·재전달','소비자 장애로 잃은 작업','확인 시점과 가시성 시간 제한'],['멱등 키','같은 작업의 중복 효과','키 범위·보존 기간·내용 일치'],['처리 기록과 변경의 원자성','변경 뒤 기록 실패 또는 반대 순서','트랜잭션·outbox·inbox 패턴'],['재시도 한도와 격리 큐','영구 실패 작업의 무한 반복','운영 알림·재처리·민감 정보'],['관측 지표','느린 적체와 부분 실패','큐 길이·작업 나이·처리율·거부율']])}<p>브로커의 전달 보장만으로 외부 결제나 이메일 효과가 정확히 한 번이 되지는 않아요. 소비자가 같은 메시지를 다시 받아도 이미 처리한 키를 확인하고 동일 결과를 연결하도록 업무 상태와 함께 설계해요.</p>`}
 ],questions:[
 {q:'초당 8개가 도착하고 3개를 처리하는 상태가 계속되면?',options:['대기열이 초당 5개씩 늘어요.','항상 대기열이 0이에요.','처리율이 자동으로 8개가 돼요.'],answer:0,feedback:['맞아요. 지속적 용량 차이가 적체가 돼요.','처리보다 도착이 많아요.','큐 자체가 소비자 용량을 늘리지는 않아요.'],review:'b02'},
 {q:'제한 큐와 백프레셔의 공통 목적은?',options:['감당할 수 없는 적체에 상한과 신호를 만들어요.','모든 작업을 무한히 메모리에 보관해요.','중복 처리를 자동으로 완전히 없애요.'],answer:0,feedback:['맞아요. 과부하를 일찍 드러내고 자원을 보호해요.','그 방식은 무제한 큐에 가까워요.','멱등 처리 규칙이 별도로 필요해요.'],review:'b04'},
 {q:'많은 클라이언트가 실패 직후 동시에 재시도하는 폭주를 줄이는 방법은?',options:['제한된 재시도에 지수 백오프와 지터를 적용해요.','대기 없이 무한 재시도해요.','매번 같은 멱등 키에 다른 내용을 보내요.'],answer:0,feedback:['맞아요. 요청 시점을 흩고 추가 부하를 제한해요.','과부하를 더 키울 수 있어요.','같은 키의 의미가 깨져요.'],review:'b05'}
 ],summary:['큐는 생산자와 소비자를 분리하지만 처리율보다 높은 도착률은 적체로 남아요.','제한 큐·부하 차단·백프레셔로 자원 상한과 과부하 신호를 만들어요.','타임아웃·백오프·지터·회로 차단기와 멱등 처리를 묶어 중복과 연쇄 장애를 줄여요.'],nextQuestion:'요구사항이 주어졌을 때 구성 요소와 데이터 흐름, 실패 처리를 어떻게 한 장의 설계로 정리할까요?',sources:[['Google SRE · Addressing Cascading Failures','https://sre.google/sre-book/addressing-cascading-failures/'],['AWS Well-Architected Framework','https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html'],['AWS Builders’ Library · Making retries safe','https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/']]
};
})();
