(()=>{
const {table}=CS.helpers;
CS.lessons['ch22-l01']={
 lead:'좋은 모듈은 단순히 파일을 많이 나눈 결과가 아니에요. 함께 바뀌는 책임을 모으고 바뀔 수 있는 구현을 인터페이스 뒤에 숨겨, 한 요구 변경이 불필요한 곳까지 번지지 않게 만들어요.',
 goals:['추상화·캡슐화·인터페이스가 각각 무엇을 숨기고 약속하는지 설명해요.','응집도와 결합도를 변경 이유와 의존 관계로 판단해요.','의존성 방향과 상태·부작용 경계가 변경 범위에 미치는 영향을 실습해요.'],prerequisites:['ch12-l01','ch18-l02','ch21-l01'],sections:[
 {id:'b01',title:'추상화는 필요한 약속을 남기고 캡슐화는 내부 결정을 경계 안에 숨겨요',html:`<p>추상화는 복잡한 대상에서 사용자가 알아야 할 동작을 골라 표현해요. 인터페이스는 입력·출력·오류 같은 협력 약속을 드러내고, 캡슐화는 저장 방식이나 외부 SDK처럼 바뀔 수 있는 결정을 외부가 직접 만지지 못하게 해요. 약속이 안정적이면 구현을 바꿔도 사용 코드는 그대로 둘 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="abstraction-box-visual" aria-label="대출 서비스 사용자는 lend 인터페이스만 보고 내부 재고 확인 데이터 저장 알림 구현은 캡슐 안에 숨겨짐"><span><b>사용 코드</b>lend(member, book)</span><i>인터페이스 약속</i><div><b>캡슐 내부</b><span>재고 확인</span><span>저장 방식</span><span>알림 SDK</span></div><strong>내부 변경<br>약속은 유지</strong></div><figcaption><strong>숨긴다는 것은 문서화하지 않는다는 뜻이 아니라 외부가 의존할 필요 없는 결정을 경계 안에 둔다는 뜻이에요</strong><ul class="picture-key"><li><b>추상화</b>필요한 개념과 동작을 골라요.</li><li><b>인터페이스</b>모듈 사이의 사용 약속이에요.</li><li><b>캡슐화</b>내부 상태와 결정을 통제해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'응집도는 함께 바뀌는 책임을 모으고 결합도는 변경이 번지는 연결을 줄여요',html:`<p>응집도가 높은 모듈은 하나의 분명한 변경 이유를 중심으로 기능이 모여요. 결합도가 높다는 것은 한 모듈이 다른 모듈의 구체 타입, 데이터 구조, 호출 순서를 많이 알아 작은 변경도 여러 곳에 영향을 준다는 뜻이에요. 선의 개수만 세기보다 무엇을 아는 의존인지와 변경 사례를 확인해야 해요.</p><figure class="teaching-figure concept-figure"><div class="cohesion-coupling-visual" aria-label="뒤섞인 모듈은 대출 저장 알림 책임과 여러 구현이 얽히고 분리한 모듈은 책임별로 모여 안정된 약속으로 연결"><div><b>낮은 응집·강한 결합</b><span>대출 + SQL + 메일</span><i>SDK 필드 직접 접근</i><i>DB 표 구조 직접 접근</i></div><div><b>높은 응집·느슨한 결합</b><span>대출 정책</span><span>저장소 구현</span><span>알림 구현</span><i>작은 약속으로 연결</i></div></div><figcaption><strong>모듈 하나가 반드시 함수 하나나 클래스 하나일 필요는 없으며 변경의 단위를 기준으로 판단해요</strong><ul class="picture-key"><li><b>응집</b>같은 이유로 바뀌는 일을 가까이 둬요.</li><li><b>결합</b>다른 모듈의 세부사항을 아는 정도예요.</li><li><b>변경 사례</b>실제 요구를 넣어 영향 범위를 확인해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'업무 정책이 구체 구현 대신 자신이 필요한 인터페이스에 의존하게 해요',html:`<p>대출 정책이 EmailSDK를 직접 생성하면 문자 알림으로 바꿀 때 정책 코드도 수정돼요. 정책 쪽에서 <code>Notifier.send</code> 약속을 정의하고 메일·문자 구현이 그 약속을 구현하면 컴파일 시 의존성은 바깥 구현에서 안쪽 정책의 추상화로 향해요. 실행 흐름은 여전히 정책이 알림을 호출하지만 소스 의존 방향은 달라질 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="dependency-inversion-visual" aria-label="대출 정책이 알림 인터페이스를 소유하고 메일과 문자 구현이 바깥에서 그 인터페이스를 구현"><div><b>안쪽 정책</b><span>LoanPolicy</span><strong>Notifier port</strong></div><i>구현이 약속에 의존</i><div><span>EmailNotifier</span><span>SmsNotifier</span><b>바깥 세부사항</b></div></div><figcaption><strong>의존성 역전은 호출 화살표를 없애는 기법이 아니라 안정된 정책이 불안정한 세부사항을 직접 알지 않게 하는 원칙이에요</strong><ul class="picture-key"><li><b>정책</b>필요한 동작의 약속을 정해요.</li><li><b>구현</b>약속을 지키며 기술 세부사항을 담당해요.</li><li><b>조립</b>실행 시작점에서 실제 구현을 연결해요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'메일을 문자로 교체하며 뒤섞인 구조와 분리한 구조의 변경 범위를 비교해요',html:`<p>두 구조 모두 같은 B01 대출을 저장하고 알림 한 건을 만들 수 있어요. 뒤섞인 구조에서는 대출·저장·알림 역할을 함께 바꾸지만, 분리 구조에서는 문자 구현과 조립 지점만 바꿔요. 구독자가 0명일 때도 대출 성공과 알림 생략 정책을 구별해 보세요.</p>`,lab:'module-boundary'},
 {id:'b05',title:'상태를 바꾸는 부작용은 경계를 좁히고 순수한 판단과 분리해요',html:`<p>같은 입력에 같은 결과를 계산하고 외부 상태를 바꾸지 않는 함수는 조합하고 시험하기 쉬워요. 데이터베이스 저장, 네트워크 전송, 현재 시간 읽기 같은 부작용은 필요하지만 실패와 순서가 결과에 영향을 줘요. 핵심 판단은 값으로 계산하고 부작용은 얇은 경계에서 실행하면 오류와 재시도 정책이 보이기 쉬워져요.</p><figure class="teaching-figure concept-figure"><div class="effects-boundary-visual" aria-label="순수한 대출 가능 판단이 명령 값을 만들고 바깥 효과 경계가 데이터베이스 저장과 알림 전송을 실행"><div><b>순수한 판단</b><span>입력: 회원·도서</span><strong>{ save, notify }</strong></div><i>명령 값</i><div><b>효과 경계</b><span>DB 저장</span><span>알림 전송</span><em>실패·재시도 기록</em></div></div><figcaption><strong>부작용을 완전히 없애는 대신 언제 어디서 일어나는지 드러내고 상태 변경 통로를 제한해요</strong><ul class="picture-key"><li><b>순수 계산</b>입력과 규칙만으로 결과를 만들어요.</li><li><b>효과</b>외부 세계의 상태를 바꾸거나 읽어요.</li><li><b>경계</b>실패·순서·재시도 책임을 모아요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'객체와 함수는 목적에 따라 섞어 쓰며 경계 비용도 함께 봐요',html:`${table(['접근','잘 표현하는 것','비용·주의'],[['객체와 캡슐','수명과 규칙을 가진 상태, 다형적 구현','숨은 상태·상속 결합·호출 순서'],['순수 함수와 값','변환·검증·계산 파이프라인','큰 값 복사·효과 연결 방식'],['인터페이스·포트','교체 가능한 외부 구현과 테스트 대역','약속 증가·간접 호출·버전 관리'],['모듈 경계','팀과 변경 이유에 따른 코드 소유','경계가 틀리면 잦은 교차 변경'],['공유 유틸리티','안정적인 공통 계산','무관한 책임이 모이는 잡동사니 모듈 위험']])}<p>추상화를 먼저 많이 만드는 것이 목표는 아니에요. 두 번째 구현이나 실제 변경 압력이 나타났을 때 어떤 차이를 숨겨야 하는지 확인하고, 작은 프로그램에서는 직접적인 코드가 더 이해하기 쉬울 수도 있어요.</p>`}
 ],questions:[
 {q:'인터페이스의 역할을 가장 잘 설명한 것은?',options:['모듈이 협력하는 입력·출력과 오류 약속을 드러내요.','모든 내부 필드를 외부에 공개해요.','구체 구현을 절대 바꿀 수 없게 해요.'],answer:0,feedback:['맞아요. 사용자는 약속에 의존하고 구현은 바뀔 수 있어요.','캡슐화는 불필요한 내부 접근을 제한해요.','약속을 지키면 구현을 바꿀 수 있어요.'],review:'b01'},
 {q:'응집도가 높은 모듈의 특징은?',options:['같은 이유로 함께 바뀌는 책임이 모여 있어요.','서로 무관한 기능을 한 파일에 계속 추가해요.','외부 SDK의 모든 세부 필드를 직접 알아요.'],answer:0,feedback:['맞아요. 변경 이유가 분명해져요.','무관한 변경 이유가 섞이면 응집도가 낮아져요.','구체 세부 의존이 커져요.'],review:'b02'},
 {q:'의존성 역전을 적용한 대출 정책은 무엇에 의존해야 할까요?',options:['자신이 필요로 하는 Notifier 인터페이스','특정 SMS SDK의 내부 클래스','운영 서버의 실제 전화번호 목록'],answer:0,feedback:['맞아요. 바깥 구현이 그 약속을 구현해요.','구체 SDK를 직접 알면 교체 영향이 정책으로 번져요.','운영 데이터는 정책의 소스 의존 대상이 아니에요.'],review:'b03'}
 ],summary:['추상화는 필요한 약속을 드러내고 캡슐화는 바뀔 결정을 경계 안에 둬요.','응집도와 결합도는 파일 수보다 실제 변경 이유와 영향 범위로 판단해요.','안정된 정책이 인터페이스를 소유하고 상태·부작용을 좁은 경계에서 관리해요.'],nextQuestion:'모듈을 하나의 배포로 둘지 여러 서비스와 이벤트로 나눌지는 어떤 기준으로 판단할까요?',sources:[['Parnas · On the Criteria to Decompose Systems into Modules','https://doi.org/10.1184/r1/6607958'],['Microsoft .NET · Architectural Principles','https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles'],['Oracle Java Tutorials · Interfaces','https://docs.oracle.com/javase/tutorial/java/IandI/createinterface.html']]
};

CS.lessons['ch22-l02']={
 lead:'아키텍처는 상자 그림의 이름보다 중요한 설계 결정들의 묶음이에요. 같은 기능도 배포 단위, 통신 방식, 데이터 소유권과 장애 처리에 따라 변경 속도와 운영 비용이 달라져요.',
 goals:['계층 구조와 배포 구조가 서로 다른 관점임을 설명해요.','모놀리스·마이크로서비스·이벤트 기반 구조의 비용과 이점을 비교해요.','정상 결과뿐 아니라 중간 장애와 미완료 상태로 설계를 평가해요.'],prerequisites:['ch20-l02','ch21-l02','ch22-l01'],sections:[
 {id:'b01',title:'계층은 책임과 의존 방향을 정리하며 반드시 별도 서버를 뜻하지 않아요',html:`<p>표현 계층은 사용자 입력과 출력을, 응용 계층은 사용 사례 흐름을, 도메인 계층은 핵심 규칙을, 인프라 계층은 데이터베이스와 외부 시스템 연결을 담당할 수 있어요. 이 계층들은 한 프로세스와 한 배포 파일 안에도 존재할 수 있어요. 계층을 건너뛰는 편법이 쌓이면 안쪽 정책이 바깥 기술에 묶여요.</p><figure class="teaching-figure concept-figure"><div class="layered-architecture-visual" aria-label="표현 응용 도메인 인프라 계층이 있으며 소스 의존은 안쪽 도메인 규칙을 향함"><span><b>표현</b>HTTP · 화면</span><span><b>응용</b>주문 사용 사례</span><strong><b>도메인</b>가격·재고 규칙</strong><span><b>인프라</b>DB · 메시지</span><i>소스 의존은 안쪽 규칙으로</i></div><figcaption><strong>논리적 계층, 프로세스 경계, 배포 경계와 네트워크 경계는 각각 따로 결정해요</strong><ul class="picture-key"><li><b>계층</b>책임과 허용된 의존을 정리해요.</li><li><b>배포</b>함께 출시하고 되돌리는 단위예요.</li><li><b>런타임</b>프로세스와 네트워크 경계를 정해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'모놀리스는 함께 배포하고 마이크로서비스는 경계를 원격 호출과 운영 단위로 만들어요',html:`<p>잘 나눈 모듈형 모놀리스는 한 프로세스 안에서 빠른 호출과 하나의 거래를 사용하며 개발·배포가 단순할 수 있어요. 마이크로서비스는 업무 능력별 독립 배포와 확장을 돕지만 원격 실패, 지연, 서비스 발견, 분산 추적, 데이터 일관성과 버전 관리가 필요해요. 시스템이 작고 팀이 하나라면 분리 비용이 이득보다 클 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="monolith-services-visual" aria-label="한 배포 안 주문 재고 알림 모듈과 각각 독립 배포 및 데이터 저장소를 가진 세 서비스를 비교"><div><b>모듈형 모놀리스</b><span>한 배포</span><i>주문 | 재고 | 알림</i><strong>내부 호출 · 거래 1개 가능</strong></div><div><b>마이크로서비스</b><span>Order</span><span>Inventory</span><span>Notify</span><strong>독립 배포 · 원격 실패</strong></div></div><figcaption><strong>서비스 수가 많다는 사실만으로 책임 경계가 좋아지는 것은 아니며 잘못 나누면 분산된 결합이 생겨요</strong><ul class="picture-key"><li><b>모놀리스</b>한 단위로 배포해도 내부 모듈은 나눌 수 있어요.</li><li><b>서비스</b>경계를 독립 배포와 데이터 소유권으로 강화해요.</li><li><b>비용</b>네트워크와 운영 복잡성이 추가돼요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'같은 주문을 모놀리스·서비스·이벤트 구조로 실행하고 장애 뒤 상태를 확인해요',html:`<p>정상 흐름은 모두 주문 완료·재고 예약·알림 전송 결과를 낼 수 있어요. 하지만 모놀리스의 내부 원격 경계는 0개이고 분리 서비스 예제는 2개예요. 재고 장애는 주문 성공으로 숨기지 않고, 알림을 필수로 볼지 별도 재시도로 볼지 정책에 따라 남는 상태가 달라져요.</p>`,lab:'architecture-tradeoff'},
 {id:'b04',title:'이벤트 기반 구조는 생산자와 소비자를 시간적으로 분리해 독립 반응을 추가해요',html:`<p>주문 서비스는 <code>OrderCreated</code> 사건을 발행하고 재고·알림·분석 소비자가 각자 처리할 수 있어요. 생산자는 누가 구독하는지 몰라도 새 소비자를 추가할 수 있지만, 완료 시점이 흩어져 최종 일관성, 중복, 순서, 실패 재처리와 상관관계 추적을 설계해야 해요. 단순한 즉시 요청·응답에는 브로커 비용이 불필요할 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="event-architecture-visual" aria-label="주문 생산자가 이벤트 브로커에 OrderCreated를 발행하고 재고 알림 분석 소비자가 독립적으로 처리"><span><b>Order</b>OrderCreated</span><i>발행</i><strong>Event<br>Broker</strong><i>구독</i><div><span>Inventory</span><span>Notify</span><span>Analytics</span></div><em>각 소비자의 완료 시점은 다를 수 있음</em></div><figcaption><strong>느슨한 연결은 책임이 사라진다는 뜻이 아니며 전달·중복·관측 책임이 메시지 경계에 생겨요</strong><ul class="picture-key"><li><b>생산자</b>사건을 기록하고 발행해요.</li><li><b>소비자</b>자기 속도로 독립 처리해요.</li><li><b>추적</b>상관관계 ID로 한 업무 흐름을 연결해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'설계 패턴은 반복되는 변경 문제에 이름을 붙인 선택지예요',html:`<p><strong>전략 패턴</strong>은 할인 계산처럼 하나의 자리에 여러 알고리즘을 교체해 넣고, <strong>관찰자 패턴</strong>은 사건 하나에 여러 반응을 연결해요. 패턴 이름을 먼저 고르면 작은 조건문을 불필요한 클래스와 간접 호출로 만들 수 있어요. 실제 변경 요구와 참가자 관계, 실패 정책을 먼저 적어요.</p><figure class="teaching-figure concept-figure"><div class="patterns-problem-visual" aria-label="전략 패턴은 할인 정책 하나를 회원 계절 쿠폰 전략으로 교체하고 관찰자 패턴은 주문 사건을 알림 통계 적립 반응으로 전달"><div><b>전략 Strategy</b><strong>가격 계산</strong><span>회원 할인</span><span>쿠폰 할인</span><span>시즌 할인</span></div><div><b>관찰자 Observer</b><strong>주문 사건</strong><span>알림</span><span>통계</span><span>포인트</span></div></div><figcaption><strong>패턴의 가치는 이름이 아니라 어떤 변화와 협력을 국소화하는지에 있어요</strong><ul class="picture-key"><li><b>전략</b>같은 목적의 알고리즘을 교체해요.</li><li><b>관찰자</b>발행자와 여러 반응을 분리해요.</li><li><b>비용</b>객체·약속·디버깅 경로가 늘 수 있어요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'아키텍처는 품질 시나리오와 실패 사례를 놓고 비교해요',html:`${table(['질문','모듈형 모놀리스가 유리할 수 있는 조건','분리·이벤트 구조가 유리할 수 있는 조건'],[['변경·배포','작은 팀이 기능을 함께 출시','업무 영역별 팀이 독립적으로 자주 배포'],['성능·통신','낮은 지연의 내부 호출과 한 거래','비동기 처리와 영역별 독립 확장'],['데이터 일관성','한 저장소 거래가 핵심','영역별 데이터 자율성과 수렴 허용'],['장애 격리','단순한 복구와 적은 움직이는 부품','부분 장애 격리와 독립 용량 조정'],['운영 역량','간단한 배포·로그·디버깅 필요','자동화·관측·메시징 경험 충분']])}<p>“주문 API p95 200ms”, “알림 장애에도 주문은 접수”, “재고는 중복 예약 금지”처럼 자극·환경·측정 가능한 반응을 품질 시나리오로 적어요. 한 목표를 개선하는 선택이 다른 목표의 비용을 높일 수 있으므로 결정과 근거를 기록하고 실제 운영 결과로 다시 검토해요.</p>`}
 ],questions:[
 {q:'계층 구조와 배포 구조에 대해 맞는 설명은?',options:['여러 논리 계층이 하나의 배포 안에 있을 수 있어요.','계층 하나마다 반드시 물리 서버가 필요해요.','도메인 계층은 항상 DB 제품을 직접 알아야 해요.'],answer:0,feedback:['맞아요. 책임 분리와 배포 분리는 다른 결정이에요.','논리적 계층을 서버 수와 같게 볼 수 없어요.','도메인 규칙이 바깥 기술에 묶일 수 있어요.'],review:'b01'},
 {q:'마이크로서비스로 분리할 때 새로 생기는 대표 비용은?',options:['원격 실패·지연·분산 관측과 데이터 일관성 처리','모든 네트워크 호출의 완전한 제거','항상 하나의 로컬 거래로 전체 변경 확정'],answer:0,feedback:['맞아요. 독립 배포의 대가로 분산 시스템 비용이 생겨요.','서비스 사이는 네트워크 호출이 늘 수 있어요.','서비스별 데이터는 한 로컬 거래로 묶이지 않을 수 있어요.'],review:'b02'},
 {q:'이벤트 기반 구조에서 주문 발행 직후 가능한 상태는?',options:['재고와 알림 소비자가 아직 처리 중일 수 있어요.','모든 소비자가 반드시 같은 순간 완료해요.','중복과 순서 문제를 고려할 필요가 없어요.'],answer:0,feedback:['맞아요. 소비자는 각자 속도로 처리해 최종 수렴 구간이 생겨요.','완료 시점은 서로 다를 수 있어요.','재전달과 병렬 소비 때문에 별도 규칙이 필요해요.'],review:'b04'}
 ],summary:['계층·프로세스·배포·네트워크 경계는 서로 다른 설계 결정이에요.','모놀리스·마이크로서비스·이벤트 구조는 독립성의 이점과 분산·운영 비용을 교환해요.','품질 시나리오와 중간 장애 뒤 상태로 구조와 패턴의 적합성을 평가해요.'],nextQuestion:'선택한 설계가 요구사항과 경계 조건을 계속 지키는지 어떤 테스트로 증명할까요?',sources:[['Azure Architecture Center · Architecture Styles','https://learn.microsoft.com/en-us/azure/architecture/guide/architecture-styles/'],['Azure Architecture Center · Event-driven Style','https://learn.microsoft.com/en-us/azure/architecture/guide/architecture-styles/event-driven'],['Martin Fowler · Microservice Trade-Offs','https://martinfowler.com/articles/microservice-trade-offs.html'],['CMU SEI · Quality Attributes','https://www.sei.cmu.edu/library/quality-attributes/']]
};
})();
