(()=>{
const {table}=CS.helpers;
CS.lessons['ch23-l01']={
 lead:'테스트는 “몇 번 실행해 보니 됐다”를 넘어, 어느 범위에서 어떤 조건을 지켜야 하는지 실행 가능한 예로 기록하는 일이에요. 정상값뿐 아니라 경계·실패·상태 변화를 의도적으로 선택해야 해요.',
 goals:['단위·통합·시스템 테스트의 범위와 발견하기 쉬운 문제를 구별해요.','경계값·동등 분할·상태 전이로 적은 수의 의미 있는 사례를 만들어요.','예시 결과와 불변조건 검사를 결합해 값이 사라지는 정렬 버그를 찾아요.'],prerequisites:['ch07-l01','ch11-l01','ch22-l01'],sections:[
 {id:'b01',title:'테스트 범위가 커질수록 실제 연결을 많이 보지만 원인과 실행 비용도 커져요',html:`<p><strong>단위 테스트</strong>는 작은 함수나 모듈의 규칙을 빠르게 확인해요. <strong>통합 테스트</strong>는 데이터베이스·파일·서비스처럼 두 부분 이상의 실제 약속이 맞는지 보고, <strong>시스템 테스트</strong>는 배포된 흐름을 사용자 관점에서 확인해요. 이름보다 격리 범위와 실제로 연결한 구성 요소를 기록하는 편이 정확해요.</p><figure class="teaching-figure concept-figure"><div class="test-scope-visual" aria-label="많고 빠른 작은 단위 테스트 위에 통합 테스트와 적지만 넓은 시스템 테스트가 쌓인 구조"><div class="system"><b>시스템</b><span>브라우저 → 서버 → DB</span><em>넓음 · 느림 · 원인 추적 어려움</em></div><div class="integration"><b>통합</b><span>저장소 ↔ 실제 DB</span></div><div class="unit"><b>단위</b><span>가격 규칙 · 정렬 조건 · 파서</span><em>작음 · 빠름 · 정확한 원인</em></div></div><figcaption><strong>한 종류가 다른 종류를 완전히 대체하지 않으며 위험이 있는 경계마다 알맞은 범위를 조합해요</strong><ul class="picture-key"><li><b>단위</b>규칙과 경계값을 빠르게 많이 확인해요.</li><li><b>통합</b>형식·쿼리·프로토콜 약속을 확인해요.</li><li><b>시스템</b>실제 배포 흐름의 중요한 경로를 확인해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'동등 분할로 대표값을 고르고 경계 바로 아래·같음·바로 위를 검사해요',html:`<p>입력 영역에서 같은 동작을 기대하는 값들을 묶으면 모든 값을 시험하지 않고 대표값을 고를 수 있어요. 그러나 비교 연산자와 길이 제한처럼 동작이 바뀌는 경계에서는 한 칸 아래, 경계값, 한 칸 위가 서로 다른 결함을 드러내요. 정상 영역뿐 아니라 빈값, 형식 오류, 최대값 초과도 별도 부류예요.</p><figure class="teaching-figure concept-figure"><div class="boundary-partition-visual" aria-label="무료 배송 기준 10000원을 중심으로 9999 10000 10001을 검사하고 빈값과 잘못된 형식을 별도 입력 부류로 둠"><div><span>유료 배송 영역</span><b>9,999</b></div><strong>10,000<br>경계</strong><div><b>10,001</b><span>무료 배송 영역</span></div><em>별도 부류 · 빈값 · 문자 · 음수</em></div><figcaption><strong>경계는 숫자뿐 아니라 배열 길이, 날짜 전환, 권한 단계, 상태 전이에도 있어요</strong><ul class="picture-key"><li><b>대표값</b>같은 동작을 하는 영역에서 골라요.</li><li><b>경계값</b>비교와 인덱스 실수를 잘 드러내요.</li><li><b>실패 입력</b>정상값으로 몰래 바꾸지 않고 거부 규칙을 확인해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'정렬 여부와 항목 보존을 따로 검사해 중복이 사라지는 버그를 찾아요',html:`<p>입력 <code>[2,1,2]</code>를 Set으로 만든 뒤 정렬하면 출력 <code>[1,2]</code>는 오름차순이지만 2 하나가 사라져요. “정렬돼 있다”만 검사하면 통과하므로 출력의 값과 개수가 입력의 다중집합과 같은지도 확인해야 해요. 수정 함수와 빈 배열·원소 하나 사례도 비교하세요.</p>`,lab:'test-invariants'},
 {id:'b04',title:'상태가 있는 기능은 값 목록보다 허용된 전이와 금지된 전이를 검사해요',html:`<p>주문은 생성됨→결제됨→배송됨처럼 상태를 가져요. 결제 전 배송이나 취소 뒤 결제처럼 금지된 전이가 거부되는지도 테스트해야 해요. 한 상태에서 같은 요청을 반복했을 때 중복 효과가 없는지, 실패 뒤 어느 상태가 남는지도 중요해요.</p><figure class="teaching-figure concept-figure"><div class="state-test-visual" aria-label="주문 생성 결제 배송 완료의 정상 전이와 생성에서 바로 배송 및 취소 후 결제의 금지 전이"><span><b>생성</b></span><i>pay</i><span><b>결제</b></span><i>ship</i><span><b>배송</b></span><i>deliver</i><strong>완료</strong><div><em>생성 → 배송 ✕</em><em>취소 → 결제 ✕</em><em>pay 재시도 → 중복 결제 ✕</em></div></div><figcaption><strong>상태 전이 테스트는 결과값뿐 아니라 이전 상태·행동·다음 상태의 조합을 검증해요</strong><ul class="picture-key"><li><b>정상 전이</b>허용된 순서가 원하는 상태를 만들어요.</li><li><b>금지 전이</b>오류 뒤 기존 상태가 보존돼요.</li><li><b>반복</b>재시도와 중복 요청의 효과를 확인해요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'속성 기반 테스트는 많은 입력에서 항상 지켜야 할 규칙과 작은 반례를 찾아요',html:`<p>예시 기반 테스트는 <code>[2,1,2] → [1,2,2]</code>처럼 기대 결과를 정확히 적어요. 속성 기반 테스트는 여러 배열을 생성해 “출력은 정렬됨”, “길이와 항목 개수가 보존됨”, “두 번 정렬해도 같음” 같은 불변조건을 검사해요. 실패하면 도구는 보통 문제를 재현하는 더 작은 입력으로 줄여 줘요.</p><figure class="teaching-figure concept-figure"><div class="property-test-visual" aria-label="입력 생성기가 여러 배열을 정렬 함수에 보내 불변조건을 검사하고 실패 입력을 2 1 2로 축소"><span><b>입력 생성</b>[ ] · [7] · [3,1] · [2,1,2] …</span><i>→</i><strong>정렬 함수</strong><i>→</i><div><b>속성 검사</b><span>오름차순</span><span>다중집합 보존</span><span>멱등성</span></div><em>실패 반례 축소 → [0,0]</em></div><figcaption><strong>무작위 호출 횟수만 늘리는 것이 아니라 의미 있는 생성 범위와 참이어야 할 속성을 정의해야 해요</strong><ul class="picture-key"><li><b>생성기</b>정상·경계·특수 형태를 만들어요.</li><li><b>속성</b>모든 유효 입력에 지킬 규칙이에요.</li><li><b>축소</b>원인을 보기 쉬운 작은 반례를 찾아요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'테스트 대역은 통제와 관찰을 돕지만 실제 연동 확인을 없애지 않아요',html:`${table(['대역·환경','주요 목적','놓칠 수 있는 것'],[['Stub','준비한 응답을 반환해 실패·경계 상황 재현','실제 API 형식·지연·인증 변화'],['Fake','메모리 DB처럼 가벼운 동작 구현','실제 DB 제약·쿼리·거래 차이'],['Spy','호출 횟수와 인자를 기록','최종 사용자 결과가 맞는지'],['Mock','예상한 상호작용 순서·횟수 확인','내부 구현에 테스트가 강하게 묶일 수 있음'],['실제 연동 환경','제품의 형식·구성·실패를 확인','느린 실행·데이터 준비·불안정성']])}<p>대역으로 핵심 정책을 빠르게 검증하고, 실제 경계와 다른 점이 큰 곳에는 계약·통합 테스트를 둬요. 테스트 자체가 구현을 그대로 복사하면 같은 오해를 반복할 수 있으므로 요구사항과 독립된 예시·불변조건으로 기대값을 만들어요.</p>`}
 ],questions:[
 {q:'[2,1,2]를 [1,2]로 만든 결과가 오름차순 검사를 통과했다면 무엇을 더 검사해야 할까요?',options:['입력 항목과 개수가 모두 보존됐는지','첫 값이 1인지 한 번만 확인','함수 이름에 sort가 포함됐는지'],answer:0,feedback:['맞아요. 다중집합 보존 조건이 중복 손실을 찾아요.','한 예시의 첫 값만으로 전체 정확성을 알 수 없어요.','이름은 실행 결과를 보장하지 않아요.'],review:'b03'},
 {q:'10,000원 이상 무료 배송 규칙의 좋은 경계 사례 묶음은?',options:['9,999·10,000·10,001원','1·2·3원만','20,000원 하나만'],answer:0,feedback:['맞아요. 경계 바로 아래·같음·위의 비교 결과를 확인해요.','기준점 주변 결함을 놓쳐요.','정상 영역 한 값만 확인해요.'],review:'b02'},
 {q:'테스트 대역을 사용해도 실제 통합 테스트가 필요한 이유는?',options:['대역이 실제 형식·제약·네트워크 동작과 다를 수 있기 때문이에요.','대역은 언제나 실제 시스템보다 느리기 때문이에요.','단위 테스트는 어떤 규칙도 확인하지 못하기 때문이에요.'],answer:0,feedback:['맞아요. 경계의 실제 약속을 별도로 확인해요.','대역은 보통 빠르고 통제하기 쉬워요.','단위 테스트는 핵심 규칙에 유용해요.'],review:'b06'}
 ],summary:['단위·통합·시스템 테스트는 서로 다른 범위와 결함을 다뤄요.','동등 분할·경계값·상태 전이로 의미 있는 정상·실패 사례를 선택해요.','예시 기대값과 불변조건을 함께 검사하고 대역과 실제 연동의 차이를 확인해요.'],nextQuestion:'테스트가 실패했을 때 로그와 중단점으로 원인을 어떻게 좁히고 수정이 새 오류를 만들지 않았는지 확인할까요?',sources:[['Google Testing Blog · Test Sizes','https://testing.googleblog.com/2010/12/test-sizes.html'],['Hypothesis · Property-based Testing Documentation','https://hypothesis.readthedocs.io/'],['Node.js · Test Runner','https://nodejs.org/api/test.html']]
};

CS.lessons['ch23-l02']={
 lead:'디버깅은 코드를 무작정 바꾸는 작업이 아니라 실패를 재현하고, 원인 가설을 세우고, 관측으로 좁힌 뒤, 최소 수정과 회귀 검사로 증거를 쌓는 과정이에요.',
 goals:['재현·가설·관측·수정·회귀의 디버깅 순서를 설명해요.','로그·중단점·호출 스택이 제공하는 증거를 구별해요.','정적 분석·리뷰·성능·접근성을 포함한 품질 기준을 설명해요.'],prerequisites:['ch16-l01','ch18-l01','ch23-l01'],sections:[
 {id:'b01',title:'먼저 같은 실패를 다시 만들고 기대와 실제가 처음 갈라지는 지점을 찾아요',html:`<p>재현 절차에는 입력, 시작 상태, 환경, 실제 결과와 기대 결과를 적어요. “가끔 안 됨”을 가장 작은 사례로 줄이면 반복 속도가 빨라지고 관련 없는 원인을 제외할 수 있어요. 그다음 하나의 가설을 세우고 로그나 중단점으로 확인한 뒤 수정해요.</p><figure class="teaching-figure concept-figure"><div class="debug-cycle-visual" aria-label="실패 재현에서 가설 관측 원인 수정 회귀로 이어지고 회귀 실패 시 다시 재현으로 돌아가는 순환"><span><b>1 재현</b>10,000원만 실패</span><i>→</i><span><b>2 가설</b>비교 연산자</span><i>→</i><span><b>3 관측</b>false 확인</span><i>→</i><span><b>4 수정</b>> → >=</span><i>→</i><strong>5 회귀<br>세 값 통과</strong></div><figcaption><strong>증거 없이 여러 곳을 한꺼번에 고치면 어떤 변경이 문제를 해결했는지 알기 어려워져요</strong><ul class="picture-key"><li><b>재현</b>반복 가능한 입력과 절차를 고정해요.</li><li><b>가설</b>관측으로 틀릴 수 있는 설명을 세워요.</li><li><b>회귀</b>수정한 사례와 주변 기능을 다시 검사해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'로그는 시간 흐름을 남기고 중단점은 순간 값을 멈춰 보며 호출 스택은 경로를 보여줘요',html:`<p>구조화 로그에는 사건 이름, 시각, 요청 ID와 필요한 상태를 남겨 여러 구성 요소의 흐름을 연결해요. 중단점은 특정 줄·조건·예외·네트워크 요청에서 실행을 멈추고 현재 변수와 스코프를 살펴요. 호출 스택은 현재 함수가 어떤 호출들을 거쳐 왔는지 보여줘 원인 위치를 좁혀요.</p><figure class="teaching-figure concept-figure"><div class="debug-tools-visual" aria-label="요청 ID가 있는 로그 시간선과 조건부 중단점에서의 변수 값 및 main checkout shipping 호출 스택"><div><b>로그</b><span>req-7 checkout</span><span>req-7 price=10000</span><span>req-7 fee=3000</span></div><div><b>중단점</b><span>price: 10000</span><span>price > 10000: false</span></div><div><b>호출 스택</b><span>shippingFee</span><span>checkout</span><span>click handler</span></div></div><figcaption><strong>민감 정보와 불필요한 전체 객체를 로그에 남기지 않고 질문에 필요한 증거를 선택해요</strong><ul class="picture-key"><li><b>로그</b>실행이 지나간 뒤의 사건을 연결해요.</li><li><b>중단점</b>현재 변수와 분기 결과를 관찰해요.</li><li><b>스택</b>현재 위치까지 온 호출 경로를 보여줘요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'10,000원 경계에서 실패를 재현하고 비교식을 수정한 뒤 세 값을 회귀 검사해요',html:`<p>요구사항은 10,000원 이상이면 배송비 0원이고 그 아래는 3,000원이에요. 초기 구현 <code>price &gt; 10000</code>은 9,999원과 10,001원에서는 맞지만 정확히 10,000원에서 실패해요. 비교 결과를 관측하고 <code>&gt;=</code>로 고친 뒤 세 사례를 다시 실행하세요.</p>`,lab:'boundary-debugging'},
 {id:'b04',title:'최소 재현 사례는 수정 뒤 영구 회귀 테스트가 되어 같은 결함의 재등장을 막아요',html:`<p>큰 주문 화면 전체가 아니라 <code>shippingFee(10000)</code> 하나로 실패를 줄이면 원인을 빠르게 볼 수 있어요. 수정한 뒤 이 사례를 테스트 모음에 남기고, 양옆 경계와 기존 정상 사례도 함께 실행해요. 테스트가 실패했는데 기대값만 현재 구현에 맞춰 바꾸면 결함을 숨길 수 있어 요구사항 근거를 확인해야 해요.</p><figure class="teaching-figure concept-figure"><div class="minimal-regression-visual" aria-label="복잡한 주문 화면 실패를 shippingFee 10000 최소 사례로 줄이고 수정 뒤 9999 10000 10001 회귀 묶음에 추가"><div><b>큰 실패</b><span>장바구니+쿠폰+로그인+배송</span></div><i>축소</i><strong>shippingFee(10000)<br>기대 0 · 실제 3000</strong><i>수정 뒤</i><div><b>회귀 묶음</b><span>9999 ✓</span><span>10000 ✓</span><span>10001 ✓</span></div></div><figcaption><strong>재현에 필요 없는 조건을 하나씩 제거하되 실패 원인은 그대로 남겨요</strong><ul class="picture-key"><li><b>최소성</b>원인과 무관한 상태를 줄여요.</li><li><b>고정</b>실패 입력을 자동 테스트로 보존해요.</li><li><b>주변 검사</b>수정이 인접 동작을 깨지 않았는지 봐요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'정적 분석·타입 검사·코드 리뷰는 실행 전 서로 다른 결함 신호를 찾아요',html:`<p>린터는 의심스러운 문법과 규칙 위반을, 타입 검사는 값의 가능한 형태와 잘못된 사용을 찾아요. 정적 분석은 자원 누수나 도달 경로 같은 더 넓은 문제를 검사할 수 있어요. 코드 리뷰는 요구사항, 이름, 경계, 보안과 유지보수성을 사람의 맥락으로 확인해요. 어느 하나도 실행 테스트를 완전히 대체하지 않아요.</p><figure class="teaching-figure concept-figure"><div class="static-review-visual" aria-label="소스 코드가 린터 타입 검사 정적 분석 자동 검사와 사람 코드 리뷰를 거쳐 실행 테스트로 이어짐"><strong>Source<br>Change</strong><i>→</i><div><span><b>Lint</b>규칙·의심 문법</span><span><b>Type</b>값의 형태</span><span><b>Static</b>경로·자원</span></div><i>+</i><div><span><b>Review</b>요구·설계·보안</span><span><b>Tests</b>실행 결과</span></div></div><figcaption><strong>품질 도구는 결함이 없음을 증명하는 도장이 아니라 서로 다른 종류의 피드백을 빠르게 주는 장치예요</strong><ul class="picture-key"><li><b>자동 검사</b>반복 가능한 규칙을 빠르게 확인해요.</li><li><b>리뷰</b>설계 의도와 읽기 어려운 부분을 질문해요.</li><li><b>실행</b>실제 환경에서 나타나는 결과를 확인해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'소프트웨어 품질은 정답뿐 아니라 성능·보안·사용성·접근성·운영성을 함께 봐요',html:`${table(['품질 관점','확인 질문','관찰 예'],[['기능 정확성','요구한 결과와 오류 처리가 맞나요?','불변조건·경계값·상태 전이'],['신뢰성·복구','일부 실패 뒤 안전하게 계속하거나 회복하나요?','재시도·중복·백업·복구 시간'],['성능·효율','목표 부하에서 지연과 자원 사용이 맞나요?','p95 지연·처리량·메모리'],['보안·개인정보','권한과 데이터가 신뢰 경계에서 보호되나요?','인가 실패·민감 로그·의존성 검토'],['사용성·접근성','다양한 사용자가 기능을 이해하고 조작하나요?','키보드·이름·대비·오류 안내'],['유지보수·운영','변경·관측·배포·되돌리기가 가능한가요?','테스트 시간·로그·경보·롤백']])}<p>모든 지표를 최대화할 수는 없어요. 중요한 사용자와 환경, 자극, 측정 가능한 반응을 시나리오로 정하고 자동 검사와 실제 사용자·운영 관찰을 함께 사용해요.</p>`}
 ],questions:[
 {q:'디버깅을 시작할 때 가장 먼저 할 일은?',options:['실패 입력·상태·환경과 기대·실제를 기록해 재현해요.','관련 있어 보이는 코드를 모두 동시에 바꿔요.','테스트의 기대값을 실제 결과에 맞춰요.'],answer:0,feedback:['맞아요. 반복 가능한 재현이 가설과 관측의 기준이 돼요.','원인을 확인하기 어려워져요.','요구사항이 맞는지 먼저 확인해야 해요.'],review:'b01'},
 {q:'중단점에서 주로 확인할 수 있는 것은?',options:['그 순간의 변수·스코프·분기 결과와 호출 스택','모든 미래 사용자의 행동','코드 리뷰 의견의 자동 합의'],answer:0,feedback:['맞아요. 실행을 멈추고 현재 상태와 경로를 관찰해요.','실행 도구가 미래 행동을 알 수는 없어요.','리뷰는 별도의 사람 협력 과정이에요.'],review:'b02'},
 {q:'10,000원 경계 버그를 고친 뒤 적절한 행동은?',options:['9,999·10,000·10,001원과 기존 테스트를 다시 실행해요.','실패했던 10,000원 테스트를 삭제해요.','브라우저에서 한 번 성공하면 모든 검증을 끝내요.'],answer:0,feedback:['맞아요. 수정 사례와 인접 경계를 회귀 검사해요.','실패 입력은 재발을 막는 중요한 사례예요.','다른 경로와 환경에서 회귀가 생길 수 있어요.'],review:'b04'}
 ],summary:['디버깅은 재현·가설·관측·수정·회귀의 증거 중심 순환이에요.','로그·중단점·호출 스택과 최소 재현 사례로 기대와 실제가 갈라지는 지점을 좁혀요.','정적 검사·리뷰·실행 테스트와 성능·보안·접근성·운영 지표를 함께 사용해요.'],nextQuestion:'검증된 프로그램을 다른 환경에 안전하게 배포하고 실제 장애를 빠르게 발견·복구하려면 무엇이 필요할까요?',sources:[['Chrome DevTools · Debug JavaScript','https://developer.chrome.com/docs/devtools/javascript/'],['Chrome DevTools · Breakpoints Reference','https://developer.chrome.com/docs/devtools/javascript/breakpoints/'],['TypeScript Handbook','https://www.typescriptlang.org/docs/handbook/intro.html'],['W3C WAI · WCAG 2.2 Quick Reference','https://www.w3.org/WAI/WCAG22/quickref/']]
};
})();
