(()=>{
const {table}=CS.helpers;
CS.lessons['ch24-l01']={
 lead:'배포는 완성된 코드를 서버에 복사하는 한 번의 동작이 아니라 같은 산출물을 검증하고, 적은 사용자부터 노출하고, 관측 결과에 따라 확대하거나 안전한 버전으로 되돌리는 변화 관리 과정이에요.',
 goals:['프로세스·가상 머신·컨테이너의 실행 경계와 공유 자원을 구별해요.','산출물과 환경별 구성을 분리하고 CI/CD의 단계별 검증을 설명해요.','롤링·블루그린·카나리 배포와 롤백의 위험 제어 방식을 비교해요.'],prerequisites:['ch04-l01','ch16-l02','ch23-l02'],sections:[
 {id:'b01',title:'프로세스·가상 머신·컨테이너는 격리하는 경계와 공유하는 자원이 달라요',html:`<p><strong>프로세스</strong>는 운영체제가 실행 중인 프로그램에 메모리·파일 같은 자원을 배정한 단위예요. <strong>가상 머신</strong>은 가상 하드웨어 위에 게스트 운영체제와 커널까지 각각 두고, <strong>컨테이너</strong>는 호스트 커널을 공유하면서 프로세스·파일·네트워크 보기를 격리해요. 컨테이너도 보안 경계와 자원 제한을 올바르게 설정해야 해요.</p><figure class="teaching-figure concept-figure"><div class="runtime-boundaries-visual" aria-label="프로세스 컨테이너 가상 머신이 각각 공유하는 커널과 운영체제 경계 비교"><div><b>프로세스</b><span>앱 A</span><span>앱 B</span><em>같은 OS의 자원 관리</em></div><div><b>컨테이너</b><span>앱+필요 파일</span><span>앱+필요 파일</span><strong>호스트 커널 공유</strong></div><div><b>가상 머신</b><span>앱+게스트 OS</span><span>앱+게스트 OS</span><strong>가상 하드웨어</strong></div></div><figcaption><strong>“가볍다”는 격리가 없다는 뜻이 아니라 게스트 커널을 각각 두지 않는다는 뜻이에요</strong><ul class="picture-key"><li><b>프로세스</b>운영체제가 실행과 자원을 관리해요.</li><li><b>컨테이너</b>격리된 프로세스들이 호스트 커널을 공유해요.</li><li><b>가상 머신</b>각자 운영체제와 커널을 실행해요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'한 번 만든 산출물은 그대로 옮기고 환경별 주소와 비밀값은 밖에서 주입해요',html:`<p>커밋에서 만든 이미지나 패키지를 개발·검증·운영 환경마다 다시 만들면 내용이 달라질 수 있어요. 같은 불변 산출물을 단계별로 승격하고 데이터베이스 주소, 기능 플래그, 비밀키처럼 환경에 따라 달라지는 값만 구성으로 주입해요. 비밀값은 소스 코드와 이미지에 넣지 않고 접근이 통제된 저장소에서 전달해요.</p><figure class="teaching-figure concept-figure"><div class="artifact-config-visual" aria-label="하나의 동일한 앱 산출물이 개발 검증 운영 환경의 서로 다른 구성과 결합"><strong>app:v2.4.1<br>동일 산출물</strong><i>+</i><div><span><b>개발</b>DEV_DB · 테스트 키</span><span><b>검증</b>STAGE_DB · 검증 키</span><span><b>운영</b>PROD_DB · 운영 비밀</span></div><em>코드 변경 없이 구성 주입</em></div><figcaption><strong>어떤 커밋과 빌드가 실행 중인지 식별할 수 있어야 같은 버전을 재현하고 되돌릴 수 있어요</strong><ul class="picture-key"><li><b>산출물</b>코드와 실행 의존성을 묶은 버전이에요.</li><li><b>구성</b>환경마다 달라지는 주소·제한·플래그예요.</li><li><b>비밀</b>소스와 분리하고 최소 권한으로 전달해요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'커밋에서 운영까지 작은 검증 관문을 통과시키고 이력으로 원인을 추적해요',html:`<p>버전 관리는 누가 무엇을 왜 바꿨는지 비교하고 이전 상태를 찾게 해요. CI는 변경마다 빌드·정적 검사·테스트를 같은 절차로 실행하고, CD는 검증된 산출물을 환경에 배치해요. 빠른 검사부터 실제 통합·보안·승인·소규모 운영 관측으로 이어지며 실패한 관문에서는 다음 단계로 넘기지 않아요.</p><figure class="teaching-figure concept-figure"><div class="cicd-pipeline-visual" aria-label="커밋 빌드 단위 테스트 통합 테스트 검증 환경 카나리 운영과 관측 관문"><span><b>Commit</b>변경 이력</span><i>→</i><span><b>Build</b>산출물</span><i>→</i><span><b>Test</b>단위·통합</span><i>→</i><span><b>Stage</b>운영 유사</span><i>→</i><strong>Canary<br>관측 후 확대</strong><em>실패하면 중단 · 같은 산출물 유지</em></div><figcaption><strong>자동화는 무조건 배포하는 장치가 아니라 같은 검증을 빠뜨리지 않게 하는 실행 가능한 절차예요</strong><ul class="picture-key"><li><b>추적</b>커밋·빌드·배포 버전을 연결해요.</li><li><b>관문</b>실패한 변경의 진행을 멈춰요.</li><li><b>승격</b>검증된 동일 산출물을 다음 환경으로 옮겨요.</li></ul></figcaption></figure>`},
 {id:'b04',title:'v2에 10%만 보내 오류를 먼저 발견하고 v1으로 롤백해요',html:`<p>v1은 정상이고 v2는 모든 요청이 실패하는 시나리오예요. 20개 요청 중 매 10번째만 v2로 보내면 v2 요청은 2개, 전체 오류율은 10%이지만 v2 오류율은 100%예요. 버전별 지표로 원인을 분리하고 v2 유입을 0%로 바꾼 뒤 새 요청이 정상인지 확인하세요.</p>`,lab:'canary-deployment'},
 {id:'b05',title:'롤링·블루그린·카나리는 새 버전에 노출되는 범위와 되돌리는 방법이 달라요',html:`<p><strong>롤링</strong>은 이전 인스턴스를 조금씩 줄이며 새 인스턴스를 늘려요. <strong>블루그린</strong>은 두 환경을 준비하고 트래픽 대상을 한 번에 바꿔 빠르게 전환할 수 있지만 자원이 더 필요해요. <strong>카나리</strong>는 일부 사용자나 요청에만 새 버전을 보내 실제 지표를 본 뒤 확대해요. 데이터베이스처럼 되돌리기 어려운 변경은 애플리케이션 롤백과 별도 호환 계획이 필요해요.</p><figure class="teaching-figure concept-figure"><div class="deployment-strategies-visual" aria-label="롤링 블루그린 카나리 배포에서 v1과 v2로 바뀌는 트래픽 범위 비교"><div><b>롤링</b><span>v1 v1 v2 v2</span><em>인스턴스를 점진 교체</em></div><div><b>블루그린</b><span>Blue v1</span><i>스위치</i><span>Green v2</span></div><div><b>카나리</b><span>v1 90%</span><strong>v2 10%</strong><em>지표 확인 뒤 확대</em></div></div><figcaption><strong>전략 이름보다 실패 시 영향 범위, 전환 시간, 추가 자원, 상태 호환성을 함께 판단해요</strong><ul class="picture-key"><li><b>롤링</b>용량을 유지하며 여러 단계로 교체해요.</li><li><b>블루그린</b>준비된 두 환경 사이를 전환해요.</li><li><b>카나리</b>실제 영향의 작은 표본부터 관찰해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'롤백은 버튼 하나가 아니라 되돌릴 수 있는 변경과 확인 절차를 미리 준비하는 일이에요',html:`${table(['시점','준비·판단','확인할 것'],[['배포 전','버전 식별·백업·호환 가능한 DB 변경·중단 기준 정의','이전 버전이 새 스키마에서도 동작하는가?'],['소규모 노출','새 버전과 이전 버전의 오류·지연·핵심 업무 지표 비교','표본 수와 관측 시간이 판단에 충분한가?'],['중단·롤백','새 유입 정지, 이전 버전 전환, 진행 중 작업 보호','사용자 영향이 줄고 새 오류가 멈췄는가?'],['롤백 뒤','데이터 정합성·캐시·큐·외부 호출과 원인 기록','숨은 손상과 재처리 항목이 남았는가?']])}<p>배포 성공은 프로세스가 떴다는 뜻에 그치지 않아요. 사용자 요청이 정상이고 오류·지연·데이터가 목표 범위인지 확인해야 해요. 롤백 자체도 정기적으로 연습해야 실제 장애에서 절차와 권한 문제가 드러나요.</p>`}
 ],questions:[
 {q:'컨테이너와 가상 머신의 대표적인 차이는?',options:['컨테이너는 보통 호스트 커널을 공유하고 VM은 게스트 운영체제와 커널을 가져요.','컨테이너는 프로세스를 실행하지 않아요.','VM만 파일과 네트워크를 격리할 수 있어요.'],answer:0,feedback:['맞아요. 실행 경계와 공유 자원이 달라요.','컨테이너는 격리된 프로세스를 실행해요.','컨테이너도 네임스페이스 등으로 보기를 격리해요.'],review:'b01'},
 {q:'개발·검증·운영 환경에 같은 버전을 배포할 때 좋은 방법은?',options:['동일 산출물을 승격하고 환경별 구성만 안전하게 주입해요.','각 환경에서 소스를 다르게 고쳐 다시 빌드해요.','운영 비밀키를 이미지에 함께 저장해요.'],answer:0,feedback:['맞아요. 산출물 차이를 줄이고 구성은 외부에서 관리해요.','어떤 차이가 원인인지 추적하기 어려워져요.','이미지 유출과 권한 확산 위험이 커져요.'],review:'b02'},
 {q:'카나리에서 전체 오류율 10%, v2 오류율 100%가 함께 관측됐다면 먼저 할 판단은?',options:['v2에 문제가 집중됐는지 확인하고 확대를 멈추거나 롤백해요.','전체 오류율만 보고 v2를 100%로 확대해요.','관측하지 않은 요청은 모두 성공으로 계산해요.'],answer:0,feedback:['맞아요. 버전별 지표로 영향 범위를 분리해요.','실패 버전의 영향만 키우게 돼요.','관측하지 않은 결과는 데이터가 아니에요.'],review:'b04'}
 ],summary:['컨테이너·VM은 실행 격리 경계와 공유 자원이 다르며 목적에 맞게 조합해요.','동일 산출물과 환경별 구성을 분리하고 변경 이력과 단계별 관문을 연결해요.','새 버전은 작은 범위부터 관측하며 데이터 호환까지 포함한 롤백 절차를 준비해요.'],nextQuestion:'배포 뒤 실제 사용자의 장애를 빠르게 발견하고 평균에 숨은 느린 요청과 복구 목표를 어떻게 측정할까요?',sources:[['Docker Docs · What is a container?','https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/'],['Kubernetes · Deployments','https://kubernetes.io/docs/concepts/workloads/controllers/deployment/'],['The Twelve-Factor App · Config','https://12factor.net/config']]
};

CS.lessons['ch24-l02']={
 lead:'운영 중인 시스템은 내부를 관찰할 증거와 장애 때 우선순위를 정할 목표가 필요해요. 로그·지표·추적을 연결하고 사용자 관점의 SLI/SLO와 복구 목표를 실제 관측값과 비교해야 해요.',
 goals:['로그·지표·분산 추적이 답하는 질문과 연결 기준을 구별해요.','평균과 백분위수, SLI와 SLO를 실제 표본에서 해석해요.','RPO·RTO와 발견·완화·복구·회고의 장애 대응 흐름을 설명해요.'],prerequisites:['ch20-l02','ch23-l02','ch24-l01'],sections:[
 {id:'b01',title:'지표가 이상을 알리고 추적이 느린 경로를 좁히며 로그가 사건의 세부 맥락을 보여줘요',html:`<p><strong>지표</strong>는 오류율·지연·요청량처럼 시간에 따른 수치를 집계해 경보와 추세에 적합해요. <strong>분산 추적</strong>은 하나의 요청이 서비스들을 거친 순서와 각 구간 시간을 보여줘요. <strong>로그</strong>는 특정 사건의 상태와 오류 맥락을 남겨요. 요청 ID·trace ID·버전·시각을 연결하면 “무엇이 나빴나”에서 “어느 요청의 어디가 왜 느렸나”로 좁힐 수 있어요.</p><figure class="teaching-figure concept-figure"><div class="observability-signals-visual" aria-label="오류율 경보에서 느린 요청의 추적 경로와 해당 요청 ID의 로그로 좁혀가는 과정"><div><b>Metrics</b><strong>p95 ↑ · error ↑</strong><span>언제 무엇이 나쁜가?</span></div><i>→</i><div><b>Trace · req-7</b><span>web 20ms</span><strong>db 980ms</strong><span>어느 구간인가?</span></div><i>→</i><div><b>Logs · req-7</b><span>pool timeout</span><span>어떤 사건인가?</span></div></div><figcaption><strong>세 신호를 많이 모으는 것보다 같은 요청과 배포 버전으로 연결하고 필요한 기간만 보존하는 설계가 중요해요</strong><ul class="picture-key"><li><b>지표</b>집계된 변화와 경보를 보여줘요.</li><li><b>추적</b>요청의 서비스별 경로와 시간을 보여줘요.</li><li><b>로그</b>사건의 세부 값과 오류 맥락을 남겨요.</li></ul></figcaption></figure>`},
 {id:'b02',title:'평균만 보면 소수의 매우 느린 요청이 겪는 사용자 경험을 숨길 수 있어요',html:`<p>10ms 요청 9개와 1000ms 요청 1개의 평균은 109ms예요. 그러나 가장 가까운 순위법으로 정렬한 p95는 1000ms라 꼬리 지연이 드러나요. 백분위수는 “p95 요청이 정확히 이만큼 걸린다”가 아니라 관측값의 약 95%가 이 값 이하라는 경계예요. 표본 수·기간·성공과 실패 요청의 구분도 함께 기록해야 해요.</p><figure class="teaching-figure concept-figure"><div class="latency-tail-visual" aria-label="10밀리초 요청 아홉 개와 1000밀리초 요청 하나에서 평균 109와 p95 1000 비교"><div><span>10</span><span>10</span><span>10</span><span>10</span><span>10</span><span>10</span><span>10</span><span>10</span><span>10</span><strong>1000ms</strong></div><p><b>평균 109ms</b><em>꼬리 한 개가 압축되어 보임</em></p><p><b>p95 1000ms</b><em>느린 사용자 구간을 드러냄</em></p></div><figcaption><strong>하나의 숫자로 모든 사용 경험을 설명하지 말고 분포와 중요한 백분위수를 함께 봐요</strong><ul class="picture-key"><li><b>평균</b>전체 합을 개수로 나눈 중심값이에요.</li><li><b>p95</b>정렬된 분포의 느린 꼬리를 살펴요.</li><li><b>표본</b>0개일 때는 0ms가 아니라 데이터 없음이에요.</li></ul></figcaption></figure>`},
 {id:'b03',title:'평균·p95를 직접 계산하고 실제 복구 결과를 RPO·RTO 목표와 따로 비교해요',html:`<p>기본 지연 표본의 평균은 109ms이고 p95는 1000ms예요. 마지막 복구 지점 12:00, 장애 12:10, 서비스 복구 12:25라면 실제 데이터 손실 가능 구간은 10분, 실제 복구 시간은 15분이에요. 목표를 엄격하게 또는 완화해 두 값이 각각 충족되는지 비교하고 모순된 시각이 거부되는지도 확인하세요.</p>`,lab:'observability-recovery'},
 {id:'b04',title:'SLI는 사용자 관점의 측정값이고 SLO는 그 측정값에 정한 목표예요',html:`<p><strong>SLI</strong>는 “성공한 요청 비율”, “p95 지연”, “올바른 검색 결과 비율”처럼 사용자 경험을 나타내는 측정 방법과 값이에요. <strong>SLO</strong>는 일정 기간 동안 성공률 99.9%처럼 합의한 목표예요. 100%를 막연히 약속하기보다 허용 가능한 실패 범위인 오류 예산을 두고 배포 속도와 신뢰성 투자의 결정을 연결해요.</p><figure class="teaching-figure concept-figure"><div class="slo-budget-visual" aria-label="1000개 요청 중 SLO 99퍼센트가 허용하는 오류 예산 10개와 실제 오류 7개"><div><b>SLI 측정</b><span>성공 요청 / 전체 유효 요청</span><strong>993 / 1000 = 99.3%</strong></div><i>목표</i><div><b>SLO 99.0%</b><span>허용 실패 10개</span><strong>실제 실패 7개</strong><em>남은 예산 3개</em></div></div><figcaption><strong>좋은 SLI는 서버가 켜졌는지가 아니라 사용자가 의도한 작업을 성공했는지를 가능한 한 가깝게 측정해요</strong><ul class="picture-key"><li><b>SLI</b>사용자 경험을 나타내는 측정 규칙과 값이에요.</li><li><b>SLO</b>기간과 측정 규칙에 정한 목표예요.</li><li><b>오류 예산</b>목표가 허용한 실패 범위예요.</li></ul></figcaption></figure>`},
 {id:'b05',title:'RPO는 되돌아갈 수 있는 데이터 시점이고 RTO는 서비스를 복구할 시간 목표예요',html:`<p><strong>RPO</strong>는 장애 시점에서 얼마나 이전의 데이터까지 잃는 것을 감수할지 정한 복구 시점 목표예요. 백업·복제 주기와 관련돼요. <strong>RTO</strong>는 장애 뒤 서비스 기능을 목표 수준으로 되돌릴 때까지 허용하는 시간이에요. 백업 파일이 있다는 사실만으로 복구가 보장되지 않으므로 실제 복원, 데이터 검증, 권한과 의존 서비스까지 정기적으로 연습해요.</p><figure class="teaching-figure concept-figure"><div class="recovery-objectives-visual" aria-label="마지막 복구 지점에서 장애까지 RPO 구간과 장애에서 서비스 복구까지 RTO 구간"><span><b>12:00</b>마지막 복구 지점</span><i class="rpo">데이터 손실 가능 구간<br><b>실제 10분</b></i><strong><b>12:10</b>장애</strong><i class="rto">서비스 중단 구간<br><b>실제 15분</b></i><span><b>12:25</b>서비스 복구</span></div><figcaption><strong>RPO와 RTO는 목표이고 장애가 끝난 뒤 실제 손실 구간과 복구 시간을 별도로 측정해 비교해요</strong><ul class="picture-key"><li><b>RPO</b>데이터가 어느 시점까지 복구돼야 하는지 정해요.</li><li><b>RTO</b>얼마 안에 기능을 복구할지 정해요.</li><li><b>복구 훈련</b>백업이 실제로 열리고 절차가 시간 안에 끝나는지 검증해요.</li></ul></figcaption></figure>`},
 {id:'b06',title:'장애 대응은 발견·완화·복구·회고를 나누고 사용자 영향부터 줄여요',html:`${table(['단계','핵심 질문','행동과 기록'],[['발견·선언','어떤 사용자가 얼마나 영향을 받나요?','증상·시작 시각·심각도·담당 역할을 공유'],['완화','영향을 가장 빨리 줄일 안전한 행동은?','롤백·기능 차단·트래픽 우회·부하 제한'],['복구·검증','핵심 기능과 데이터가 실제로 정상인가요?','사용자 경로·SLI·큐·정합성을 확인'],['회고·개선','어떤 조건과 방어 실패가 사건을 만들었나요?','비난 없이 시간선·원인·재발 방지·담당자 기록']])}<p>장애 중에는 완벽한 원인 분석보다 사용자 영향을 줄이는 완화가 먼저일 수 있어요. 복구 뒤에는 “누가 실수했나”에 멈추지 않고 감지·배포·검증·권한·절차 중 어떤 방어를 개선할지 실행 항목으로 남겨요.</p>`}
 ],questions:[
 {q:'평균 지연이 양호해 보여도 p95 같은 백분위수를 함께 보는 이유는?',options:['소수의 매우 느린 요청이 평균에 가려질 수 있기 때문이에요.','p95는 언제나 평균보다 작기 때문이에요.','표본이 없어도 p95는 0ms로 계산되기 때문이에요.'],answer:0,feedback:['맞아요. 분포의 느린 꼬리를 별도로 볼 수 있어요.','분포에 따라 다르며 일반적으로 그런 규칙은 없어요.','표본이 없으면 데이터 없음으로 처리해야 해요.'],review:'b02'},
 {q:'RPO 5분과 RTO 20분은 각각 무엇을 뜻하나요?',options:['허용 데이터 손실 시점 목표 5분과 서비스 복구 시간 목표 20분이에요.','복구 시간 5분과 로그 보존 기간 20분이에요.','평균 지연 5분과 p95 지연 20분이에요.'],answer:0,feedback:['맞아요. 두 목표는 데이터 시점과 서비스 시간이라는 다른 축이에요.','RPO는 로그 보존 기간이 아니에요.','둘 다 요청 지연 지표가 아니에요.'],review:'b05'},
 {q:'장애 회고의 가장 적절한 목적은?',options:['시간선과 방어 실패를 이해해 재발 방지 행동을 정해요.','개인의 실수를 공개해 처벌만 결정해요.','관측 기록을 모두 지워 사건을 종료해요.'],answer:0,feedback:['맞아요. 시스템과 절차를 개선할 구체적 항목을 만들어요.','비난은 정보 공유와 학습을 막을 수 있어요.','증거는 원인 이해와 개선 검증에 필요해요.'],review:'b06'}
 ],summary:['지표·추적·로그를 요청·버전·시각으로 연결해 증상에서 원인 후보로 좁혀요.','평균과 백분위수를 함께 보고 사용자 관점 SLI를 기간이 있는 SLO와 비교해요.','RPO·RTO를 실제 결과와 따로 비교하며 발견·완화·복구·회고로 장애를 다뤄요.'],nextQuestion:'이제 24개 대단원을 연결해 하나의 요청이 하드웨어·운영체제·네트워크·데이터·소프트웨어·운영을 지나는 전체 흐름을 설명할 수 있을까요?',sources:[['Google SRE · Monitoring Distributed Systems','https://sre.google/sre-book/monitoring-distributed-systems/'],['Google SRE · Service Level Objectives','https://sre.google/sre-book/service-level-objectives/'],['OpenTelemetry · Signals','https://opentelemetry.io/docs/concepts/signals/'],['AWS Well-Architected · Disaster Recovery Objectives','https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/disaster-recovery-dr-objectives.html']]
};
})();
