(()=>{
'use strict';
const root=CS.learning=CS.learning||{};
const diagram=(item,caseId)=>{
 const body={
  latency:'<div class="case-bars latency-bars"><i style="--v:2"><b>1</b><span>10</span></i><i style="--v:2"><b>2</b><span>10</span></i><i style="--v:2"><b>3</b><span>10</span></i><i style="--v:2"><b>4</b><span>10</span></i><i style="--v:2"><b>5</b><span>10</span></i><i style="--v:2"><b>6</b><span>10</span></i><i style="--v:2"><b>7</b><span>10</span></i><i style="--v:2"><b>8</b><span>10</span></i><i style="--v:2"><b>9</b><span>10</span></i><i class="hot" style="--v:100"><b>10</b><span>1000ms</span></i></div>',
  segments:'<div class="case-segments"><span style="--w:6">네트워크<b>60ms</b></span><span style="--w:6">서버<b>60ms</b></span><span class="hot" style="--w:88">DB<b>880ms</b></span></div>',
  plan:'<div class="case-plan"><span>같은 WHERE<br><b>결과 1행</b></span><i>→</i><span>SCAN ↔ SEARCH<br><b>접근 계획</b></span><i>→</i><span>같은 조건 재측정<br><b>실제 시간</b></span></div>',
  storage:'<div class="case-storage"><span>작업 메모리<small>전원·새 문서에서 소실</small></span><i>→ 저장</i><span>확정 저장<small>커밋 경계 확인</small></span><i>⇢ 복제</i><span>복제본<small>최신 버전 확인</small></span></div>',
  wal:'<div class="case-wal"><span>UPDATE 100→120<b>내구화</b></span><i></i><span>COMMIT<b>내구화 전/후</b></span><i></i><span>장애·복구<b>100 또는 120</b></span></div>',
  recovery:'<div class="case-timeline"><span><b>12:00</b>복구 지점</span><i>RPO 관측 10분</i><strong><b>12:10</b>장애</strong><i>RTO 관측 15분</i><span><b>12:25</b>서비스 복구</span></div>',
  servers:'<div class="case-servers"><span><i style="--load:100"></i><b>96 / 40</b><small>56 초과</small></span><span><i style="--load:30"></i><b>12 / 40</b><small>28 여유</small></span><span><i style="--load:30"></i><b>12 / 40</b><small>28 여유</small></span></div>',
  queue:'<div class="case-flow"><span>생산자<b>8 / 초</b></span><i>→</i><span class="queue-box">대기열<b>+5 / 초</b></span><i>→</i><span>소비자<b>3 / 초</b></span></div>',
  amdahl:'<div class="case-amdahl"><span style="--w:10">직렬 10%<b>그대로</b></span><span style="--w:90">병렬 90%<b>코어에 분배</b></span><em>이상적 상한 10×</em></div>'
 }[item.type]||'';
 return `<figure class="case-diagram" data-diagram="${item.type}" aria-labelledby="${caseId}-${item.type}-title">${body}<figcaption><strong id="${caseId}-${item.type}-title">${item.title}</strong><span>${item.caption}</span></figcaption></figure>`;
};
const lessonLinks=(definition,returnPath,e)=>definition.lessons.map(id=>{const meta=CATALOG.lessons.find(item=>item.id===id);return `<a href="#${id}?caseReturn=${encodeURIComponent(returnPath)}">${e(meta?.title||id)}</a>`;}).join('');
function renderList(main,{escape:e}){
 const model=root.caseModel;
 main.innerHTML=`<article class="case-hub"><header class="case-hero"><div class="section-kicker">배운 원리로 문제 해결하기</div><h1 tabindex="-1">종합 사례</h1><p>한 단원의 정답을 고르는 대신 증상을 관찰하고, 가설을 세우고, 실험 결과로 설명을 고쳐 보세요.</p></header><section class="case-method"><span>관측</span><i>→</i><span>가설</span><i>→</i><span>실험</span><i>→</i><span>판단</span><i>→</i><span>설명</span></section><div class="case-list">${CS.cases.map((definition,index)=>{const state=model.load(definition),progress=model.stageIndex(state.stage)+1;return `<article><div><span>${String(index+1).padStart(2,'0')} · ${e(definition.kicker)}</span><h2>${e(definition.title)}</h2><p>${e(definition.symptom)}</p></div><div class="case-card-foot"><small>${definition.lessons.length}개 단원 · ${definition.labs.length}개 실습</small><strong>${state.completed?'설명 완료':`${progress}/5 단계`}</strong><a class="button-link primary" href="#case/${definition.id}/${state.stage}">${state.updatedAt&&state.stage!=='observe'?'이어서 해결하기':'사례 시작하기'} →</a></div></article>`;}).join('')}</div><aside class="case-note"><strong>사례 기록은 점수가 아니에요.</strong><p>가설을 바꾼 과정과 추가로 확인할 자료를 남기는 것이 목표예요. 접근 순서는 잠그지 않았습니다.</p></aside></article>`;
 main.querySelector('h1')?.focus({preventScroll:true});
}
function renderCase(main,definition,requestedStage,{escape:e,mountLab,getLabHandle,announce,requestedLab}){
 const model=root.caseModel,stage=model.stages.includes(requestedStage)?requestedStage:'observe';let state=model.load(definition);
 if(requestedLab&&definition.labs.includes(requestedLab))state=model.patch(state,{activeLab:requestedLab});
 state=model.patch(state,{stage});
 const life=new AbortController(),at=model.stageIndex(stage),returnPath=`case/${definition.id}/${stage}`,hypothesis=definition.hypotheses.find(item=>item.id===state.hypothesis),previous=model.stages[Math.max(0,at-1)],next=model.stages[Math.min(model.stages.length-1,at+1)];
 const header=`<header class="case-study-head"><a href="#cases">← 종합 사례</a><div class="section-kicker">${e(definition.kicker)}</div><h1 tabindex="-1">${e(definition.title)}</h1><p>${e(definition.symptom)}</p><div class="case-progress" aria-label="사례 진행 단계">${model.stages.map((item,index)=>`<a href="#case/${definition.id}/${item}" class="${index===at?'current ':''}${index<at?'visited':''}"><b>${index+1}</b><span>${['관측','가설','실험','판단','설명'][index]}</span></a>`).join('')}</div></header>`;
 let body='';
 if(stage==='observe')body=`<section class="case-stage"><div class="section-kicker">1 · 증상과 자료</div><h2>먼저 보이는 사실만 적어요</h2><div class="case-observations">${definition.observations.map((item,index)=>`<p><b>${index+1}</b>${e(item)}</p>`).join('')}</div><div class="case-diagrams">${definition.diagrams.map(item=>diagram(item,definition.id)).join('')}</div><aside class="case-cautions"><strong>자료를 읽을 때 지킬 범위</strong><ul>${definition.cautions.map(item=>`<li>${e(item)}</li>`).join('')}</ul></aside></section>`;
 if(stage==='hypothesize')body=`<section class="case-stage"><div class="section-kicker">2 · 원인 후보</div><h2>현재 자료로 가장 먼저 확인할 가설은?</h2><p class="case-instruction">정답을 맞히는 단계가 아니에요. 지금 가진 자료와 연결되는 이유를 적고 실험 뒤 바꿀 수 있어요.</p><fieldset class="case-hypotheses"><legend>가설 하나를 선택해요</legend>${definition.hypotheses.map(item=>`<label><input type="radio" name="case-hypothesis" value="${item.id}" ${state.hypothesis===item.id?'checked':''}><span><b>${e(item.title)}</b><small>실험 뒤 근거·반례·미확인 사항을 구분해요.</small></span></label>`).join('')}</fieldset><label class="case-writing"><span>이 가설을 먼저 확인할 이유 <small>20자 이상</small></span><textarea data-case-field="reason" maxlength="800" rows="5">${e(state.reason)}</textarea></label></section>`;
 if(stage==='experiment'){
  const labId=definition.labs.includes(state.activeLab)?state.activeLab:definition.labs[0],evidence=state.evidence.find(item=>item.labId===labId);
  body=`<section class="case-stage case-experiment"><div class="section-kicker">3 · 비교 실험</div><h2>가설을 구분할 상태를 직접 만들어요</h2>${!state.hypothesis?'<div class="case-missing">아직 가설을 고르지 않았어요. 실험은 할 수 있지만 판단 전에 <a href="#case/'+definition.id+'/hypothesize">가설과 이유를 먼저 남겨 주세요.</a></div>':''}<div class="case-lab-tabs" role="navigation" aria-label="사례 실습 선택">${definition.labs.map(id=>`<a href="#case/${definition.id}/experiment?lab=${id}" class="${id===labId?'active':''}">${e(CS.labs[id]?.title||id)}</a>`).join('')}</div><div class="case-experiment-brief"><strong>이 실험에서 구분할 것</strong><p>${e(definition.experimentNotes[labId])}</p></div><div data-case-lab="${labId}"></div><section class="case-evidence"><h3>사례 근거로 남기기</h3><p>위 비교 미션의 A 또는 B 조건을 실제로 만든 뒤 현재 상태를 기록해요.</p><label class="case-writing"><span>이 상태가 가설 판단에 주는 의미 <small>15자 이상</small></span><textarea data-case-evidence-note maxlength="600" rows="3">${e(evidence?.note||'')}</textarea></label><button type="button" class="primary" data-record-evidence="${labId}">현재 실험 결과 기록</button><output data-evidence-status>${e(evidence?`기록됨 · ${evidence.summary}`:'아직 사례 근거를 기록하지 않았어요.')}</output></section></section>`;
 }
 if(stage==='compare')body=`<section class="case-stage"><div class="section-kicker">4 · 가설과 결과 대조</div><h2>처음 생각을 유지하거나 고쳐요</h2>${hypothesis?`<article class="case-verdict ${hypothesis.verdict}"><span>선택한 가설 · ${e(hypothesis.title)}</span><strong>${hypothesis.verdict==='supported'?'현재 자료가 우선 지지해요':hypothesis.verdict==='conflict'?'현재 자료와 충돌해요':'가능하지만 아직 확정하지 못했어요'}</strong><p>${e(hypothesis.feedback)}</p></article>`:'<div class="case-missing">선택한 가설이 없어요. <a href="#case/'+definition.id+'/hypothesize">가설 단계에서 먼저 골라 주세요.</a></div>'}<div class="case-evidence-list"><h3>내가 기록한 실험 근거</h3>${state.evidence.length?state.evidence.map(item=>`<p><b>${e(CS.labs[item.labId]?.title||item.labId)}</b><span>${e(item.summary||item.note)}</span><small>${e(item.note)}</small></p>`).join(''):'<p class="muted">아직 기록한 실험 근거가 없어요. 실험 단계에서 A 또는 B 조건을 실행해 보세요.</p>'}</div><label class="case-writing"><span>가설을 유지하거나 바꾼 이유 <small>30자 이상</small></span><textarea data-case-field="judgement" maxlength="1000" rows="6">${e(state.judgement)}</textarea></label></section>`;
 if(stage==='explain')body=`<section class="case-stage"><div class="section-kicker">5 · 개선안과 설명</div><h2>관측부터 한계까지 한 흐름으로 설명해요</h2><label class="case-select"><span>먼저 시도할 개선안</span><select data-case-field="improvement"><option value="">선택해 주세요</option>${definition.improvement.map(item=>`<option value="${e(item)}" ${state.improvement===item?'selected':''}>${e(item)}</option>`).join('')}</select></label><label class="case-writing"><span>관측 → 원인 후보 → 실험 결과 → 개선안 → 한계 <small>40자 이상</small></span><textarea data-case-field="explanation" maxlength="1800" rows="9">${e(state.explanation)}</textarea></label><label class="case-writing"><span>추가로 확인할 자료나 지표 <small>20자 이상</small></span><textarea data-case-field="additionalCheck" maxlength="800" rows="4">${e(state.additionalCheck)}</textarea></label><fieldset class="case-final-checks"><legend>내 설명을 스스로 점검해요</legend>${['관측 사실과 추측을 구분했어요.','실험에서 바꾼 조건과 단위를 밝혔어요.','이 결과로 단정할 수 없는 한계를 적었어요.'].map((text,index)=>`<label><input type="checkbox" data-case-check="c${index+1}" ${state.checks[`c${index+1}`]?'checked':''}><span>${text}</span></label>`).join('')}</fieldset><button type="button" class="button-link primary" data-case-complete>설명 기록 완료</button><output class="case-complete-status">${state.completed?'설명 기록을 완료했어요. 자동 이해도 점수는 매기지 않아요.':'세 확인 항목과 서술을 채우면 기록을 완료할 수 있어요.'}</output>${state.completed?`<section class="case-finish"><h3>내 문제 해결 기록</h3><dl><div><dt>확인한 근거</dt><dd>${state.evidence.map(item=>e(item.summary||item.note)).join('<br>')||'기록 없음'}</dd></div><div><dt>처음 가설</dt><dd>${e(definition.hypotheses.find(item=>item.id===state.originalHypothesis)?.title||'기록 없음')}</dd></div><div><dt>마지막 판단</dt><dd>${e(state.judgement)}</dd></div><div><dt>추가로 확인할 것</dt><dd>${e(state.additionalCheck)}</dd></div></dl></section>`:''}</section>`;
 main.innerHTML=`<article class="case-study">${header}${body}<aside class="case-related"><div><strong>연결 단원</strong><span>${lessonLinks(definition,returnPath,e)}</span></div><div><strong>선수 개념</strong><span>${definition.prerequisites.map(e).join(' · ')}</span></div></aside><nav class="case-stage-nav">${at?`<a href="#case/${definition.id}/${previous}">← 이전 단계</a>`:'<a href="#cases">← 사례 목록</a>'}${at<model.stages.length-1?`<button type="button" class="primary" data-case-next="${next}">다음 단계 →</button>`:'<a href="#cases">다른 사례 보기 →</a>'}</nav></article>`;
 const labRoot=main.querySelector('[data-case-lab]');if(labRoot)mountLab(labRoot,labRoot.dataset.caseLab);
 const persistField=target=>{state=model.patch(state,{[target.dataset.caseField]:target.value});};
 main.addEventListener('input',event=>{const field=event.target.closest('[data-case-field]');if(field)persistField(field);},{signal:life.signal});
 main.addEventListener('change',event=>{const radio=event.target.closest('input[name="case-hypothesis"]'),check=event.target.closest('[data-case-check]'),field=event.target.closest('select[data-case-field]');if(radio){state=model.patch(state,{hypothesis:radio.value,originalHypothesis:state.originalHypothesis||radio.value});}if(check){state=model.patch(state,{checks:{...state.checks,[check.dataset.caseCheck]:check.checked}});}if(field)persistField(field);},{signal:life.signal});
 main.addEventListener('click',event=>{
  const nextButton=event.target.closest('[data-case-next]'),recordButton=event.target.closest('[data-record-evidence]'),completeButton=event.target.closest('[data-case-complete]');
  if(nextButton){if(stage==='hypothesize'&&(!state.hypothesis||state.reason.trim().length<20)){announce('가설 하나와 20자 이상의 이유를 먼저 남겨 주세요.');return;}location.hash=`#case/${definition.id}/${nextButton.dataset.caseNext}`;}
  if(recordButton){const note=main.querySelector('[data-case-evidence-note]').value.trim(),handle=getLabHandle?.(recordButton.dataset.recordEvidence);if(note.length<15){announce('실험 결과가 판단에 주는 의미를 15자 이상 적어 주세요.');return;}const current=handle?.read(),capture=current&&(CS.learning.labAdapters.capture(current.lab,current.state,current.parameters,'A')||CS.learning.labAdapters.capture(current.lab,current.state,current.parameters,'B'));if(!capture){announce('비교 미션의 A 또는 B 조건을 실제로 만든 뒤 기록해 주세요.');return;}state=model.record(state,current.lab,note);state.evidence[state.evidence.length-1].summary=capture.summary;state=model.save(state);main.querySelector('[data-evidence-status]').textContent=`기록됨 · ${capture.summary}`;announce('현재 실험 결과를 사례 근거로 기록했어요.');}
  if(completeButton){state=model.complete(state);if(!state.completed){announce('40자 설명, 20자 추가 확인, 세 확인 항목을 모두 채워 주세요.');return;}location.hash=`#case/${definition.id}/explain?completed=1`;announce('사례 설명 기록을 완료했어요.');}
 },{signal:life.signal});
 main.querySelector('h1')?.focus({preventScroll:true});
 return ()=>life.abort();
}
root.caseView={renderList,renderCase};
})();
