(()=>{
const {escape:e,table,integer}=CS.helpers;
const books=[{id:'B01',title:'컴퓨터 첫걸음',stock:2},{id:'B02',title:'자료구조 이야기',stock:0},{id:'B03',title:'컴퓨터 첫걸음',stock:1}],members=[{id:'M1',name:'민지'},{id:'M2',name:'준호'}],loans=[{member:'M1',book:'B02'},{member:'M2',book:'B01'}];
CS.labs['library-query']={custom:true,title:'제목이 같아도 다른 책이에요',type:'브라우저 배열로 만든 DB 구조 모형',intro:'대출 가능 필터를 누르고 원본과 결과를 비교해 보세요. 이어서 키로 연결한 대출 기록을 확인해요.',limit:'아래 조회와 제약 검사는 JavaScript 배열로 구현한 학습 모형이에요. 실제 DBMS는 아니며 새로고침하면 초기화돼요. 수량은 현재 대출 가능한 권수예요.',
 initial(){return {filter:'all',sort:false,linked:false,events:[]};},
 action(s,a){if(a==='reset')return this.initial();const n=structuredClone(s);if(['all','available','none'].includes(a)){n.filter=a;n.events.push(a==='available'?'수량 > 0 조건으로 결과만 골랐어요. 원본 행은 그대로예요.':a==='none'?'수량 > 9 조건을 만족하는 책이 없어요.':'전체 책을 다시 조회했어요.');}else if(a==='sort'){n.sort=!n.sort;n.events.push(n.sort?'결과를 수량 내림차순, 같으면 ID 순으로 정렬했어요.':'결과를 ID 순으로 표시해요.');}else if(a==='link'){n.linked=!n.linked;n.events.push('회원 ID와 도서 ID로 연결해 이름과 제목을 가져와요.');}else if(a==='duplicate')throw Error('기본키 오류: B01은 이미 있어요. 같은 제목은 가능하지만 같은 ID를 다시 넣을 수는 없어요.');else if(a==='missing')throw Error('외래키 오류: 도서 B99가 없어서 대출 기록을 연결할 수 없어요.');else throw Error('알 수 없는 조회예요.');return n;},
 describe(s){return s.events.at(-1)||'원본 도서 3행, 열 3개예요. ID는 B01·B02·B03으로 서로 달라요.';},
 actions(s){return [{id:'all',text:'전체 보기'},{id:'available',text:'대출 가능',primary:true},{id:'none',text:'수량 9 초과'},{id:'sort',text:s.sort?'ID 순으로':'수량 내림차순'},{id:'link',text:s.linked?'연결 접기':'회원·대출 연결'},{id:'duplicate',text:'중복 ID 시도'},{id:'missing',text:'없는 책 연결 시도'},{id:'reset',text:'예시로 초기화'}];},
 render(s){let rows=books.filter(b=>s.filter==='all'||(s.filter==='available'?b.stock>0:b.stock>9));rows.sort(s.sort?(a,b)=>b.stock-a.stock||a.id.localeCompare(b.id):(a,b)=>a.id.localeCompare(b.id));const show=list=>table(['도서 ID · PK','제목','남은 수량'],list.map(b=>[b.id,b.title,b.stock]));return `<h4>원본 · 항상 3행</h4>${show(books)}<h4>조회 결과 · ${rows.length}행</h4>${rows.length?show(rows):'<p>조건에 맞는 행이 없어요. 원본 데이터가 삭제된 것은 아니에요.</p>'}${s.linked?`<h4>대출 기록을 키로 연결</h4>${table(['회원 ID','회원 이름','도서 ID','도서 제목'],loans.map(l=>[l.member,members.find(m=>m.id===l.member).name,l.book,books.find(b=>b.id===l.book).title]))}<p class="small">같은 제목인 B01과 B03도 ID가 달라요. 준호의 기록은 B01을 가리켜요.</p>`:''}`;}
};
CS.labs['loan-transaction']={title:'대출 도중 오류를 넣어 보세요',type:'원자성을 보여 주는 트랜잭션 모형',intro:'작업 중 사본과 확정된 값을 나란히 봐요. 오류 위치를 바꿔 성공과 롤백을 비교해 보세요.',limit:'브라우저 안의 상태 모형이에요. 실제 저장장치에 기록하지 않으며, 동시 트랜잭션·DB 제품별 격리 수준·복구 로그 구현은 생략했어요.',
 fields:[{key:'stock',label:'시작 수량',value:'1',inputmode:'numeric'},{key:'failure',label:'오류 위치',value:'none',options:[{value:'none',label:'오류 없음'},{value:'after-decrement',label:'수량 차감 직후'}]},{key:'member',label:'회원',value:'M1',options:[{value:'M1',label:'M1 · 등록된 회원'},{value:'M9',label:'M9 · 없는 회원'}]},{key:'role',label:'권한',value:'librarian',options:[{value:'librarian',label:'사서 · 조회와 대출'},{value:'reader',label:'방문자 · 조회만'}]}],
 validate(raw){if(!['none','after-decrement'].includes(raw.failure)||!['M1','M9'].includes(raw.member)||!['librarian','reader'].includes(raw.role))throw Error('오류 위치·회원·권한을 목록에서 선택해 주세요.');return {stock:integer(raw.stock,0,1,'시작 수량'),failure:raw.failure,member:raw.member,role:raw.role};},
 initial(p){return {phase:0,committed:{stock:p.stock,loans:0},working:null,events:[],done:false};},
 step(s,p){if(s.done)return s;const n=structuredClone(s);if(n.phase===0){const error=p.role==='reader'?'대출 권한이 없어요.':p.member!=='M1'?'등록되지 않은 회원이에요.':p.stock===0?'남은 책이 없어요.':null;if(error){n.done=true;n.events.push(error+' 확정 데이터는 그대로예요.');}else{n.working=structuredClone(n.committed);n.phase=1;n.events.push('BEGIN · 검사 통과. 작업 중 사본을 준비했어요.');}}
 else if(n.phase===1){n.working.stock--;n.phase=2;n.events.push('작업 중 수량을 1 줄였어요. 아직 확정하지 않았어요.');}
 else if(n.phase===2){if(p.failure==='after-decrement'){n.working=null;n.done=true;n.phase=4;n.events.push('오류 발생 → ROLLBACK. 부분 변경을 버려 확정 수량 1·기록 0을 유지해요.');}else{n.working.loans++;n.phase=3;n.events.push('작업 중 대출 기록을 1건 추가했어요.');}}
 else if(n.phase===3){n.committed=structuredClone(n.working);n.working=null;n.phase=4;n.done=true;n.events.push('COMMIT · 수량 0과 대출 기록 1건을 함께 확정했어요.');}return n;},
 describe(s){return s.events.at(-1)||'확정된 책 1권이 있나요? 조건을 확인하고 대출을 시작해 보세요.';},
 render(s){return table(['영역','남은 수량','대출 기록'],[['확정 상태',s.committed.stock,s.committed.loans+'건'],['작업 중 사본',s.working?.stock??'없음',s.working?s.working.loans+'건':'없음']])+`<p>${s.working?'작업 중인 두 값은 아직 확정 데이터에 반영되지 않았어요.':s.done?'이번 시도는 끝났어요. 입력을 바꾸거나 처음부터 다시 비교해 보세요.':'시작 전 검사를 기다려요.'}</p>`;}
};
})();
