(()=>{
const {escape:e,integer,table}=CS.helpers;
const weights=[128,64,32,16,8,4,2,1];
const utf8Bytes=text=>Array.from(new TextEncoder().encode(text));
CS.helpers.utf8Bytes=utf8Bytes;
CS.labs['bit-byte']={
 title:'8개 스위치로 숫자와 문자를 표현해 보세요',type:'실제 8비트 계산 · UTF-8 인코딩',intro:'스위치를 눌러 자리값의 합을 바꾸고, 같은 문자도 UTF-8에서 몇 바이트가 되는지 비교해요.',limit:'숫자 스위치는 0~255인 부호 없는 8비트 정수 모형이에요. 문자 칸은 브라우저의 TextEncoder로 UTF-8 바이트를 실제 계산해요. 화면에 보이는 글자 수와 코드 포인트 수는 항상 같지 않을 수 있어요.',custom:true,
 initial(){return {bits:[0,0,0,0,0,1,0,1],text:'A가',events:[]};},
 action(s,a,data){if(a==='reset')return this.initial();const n=structuredClone(s);if(a==='bit'){const i=Number(data);if(!Number.isInteger(i)||i<0||i>7)throw Error('0부터 7까지의 비트 위치를 선택해 주세요.');n.bits[i]=n.bits[i]?0:1;n.events.push(`${weights[i]} 자리 스위치를 ${n.bits[i]?'켰어요':'껐어요'}.`);}else if(a==='text'){n.text=String(data).slice(0,20);n.events.push('문자열의 UTF-8 바이트를 다시 계산했어요.');}else if(a.startsWith('preset-')){const value=Number(a.slice(7));if(!Number.isInteger(value)||value<0||value>255)throw Error('0부터 255까지의 예시만 선택할 수 있어요.');n.bits=weights.map(w=>(value&w)?1:0);n.events.push(`${value}을 8비트로 바꿨어요.`);}else throw Error('알 수 없는 스위치 동작이에요.');return n;},
 describe(s){const value=s.bits.reduce((sum,b,i)=>sum+b*weights[i],0),bytes=utf8Bytes(s.text);return `${s.bits.join('')} = ${value} · 입력한 문자열 ${Array.from(s.text).length}개 코드 포인트 = UTF-8 ${bytes.length}바이트`;},
 actions(){return [{id:'preset-0',text:'0 만들기'},{id:'preset-5',text:'5 만들기',primary:true},{id:'preset-42',text:'42 만들기'},{id:'preset-255',text:'255 만들기'},{id:'reset',text:'예시로 초기화'}];},
 render(s){const value=s.bits.reduce((sum,b,i)=>sum+b*weights[i],0),on=weights.filter((_,i)=>s.bits[i]),bytes=utf8Bytes(s.text);return `<div class="bit-grid" role="group" aria-label="8비트 스위치">${s.bits.map((b,i)=>`<button type="button" class="bit-switch ${b?'on':''}" data-action="bit" data-value="${i}" aria-pressed="${!!b}"><span>${weights[i]}</span><strong>${b}</strong></button>`).join('')}</div><p class="binary-readout"><strong>${s.bits.join('')}</strong><span>${on.length?on.join(' + '):'켜진 자리값 없음'} = ${value}</span></p><label class="inline-lab-field">문자열 <input value="${e(s.text)}" data-action="text" maxlength="20" autocomplete="off"></label>${table(['읽는 관점','결과'],[['코드 포인트',Array.from(s.text).map(ch=>`U+${ch.codePointAt(0).toString(16).toUpperCase().padStart(4,'0')}`).join(' · ')||'없음'],['UTF-8 16진수 바이트',bytes.map(v=>v.toString(16).toUpperCase().padStart(2,'0')).join(' ')||'없음'],['UTF-8 크기',bytes.length+'바이트']])}`;}
};
CS.labs['pixel-size']={
 title:'픽셀 수와 압축 전 크기를 계산해 보세요',type:'비트맵 원시 데이터 계산',intro:'작은 8×8 RGB 이미지를 픽셀 격자로 보고, 압축하기 전 색상 데이터가 몇 바이트인지 단계별로 계산해요.',limit:'파일 헤더·색상 프로필·메타데이터·압축은 생략한 원시 색상 데이터 모형이에요. 실제 PNG나 JPEG 파일 크기를 예측하는 계산이 아니에요.',
 fields:[{key:'width',label:'가로 픽셀',value:'8',inputmode:'numeric'},{key:'height',label:'세로 픽셀',value:'8',inputmode:'numeric'},{key:'channels',label:'픽셀당 바이트',value:'3',options:[{value:'1',label:'회색조 · 1B'},{value:'3',label:'RGB · 3B'},{value:'4',label:'RGBA · 4B'}]}],
 validate(raw){return {width:integer(raw.width,1,64,'가로 픽셀'),height:integer(raw.height,1,64,'세로 픽셀'),channels:integer(raw.channels,1,4,'픽셀당 바이트')};},
 initial(){return {phase:0,events:[],done:false};},
 step(s,p){if(s.done)return s;const n=structuredClone(s);n.phase++;const pixels=p.width*p.height,bytes=pixels*p.channels;n.events.push(n.phase===1?`${p.width} × ${p.height} = ${pixels}픽셀을 세었어요.`:n.phase===2?`${pixels} × ${p.channels} = ${bytes}바이트예요.`:'압축 파일은 반복·예측 가능성·형식에 따라 크기가 달라짐을 확인했어요.');if(n.phase===3)n.done=true;return n;},
 describe(s,p){const pixels=p.width*p.height,bytes=pixels*p.channels;return s.phase===0?'먼저 가로와 세로를 곱해 픽셀 수를 구해 보세요.':s.phase===1?`${pixels}픽셀. 이제 픽셀 하나의 바이트 수를 곱해요.`:s.phase===2?`압축 전 색상 데이터는 ${bytes}바이트예요. 실제 파일 크기와 같은지 마지막으로 구별해요.`:`계산 완료 · ${pixels}픽셀, 압축 전 ${bytes}바이트. 압축된 파일 크기는 별도예요.`;},
 render(s,p){const pixels=p.width*p.height,shown=Math.min(pixels,64),bytes=pixels*p.channels;return `<div class="pixel-preview" style="--cols:${Math.min(p.width,8)}" aria-label="최대 64개까지만 보이는 픽셀 격자">${Array.from({length:shown},(_,i)=>`<span style="--tone:${(i*37)%255}"></span>`).join('')}</div>${table(['계산','값'],[['픽셀 수',s.phase?`${p.width} × ${p.height} = ${pixels}`:'아직 계산 전'],['압축 전 색상 데이터',s.phase>=2?`${pixels} × ${p.channels}B = ${bytes}B`:'아직 계산 전'],['파일 크기',s.done?'형식·압축·메타데이터에 따라 달라요.':'마지막 단계에서 구별해요.']])}`;}
};
CS.labs['stack-queue']={
 title:'같은 A·B·C를 스택과 큐에서 꺼내 보세요',type:'실제 자료구조 연산',intro:'저장된 항목은 같아도 꺼내는 위치 규칙이 다르면 결과 순서가 달라져요.',limit:'항목은 최대 12개이고 각 입력을 하나의 값으로 다뤄요. 내부 구현은 JavaScript 배열이지만, 화면의 연산은 선택한 추상 자료형이 허용하는 끝에서만 수행해요.',custom:true,
 initial(){return {kind:'stack',items:['A','B','C'],input:'D',removed:[],events:[]};},
 action(s,a,data){if(a==='reset')return this.initial();const n=structuredClone(s);if(a==='edit'){n.input=String(data).trim().slice(0,8);return n;}if(a==='stack'||a==='queue'||a==='deque'){n.kind=a;n.removed=[];n.events.push(`${a==='stack'?'스택':a==='queue'?'큐':'덱'} 규칙으로 바꿨어요.`);return n;}if(a==='add'){if(!n.input)throw Error('추가할 값을 먼저 입력해 주세요.');if(n.items.length>=12)throw Error('이 모형은 최대 12개까지만 담아요. 기존 항목은 그대로예요.');n.items.push(n.input);n.events.push(`${n.input}을 ${n.kind==='stack'?'맨 위':n.kind==='queue'?'뒤':'오른쪽'}에 넣었어요.`);return n;}if(a==='remove'||a==='remove-left'){if(!n.items.length)throw Error('비어 있어서 꺼낼 값이 없어요.');const left=n.kind==='queue'||a==='remove-left',value=left?n.items.shift():n.items.pop();n.removed.push(value);n.events.push(`${value}을 ${left?'왼쪽':'오른쪽'}에서 꺼냈어요.`);return n;}throw Error('알 수 없는 자료구조 동작이에요.');},
 describe(s){return s.events.at(-1)||'A, B, C를 차례로 넣은 상태예요. 스택과 큐에서 하나씩 꺼내 비교해 보세요.';},
 actions(s){return [{id:'stack',text:'스택 LIFO',primary:s.kind==='stack'},{id:'queue',text:'큐 FIFO',primary:s.kind==='queue'},{id:'deque',text:'덱 양쪽',primary:s.kind==='deque'},{id:'add',text:'값 넣기'},{id:'remove',text:s.kind==='stack'?'맨 위 꺼내기':s.kind==='queue'?'맨 앞 꺼내기':'오른쪽 꺼내기',disabled:!s.items.length},...(s.kind==='deque'?[{id:'remove-left',text:'왼쪽 꺼내기',disabled:!s.items.length}]:[]),{id:'reset',text:'A·B·C로 초기화'}];},
 render(s){return `<label class="inline-lab-field">추가할 값 <input value="${e(s.input)}" data-action="edit" maxlength="8" autocomplete="off"></label><div class="structure-label"><span>${s.kind==='stack'?'바닥':s.kind==='queue'?'먼저 나가는 쪽':'왼쪽'}</span><strong>${s.kind==='stack'?'스택':s.kind==='queue'?'큐':'덱'}</strong><span>${s.kind==='stack'?'맨 위':s.kind==='queue'?'새 값이 들어오는 쪽':'오른쪽'}</span></div><div class="structure-track">${s.items.map((v,i)=>`<span class="token ${s.kind==='stack'&&i===s.items.length-1?'current':''}">${e(v)}</span>`).join('')||'<span class="token empty">비어 있음</span>'}</div><p class="small">꺼낸 순서 · <strong>${s.removed.map(e).join(' → ')||'아직 없음'}</strong></p>`;}
};
const hashOf=value=>Array.from(value).reduce((sum,ch)=>sum+ch.codePointAt(0),0)%4;
CS.helpers.hashOf=hashOf;
CS.labs['hash-buckets']={
 title:'해시 충돌과 Set의 중복 처리를 살펴보세요',type:'4개 버킷 해시 모형',intro:'문자열을 네 버킷 중 하나로 보내요. 다른 키가 같은 버킷을 써도 둘 다 보관할 수 있는지 확인해요.',limit:'교육용 해시 함수는 코드 포인트 합을 4로 나눈 나머지예요. 실제 언어와 라이브러리는 다른 함수·용량·충돌 해결법을 사용하며 평균 O(1)이 최악의 경우까지 보장된다는 뜻은 아니에요.',custom:true,
 initial(){return {input:'A',mode:'map',entries:[],events:[]};},
 action(s,a,data){if(a==='reset')return this.initial();const n=structuredClone(s);if(a==='edit'){n.input=String(data).trim().slice(0,10);return n;}if(a==='map'||a==='set'){n.mode=a;n.entries=[];n.events.push(a==='map'?'키를 구별해 값을 저장하는 Map 모형이에요.':'같은 값을 한 번만 유지하는 Set 모형이에요.');return n;}if(a==='preset'){n.entries=['A','E','B'];n.events.push('A와 E는 같은 버킷에 들어가지만 서로 다른 값이라 함께 남아요.');return n;}if(a==='add'){if(!n.input)throw Error('추가할 값을 입력해 주세요.');if(n.entries.length>=12)throw Error('이 모형은 최대 12개까지만 저장해요.');if(n.mode==='set'&&n.entries.includes(n.input)){n.events.push(`입력한 값 ${n.input}는 이미 있어 Set의 항목 수가 늘어나지 않았어요.`);return n;}n.entries.push(n.input);n.events.push(`${n.input} → 버킷 ${hashOf(n.input)}에 저장했어요.`);return n;}throw Error('알 수 없는 해시 동작이에요.');},
 describe(s){return s.events.at(-1)||'A를 넣거나 충돌 예시를 불러 버킷 배치를 확인해 보세요.';},
 actions(s){return [{id:'map',text:'Map 모형',primary:s.mode==='map'},{id:'set',text:'Set 모형',primary:s.mode==='set'},{id:'add',text:'값 저장'},{id:'preset',text:'A·E·B 충돌 예시'},{id:'reset',text:'초기화'}];},
 render(s){const buckets=Array.from({length:4},()=>[]);s.entries.forEach(v=>buckets[hashOf(v)].push(v));return `<label class="inline-lab-field">저장할 값 <input value="${e(s.input)}" data-action="edit" maxlength="10" autocomplete="off"></label><div class="bucket-grid">${buckets.map((values,i)=>`<div><strong>버킷 ${i}</strong><div class="token-row">${values.map(v=>`<span class="token">${e(v)}</span>`).join('')||'<span class="token empty">빈칸</span>'}</div></div>`).join('')}</div><p class="small">저장된 항목 ${s.entries.length}개 · 같은 버킷의 항목도 키나 값을 다시 비교해 구별해요.</p>`;}
};
})();
