(()=>{
const {escape:e,integer,table}=CS.helpers;

CS.labs['space-growth']={
 title:'입력 n개가 차지하는 공간을 나누어 계산해 보세요',type:'고정 폭 값 저장 공간 모형',intro:'정수 하나를 4바이트로 정한 모형에서 입력 공간과 알고리즘이 새로 쓰는 보조 공간을 따로 계산해요.',limit:'값 하나를 정확히 4B로 놓는 교육용 모형이에요. 배열 머리 정보·정렬·참조·객체·메모리 할당기의 비용은 세지 않으며, JavaScript의 실제 메모리 사용량도 측정하지 않아요.',
 fields:[{key:'n',label:'입력 개수 n',value:'10',inputmode:'numeric'},{key:'method',label:'처리 방법',value:'copy',options:[{value:'copy',label:'전체 복사본 만들기'},{value:'sum',label:'합계 변수만 쓰기'}]}],
 validate(raw){const n=integer(raw.n,0,100,'입력 개수 n');if(!['copy','sum'].includes(raw.method))throw Error('처리 방법을 다시 골라 주세요.');return {n,method:raw.method};},
 initial(){return {phase:0,done:false,events:[]};},
 step(s,p){if(s.done)return s;const n=structuredClone(s),input=p.n*4,extra=p.method==='copy'?p.n*4:4;n.phase++;n.events.push(n.phase===1?`입력 ${p.n}개 × 4B = ${input}B예요.`:n.phase===2?`${p.method==='copy'?'복사본 '+p.n+'개':'합계 변수 한 개'}에 ${extra}B를 더 써요.`:`이 모형에서 동시에 필요한 합계는 ${input+extra}B예요.`);if(n.phase===3)n.done=true;return n;},
 describe(s,p){const input=p.n*4,extra=p.method==='copy'?p.n*4:4,total=input+extra;if(s.phase===0)return '먼저 이미 주어진 입력이 차지하는 공간부터 세어 보세요.';if(s.phase===1)return `입력 공간 ${input}B. 이제 처리 과정이 새로 만드는 보조 공간을 세어요.`;if(s.phase===2)return `보조 공간 ${extra}B. 입력과 보조 공간을 같은 기준으로 합쳐 보세요.`;return `계산 완료 · 입력 ${input}B + 보조 ${extra}B = ${total}B`;},
 render(s,p){const input=p.n*4,extra=p.method==='copy'?p.n*4:4,total=input+extra,shown=Math.min(p.n,20);return `<div class="space-lanes"><div><strong>입력 공간</strong><div class="space-cells">${Array.from({length:shown},()=>'<span></span>').join('')}${p.n>20?'<b>…</b>':''}${!p.n?'<em>0칸</em>':''}</div></div><div><strong>보조 공간</strong><div class="space-cells extra">${s.phase>=2?(p.method==='copy'?(Array.from({length:shown},()=>'<span></span>').join('')+(p.n>20?'<b>…</b>':'')+(!p.n?'<em>0칸</em>':'')):'<i>합계 변수 1칸</i>'):'<em>다음 단계에서 계산</em>'}</div></div></div>${table(['세는 범위','필요한 공간','입력 증가에 따른 분류'],[['입력 배열',s.phase?`${input}B`:'아직 계산 전','O(n)'],['추가 작업 공간',s.phase>=2?`${extra}B`:'아직 계산 전',p.method==='copy'?'O(n)':'O(1)'],['이 모형의 합계',s.done?`${total}B`:'마지막 단계에서 계산','무엇을 포함했는지 함께 표시']])}`;}
};

CS.labs['bounded-buffer']={
 title:'모두 보관하기와 최근 20개만 보관하기를 비교하세요',type:'실제 목록 추가·제거',intro:'메시지를 계속 넣어 저장된 항목 수가 어떻게 달라지는지 확인해요. 최근 모드에서는 21번째가 들어올 때 가장 오래된 참조를 제거해요.',limit:'각 메시지를 같은 크기의 한 칸으로 보는 모형이에요. 목록에서 참조를 제거해도 JavaScript 엔진이 실제 메모리를 언제 회수할지는 이 화면이 보장하거나 측정하지 않아요.',custom:true,
 initial(){return {mode:'all',next:1,input:'새 메시지',items:[],events:[]};},
 action(s,a,data){if(a==='reset')return this.initial();const n=structuredClone(s);if(a==='edit'){n.input=String(data).trim().slice(0,30);return n;}if(a==='all'||a==='recent'){n.mode=a;n.items=a==='recent'?n.items.slice(-20):n.items;n.events.push(a==='recent'?'최근 20개만 남기도록 오래된 항목을 제거했어요.':'앞으로 들어오는 메시지를 모두 보관해요.');return n;}const addOne=()=>{const text=n.input||`메시지 ${n.next}`;n.items.push(`${n.next}. ${text}`);n.next++;if(n.mode==='recent'&&n.items.length>20)n.items.shift();};if(a==='add'){addOne();n.events.push(`한 개를 추가해 저장 목록에 ${n.items.length}개가 있어요.`);return n;}if(a==='add25'){for(let i=0;i<25;i++)addOne();n.events.push(`25개를 추가해 저장 목록에 ${n.items.length}개가 있어요.`);return n;}throw Error('알 수 없는 보관 동작이에요.');},
 describe(s){return `${s.mode==='all'?'모두 보관':'최근 20개 보관'} · 지금 목록에 ${s.items.length}개 · 지금까지 만든 메시지 ${s.next-1}개`;},
 actions(s){return [{id:'all',text:'모두 보관',primary:s.mode==='all'},{id:'recent',text:'최근 20개만',primary:s.mode==='recent'},{id:'add',text:'1개 추가'},{id:'add25',text:'25개 빠르게 추가'},{id:'reset',text:'비우기'}];},
 render(s){return `<label class="inline-lab-field">메시지 내용 <input value="${e(s.input)}" data-action="edit" maxlength="30" autocomplete="off"></label><div class="buffer-summary"><strong>${s.items.length}</strong><span>저장된 메시지</span><small>${s.mode==='recent'?'상한 20개':'상한 없음'}</small></div><div class="buffer-track" aria-label="저장된 메시지 목록">${s.items.slice(-20).map((v,i)=>`<span class="${i===s.items.slice(-20).length-1?'newest':''}">${e(v)}</span>`).join('')||'<em>아직 저장된 메시지가 없어요.</em>'}</div><p class="small">화면에는 최대 20개를 그려요. 핵심은 화면에 숨겼는지가 아니라 <strong>저장 목록에 몇 개가 남아 있는지</strong>예요.</p>`;}
};

CS.labs['search-compare']={
 title:'순차 탐색과 이진 탐색의 비교 횟수를 세어 보세요',type:'실제 비교 이벤트 계수',intro:'목표값과 비교할 때마다 정확히 한 번을 세어요. 자동 실행의 애니메이션 시간은 알고리즘 성능에 포함하지 않아요.',limit:'목록은 1부터 n까지의 정수예요. 이진 탐색은 오름차순 정렬 입력에서만 실행하며, 매 단계 가운데 인덱스는 floor((low+high)/2)로 정해요.',
 fields:[{key:'n',label:'목록 크기 n',value:'16',inputmode:'numeric'},{key:'target',label:'찾을 값',value:'16',inputmode:'numeric'},{key:'algorithm',label:'탐색 방법',value:'binary',options:[{value:'linear',label:'순차 탐색'},{value:'binary',label:'이진 탐색'}]},{key:'order',label:'목록 상태',value:'sorted',options:[{value:'sorted',label:'오름차순 정렬'},{value:'unsorted',label:'정렬되지 않음'}]}],
 validate(raw){const n=integer(raw.n,0,32,'목록 크기 n'),target=integer(raw.target,0,99,'찾을 값');if(!['linear','binary'].includes(raw.algorithm))throw Error('탐색 방법을 다시 골라 주세요.');if(!['sorted','unsorted'].includes(raw.order))throw Error('목록 상태를 다시 골라 주세요.');if(raw.algorithm==='binary'&&raw.order!=='sorted')throw Error('이진 탐색은 오름차순으로 정렬된 목록이 필요해요. 목록 상태나 탐색 방법을 바꿔 주세요.');return {n,target,algorithm:raw.algorithm,order:raw.order};},
 values(p){const arr=Array.from({length:p.n},(_,i)=>i+1);if(p.order==='unsorted'&&arr.length>1)arr.unshift(arr.pop());return arr;},
 initial(p){return {index:0,low:0,high:p.n-1,current:null,comparisons:0,checked:[],found:false,done:p.n===0,events:p.n===0?['빈 목록이라 비교 없이 찾지 못했어요.']:[]};},
 step(s,p){if(s.done)return s;const n=structuredClone(s),values=this.values(p),i=p.algorithm==='linear'?n.index:Math.floor((n.low+n.high)/2),value=values[i];n.current=i;n.checked.push(i);n.comparisons++;if(value===p.target){n.found=true;n.done=true;n.events.push(`${value}과 비교해 목표를 찾았어요.`);return n;}if(p.algorithm==='linear'){n.index++;if(n.index>=values.length)n.done=true;}else if(value<p.target)n.low=i+1;else n.high=i-1;if(p.algorithm==='binary'&&n.low>n.high)n.done=true;n.events.push(`${value}과 비교했지만 달라서 ${n.done?'탐색을 끝냈어요.':'후보를 줄였어요.'}`);return n;},
 describe(s,p){if(p.n===0)return '빈 목록 · 비교 0회 · 찾지 못함';if(!s.comparisons)return `${p.algorithm==='linear'?'왼쪽 첫 항목':'가운데 항목'}부터 비교해 보세요.`;if(s.done)return `${s.found?'찾음':'찾지 못함'} · 실제 비교 ${s.comparisons}회`;return `비교 ${s.comparisons}회 · 다음 후보 ${p.algorithm==='linear'?Math.max(0,p.n-s.index):Math.max(0,s.high-s.low+1)}개`;},
 render(s,p){const values=this.values(p),candidate=i=>p.algorithm==='linear'?i>=s.index:i>=s.low&&i<=s.high;return `<div class="search-meta"><span>비교 <strong>${s.comparisons}</strong>회</span><span>남은 후보 <strong>${s.done?0:values.filter((_,i)=>candidate(i)).length}</strong>개</span><span>결과 <strong>${s.done?(s.found?'찾음':'없음'):'탐색 중'}</strong></span></div><div class="search-track" aria-label="탐색할 값 목록">${values.map((v,i)=>`<span class="${i===s.current?'current ':''}${s.checked.includes(i)?'checked ':''}${!s.done&&candidate(i)?'candidate':''}">${v}</span>`).join('')||'<em>빈 목록</em>'}</div><div class="search-legend"><span><i class="candidate"></i>남은 후보</span><span><i class="checked"></i>확인함</span><span><i class="current"></i>방금 비교</span></div>`;}
};

CS.labs['network-delay']={
 title:'전송 시간과 왕복 지연을 따로 계산해 보세요',type:'단순 네트워크 지연 계산',intro:'파일 크기와 전송률로 순수 전송 시간을 계산하고, 별도의 왕복 지연을 한 번 더해요.',limit:'십진 단위 1MB=8Mb를 사용하고 한 번의 RTT만 더하는 단순 모형이에요. 실제 연결 설정·프로토콜 헤더·혼잡·재전송·서버 처리 시간은 포함하지 않아요.',
 fields:[{key:'size',label:'데이터 크기 MB',value:'10',inputmode:'numeric'},{key:'rate',label:'전송률 Mbps',value:'10',inputmode:'numeric'},{key:'rtt',label:'왕복 지연 ms',value:'100',inputmode:'numeric'}],
 validate(raw){return {size:integer(raw.size,0,10000,'데이터 크기 MB'),rate:integer(raw.rate,1,100000,'전송률 Mbps'),rtt:integer(raw.rtt,0,60000,'왕복 지연 ms')};},
 initial(){return {phase:0,done:false,events:[]};},
 step(s,p){if(s.done)return s;const n=structuredClone(s),bits=p.size*8,tx=bits/p.rate;n.phase++;n.events.push(n.phase===1?`${p.size}MB × 8 = ${bits}Mb예요.`:n.phase===2?`${bits}Mb ÷ ${p.rate}Mbps = ${tx.toFixed(3)}초예요.`:`전송 ${tx.toFixed(3)}초 + RTT ${(p.rtt/1000).toFixed(3)}초를 더했어요.`);if(n.phase===3)n.done=true;return n;},
 describe(s,p){const tx=p.size*8/p.rate,total=tx+p.rtt/1000;if(s.phase===0)return '먼저 MB를 Mb로 바꾸기 위해 8을 곱해 보세요.';if(s.phase===1)return `${p.size*8}Mb. 이제 전송률로 나누어요.`;if(s.phase===2)return `순수 전송 ${tx.toFixed(3)}초. 왕복 지연은 별도로 남아 있어요.`;return `단순 합계 ${total.toFixed(3)}초 · 전송 ${tx.toFixed(3)}초 + RTT ${(p.rtt/1000).toFixed(3)}초`;},
 render(s,p){const tx=p.size*8/p.rate,total=tx+p.rtt/1000;return `${table(['구간','계산','결과'],[['데이터를 비트로',`${p.size}MB × 8`,s.phase>=1?`${p.size*8}Mb`:'아직 계산 전'],['순수 전송',`${p.size*8}Mb ÷ ${p.rate}Mbps`,s.phase>=2?`${tx.toFixed(3)}초`:'아직 계산 전'],['왕복 지연과 합계',`전송 + ${p.rtt}ms`,s.done?`${total.toFixed(3)}초`:'마지막 단계에서 계산']])}<div class="delay-bar"><span style="--share:${total?Math.max(3,tx/total*100):50}%">전송 시간</span><b>왕복 지연</b></div>`;}
};
})();
