(()=>{
const {escape:e,table}=CS.helpers;
CS.labs['layer-message']={
 title:'메시지에 전달 정보를 붙이고 다시 꺼내 보세요',type:'단순화한 TCP/IP 캡슐화 모형',intro:'송신 측에서는 아래 역할로 내려가며 정보를 붙이고, 수신 측에서는 반대 순서로 필요한 정보를 읽어 원래 내용을 복원해요.',limit:'학습용 TCP/IP 역할 모형이에요. 실제 헤더의 비트 구조·오류 검사·MTU·재전송은 생략하며, OSI의 모든 계층에 똑같은 봉투가 하나씩 붙는다는 뜻이 아니에요.',
 fields:[{key:'message',label:'보낼 내용',value:'HI',wide:true},{key:'destination',label:'목적지',value:'B',options:[{value:'B',label:'수신자 B · 주소 있음'},{value:'unknown',label:'주소를 모르는 목적지'}]}],
 validate(raw){const message=String(raw.message??'').slice(0,20);if(!['B','unknown'].includes(raw.destination))throw Error('목적지를 다시 골라 주세요.');return {message,destination:raw.destination};},
 initial(){return {phase:0,done:false,failed:false,restored:null,events:[]};},
 step(s,p){if(s.done)return s;const n=structuredClone(s);n.phase++;const notes=['응용 데이터의 형식을 정했어요.','전송 계층이 프로그램을 구별할 포트 정보를 붙였어요.','네트워크 계층이 목적지 IP 정보를 확인했어요.','링크 계층이 다음 구간 전달 정보를 붙였어요.','신호로 바꾸어 링크를 건너 수신 측에 도착했어요.','수신 링크가 프레임 정보를 확인했어요.','수신 네트워크가 IP 정보를 확인했어요.','수신 전송이 포트로 알맞은 앱에 넘겼어요.','응용이 원래 내용을 해석했어요.'];if(n.phase===3&&p.destination==='unknown'){n.failed=true;n.done=true;n.events.push('목적지 주소를 알 수 없어 네트워크 단계에서 전달을 중단했어요.');return n;}n.events.push(notes[n.phase-1]);if(n.phase===9){n.restored=p.message;n.done=true;}return n;},
 describe(s,p){if(s.failed)return '전달 실패 · 목적지 주소를 알 수 없어 수신 메시지를 만들지 않았어요.';if(s.done)return `전달 완료 · 수신 앱이 ${p.message===''?'빈 내용':`“${p.message}”`}을 복원했어요.`;const labels=['보낼 내용을 준비해요','응용 데이터','세그먼트','패킷','프레임','신호 전달','프레임 해석','패킷 해석','세그먼트 해석'];return `${labels[s.phase]} · ${s.phase<5?'송신 측에서 아래로':'수신 측에서 위로'} 이동해요.`;},
 render(s,p){const send=s.phase<=5,depth=s.phase===0?0:s.phase<=5?s.phase:Math.max(0,9-s.phase),layers=[['app','내용',p.message===''?'빈 내용':e(p.message)],['transport','전송','목적 포트 443'],['network','네트워크',p.destination==='B'?'예시 IP 203.0.113.7':'목적지 주소 없음'],['link','링크','다음 구간 주소'],['signal','물리','빛·전기·무선 신호']];return `<div class="layer-route"><strong>송신자 A</strong><span class="${send?'active':''}">${send?'포장 중':'보냄'}</span><i></i><span class="${!send&&!s.failed?'active':''}">${s.failed?'전달 중단':send?'이동 전':'해석 중'}</span><strong>수신자 B</strong></div><div class="packet-stack ${s.failed?'failed':''}">${layers.slice(0,depth).reverse().map(([c,name,value],i)=>`<div class="packet-layer ${c}"><b>${name}</b><span>${value}</span>${i===depth-1&&depth<5?`<em>${p.message===''?'빈 내용':e(p.message)}</em>`:''}</div>`).join('')||`<div class="packet-payload">${p.message===''?'빈 내용':e(p.message)}</div>`}</div>${table(['현재 상태','값'],[['방향',send?'송신 · 아래 역할로':'수신 · 위 역할로'],['붙인 전달 정보',`${Math.min(depth,4)}종류`],['복원한 내용',s.restored===null?'아직 없음':s.restored===''?'빈 내용':e(s.restored)]])}`;}
};

CS.labs['segment-order']={
 title:'순서가 바뀌거나 빠진 조각을 다시 모아 보세요',type:'세 조각 전달 모형',intro:'IP 전달에서 조각이 순서대로 도착한다고 기대하지 않고, 수신 측이 번호를 보고 모으며 빠진 조각을 확인하는 상황을 살펴요.',limit:'TCP 전체를 구현한 것이 아니라 세 조각의 순서 정리와 누락 확인만 보여 주는 모형이에요. IP 자체가 전달·순서·재전송을 보장한다는 뜻이 아니에요.',custom:true,
 initial(){return {arrival:[2,1,3],received:[],expected:[1,2,3],events:[],complete:false};},
 action(s,a){if(a==='reset')return this.initial();const n=structuredClone(s);if(a==='shuffled'){n.arrival=[2,1,3];n.received=[];n.events.push('2·1·3 순서로 도착하는 예시를 준비했어요.');n.complete=false;return n;}if(a==='missing'){n.arrival=[1,3];n.received=[];n.events.push('2번 조각이 빠진 예시를 준비했어요.');n.complete=false;return n;}if(a==='receive'){if(!n.arrival.length)throw Error('도착 대기 중인 조각이 없어요. 빠진 조각을 요청하거나 예시를 초기화해 주세요.');const part=n.arrival.shift();n.received.push(part);n.complete=n.expected.every(x=>n.received.includes(x));n.events.push(`${part}번 조각을 받았어요.`);return n;}if(a==='retry'){const missing=n.expected.filter(x=>!n.received.includes(x)&&!n.arrival.includes(x));if(!missing.length)throw Error('다시 요청할 빠진 조각이 없어요.');n.arrival.push(...missing);n.events.push(`빠진 ${missing.join('·')}번 조각을 다시 요청했어요.`);return n;}throw Error('알 수 없는 조각 동작이에요.');},
 describe(s){const missing=s.expected.filter(x=>!s.received.includes(x)&&!s.arrival.includes(x));if(s.complete)return '세 조각을 모두 받아 1 → 2 → 3 순서로 다시 모았어요.';return `받은 조각 ${s.received.length}개 · 대기 ${s.arrival.length}개${missing.length?` · 빠짐 ${missing.join('·')}번`:''}`;},
 actions(s){return [{id:'receive',text:'다음 도착 받기',primary:!!s.arrival.length},{id:'retry',text:'빠진 조각 다시 요청'},{id:'shuffled',text:'2·1·3 예시'},{id:'missing',text:'2번 누락 예시'},{id:'reset',text:'초기화'}];},
 render(s){const missing=s.expected.filter(x=>!s.received.includes(x)&&!s.arrival.includes(x));return `<div class="segment-board"><div><strong>도착 대기</strong><p>${s.arrival.map(x=>`<span>${x}</span>`).join('')||'<em>없음</em>'}</p></div><div><strong>받은 순서</strong><p>${s.received.map(x=>`<span>${x}</span>`).join('')||'<em>아직 없음</em>'}</p></div><div><strong>다시 모은 순서</strong><p>${s.expected.map(x=>`<span class="${s.received.includes(x)?'ready':missing.includes(x)?'missing':''}">${s.received.includes(x)?x:'?'}</span>`).join('')}</p></div></div>`;}
};

CS.labs['http-library']={
 title:'도서 정보 URL을 해석하고 모의 응답을 받아 보세요',type:'실제 URL 파서 · 모의 HTTP 서버',intro:'브라우저의 URL 파서로 주소를 나눈 뒤 DNS 주소록, 요청, 응답을 차례로 확인해요.',limit:'인터넷에 요청하지 않는 결정적 모형이에요. library.example과 203.0.113.10은 문서용 예시이고, HTTP 버전·연결 재사용·캐시·프록시·리다이렉트는 생략해요.',
 fields:[{key:'url',label:'요청 URL',value:'https://library.example/books?id=B01',wide:true},{key:'scenario',label:'서버 상황',value:'normal',options:[{value:'normal',label:'ID에 맞는 정상 처리'},{value:'server',label:'서버 내부 오류'},{value:'connection',label:'연결 실패'},{value:'empty',label:'성공 · 본문 없음'}]}],
 validate(raw){let url;try{url=new URL(String(raw.url));}catch{throw Error('요청 URL에 올바른 절대 주소를 입력해 주세요.');}if(url.hostname!=='library.example'||url.pathname!=='/books')throw Error('요청 URL은 https://library.example/books 경로를 사용해 주세요.');const id=url.searchParams.get('id');if(!id)throw Error('요청 URL의 질의 문자열에 id를 넣어 주세요.');if(!['normal','server','connection','empty'].includes(raw.scenario))throw Error('서버 상황을 다시 골라 주세요.');return {url:url.href,id,scenario:raw.scenario,protocol:url.protocol,host:url.hostname,path:url.pathname,query:url.search};},
 initial(){return {phase:0,done:false,status:null,body:null,connected:null,events:[]};},
 outcome(p){if(p.scenario==='connection')return {connected:false,status:null,body:null};if(p.scenario==='server')return {connected:true,status:500,body:{error:'서버 내부 오류'}};if(p.scenario==='empty')return {connected:true,status:204,body:null};if(p.id==='B01')return {connected:true,status:200,body:{id:'B01',title:'컴퓨터 첫걸음',stock:2}};return {connected:true,status:404,body:{error:'도서를 찾지 못함'}};},
 step(s,p){if(s.done)return s;const n=structuredClone(s);n.phase++;if(n.phase===1)n.events.push(`URL에서 호스트 ${p.host}, 경로 ${p.path}, id ${p.id}를 읽었어요.`);if(n.phase===2)n.events.push('학습용 DNS 주소록에서 203.0.113.10을 찾았어요.');if(n.phase===3)n.events.push(`GET ${p.path}${p.query} 요청을 준비했어요.`);if(n.phase===4){Object.assign(n,this.outcome(p));n.events.push(n.connected?`HTTP ${n.status} 응답을 받았어요.`:'연결하지 못해 HTTP 응답을 받지 못했어요.');}if(n.phase===5){n.done=true;n.events.push(n.connected?'응답 상태와 본문을 따로 확인했어요.':'상태코드를 만들지 않고 연결 실패로 끝냈어요.');}return n;},
 describe(s,p){if(s.done&&!s.connected)return '연결 실패 · HTTP 응답과 상태코드가 없어요.';if(s.done)return `응답 완료 · HTTP ${s.status} · ${s.body?'본문 있음':'본문 없음'}`;return ['URL을 먼저 해석해요.','URL 해석 완료 · DNS 이름을 조회해요.','예시 IP 확인 · 요청을 만들어요.','요청 준비 완료 · 응답을 기다려요.','응답 도착 · 상태와 본문을 확인해요.'][s.phase];},
 render(s,p){return `<div class="http-flow"><div class="${s.phase>=1?'done':''}"><b>URL</b><span>${e(p.host)}</span><small>${e(p.path+p.query)}</small></div><i></i><div class="${s.phase>=2?'done':''}"><b>DNS</b><span>${s.phase>=2?'203.0.113.10':'대기'}</span></div><i></i><div class="${s.phase>=3?'done':''}"><b>요청</b><span>${s.phase>=3?'GET':'대기'}</span></div><i></i><div class="${s.phase>=4?'done':''} ${s.connected===false?'failed':''}"><b>응답</b><span>${s.phase>=4?(s.status===null?'없음':s.status):'대기'}</span></div></div>${table(['구분','현재 값'],[['요청 대상',`GET ${e(p.path+p.query)}`],['HTTP 상태코드',s.status===null?'없음':String(s.status)],['응답 본문',s.body?`<code>${e(JSON.stringify(s.body))}</code>`:'없음'],['연결 결과',s.connected===null?'아직 시도 전':s.connected?'응답 받음':'연결 실패']])}`;}
};

CS.labs['tls-handshake']={
 title:'TLS 연결에서 확인하는 일을 순서대로 살펴보세요',type:'TLS 1.3 개념 흐름 모형',intro:'서버 인증서 확인, 암호화에 쓸 키 합의, 보호된 HTTP 통신이라는 역할을 단계별로 봐요.',limit:'실제 암호 연산이나 인증서 체인을 구현하지 않는 역할 모형이에요. Base64·문자 뒤집기 같은 가짜 암호문을 만들지 않으며 TLS 버전과 암호 스위트의 세부 교환은 생략해요.',
 fields:[{key:'certificate',label:'서버 인증서 상태',value:'valid',options:[{value:'valid',label:'유효 · 이름 일치'},{value:'expired',label:'기간 만료'},{value:'mismatch',label:'이름 불일치'}]}],
 validate(raw){if(!['valid','expired','mismatch'].includes(raw.certificate))throw Error('서버 인증서 상태를 다시 골라 주세요.');return {certificate:raw.certificate};},
 initial(){return {phase:0,done:false,failed:false,events:[]};},
 step(s,p){if(s.done)return s;const n=structuredClone(s);n.phase++;if(n.phase===1)n.events.push('클라이언트와 서버가 지원 정보를 교환하기 시작했어요.');if(n.phase===2&&p.certificate!=='valid'){n.failed=true;n.done=true;n.events.push(p.certificate==='expired'?'인증서 유효 기간 검사를 통과하지 못했어요.':'인증서의 서버 이름이 접속 이름과 다릅니다.');return n;}if(n.phase===2)n.events.push('신뢰 경로·기간·서버 이름을 확인했어요.');if(n.phase===3)n.events.push('양쪽이 통신을 보호할 키를 합의했어요.');if(n.phase===4){n.done=true;n.events.push('보호된 연결 안에서 HTTP 요청과 응답을 주고받을 준비가 됐어요.');}return n;},
 describe(s){if(s.failed)return 'TLS 연결 중단 · 인증서 검증을 통과하지 못했어요.';if(s.done)return 'TLS 연결 준비 완료 · 이제 HTTP 메시지를 보호해 전송할 수 있어요.';return ['연결을 시작해 보세요.','서버 인증서를 확인해요.','통신 키를 합의해요.','보호된 채널을 완성해요.'][s.phase];},
 render(s){const steps=[['인사','지원 정보'],['인증서','신뢰·기간·이름'],['키 합의','통신 키 설정'],['보호 통신','HTTP 메시지']];return `<div class="tls-steps">${steps.map((x,i)=>`<div class="${s.phase>i?'done':''} ${s.failed&&i===1?'failed':''}"><span>${i+1}</span><b>${x[0]}</b><small>${x[1]}</small></div>`).join('<i></i>')}</div><p class="small">HTTPS는 전송 중 내용을 보호하고 접속한 서버 이름에 대한 인증을 돕지만, 웹사이트의 모든 내용이 사실이거나 안전한 행동만 한다는 보증은 아니에요.</p>`;}
};
})();
