(()=>{
const {escape:e,table}=CS.helpers;
const parseItems=raw=>{const text=String(raw??'').trim();if(!text)return [];const parts=text.split(',').map(x=>x.trim());if(parts.length>10)throw Error('정렬할 항목은 최대 10개까지 입력해 주세요.');const items=parts.map((part,i)=>{const m=part.match(/^(-?\d+)\s*([A-Za-z가-힣][A-Za-z0-9가-힣_-]*)$/);if(!m)throw Error(`${i+1}번째 항목을 3A처럼 정수 값과 식별자로 입력해 주세요.`);return {value:Number(m[1]),id:m[2],origin:i};});if(new Set(items.map(x=>x.id)).size!==items.length)throw Error('각 항목의 식별자는 서로 다르게 입력해 주세요.');return items;};
const sorted=arr=>arr.every((x,i)=>!i||arr[i-1].value<=x.value);
CS.helpers.parseSortItems=parseItems;
CS.labs['stable-sort']={
 title:'식별자가 붙은 값을 한 단계씩 정렬해 보세요',type:'실제 안정 삽입·버블 정렬',intro:'값이 같아도 B와 D라는 원래 순서를 추적해 안정성을 확인해요. 비교와 이동·교환 횟수도 따로 셉니다.',limit:'최대 10개 항목을 교육용으로 실행해요. 삽입 정렬은 항목을 고르는 단계와 비교·이동을 분리하고, 버블 정렬은 인접 비교 한 번을 한 단계로 보여 줘요.',
 fields:[{key:'items',label:'값+식별자 목록',value:'3A,1B,2C,1D',wide:true},{key:'algorithm',label:'정렬 방법',value:'insertion',options:[{value:'insertion',label:'삽입 정렬 · 안정'},{value:'bubble',label:'버블 정렬 · 안정'}]}],
 validate(raw){if(!['insertion','bubble'].includes(raw.algorithm))throw Error('정렬 방법을 다시 골라 주세요.');const items=String(raw.items??'').trim();return {items,parsedItems:parseItems(items),algorithm:raw.algorithm};},
 initial(p){const base={arr:structuredClone(p.parsedItems),comparisons:0,moves:0,events:[],done:p.parsedItems.length<2};return p.algorithm==='insertion'?{...base,i:1,j:1,key:null,phase:'pick'}:{...base,pass:0,index:0};},
 advanceInsertion(n){if(n.i>=n.arr.length){n.done=true;return;}if(n.phase==='pick'){n.key=n.arr[n.i];n.j=n.i;n.phase='compare';n.events.push(`${n.key.value}${n.key.id}를 정렬된 앞부분에 넣을 위치를 찾아요.`);return;}if(n.j===0){n.arr[0]=n.key;n.moves++;n.events.push(`${n.key.value}${n.key.id}를 맨 앞에 놓았어요.`);n.i++;n.key=null;n.phase='pick';if(n.i>=n.arr.length)n.done=true;return;}n.comparisons++;const left=n.arr[n.j-1];if(left.value>n.key.value){n.phase='move';n.events.push(`${left.value}${left.id} > ${n.key.value}${n.key.id}라서 오른쪽으로 옮길 준비를 해요.`);return;}n.arr[n.j]=n.key;n.moves++;n.events.push(`${left.value}${left.id} ≤ ${n.key.value}${n.key.id}라서 그 뒤에 놓아요.`);n.i++;n.key=null;n.phase='pick';if(n.i>=n.arr.length)n.done=true;},
 step(s,p){if(s.done)return s;const n=structuredClone(s);if(p.algorithm==='insertion'){if(n.phase==='move'){n.arr[n.j]=n.arr[n.j-1];n.j--;n.moves++;n.phase='compare';n.events.push('한 칸 오른쪽으로 이동했어요.');}else this.advanceInsertion(n);}else{const end=n.arr.length-1-n.pass;if(n.index>=end){n.pass++;n.index=0;if(n.pass>=n.arr.length-1){n.done=true;n.events.push('모든 패스를 마쳤어요.');}else n.events.push(`뒤 ${n.pass}개가 제자리를 찾았어요.`);return n;}const a=n.arr[n.index],b=n.arr[n.index+1];n.comparisons++;if(a.value>b.value){[n.arr[n.index],n.arr[n.index+1]]=[b,a];n.moves++;n.events.push(`${a.value}${a.id}와 ${b.value}${b.id}를 비교해 교환했어요.`);}else n.events.push(`${a.value}${a.id}와 ${b.value}${b.id}의 순서를 유지했어요.`);n.index++;}if(n.done&&!sorted(n.arr))throw Error('정렬 상태를 확인할 수 없어요.');return n;},
 describe(s,p){if(s.done)return `정렬 완료 · ${s.arr.map(x=>x.value+x.id).join(' → ')||'빈 목록'} · 비교 ${s.comparisons}회 · ${p.algorithm==='bubble'?'교환':'이동'} ${s.moves}회`;return `${p.algorithm==='insertion'?'삽입':'버블'} 정렬 진행 중 · 비교 ${s.comparisons}회 · ${p.algorithm==='bubble'?'교환':'이동'} ${s.moves}회`;},
 render(s,p){const active=p.algorithm==='insertion'?(s.key?[s.j-1,s.j]:[s.i]):[s.index,s.index+1],stablePairs=s.arr.filter(x=>x.value===1).map(x=>x.id).join(' → ');return `<div class="sort-metrics"><span>비교<strong>${s.comparisons}</strong></span><span>${p.algorithm==='bubble'?'교환':'이동'}<strong>${s.moves}</strong></span><span>값 1의 식별자 순서<strong>${stablePairs||'없음'}</strong></span></div><div class="sort-track">${s.arr.map((x,i)=>`<span class="${active.includes(i)?'active ':''}${p.algorithm==='insertion'&&i<s.i&&!s.key?'fixed ':''}${p.algorithm==='bubble'&&i>=s.arr.length-s.pass?'fixed':''}" style="--h:${Math.max(28,Math.min(110,34+Math.abs(x.value)*13))}px"><i style="height:var(--h)"></i><b>${x.value}</b><small>${e(x.id)}</small></span>`).join('')||'<em>빈 목록은 이미 정렬됐어요.</em>'}</div>${table(['검사','결과'],[['비내림차순',s.done?(sorted(s.arr)?'통과':'실패'):'완료 뒤 검사'],['항목 보존',`${s.arr.length}개 유지`],['같은 값의 원래 순서',stablePairs||'비교할 중복값 없음']])}`;}
};

const parseCoins=raw=>{const parts=String(raw??'').split(',').map(x=>x.trim()).filter(Boolean);if(!parts.length)throw Error('동전을 하나 이상 입력해 주세요.');if(parts.length>8)throw Error('동전은 최대 8종류까지 입력해 주세요.');const coins=parts.map((x,i)=>{if(!/^\d+$/.test(x)||+x<=0||+x>30)throw Error(`${i+1}번째 동전을 1부터 30까지의 양의 정수로 입력해 주세요.`);return +x;});return [...new Set(coins)].sort((a,b)=>a-b);};
CS.helpers.parseCoins=parseCoins;
CS.labs['coin-strategies']={
 title:'탐욕 선택과 동적 계획법으로 동전 개수를 비교하세요',type:'실제 탐욕·DP 계산',intro:'큰 동전을 먼저 고르는 탐욕법과, 0부터 작은 금액의 최적 답을 쌓는 동적 계획법을 같은 입력에서 실행해요.',limit:'동전은 1~30의 양의 정수, 금액은 0~30으로 제한해요. DP는 최소 동전 개수만 계산하며 도달 불가를 0개로 표시하지 않아요.',custom:true,
 initial(){return this.make('1,3,4','6');},
 make(coinsInput,amountInput){const coins=parseCoins(coinsInput);if(!/^\d+$/.test(String(amountInput).trim())||+amountInput>30)throw Error('금액을 0부터 30까지의 정수로 입력해 주세요.');const amount=+amountInput,descending=[...coins].sort((a,b)=>b-a);return {coinsInput,amountInput:String(amount),coins,amount,descending,greedy:{remain:amount,picks:[],done:amount===0,impossible:false},dp:{values:[0,...Array(amount).fill(Infinity)],choice:Array(amount+1).fill(null),next:1,done:amount===0},events:[]};},
 action(s,a,data){if(a==='reset')return this.initial();const n=structuredClone(s);if(a==='edit-coins'){n.coinsInput=String(data).slice(0,40);return n;}if(a==='edit-amount'){n.amountInput=String(data).slice(0,3);return n;}if(a==='apply')return this.make(n.coinsInput,n.amountInput);const greedyStep=()=>{if(n.greedy.done)return;const coin=n.descending.find(c=>c<=n.greedy.remain);if(!coin){n.greedy.impossible=true;n.greedy.done=true;n.events.push(`탐욕법은 남은 ${n.greedy.remain}을 만들 수 없어 멈췄어요.`);return;}n.greedy.picks.push(coin);n.greedy.remain-=coin;n.greedy.done=n.greedy.remain===0;n.events.push(`탐욕법이 ${coin}을 골라 ${n.greedy.remain}이 남았어요.`);};const dpStep=()=>{if(n.dp.done)return;const value=n.dp.next;let best=Infinity,choice=null;for(const coin of n.coins)if(coin<=value&&Number.isFinite(n.dp.values[value-coin])&&n.dp.values[value-coin]+1<best){best=n.dp.values[value-coin]+1;choice=coin;}n.dp.values[value]=best;n.dp.choice[value]=choice;n.events.push(Number.isFinite(best)?`DP[${value}] = ${best}, 마지막 동전 ${choice}예요.`:`DP[${value}]은 아직 만들 수 없어요.`);n.dp.next++;if(n.dp.next>n.amount)n.dp.done=true;};if(a==='greedy'){greedyStep();return n;}if(a==='dp'){dpStep();return n;}if(a==='all'){let guard=0;while(!n.greedy.done&&guard++<100)greedyStep();guard=0;while(!n.dp.done&&guard++<100)dpStep();return n;}throw Error('알 수 없는 동전 계산 동작이에요.');},
 describe(s){const g=s.greedy.done?(s.greedy.impossible?'도달 불가':`${s.greedy.picks.length}개`):`남은 금액 ${s.greedy.remain}`,d=s.dp.done?(Number.isFinite(s.dp.values[s.amount])?`${s.dp.values[s.amount]}개`:'도달 불가'):`DP[${s.dp.next}] 계산 전`;return `탐욕 ${g} · 최적 DP ${d}`;},
 actions(s){return [{id:'apply',text:'입력 적용'},{id:'greedy',text:'탐욕 한 단계',primary:!s.greedy.done},{id:'dp',text:'DP 한 칸',primary:s.greedy.done&&!s.dp.done},{id:'all',text:'둘 다 끝까지'},{id:'reset',text:'1·3·4 / 6으로 초기화'}];},
 render(s){const best=s.dp.values[s.amount];return `<div class="coin-inputs"><label>동전 종류<input value="${e(s.coinsInput)}" data-action="edit-coins" inputmode="numeric"></label><label>만들 금액<input value="${e(s.amountInput)}" data-action="edit-amount" inputmode="numeric"></label></div><div class="strategy-columns"><div><strong>큰 동전부터 고르기</strong><div class="coin-picks">${s.greedy.picks.map(c=>`<span>${c}</span>`).join('')||'<em>아직 선택 전</em>'}</div><small>남은 금액 ${s.greedy.remain}</small></div><div><strong>작은 답부터 쌓기</strong><div class="dp-row">${s.dp.values.map((v,i)=>`<span class="${i<s.dp.next?'ready':''}"><b>${i}</b><i>${Number.isFinite(v)?v:'–'}</i></span>`).join('')}</div><small>${s.dp.done?(Number.isFinite(best)?`최소 ${best}개`:'도달할 수 없음'):`다음은 ${s.dp.next}`}</small></div></div>`;}
};
})();
