(()=>{
const {escape:e,table}=CS.helpers;
const parseKeys=raw=>{const text=String(raw??'').trim();if(!text)return [];const parts=text.split(',').map(x=>x.trim());if(parts.length>9)throw Error('트리 키는 최대 9개까지 입력해 주세요.');const keys=parts.map((x,i)=>{if(!/^-?\d+$/.test(x)||+x<-99||+x>99)throw Error(`${i+1}번째 키를 -99부터 99까지의 정수로 입력해 주세요.`);return +x;});if(new Set(keys).size!==keys.length)throw Error('이 모형에서는 중복 키를 넣지 않아요. 서로 다른 키를 입력해 주세요.');return keys;};
const insert=(root,key)=>{if(!root)return {key,left:null,right:null};let node=root;while(true){if(key===node.key)return false;if(key<node.key){if(node.left)node=node.left;else{node.left={key,left:null,right:null};return true;}}else if(node.right)node=node.right;else{node.right={key,left:null,right:null};return true;}}};
const buildTree=keys=>{let root=null;for(const key of keys){if(!root)root={key,left:null,right:null};else insert(root,key);}return root;};
const walk=(root,order,out=[])=>{if(!root)return out;if(order==='preorder')out.push(root.key);walk(root.left,order,out);if(order==='inorder')out.push(root.key);walk(root.right,order,out);if(order==='postorder')out.push(root.key);return out;};
const layoutTree=root=>{const nodes=[],edges=[];let index=0;const visit=(node,depth,parent=null)=>{if(!node)return;visit(node.left,depth+1,node);const item={key:node.key,depth,x:70+index*80,y:45+depth*78};nodes.push(item);index++;visit(node.right,depth+1,node);};visit(root,0);const byKey=Object.fromEntries(nodes.map(n=>[n.key,n]));const edgeVisit=node=>{if(!node)return;for(const child of [node.left,node.right])if(child){edges.push([byKey[node.key],byKey[child.key]]);edgeVisit(child);}};edgeVisit(root);return {nodes,edges,width:Math.max(220,140+Math.max(1,nodes.length-1)*80),height:Math.max(150,100+(nodes.reduce((m,n)=>Math.max(m,n.depth),0)+1)*78)};};
CS.helpers.parseTreeKeys=parseKeys;
CS.labs['bst-traversal']={
 title:'숫자를 BST에 넣고 경로와 순회를 확인하세요',type:'실제 이진 탐색 트리 연산',intro:'각 키를 비교해 작은 값은 왼쪽, 큰 값은 오른쪽에 넣어요. 탐색 경로와 세 순회의 방문 시점을 한 단계씩 표시해요.',limit:'키는 -99~99의 서로 다른 정수 최대 9개예요. 이 실습은 중복 키를 거부하는 단순 BST이며 스스로 균형을 맞추지 않아요.',custom:true,
 initial(){return this.make('4,2,6,1,3');},
 make(treeInput){const keys=parseKeys(treeInput);return {treeInput:String(treeInput),newInput:'5',searchInput:'3',order:'inorder',root:buildTree(keys),keys,queue:[],visited:[],active:null,searchPath:[],found:null,events:[]};},
 action(s,a,data){if(a==='reset')return this.make('4,2,6,1,3');const n=structuredClone(s);if(a==='edit-tree'){n.treeInput=String(data).slice(0,40);return n;}if(a==='edit-new'){n.newInput=String(data).slice(0,4);return n;}if(a==='edit-search'){n.searchInput=String(data).slice(0,4);return n;}if(a==='order'){if(!['preorder','inorder','postorder'].includes(data))throw Error('순회 방법을 다시 골라 주세요.');n.order=data;n.queue=[];n.visited=[];n.active=null;n.searchPath=[];n.found=null;return n;}if(a==='build')return this.make(n.treeInput);if(a==='empty')return this.make('');const one=value=>{if(!/^-?\d+$/.test(String(value).trim())||+value<-99||+value>99)throw Error('추가·탐색 키를 -99부터 99까지의 정수로 입력해 주세요.');return +value;};if(a==='add'){const key=one(n.newInput);if(n.keys.length>=9)throw Error('트리 키는 최대 9개까지 입력해 주세요.');if(!n.root)n.root={key,left:null,right:null};else if(!insert(n.root,key))throw Error('이 모형에서는 중복 키를 넣지 않아요.');n.keys.push(key);n.treeInput=n.keys.join(',');n.queue=[];n.visited=[];n.active=key;n.searchPath=[];n.found=null;n.events.push(`${key}를 BST 조건에 맞는 자리에 넣었어요.`);return n;}if(a==='search'){const key=one(n.searchInput),path=[];let node=n.root;while(node){path.push(node.key);if(node.key===key)break;node=key<node.key?node.left:node.right;}n.searchPath=path;n.active=path.at(-1)??null;n.found=!!node;n.queue=[];n.visited=[];n.events.push(path.length?`${path.join(' → ')} 경로로 ${node?'찾았어요.':'빈 링크에 도착했어요.'}`:'빈 트리라 비교할 노드가 없어요.');return n;}const prepare=()=>{if(!n.queue.length&&!n.visited.length)n.queue=walk(n.root,n.order,[]);};if(a==='visit'){prepare();if(n.queue.length){n.active=n.queue.shift();n.visited.push(n.active);n.searchPath=[];n.found=null;n.events.push(`${n.active}을 방문했어요.`);}return n;}if(a==='all'){prepare();while(n.queue.length){n.active=n.queue.shift();n.visited.push(n.active);}n.searchPath=[];n.found=null;n.events.push(`${n.order} 순회를 마쳤어요.`);return n;}throw Error('알 수 없는 트리 동작이에요.');},
 describe(s){if(s.searchPath.length)return `${s.searchInput} 탐색 · ${s.searchPath.join(' → ')} · ${s.found?'찾음':'찾지 못함'}`;if(s.visited.length)return `${s.order==='inorder'?'중위':s.order==='preorder'?'전위':'후위'} 순회 · ${s.visited.join(' → ')}${s.queue.length?' · 다음 '+s.queue[0]:' · 완료'}`;return s.root?`루트 ${s.root.key} · 노드 ${s.keys.length}개 · 루트 깊이 0`:'빈 트리 · 탐색하면 찾지 못함';},
 actions(){return [{id:'build',text:'입력으로 트리 만들기'},{id:'add',text:'키 추가'},{id:'search',text:'키 탐색'},{id:'visit',text:'순회 한 단계',primary:true},{id:'all',text:'순회 끝까지'},{id:'empty',text:'빈 트리'},{id:'reset',text:'기본 트리'}];},
 render(s){const l=layoutTree(s.root),orderName=s.order==='inorder'?'중위':s.order==='preorder'?'전위':'후위';return `<div class="tree-inputs"><label>처음 넣을 키<input value="${e(s.treeInput)}" data-action="edit-tree" inputmode="numeric"></label><label>추가할 키<input value="${e(s.newInput)}" data-action="edit-new" inputmode="numeric"></label><label>찾을 키<input value="${e(s.searchInput)}" data-action="edit-search" inputmode="numeric"></label><label>순회 방법<select data-action="order"><option value="inorder" ${s.order==='inorder'?'selected':''}>중위 · 왼쪽-자신-오른쪽</option><option value="preorder" ${s.order==='preorder'?'selected':''}>전위 · 자신-왼쪽-오른쪽</option><option value="postorder" ${s.order==='postorder'?'selected':''}>후위 · 왼쪽-오른쪽-자신</option></select></label></div><div class="bst-live"><svg viewBox="0 0 ${l.width} ${l.height}" role="img" aria-label="현재 이진 탐색 트리">${l.edges.map(([a,b])=>`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"></line>`).join('')}${l.nodes.map(v=>`<g class="${s.active===v.key?'active ':''}${s.searchPath.includes(v.key)?'path ':''}${s.visited.includes(v.key)?'visited':''}" transform="translate(${v.x} ${v.y})"><circle r="24"></circle><text text-anchor="middle" dy="5">${v.key}</text><title>${v.key}, 깊이 ${v.depth}</title></g>`).join('')}</svg>${!s.root?'<p>아직 노드가 없어요.</p>':''}</div><div class="visit-strip"><strong>${orderName} 방문</strong>${s.visited.map(v=>`<span>${v}</span>`).join('')||'<em>순회 전</em>'}${s.queue.length?`<small>남은 순서 ${s.queue.join(' · ')}</small>`:''}</div>`;}
};

const edgeKey=(a,b)=>[a,b].sort().join('');
const graphEdges=p=>[{a:'A',b:'B',w:p.ab},{a:'B',b:'C',w:p.bc},{a:'A',b:'C',w:p.ac}];
const neighbors=(v,p)=>graphEdges(p).flatMap(x=>x.a===v?[[x.b,x.w]]:x.b===v?[[x.a,x.w]]:[]).sort((a,b)=>a[0].localeCompare(b[0]));
const makePath=(parent,target)=>{const path=[];for(let v=target;v!=null;v=parent[v]??null)path.unshift(v);return path;};
CS.labs['graph-paths']={
 title:'가까운 길과 비용이 적은 길을 비교하세요',type:'실제 BFS·다익스트라 탐색',intro:'같은 지도에서 BFS는 지나간 간선 수를, 다익스트라는 입력한 비용의 합을 기준으로 경로를 찾아요.',limit:'A·B·C는 서로 연결되고 D는 떨어진 고정 그래프예요. 비용은 0~20의 정수만 허용하며, 다익스트라가 전제로 삼지 않는 음수 비용은 실행 전에 거부해요.',
 fields:[{key:'algorithm',label:'탐색 방법',value:'bfs',options:[{value:'bfs',label:'BFS · 최소 간선 수'},{value:'dijkstra',label:'다익스트라 · 최소 비용'}]},{key:'target',label:'도착점',value:'C',options:[{value:'C',label:'C · 연결됨'},{value:'D',label:'D · 연결 안 됨'}]},{key:'ab',label:'A-B 비용',value:'1',inputmode:'numeric'},{key:'bc',label:'B-C 비용',value:'1',inputmode:'numeric'},{key:'ac',label:'A-C 비용',value:'5',inputmode:'numeric'}],
 validate(raw){const cost=(v,name)=>{if(!/^\d+$/.test(String(v).trim())||+v>20)throw Error(`${name}에 0부터 20까지의 정수 비용을 입력해 주세요.`);return +v;};if(!['bfs','dijkstra'].includes(raw.algorithm))throw Error('탐색 방법을 다시 골라 주세요.');if(!['C','D'].includes(raw.target))throw Error('도착점을 다시 골라 주세요.');return {algorithm:raw.algorithm,target:raw.target,ab:cost(raw.ab,'A-B 비용'),bc:cost(raw.bc,'B-C 비용'),ac:cost(raw.ac,'A-C 비용')};},
 initial(p){return p.algorithm==='bfs'?{frontier:[{v:'A',path:['A']}],discovered:['A'],visited:[],current:null,path:[],cost:null,done:false,found:false,events:[]}:{frontier:[],dist:{A:0,B:Infinity,C:Infinity,D:Infinity},parent:{A:null},visited:[],current:null,path:[],cost:null,done:false,found:false,events:[]};},
 step(s,p){if(s.done)return s;const n=structuredClone(s);if(p.algorithm==='bfs'){const item=n.frontier.shift();if(!item){n.done=true;n.events.push(`${p.target}에 도달할 수 없어요.`);return n;}n.current=item.v;n.visited.push(item.v);n.events.push(`${item.v}를 큐에서 꺼내 방문했어요.`);if(item.v===p.target){n.done=true;n.found=true;n.path=item.path;n.cost=item.path.length-1;return n;}for(const [v] of neighbors(item.v,p))if(!n.discovered.includes(v)){n.discovered.push(v);n.frontier.push({v,path:[...item.path,v]});}if(!n.frontier.length){n.done=true;n.events.push(`${p.target}에 도달할 수 없어요.`);}return n;}const unsettled=['A','B','C','D'].filter(v=>!n.visited.includes(v)&&Number.isFinite(n.dist[v])).sort((a,b)=>n.dist[a]-n.dist[b]||a.localeCompare(b));if(!unsettled.length){n.done=true;n.events.push(`${p.target}에 도달할 수 없어요.`);return n;}const u=unsettled[0];n.current=u;n.visited.push(u);n.events.push(`${u}의 현재 최소 비용 ${n.dist[u]}을 확정했어요.`);if(u===p.target){n.done=true;n.found=true;n.path=makePath(n.parent,u);n.cost=n.dist[u];return n;}for(const [v,w] of neighbors(u,p))if(!n.visited.includes(v)&&n.dist[u]+w<n.dist[v]){n.dist[v]=n.dist[u]+w;n.parent[v]=u;n.events.push(`${v}의 비용을 ${n.dist[v]}로 줄였어요.`);}const remains=['A','B','C','D'].some(v=>!n.visited.includes(v)&&Number.isFinite(n.dist[v]));if(!remains){n.done=true;n.events.push(`${p.target}에 도달할 수 없어요.`);}return n;},
 describe(s,p){if(s.done)return s.found?`${p.algorithm==='bfs'?'BFS 최소 간선':'다익스트라 최소 비용'} 경로 · ${s.path.join(' → ')} · ${p.algorithm==='bfs'?s.cost+'개 간선':'비용 '+s.cost}`:`${p.target}에 도달할 수 없음`;return `${p.algorithm==='bfs'?'BFS 큐':'다익스트라'} 진행 중 · 방문 ${s.visited.join(' → ')||'없음'}`;},
 render(s,p){const pos={A:[75,145],B:[260,55],C:[445,145],D:[260,245]},pathEdges=new Set(s.path.slice(1).map((v,i)=>edgeKey(s.path[i],v))),front=p.algorithm==='bfs'?s.frontier.map(x=>x.v):['A','B','C','D'].filter(v=>!s.visited.includes(v)&&Number.isFinite(s.dist[v])).sort((a,b)=>s.dist[a]-s.dist[b]);return `<div class="graph-live"><svg viewBox="0 0 520 300" role="img" aria-label="A B C가 연결되고 D는 떨어진 비용 그래프">${graphEdges(p).map(x=>{const [x1,y1]=pos[x.a],[x2,y2]=pos[x.b],active=pathEdges.has(edgeKey(x.a,x.b));return `<g class="${active?'chosen':''}"><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"></line><text x="${(x1+x2)/2}" y="${(y1+y2)/2-8}">${x.w}</text></g>`;}).join('')}${Object.entries(pos).map(([v,[x,y]])=>`<g class="${s.current===v?'active ':''}${s.visited.includes(v)?'visited':''}" transform="translate(${x} ${y})"><circle r="29"></circle><text text-anchor="middle" dy="6">${v}</text></g>`).join('')}</svg></div><div class="graph-state"><div><strong>${p.algorithm==='bfs'?'큐':'다음 후보'}</strong><p>${front.map(v=>`<span>${v}</span>`).join('')||'<em>비어 있음</em>'}</p></div><div><strong>방문 완료</strong><p>${s.visited.map(v=>`<span>${v}</span>`).join('')||'<em>아직 없음</em>'}</p></div></div>${p.algorithm==='dijkstra'?table(['정점','A','B','C','D'],[['현재 최소 비용',...['A','B','C','D'].map(v=>Number.isFinite(s.dist[v])?s.dist[v]:'∞')]]):'<p class="small">BFS에서는 간선 비용 숫자를 사용하지 않고, 시작점에서 몇 개의 간선을 지났는지 세어요.</p>'}`;}
};
})();
