(()=>{
const {escape:e,table}=CS.helpers;
const push=(state,event)=>{state.events.push(event);return state;};

CS.labs['system-call-boundary']={
 title:'파일 읽기 요청이 커널을 통과하는 길을 따라가세요',type:'실제 시스템 콜 상태 모형',intro:'프로그램의 read 요청이 보호 경계를 지나 권한 검사와 장치 작업을 거친 뒤 어디로 돌아오는지 한 단계씩 확인해요.',limit:'교육용 단일 CPU 모형이에요. 실제 시스템 콜 번호·진입 명령·스케줄링 시점과 장치 경로는 운영체제와 CPU에 따라 달라져요.',
 fields:[{key:'scenario',label:'요청 조건',value:'allowed',options:[{value:'allowed',label:'읽기 허용 · 정상 완료'},{value:'denied',label:'권한 없음 · 오류 반환'},{value:'direct',label:'사용자 모드에서 장치 직접 접근'}]}],
 validate(raw){if(!['allowed','denied','direct'].includes(raw.scenario))throw Error('요청 조건을 다시 골라 주세요.');return {scenario:raw.scenario};},
 initial(){return {phase:0,mode:'USER',actor:'프로그램 A',process:'RUNNING',request:'read(notes.txt)',location:'사용자 코드',returnPoint:'read 다음 명령',returnValue:null,contents:null,done:false,events:[]};},
 step(s,p){if(s.done)return s;const n=structuredClone(s);
  if(p.scenario==='direct'){n.phase=1;n.location='보호 경계';n.returnValue='PROTECTION';n.done=true;return push(n,'USER 모드의 직접 장치 제어를 보호 장치가 막았어요.');}
  if(n.phase===0){n.phase=1;n.mode='KERNEL';n.actor='시스템 콜 진입 코드';n.location='커널 진입점';return push(n,'시스템 콜 진입: USER의 돌아갈 위치와 실행 문맥을 보관했어요.');}
  if(n.phase===1){n.phase=2;n.actor='파일 시스템';n.location='권한·인자 검사';if(p.scenario==='denied')return push(n,'권한 검사에서 읽기 권한이 없음을 확인했어요.');return push(n,'파일 설명자와 읽기 권한을 확인했어요.');}
  if(n.phase===2&&p.scenario==='denied'){n.phase=5;n.mode='USER';n.actor='프로그램 A';n.process='RUNNING';n.location=n.returnPoint;n.returnValue='EACCES';n.done=true;return push(n,'파일 내용 없이 EACCES 오류를 USER 코드로 돌려줬어요.');}
  if(n.phase===2){n.phase=3;n.actor='장치 드라이버';n.process='WAITING';n.location='장치 요청 큐';return push(n,'드라이버에 읽기를 맡기고 프로그램 A는 WAITING이 됐어요.');}
  if(n.phase===3){n.phase=4;n.actor='장치 완료 인터럽트';n.process='READY';n.location='커널 완료 처리';n.contents='HELLO';return push(n,'장치 완료 인터럽트가 도착했고 프로그램 A는 READY가 됐어요.');}
  n.phase=5;n.mode='USER';n.actor='프로그램 A';n.process='RUNNING';n.location=n.returnPoint;n.returnValue='5 bytes';n.done=true;return push(n,'스케줄된 프로그램 A가 보관한 위치에서 실행을 이어가요.');
 },
 describe(s){if(s.done)return s.returnValue==='5 bytes'?'USER 복귀 · HELLO · 5 bytes':s.returnValue==='EACCES'?'USER 복귀 · EACCES · 내용 없음':'USER 모드 직접 장치 접근 차단';return `${s.mode} · ${s.actor} · ${s.process}`;},
 render(s){const steps=['요청 준비','커널 진입','권한 검사','장치 대기','완료 알림','USER 복귀'];return `<div class="syscall-state"><div class="mode-panel ${s.mode.toLowerCase()}"><span>현재 모드</span><strong>${s.mode}</strong><small>${e(s.actor)}</small></div><div class="syscall-facts"><p><span>프로세스</span><strong>${e(s.process)}</strong></p><p><span>요청 위치</span><strong>${e(s.location)}</strong></p><p><span>복귀 지점</span><strong>${e(s.returnPoint)}</strong></p><p><span>반환값</span><strong>${e(s.returnValue??'아직 없음')}</strong></p></div></div><ol class="syscall-steps">${steps.map((v,i)=>`<li class="${i<s.phase?'done ':''}${i===s.phase?'active':''}"><i>${i+1}</i><span>${v}</span></li>`).join('')}</ol><div class="return-card"><div><span>사용자 버퍼</span><strong>${s.contents?e(s.contents):'비어 있음'}</strong></div><div><span>보호 경계</span><strong>${s.mode==='KERNEL'?'커널 안에서 처리 중':s.done?'USER로 돌아옴':'진입 전'}</strong></div></div>`;}
};

const pipeInitial=()=>({capacity:2,pending:['A','B','C'],buffer:[],received:[],writerOpen:true,readerOpen:true,sender:'READY',receiver:'READY',eof:false,failure:null,events:[],done:false});
const pipeWrite=s=>{const n=structuredClone(s);n.failure=null;if(!n.writerOpen){n.failure='쓰기 끝이 이미 닫혔어요.';return push(n,n.failure);}if(!n.readerOpen){n.failure='읽기 끝이 닫혀 쓰기가 실패했어요(EPIPE 모형).';return push(n,n.failure);}if(!n.pending.length)return push(n,'보낼 메시지가 더 없어요.');if(n.buffer.length>=n.capacity){n.sender='WAITING';return push(n,`${n.pending[0]} 쓰기 대기: 버퍼가 가득 찼어요.`);}const message=n.pending.shift();n.buffer.push(message);n.sender='READY';if(n.receiver==='WAITING')n.receiver='READY';return push(n,`${message}를 버퍼에 썼어요.`);};
const pipeRead=s=>{const n=structuredClone(s);n.failure=null;if(!n.readerOpen){n.failure='읽기 끝이 이미 닫혔어요.';return push(n,n.failure);}if(n.buffer.length){const message=n.buffer.shift();n.received.push(message);n.receiver='READY';if(n.sender==='WAITING')n.sender='READY';return push(n,`${message}를 버퍼에서 읽었어요.`);}if(n.writerOpen){n.receiver='WAITING';return push(n,'읽기 대기: 버퍼가 비었지만 작성자가 아직 열려 있어요.');}n.receiver='EOF';n.eof=true;n.done=true;return push(n,'버퍼가 비었고 모든 쓰기 끝이 닫혀 EOF를 읽었어요.');};
CS.labs['pipe-buffer']={
 title:'용량 두 칸 파이프로 A·B·C를 전달하세요',type:'실제 유한 버퍼·종료 규칙 모형',intro:'쓰기와 읽기를 눌러 가득 찬 버퍼의 대기, FIFO 순서, 닫힌 끝의 EOF와 쓰기 실패를 직접 확인해요.',limit:'A·B·C를 한 번의 작은 쓰기 단위로 표시한 모형이에요. 실제 POSIX 파이프는 메시지 경계를 보존하지 않는 바이트 스트림이며 여러 작성자가 있으면 규칙이 더 필요해요.',custom:true,
 initial:pipeInitial,
 action(s,a){if(a==='reset')return pipeInitial();if(a==='write')return pipeWrite(s);if(a==='read')return pipeRead(s);if(a==='close-writer'){const n=structuredClone(s);n.writerOpen=false;n.sender='CLOSED';n.failure=null;return push(n,'쓰기 끝을 닫았어요. 남은 버퍼는 계속 읽을 수 있어요.');}if(a==='close-reader'){const n=structuredClone(s);n.readerOpen=false;n.receiver='CLOSED';n.failure=null;return push(n,'읽기 끝을 닫았어요. 다음 쓰기는 실패해요.');}if(a==='run-normal'){let n=pipeInitial();for(const op of ['write','write','write','read','write','read','read'])n=op==='write'?pipeWrite(n):pipeRead(n);n.writerOpen=false;n.sender='CLOSED';n.events.push('쓰기 끝을 닫았어요.');n=pipeRead(n);return n;}throw Error('알 수 없는 파이프 동작이에요.');},
 describe(s){if(s.failure)return `실패 · ${s.failure}`;if(s.eof)return `수신 ${s.received.join(' → ')} · EOF`;return `버퍼 ${s.buffer.length}/${s.capacity} · 송신자 ${s.sender} · 수신자 ${s.receiver}`;},
 actions(s){return [{id:'write',text:'한 번 쓰기',primary:true,disabled:!s.writerOpen||!s.pending.length},{id:'read',text:'한 번 읽기',disabled:!s.readerOpen},{id:'close-writer',text:'쓰기 끝 닫기',disabled:!s.writerOpen},{id:'close-reader',text:'읽기 끝 닫기',disabled:!s.readerOpen},{id:'run-normal',text:'정상 흐름 끝까지'},{id:'reset',text:'처음부터'}];},
 render(s){const slot=i=>`<span class="${s.buffer[i]?'filled':''}">${s.buffer[i]?e(s.buffer[i]):'빈 칸'}</span>`;return `<div class="pipe-layout"><div class="pipe-peer"><small>송신 프로세스</small><strong>${e(s.sender)}</strong><p>${s.writerOpen?'쓰기 끝 열림':'쓰기 끝 닫힘'}</p></div><div class="pipe-channel"><b>커널 파이프 버퍼</b><div class="pipe-slots">${slot(0)}${slot(1)}</div><small>${s.buffer.length} / ${s.capacity}칸 사용</small></div><div class="pipe-peer"><small>수신 프로세스</small><strong>${e(s.receiver)}</strong><p>${s.readerOpen?'읽기 끝 열림':'읽기 끝 닫힘'}</p></div></div><div class="message-ledger"><div><b>보낼 순서</b><p>${s.pending.map(v=>`<span>${e(v)}</span>`).join('')||'<em>없음</em>'}</p></div><div><b>받은 순서</b><p>${s.received.map(v=>`<span>${e(v)}</span>`).join('')||'<em>없음</em>'}</p></div></div>${s.failure?`<p class="pipe-alert">${e(s.failure)}</p>`:''}${table(['확인','현재 값'],[['버퍼 범위',`${s.buffer.length} ≤ ${s.capacity}`],['쓰기 끝',s.writerOpen?'열림':'닫힘'],['읽기 끝',s.readerOpen?'열림':'닫힘'],['EOF',s.eof?'도착':'아직 아님']])}`;}
};
})();
