(()=>{
const {escape:e,table}=CS.helpers;
const memoryInitial=()=>({addressInput:'2053',addressDirty:false,translation:{phase:0,address:null,page:null,offset:null,tlb:'확인 전',pte:'확인 전',frame:null,physical:null,fault:false,done:false},policy:'fifo',capacity:3,requests:[1,2,3,1,4],cursor:0,frames:[],order:[],hits:0,faults:0,last:null,victim:null,events:[],done:false});
const resetTranslation=s=>{s.translation={phase:0,address:null,page:null,offset:null,tlb:'확인 전',pte:'확인 전',frame:null,physical:null,fault:false,done:false};};
const translateStep=s=>{const n=structuredClone(s);if(n.addressDirty){const raw=String(n.addressInput).trim();if(!/^\d+$/.test(raw)||+raw>8191)throw Error('가상 주소를 0부터 8191까지의 정수로 입력해 주세요.');resetTranslation(n);n.addressDirty=false;}const t=n.translation;if(t.done)return n;if(t.phase===0){const raw=String(n.addressInput).trim();if(!/^\d+$/.test(raw)||+raw>8191)throw Error('가상 주소를 0부터 8191까지의 정수로 입력해 주세요.');t.address=+raw;t.page=Math.floor(t.address/1024);t.offset=t.address%1024;t.phase=1;n.events.push(`${t.address}를 페이지 ${t.page}와 오프셋 ${t.offset}로 나눴어요.`);return n;}if(t.phase===1){t.tlb='MISS';t.phase=2;n.events.push('교육용 빈 TLB에서 변환을 찾지 못해 페이지 테이블을 확인해요.');return n;}if(t.phase===2){if(t.page!==2){t.pte='PRESENT=0';t.fault=true;t.done=true;t.phase=3;n.events.push(`페이지 ${t.page}가 현재 메모리에 없어 페이지 폴트가 발생했어요.`);return n;}t.pte='페이지 2 → 프레임 7';t.frame=7;t.phase=3;n.events.push('페이지 테이블에서 프레임 7 매핑을 찾았어요.');return n;}t.tlb='MISS → 채움';t.physical=t.frame*1024+t.offset;t.done=true;t.phase=4;n.events.push(`프레임 7의 시작 주소와 오프셋을 합쳐 물리 주소 ${t.physical}을 만들었어요.`);return n;};
const replacementStep=s=>{const n=structuredClone(s);if(n.cursor>=n.requests.length){n.done=true;return n;}const page=n.requests[n.cursor++];n.last=page;n.victim=null;const at=n.frames.indexOf(page);if(at>=0){n.hits++;if(n.policy==='lru'){n.order=n.order.filter(v=>v!==page);n.order.push(page);}n.events.push(`${page} 참조: 메모리 히트.`);}else{n.faults++;if(n.frames.length>=n.capacity){n.victim=n.order.shift();n.frames=n.frames.filter(v=>v!==n.victim);n.events.push(`${page} 폴트: ${n.policy==='fifo'?'가장 먼저 들어온':'가장 오래 사용하지 않은'} ${n.victim}을 내보냈어요.`);}else n.events.push(`${page} 폴트: 빈 프레임을 사용했어요.`);n.frames.push(page);n.order.push(page);}if(n.cursor>=n.requests.length)n.done=true;return n;};
CS.labs['virtual-memory']={
 title:'주소를 변환하고 페이지를 교체하세요',type:'실제 주소 계산·교체 정책 모형',intro:'한쪽에서는 가상 주소를 페이지와 오프셋으로 나누고, 다른 쪽에서는 같은 참조열을 FIFO와 LRU로 처리해요.',limit:'페이지 크기 1024B, 페이지2→프레임7인 작은 모형이에요. TLB는 처음 비어 있고, 페이지 교체의 프레임 수는 1~4개로 제한해요.',custom:true,
 initial:memoryInitial,
 action(s,a,data){if(a==='reset')return memoryInitial();if(a==='edit-address'){const n=structuredClone(s);n.addressInput=String(data).slice(0,8);n.addressDirty=true;return n;}if(a==='translate')return translateStep(s);if(a==='translate-all'){let n=structuredClone(s),guard=0;while((n.addressDirty||!n.translation.done)&&guard++<8)n=translateStep(n);return n;}if(a==='policy'){if(!['fifo','lru'].includes(data))throw Error('교체 정책을 다시 골라 주세요.');const n=memoryInitial();n.addressInput=s.addressInput;n.addressDirty=s.addressDirty;n.translation=structuredClone(s.translation);n.policy=data;return n;}if(a==='capacity'){if(!/^[1-4]$/.test(String(data)))throw Error('프레임 수를 1부터 4까지 골라 주세요.');const n=memoryInitial();n.addressInput=s.addressInput;n.addressDirty=s.addressDirty;n.translation=structuredClone(s.translation);n.policy=s.policy;n.capacity=+data;return n;}if(a==='reference')return replacementStep(s);if(a==='reference-all'){let n=structuredClone(s),guard=0;while(!n.done&&guard++<20)n=replacementStep(n);return n;}throw Error('알 수 없는 메모리 동작이에요.');},
 describe(s){const t=s.translation;const left=t.done?(t.fault?`주소 ${t.address} · 페이지 폴트 · 물리 주소 없음`:`주소 ${t.address} · 물리 주소 ${t.physical}`):`주소 변환 ${t.phase}/4`;return `${left} · ${s.policy.toUpperCase()} 히트 ${s.hits} / 폴트 ${s.faults}`;},
 actions(s){return [{id:'translate',text:'주소 변환 한 단계',primary:true,disabled:s.translation.done&&!s.addressDirty},{id:'translate-all',text:'주소 변환 끝까지',disabled:s.translation.done&&!s.addressDirty},{id:'reference',text:'참조 한 단계',primary:true,disabled:s.done},{id:'reference-all',text:'참조 끝까지',disabled:s.done},{id:'reset',text:'처음부터'}];},
 render(s){const t=s.translation;return `<div class="vm-controls"><label>가상 주소<input value="${e(s.addressInput)}" data-action="edit-address" inputmode="numeric"></label><label>교체 정책<select data-action="policy"><option value="fifo" ${s.policy==='fifo'?'selected':''}>FIFO</option><option value="lru" ${s.policy==='lru'?'selected':''}>LRU</option></select></label><label>물리 프레임 수<select data-action="capacity">${[1,2,3,4].map(v=>`<option value="${v}" ${s.capacity===v?'selected':''}>${v}개</option>`).join('')}</select></label></div><div class="vm-panels"><div><b>주소 변환</b><div class="address-bits"><span>페이지 번호<strong>${t.page??'?'}</strong></span><span>오프셋<strong>${t.offset??'?'}</strong></span></div>${table(['검사','결과'],[['TLB',t.tlb],['페이지 테이블',t.pte],['프레임',t.frame??'없음'],['물리 주소',t.physical??'없음']])}</div><div><b>${s.policy.toUpperCase()} 페이지 교체</b><div class="reference-row">${s.requests.map((v,i)=>`<span class="${i<s.cursor?'past ':''}${i===s.cursor-1?'active':''}">${v}</span>`).join('')}</div><div class="memory-frames">${Array.from({length:s.capacity},(_,i)=>`<span class="${s.frames[i]?'filled':''}">${s.frames[i]??'빈 프레임'}</span>`).join('')}</div><p class="small">다음 교체 순서: ${s.order.join(' → ')||'없음'}${s.victim?` · 방금 내보냄 ${s.victim}`:''}</p><div class="vm-score"><span>히트 <b>${s.hits}</b></span><span>폴트 <b>${s.faults}</b></span></div></div></div>`;}
};

const journalInitial=(preset='normal')=>({preset,fileName:preset==='empty'?'empty.txt':'note.txt',file:preset==='empty'?'':'A',intended:'B',size:preset==='empty'?0:1,inode:41,blocks:preset==='empty'?[]:[12],journal:null,committed:false,homeApplied:false,phase:0,crashed:false,recovered:false,error:null,events:[],done:false});
CS.labs['journal-recovery']={
 title:'파일 변경 중 멈추고 저널로 복구하세요',type:'전체 데이터 저널링 단순 모형',intro:'A를 B로 바꾸는 기록·커밋·최종 반영 사이에서 장애를 일으켜 어떤 내용이 확정되는지 확인해요.',limit:'데이터와 관련 메타데이터를 함께 저널링한다고 단순화한 모형이에요. 실제 파일 시스템의 저널 모드·쓰기 순서·장치 보장은 제품과 설정에 따라 달라요.',custom:true,
 initial:()=>journalInitial(),
 action(s,a,data){if(a==='reset')return journalInitial();if(a==='preset'){if(!['normal','empty','no-space'].includes(data))throw Error('파일 조건을 다시 골라 주세요.');return journalInitial(data);}if(a==='step'){const n=structuredClone(s);if(n.crashed||n.done)return n;if(n.preset==='no-space'){n.error='ENOSPC';n.done=true;n.events.push('공간이 없어 변경을 시작하지 않고 기존 A를 보존했어요.');return n;}if(n.phase===0){n.journal={content:n.intended,metadata:`size=${n.intended.length}`};n.phase=1;n.events.push('새 내용 B와 메타데이터를 저널에 기록했어요.');return n;}if(n.phase===1){n.committed=true;n.phase=2;n.events.push('저널 커밋 표식을 기록해 변경을 복구 가능한 상태로 만들었어요.');return n;}n.file=n.intended;n.size=n.file.length;n.blocks=n.file.length?[18]:[];n.homeApplied=true;n.phase=3;n.done=true;n.events.push('커밋된 변경을 파일의 최종 위치에 반영했어요.');return n;}if(a==='crash'){const n=structuredClone(s);if(n.done&&n.error)return n;n.crashed=true;n.done=false;n.events.push(`단계 ${n.phase}에서 전원이 끊겼어요.`);return n;}if(a==='recover'){const n=structuredClone(s);if(!n.crashed)throw Error('먼저 장애를 발생시켜 주세요.');if(n.committed&&n.journal){n.file=n.journal.content;n.size=n.file.length;n.blocks=n.file.length?[18]:[];n.homeApplied=true;n.events.push('커밋 표식이 있어 저널의 B를 최종 위치에 다시 반영했어요.');}else{n.journal=null;n.events.push('커밋되지 않은 저널 기록을 버리고 기존 확정 내용으로 돌아왔어요.');}n.crashed=false;n.recovered=true;n.done=true;return n;}if(a==='run-normal'){let n=journalInitial(s.preset);for(let i=0;i<3&&!n.done;i++)n=this.action(n,'step');return n;}throw Error('알 수 없는 저널 동작이에요.');},
 describe(s){if(s.error)return `${s.error} · 기존 파일 ${s.file||'0B'} 보존`;if(s.crashed)return `장애 발생 · 커밋 ${s.committed?'있음':'없음'} · 복구 필요`;if(s.recovered)return `복구 완료 · 확정 내용 ${s.file||'0B'}`;if(s.done)return `정상 반영 완료 · 확정 내용 ${s.file||'0B'}`;return `단계 ${s.phase}/3 · 파일 ${s.file||'0B'} · 커밋 ${s.committed?'있음':'없음'}`;},
 actions(s){return [{id:'step',text:'한 단계',primary:true,disabled:s.crashed||s.done},{id:'crash',text:'지금 장애 발생',disabled:s.crashed||!!s.error},{id:'recover',text:'재시작·복구',primary:s.crashed,disabled:!s.crashed},{id:'run-normal',text:'정상 저장 끝까지',disabled:s.crashed},{id:'reset',text:'처음부터'}];},
 render(s){return `<label class="journal-preset">파일 조건<select data-action="preset"><option value="normal" ${s.preset==='normal'?'selected':''}>A를 B로 변경</option><option value="empty" ${s.preset==='empty'?'selected':''}>0바이트 파일에서 시작</option><option value="no-space" ${s.preset==='no-space'?'selected':''}>저장 공간 부족</option></select></label><div class="journal-path"><div><small>디렉터리 항목</small><strong>${e(s.fileName)} → inode ${s.inode}</strong></div><i>→</i><div><small>메타데이터</small><strong>${s.size}B · 블록 ${s.blocks.join(', ')||'없음'}</strong></div></div><div class="journal-stages"><div class="${s.phase>=1?'active':''}"><span>1</span><b>저널 기록</b><small>${s.journal?`내용 ${e(s.journal.content)}`:'비어 있음'}</small></div><div class="${s.committed?'active':''}"><span>2</span><b>커밋 표식</b><small>${s.committed?'확정됨':'아직 없음'}</small></div><div class="${s.homeApplied?'active':''}"><span>3</span><b>최종 위치</b><small>내용 ${s.file?e(s.file):'0B'}</small></div></div><div class="journal-result"><p><span>현재 확정 파일</span><strong>${s.file?e(s.file):'0바이트'}</strong></p><p><span>시스템 상태</span><strong>${s.error??(s.crashed?'전원 꺼짐':s.recovered?'복구 완료':'동작 중')}</strong></p></div>`;}
};
})();
