(()=>{
const {escape:e,table}=CS.helpers;
const counterInitial=(mode='unsafe',workers=2)=>({mode,workers,counter:100,lockOwner:null,tasks:{A:{read:null,wrote:false,status:'READY'},B:{read:null,wrote:false,status:workers===1?'DISABLED':'READY'}},events:[],done:false});
const counterAct=(s,a)=>{const n=structuredClone(s),match=/^(read|write|acquire|release)-([ab])$/.exec(a);if(!match)throw Error('알 수 없는 카운터 동작이에요.');const op=match[1],id=match[2].toUpperCase(),t=n.tasks[id];if(id==='B'&&n.workers===1)throw Error('작업자 한 명 모드에서는 B가 실행되지 않아요.');if(op==='acquire'){if(n.mode!=='locked')throw Error('잠금 모드에서만 잠금을 얻어요.');if(n.lockOwner&&n.lockOwner!==id){t.status='WAITING';n.events.push(`${id}는 ${n.lockOwner}가 잠금을 놓을 때까지 기다려요.`);return n;}n.lockOwner=id;t.status='IN CRITICAL SECTION';n.events.push(`${id}가 잠금을 얻었어요.`);return n;}if(op==='release'){if(n.lockOwner!==id)throw Error(`${id}는 자신이 소유하지 않은 잠금을 해제할 수 없어요.`);n.lockOwner=null;t.status=t.wrote?'DONE':'READY';n.events.push(`${id}가 잠금을 해제했어요.`);return n;}if(n.mode==='locked'&&n.lockOwner!==id)throw Error(`${id}가 읽거나 쓰기 전에 잠금을 얻어야 해요.`);if(op==='read'){if(t.wrote)throw Error(`${id}는 이미 증가 작업을 마쳤어요.`);t.read=n.counter;t.status='LOCAL VALUE READY';n.events.push(`${id}가 공유 값 ${n.counter}을 읽었어요.`);return n;}if(t.read===null)throw Error(`${id}가 쓰기 전에 공유 값을 읽어야 해요.`);n.counter=t.read+1;t.wrote=true;t.status=n.mode==='locked'?'IN CRITICAL SECTION':'DONE';n.events.push(`${id}가 로컬 계산 ${t.read}+1=${n.counter}을 공유 값에 썼어요.`);n.done=n.tasks.A.wrote&&(n.workers===1||n.tasks.B.wrote);return n;};
CS.labs['counter-race']={
 title:'두 작업이 같은 카운터를 늘리는 순서를 바꿔 보세요',type:'실제 읽기·계산·쓰기 경쟁 모형',intro:'공유 값100을 A와 B가 각각 한 번 늘려요. 보호 없이 겹쳐 읽은 결과와 잠금으로 임계 구역을 나눈 결과를 비교해요.',limit:'증가를 읽기와 쓰기로 나눈 교육 모형이에요. 실제 CPU·언어의 원자성 및 메모리 순서 보장은 연산과 플랫폼에 따라 다르므로 동기화 API의 계약을 따라야 해요.',custom:true,
 initial:counterInitial,
 action(s,a,data){if(a==='reset')return counterInitial();if(a==='mode'){if(!['unsafe','locked'].includes(data))throw Error('실행 모드를 다시 골라 주세요.');return counterInitial(data,s.workers);}if(a==='workers'){if(!['1','2'].includes(String(data)))throw Error('작업자 수를 다시 골라 주세요.');return counterInitial(s.mode,+data);}if(a==='run-race'){let n=counterInitial('unsafe',s.workers);for(const op of n.workers===1?['read-a','write-a']:['read-a','read-b','write-a','write-b'])n=counterAct(n,op);return n;}if(a==='run-locked'){let n=counterInitial('locked',s.workers);for(const op of ['acquire-a','read-a','write-a','release-a',...(n.workers===2?['acquire-b','read-b','write-b','release-b']:[])])n=counterAct(n,op);return n;}return counterAct(s,a);},
 describe(s){if(s.done)return `${s.mode==='locked'?'잠금 보호':'보호 없음'} 완료 · 최종 공유 값 ${s.counter} · 증가 ${s.counter-100}/작업 ${s.workers}`;return `공유 값 ${s.counter} · 잠금 ${s.lockOwner??'비어 있음'}`;},
 actions(s){const disabledB=s.workers===1;return [{id:'read-a',text:'A 읽기'},{id:'read-b',text:'B 읽기',disabled:disabledB},{id:'write-a',text:'A 쓰기',primary:true},{id:'write-b',text:'B 쓰기',primary:true,disabled:disabledB},{id:'acquire-a',text:'A 잠금 얻기',disabled:s.mode!=='locked'},{id:'acquire-b',text:'B 잠금 얻기',disabled:s.mode!=='locked'||disabledB},{id:'release-a',text:'A 잠금 해제',disabled:s.mode!=='locked'},{id:'release-b',text:'B 잠금 해제',disabled:s.mode!=='locked'||disabledB},{id:'run-race',text:'경쟁 순서 끝까지'},{id:'run-locked',text:'잠금 순서 끝까지'},{id:'reset',text:'처음부터'}];},
 render(s){const task=id=>{const t=s.tasks[id];return `<div class="counter-task ${t.status==='WAITING'?'waiting':''}"><small>작업 ${id}</small><strong>${e(t.status)}</strong><p>읽은 값 <b>${t.read??'없음'}</b></p><p>썼는가 <b>${t.wrote?'예':'아니요'}</b></p></div>`;};return `<div class="counter-settings"><label>보호 방식<select data-action="mode"><option value="unsafe" ${s.mode==='unsafe'?'selected':''}>보호 없음</option><option value="locked" ${s.mode==='locked'?'selected':''}>뮤텍스 잠금</option></select></label><label>작업자 수<select data-action="workers"><option value="2" ${s.workers===2?'selected':''}>A와 B · 2명</option><option value="1" ${s.workers===1?'selected':''}>A만 · 1명</option></select></label></div><div class="counter-live">${task('A')}<div class="shared-counter"><small>공유 counter</small><strong>${s.counter}</strong><span>잠금 소유자<br><b>${s.lockOwner??'없음'}</b></span></div>${task('B')}</div>${table(['불변식 확인','현재'],[['완료한 증가',`${s.counter-100} / ${s.workers}`],['동시에 임계 구역 안',s.lockOwner?`${s.lockOwner} 한 명`:'없음'],['최종 기대값',`${100+s.workers}`]])}`;}
};

const deadlockInitial=(mode='opposite',workers=2)=>({mode,workers,resources:{X:null,Y:null},tasks:{A:{held:[],waiting:null,done:false,steps:0},B:{held:[],waiting:null,done:workers===1,steps:0}},condition:'RUNNING',progress:0,events:[],round:0});
const planFor=(s,id)=>s.mode==='ordered'?['X','Y']:id==='A'?['X','Y']:['Y','X'];
const detect=s=>{const a=s.tasks.A,b=s.tasks.B;if(s.workers===2&&a.waiting&&b.waiting&&s.resources[a.waiting]==='B'&&s.resources[b.waiting]==='A')s.condition='DEADLOCK';else if(a.done&&b.done)s.condition='COMPLETE';else s.condition='RUNNING';return s;};
const nextWorker=(s,id)=>{const n=structuredClone(s),t=n.tasks[id];if(id==='B'&&n.workers===1)throw Error('작업자 한 명 모드에서는 B가 없어요.');if(t.done)return n;const plan=planFor(n,id);if(t.waiting){if(n.resources[t.waiting]){n.events.push(`${id}는 ${t.waiting}을 계속 기다려요.`);return detect(n);}const r=t.waiting;n.resources[r]=id;t.held.push(r);t.waiting=null;t.steps++;n.events.push(`${id}가 기다리던 ${r}을 얻었어요.`);return detect(n);}if(t.held.length<2){const r=plan[t.held.length];if(n.resources[r]){t.waiting=r;n.events.push(`${id}가 ${r}을 요청했지만 ${n.resources[r]}가 가지고 있어요.`);return detect(n);}n.resources[r]=id;t.held.push(r);t.steps++;n.events.push(`${id}가 ${r}을 얻었어요.`);return detect(n);}for(const r of t.held)n.resources[r]=null;t.held=[];t.done=true;t.steps++;n.progress++;n.events.push(`${id}가 작업을 끝내고 두 자원을 돌려줬어요.`);return detect(n);};
CS.labs['deadlock-progress']={
 title:'두 작업이 X와 Y를 얻는 순서를 조작하세요',type:'실제 자원 소유·대기 그래프 모형',intro:'A와 B가 서로 다른 순서로 자원을 얻으면 대기 순환이 생겨요. 같은 순서를 사용하면 한 작업이 끝난 뒤 다른 작업이 진행해요.',limit:'각 자원은 하나뿐이고 작업은 두 자원을 모두 얻어야 끝나는 모형이에요. 긴 대기만으로 교착이라 하지 않고 실제 소유·대기 순환을 검사해요.',custom:true,
 initial:deadlockInitial,
 action(s,a,data){if(a==='reset')return deadlockInitial();if(a==='mode'){if(!['opposite','ordered'].includes(data))throw Error('획득 규칙을 다시 골라 주세요.');return deadlockInitial(data,s.workers);}if(a==='workers'){if(!['1','2'].includes(String(data)))throw Error('작업자 수를 다시 골라 주세요.');return deadlockInitial(s.mode,+data);}if(a==='next-a')return nextWorker(s,'A');if(a==='next-b')return nextWorker(s,'B');if(a==='run-deadlock'){let n=deadlockInitial('opposite',s.workers);if(n.workers===1){for(let i=0;i<3;i++)n=nextWorker(n,'A');return n;}for(const [id] of [['A'],['B'],['A'],['B']])n=nextWorker(n,id);return n;}if(a==='run-safe'){let n=deadlockInitial('ordered',s.workers);if(n.workers===1){for(let i=0;i<3;i++)n=nextWorker(n,'A');return n;}for(const id of ['A','B','A','A','B','B','B'])n=nextWorker(n,id);return n;}if(a==='steal'){const n=structuredClone(s),owner=n.resources.X;if(owner&&owner!=='B')throw Error(`B는 A가 소유한 X를 즉시 빼앗을 수 없어요.`);throw Error('현재 B가 빼앗을 상대 소유의 X가 없어요.');}if(a==='livelock'){const n=deadlockInitial('opposite',2);n.condition='LIVELOCK';n.round=4;n.events=['A와 B가 충돌을 피하려고 동시에 놓았어요.','둘 다 동시에 다시 시도했어요.','네 번 양보했지만 완료한 작업은 없어요.'];return n;}if(a==='starvation'){const n=deadlockInitial('ordered',2);n.condition='STARVATION RISK';n.progress=3;n.round=3;n.tasks.A.done=true;n.tasks.B.waiting='X';n.resources.X='A';n.events=['A가 X를 세 번 연속 먼저 얻었어요.','B는 계속 준비됐지만 X를 얻지 못했어요.'];return n;}throw Error('알 수 없는 자원 동작이에요.');},
 describe(s){if(s.condition==='DEADLOCK')return '교착 상태 · A와 B의 대기 순환 · 완료 0';if(s.condition==='COMPLETE')return `완료 · 작업 ${s.progress}/${s.workers} · 대기 순환 없음`;if(s.condition==='LIVELOCK')return `라이브락 · 상태 변화 ${s.round}회 · 완료 0`;if(s.condition==='STARVATION RISK')return '기아 위험 · A는 반복 진행 · B는 계속 대기';return `진행 중 · 완료 ${s.progress}/${s.workers}`;},
 actions(s){return [{id:'next-a',text:'A 다음 행동',primary:true},{id:'next-b',text:'B 다음 행동',primary:true,disabled:s.workers===1},{id:'run-deadlock',text:'대기 순환 만들기'},{id:'run-safe',text:'순서 통일 끝까지'},{id:'steal',text:'B가 X 빼앗기'},{id:'livelock',text:'라이브락 보기'},{id:'starvation',text:'기아 보기'},{id:'reset',text:'처음부터'}];},
 render(s){const worker=id=>{const t=s.tasks[id];return `<div class="resource-worker ${t.waiting?'waiting':''}"><small>작업 ${id}</small><strong>${t.done?'DONE':t.waiting?`${t.waiting} WAIT`:'READY'}</strong><p>보유 ${t.held.join(', ')||'없음'}</p></div>`;};return `<div class="resource-settings"><label>획득 규칙<select data-action="mode"><option value="opposite" ${s.mode==='opposite'?'selected':''}>A:X→Y · B:Y→X</option><option value="ordered" ${s.mode==='ordered'?'selected':''}>모두 X→Y</option></select></label><label>작업자 수<select data-action="workers"><option value="2" ${s.workers===2?'selected':''}>A와 B · 2명</option><option value="1" ${s.workers===1?'selected':''}>A만 · 1명</option></select></label></div><div class="resource-live">${worker('A')}<div class="resource-pool"><span class="${s.resources.X?'owned':''}">X<small>${s.resources.X?`${s.resources.X} 소유`:'비어 있음'}</small></span><span class="${s.resources.Y?'owned':''}">Y<small>${s.resources.Y?`${s.resources.Y} 소유`:'비어 있음'}</small></span></div>${worker('B')}</div><div class="wait-graph ${s.condition.toLowerCase().replace(/\s/g,'-')}"><b>현재 판정 ${e(s.condition)}</b><p>A ${s.tasks.A.waiting?`→ ${s.tasks.A.waiting} 대기`:'대기 없음'} · B ${s.tasks.B.waiting?`→ ${s.tasks.B.waiting} 대기`:'대기 없음'}</p><small>완료한 작업 ${s.progress} · 상태 변화/반복 ${s.round}</small></div>`;}
};
})();
