(()=>{
const {escape:e,table}=CS.helpers;
const modelInitial=()=>({members:[{id:'S1',name:'민지'},{id:'S2',name:'민지'}],books:[{id:'B01',title:'컴퓨터 첫걸음'},{id:'B02',title:'자료구조 이야기'}],loans:[{id:'T1',memberId:'S1',bookId:'B01'},{id:'T2',memberId:'S1',bookId:'B02'}],flatRows:[{loanId:'T1',memberId:'S1',memberName:'민지',bookId:'B01',bookTitle:'컴퓨터 첫걸음'},{loanId:'T2',memberId:'S1',memberName:'민지',bookId:'B02',bookTitle:'자료구조 이야기'}],view:'relations',linked:false,anomaly:false,events:[]});
CS.labs['relation-designer']={custom:true,title:'회원·도서·대출의 연결을 지켜 보세요',type:'관계와 제약을 보여 주는 브라우저 상태 모형',intro:'동명이인을 ID로 구별하고, 회원 이름을 바꿔도 대출 연결이 유지되는지 확인해요. 중복을 한 표에 모았을 때 생기는 수정 이상도 비교해요.',limit:'관계와 제약을 설명하는 JavaScript 모형이에요. 실제 DBMS는 아니며 삭제 규칙·복합키·지연 제약은 생략했어요.',
 initial:modelInitial,
 action(s,a){if(a==='reset')return modelInitial();const n=structuredClone(s);if(a==='link'){n.view='relations';n.linked=true;n.events.push('대출의 회원ID와 도서ID를 각각 기본키에 연결했어요.');}else if(a==='rename'){n.view='relations';n.members.find(m=>m.id==='S1').name='서민지';n.linked=true;n.events.push('회원 S1의 이름 한 곳만 바꿨어요. T1·T2는 여전히 S1을 가리켜요.');}else if(a==='add-unlinked'){if(!n.members.some(m=>m.id==='S3'))n.members.push({id:'S3',name:'도윤'});n.view='relations';n.events.push('대출 기록이 0건인 회원 S3도 정상적으로 존재해요.');}else if(a==='flat'){n.view='flat';n.events.push('대출마다 회원 이름과 책 제목을 복사한 한 표를 열었어요.');}else if(a==='flat-update'){n.view='flat';n.flatRows[0].memberName='서민지';n.anomaly=true;n.events.push('첫 행만 이름을 바꿔 같은 S1이 두 이름으로 보이는 수정 이상이 생겼어요.');}else if(a==='duplicate')throw Error('기본키 오류: 회원 S1은 이미 존재해요. 같은 이름은 가능하지만 같은 ID는 중복될 수 없어요.');else if(a==='missing')throw Error('외래키 오류: 존재하지 않는 도서 B99를 대출이 참조할 수 없어요.');else throw Error('알 수 없는 관계 동작이에요.');return n;},
 describe(s){return s.events.at(-1)||'회원2명·도서2권·대출2건이 키로 구별되어 있어요.';},
 actions(s){return [{id:'link',text:'키로 연결 보기',primary:true},{id:'rename',text:'S1 이름 변경'},{id:'add-unlinked',text:'대출 0건 회원 추가'},{id:'flat',text:'중복 한 표 보기'},{id:'flat-update',text:'한 행만 수정'},{id:'duplicate',text:'중복 S1 추가'},{id:'missing',text:'없는 B99 연결'},{id:'reset',text:'처음부터'}];},
 render(s){if(s.view==='flat')return `<div class="model-note ${s.anomaly?'danger':''}"><b>${s.anomaly?'수정 이상 발생':'중복된 한 표'}</b><span>${s.anomaly?'S1의 이름이 행마다 달라졌어요.':'S1의 이름과 책 제목이 대출마다 반복돼요.'}</span></div>${table(['대출ID','회원ID','회원 이름','도서ID','도서 제목'],s.flatRows.map(r=>[e(r.loanId),e(r.memberId),e(r.memberName),e(r.bookId),e(r.bookTitle)]))}<p class="small">중복 자체가 언제나 오류는 아니지만, 같은 사실을 여러 곳에서 따로 고치면 불일치 위험이 커져요.</p>`;const joined=s.loans.map(l=>{const m=s.members.find(x=>x.id===l.memberId),b=s.books.find(x=>x.id===l.bookId);return [l.id,l.memberId,m?.name||'없음',l.bookId,b?.title||'없음'];});return `<div class="relation-tables"><section><b>members</b>${table(['id · PK','name'],s.members.map(m=>[e(m.id),e(m.name)]))}</section><section><b>books</b>${table(['id · PK','title'],s.books.map(b=>[e(b.id),e(b.title)]))}</section><section><b>loans</b>${table(['id · PK','member_id · FK','book_id · FK'],s.loans.map(l=>[e(l.id),e(l.memberId),e(l.bookId)]))}</section></div>${s.linked?`<h4>키를 따라 연결한 결과</h4>${table(['대출','회원ID','회원 이름','도서ID','도서 제목'],joined.map(r=>r.map(e)))}<p class="small">민지라는 이름이 같은 S1·S2도 ID로 구별돼요. 이름이 바뀌어도 대출의 S1 참조는 유지돼요.</p>`:'<p class="small">대출 표는 이름이나 제목을 복사하지 않고 식별자를 참조해요.</p>'}`;}
};

const SQL={
 top:`SELECT m.id, m.name, COUNT(l.book_id) AS loan_count\nFROM members AS m\nLEFT JOIN loans AS l ON l.member_id = m.id\nGROUP BY m.id, m.name\nORDER BY loan_count DESC, m.id;`,
 join:`SELECT l.member_id, m.name, l.book_id, b.title\nFROM loans AS l\nJOIN members AS m ON m.id = l.member_id\nJOIN books AS b ON b.id = l.book_id\nORDER BY l.book_id;`,
 wrong:`SELECT l.book_id, m.id, m.name\nFROM loans AS l\nJOIN members AS m ON m.id = m.id\nORDER BY l.book_id, m.id;`,
 empty:`SELECT member_id, book_id\nFROM loans\nWHERE member_id = 'M9'\nORDER BY book_id;`,
 nulls:`SELECT book_id, returned_at, returned_at IS NULL AS still_on_loan\nFROM loans\nORDER BY book_id;`,
 invalid:`SELEC member_id FROM loans;`
};
const sqlInitial=()=>({sql:SQL.top,result:null,preset:'top',events:[]});
CS.labs['sql-analytics']={custom:true,async:true,title:'실제 SQLite에 질문을 보내 보세요',type:'실제 SQLite 3 · 브라우저 내 실행',intro:'회원별 대출 수를 구한 뒤 올바른 JOIN과 연결 조건이 빠진 JOIN을 비교해요. SQL을 직접 고쳐 실행해도 좋아요.',limit:'매번 새 교육용 DB에서 SQL 전체를 실행해요. 외부 서버로 보내지 않으며 실행 사이의 변경은 유지되지 않아요. 최대4,000자·결과200행·5초예요.',
 initial:sqlInitial,
 async action(s,a,data,context){if(a==='reset')return sqlInitial();if(a==='edit')return {...s,sql:data};if(a.startsWith('preset-')){const preset=a.slice(7);if(!SQL[preset])throw Error('알 수 없는 SQL 예시예요.');return {sql:SQL[preset],result:null,preset,events:[preset==='wrong'?'연결 조건이 사실상 항상 참인 잘못된 JOIN을 준비했어요. 행 수를 확인하세요.':'SQL 예시를 바꿨어요. 실행해 결과를 확인하세요.']};}if(a!=='run')throw Error('SQL 실행 동작을 확인해 주세요.');if(!s.sql.trim()||s.sql.length>4000)throw Error('SQL은1~4,000자로 입력해 주세요.');const result=await CS.helpers.executeSQL(s.sql,context?.signal);return {...s,result,events:[`SQLite ${result.version} 실행 완료 · 결과 표 ${result.results.length}개${result.truncated?' · 200행에서 중단':''}`]};},
 describe(s){return s.events.at(-1)||'기본 쿼리는 M1=2, M2=1을 계산해요.';},
 actions(){return [{id:'run',text:'SQL 실행',primary:true},{id:'preset-top',text:'회원별 집계'},{id:'preset-join',text:'올바른 JOIN'},{id:'preset-wrong',text:'조건 빠진 JOIN'},{id:'preset-empty',text:'0행 조회'},{id:'preset-nulls',text:'NULL 확인'},{id:'preset-invalid',text:'문법 오류'},{id:'reset',text:'기본 SQL'}];},
 render(s){const output=s.result?s.result.results.map((r,i)=>`<h4>결과 ${i+1} · ${r.rows.length}행</h4>${r.rows.length?table(r.columns.map(e),r.rows.map(row=>row.map(v=>v===null?'<em>NULL</em>':e(v)))):`${table(r.columns.map(e),[])}<p>조건에 맞는 행이 없어요. 원본 행이 삭제된 뜻은 아니에요.</p>`}`).join('')||'<p>실행은 끝났지만 결과 표를 반환하는 문장은 없었어요.</p>':'<p>실행 전이에요. 버튼으로 예시를 고르거나 SQL을 직접 고쳐 보세요.</p>';return `<label class="field sql-editor">SQL 입력<textarea data-action="edit" rows="8" maxlength="4000" spellcheck="false">${e(s.sql)}</textarea></label><details class="more"><summary>예제 스키마와 데이터</summary><div class="more-body"><p>members: M1 민지, M2 준호</p><p>books: B1·B2·B3</p><p>loans: M1–B1, M1–B2, M2–B3 · returned_at은 B2만 날짜, 나머지는 NULL</p></div></details><div class="sql-output">${output}</div>`;}
};
})();
