(()=>{
const {escape:e,table}=CS.helpers;
const isoInitial=(mode='statement')=>({mode,committed:[{version:1,value:100}],t1:{reads:[],snapshot:null,ended:false},t2:{pending:null,ended:false},events:[]});
const visible=s=>{if(s.mode==='transaction'&&s.t1.snapshot!==null)return s.committed.find(v=>v.version===s.t1.snapshot).value;return s.committed.at(-1).value;};
const isoStep=(s,a)=>{const n=structuredClone(s);if(a==='t1-read'){if(n.t1.ended)throw Error('종료된 T1은 다시 읽을 수 없어요.');if(n.t1.reads.length>=2)throw Error('T1은 이미 두 번 읽었어요.');if(n.mode==='transaction'&&n.t1.snapshot===null)n.t1.snapshot=n.committed.at(-1).version;const value=visible(n);n.t1.reads.push(value);n.events.push(`T1의 ${n.t1.reads.length}번째 읽기 = ${value} · ${n.mode==='statement'?'문장 시작 시점':'T1 시작 스냅샷'}`);}else if(a==='t2-write'){if(n.t2.ended)throw Error('종료된 T2는 다시 쓸 수 없어요.');if(n.t2.pending!==null)throw Error('T2는 이미120을 변경 중이에요.');n.t2.pending=120;n.events.push('T2가120을 썼지만 아직 커밋하지 않았어요. T1에는 보이지 않아요.');}else if(a==='t2-commit'){if(n.t2.ended)throw Error('T2는 이미 종료됐어요.');if(n.t2.pending===null)throw Error('T2가 먼저 값을 변경해야 해요.');n.committed.push({version:n.committed.at(-1).version+1,value:n.t2.pending});n.t2.pending=null;n.t2.ended=true;n.events.push('T2 COMMIT · 확정 버전2의 값120이 생겼어요.');}else if(a==='t1-end'){if(n.t1.ended)throw Error('T1은 이미 종료됐어요.');n.t1.ended=true;n.events.push('T1을 종료했어요.');}else throw Error('알 수 없는 격리 동작이에요.');return n;};
CS.labs['isolation-snapshots']={custom:true,title:'T1이 두 번 읽는 사이 T2를 커밋해 보세요',type:'가시성 규칙을 명시한 스냅샷 모형',intro:'문장마다 최신 확정 버전을 보는 모형과 T1 시작 스냅샷을 유지하는 모형을 비교해요. 미확정120은 어느 모형에서도 보이지 않아요.',limit:'제품 이름을 흉내 내지 않고 두 스냅샷 규칙만 비교해요. 실제 격리 수준의 쓰기 충돌·잠금·직렬화 실패는 DBMS마다 다를 수 있어요.',
 initial:()=>isoInitial(),
 action(s,a,data){if(a==='reset')return isoInitial();if(a==='mode'){if(!['statement','transaction'].includes(data))throw Error('스냅샷 규칙을 목록에서 선택해 주세요.');return isoInitial(data);}if(a==='run-statement'||a==='run-transaction'){let n=isoInitial(a==='run-statement'?'statement':'transaction');for(const step of ['t1-read','t2-write','t2-commit','t1-read'])n=isoStep(n,step);return n;}if(a==='show-uncommitted'){let n=isoInitial(s.mode);n=isoStep(n,'t1-read');n=isoStep(n,'t2-write');n=isoStep(n,'t1-read');return n;}return isoStep(s,a);},
 describe(s){return s.events.at(-1)||'확정 버전1의 값은100이에요. T1의 첫 읽기부터 시작하세요.';},
 actions(){return [{id:'t1-read',text:'T1 읽기',primary:true},{id:'t2-write',text:'T2가120 쓰기'},{id:'t2-commit',text:'T2 커밋'},{id:'t1-end',text:'T1 종료'},{id:'run-statement',text:'문장 스냅샷 끝까지'},{id:'run-transaction',text:'T1 스냅샷 끝까지'},{id:'show-uncommitted',text:'커밋 전 두 번 읽기'},{id:'reset',text:'처음부터'}];},
 render(s){return `<label class="field iso-mode">가시성 규칙<select data-action="mode"><option value="statement" ${s.mode==='statement'?'selected':''}>문장마다 최신 확정 버전</option><option value="transaction" ${s.mode==='transaction'?'selected':''}>T1 시작 스냅샷 유지</option></select></label><div class="snapshot-live"><section><small>T1</small><b>읽은 값 ${s.t1.reads.join(' → ')||'없음'}</b><span>스냅샷 ${s.t1.snapshot??'문장별'}</span></section><div><small>확정 버전</small>${s.committed.map(v=>`<b>v${v.version} = ${v.value}</b>`).join('')}<em>미확정 ${s.t2.pending??'없음'}</em></div><section><small>T2</small><b>${s.t2.ended?'COMMITTED':s.t2.pending!==null?'120 변경 중':'ACTIVE'}</b><span>미확정 값은 숨김</span></section></div>${table(['검사','현재'],[['T1 첫 읽기',s.t1.reads[0]??'아직'],['T1 둘째 읽기',s.t1.reads[1]??'아직'],['더티 리드',s.t1.reads.includes(s.t2.pending)&&s.t2.pending!==null?'발생':'없음'],['종료 상태',`T1 ${s.t1.ended?'종료':'활성'} · T2 ${s.t2.ended?'종료':'활성'}`]])}`;}
};

const walInitial=()=>({memory:100,disk:100,log:[],durable:0,txn:'READY',crashed:false,recovered:false,events:[]});
const walStep=(s,a)=>{const n=structuredClone(s);if(a==='begin'){if(n.txn!=='READY')throw Error('새 거래를 시작할 수 없는 상태예요.');n.txn='ACTIVE';n.log.push('BEGIN T1');n.events.push('BEGIN 로그를 메모리에 기록했어요.');}else if(a==='update'){if(n.txn!=='ACTIVE')throw Error('먼저 거래를 시작해야 해요.');if(n.log.some(x=>x.startsWith('UPDATE')))throw Error('변경 로그는 이미 있어요.');n.memory=120;n.log.push('UPDATE T1 100→120');n.events.push('메모리 값120과 UPDATE 로그가 생겼어요. 저장 값은100이에요.');}else if(a==='flush'){if(n.crashed)throw Error('장애 상태에서는 로그를 내구화할 수 없어요.');n.durable=n.log.length;n.events.push(`로그 ${n.durable}개를 내구화했어요.`);}else if(a==='commit'){if(n.txn!=='ACTIVE')throw Error('활성 거래만 커밋할 수 있어요.');n.log.push('COMMIT T1');n.txn='COMMITTING';n.events.push('COMMIT 로그를 만들었어요. 내구화 전에는 완료를 보장하지 않아요.');}else if(a==='crash'){if(n.crashed)throw Error('이미 장애가 발생했어요.');n.log=n.log.slice(0,n.durable);n.memory=n.disk;n.txn='CRASHED';n.crashed=true;n.events.push('장애 · 내구화되지 않은 로그와 메모리 변경이 사라졌어요.');}else if(a==='recover'){if(!n.crashed)throw Error('장애 뒤에 복구를 실행해요.');const committed=n.log.includes('COMMIT T1'),updated=n.log.some(x=>x.startsWith('UPDATE'));n.disk=committed&&updated?120:100;n.memory=n.disk;n.txn='RECOVERED';n.recovered=true;n.events.push(committed&&updated?'내구화된 UPDATE와 COMMIT을 재실행해120을 복원했어요.':updated?'내구화된 COMMIT이 없어 미완료 변경을 반영하지 않았어요. 값100을 유지해요.':'확정할 변경이 없어 원래 값100을 유지해요.');}else throw Error('알 수 없는 WAL 동작이에요.');return n;};
CS.labs['wal-recovery']={custom:true,title:'커밋 로그의 내구화 시점을 바꿔 복구하세요',type:'학습용 WAL redo 복구 모형',intro:'값100을120으로 바꾸는 T1의 로그를 먼저 내구화하고 장애를 냅니다. COMMIT 로그가 내구화됐는지에 따라 복구 결과가 달라져요.',limit:'redo 핵심만 보여 주는 모형이에요. 실제 DBMS의 LSN·페이지LSN·undo·체크포인트·동시 복구·저장장치 보장은 생략했어요.',
 initial:walInitial,
 action(s,a){if(a==='reset')return walInitial();if(a==='run-before'){let n=walInitial();for(const step of ['begin','update','flush','commit','crash','recover'])n=walStep(n,step);return n;}if(a==='run-after'){let n=walInitial();for(const step of ['begin','update','flush','commit','flush','crash','recover'])n=walStep(n,step);return n;}if(a==='run-empty'){let n=walInitial();for(const step of ['begin','commit','flush','crash','recover'])n=walStep(n,step);return n;}return walStep(s,a);},
 describe(s){return s.events.at(-1)||'메모리와 저장 값은100, 로그는 비어 있어요.';},
 actions(){return [{id:'begin',text:'BEGIN 기록',primary:true},{id:'update',text:'120 변경 기록'},{id:'flush',text:'현재 로그 내구화'},{id:'commit',text:'COMMIT 기록'},{id:'crash',text:'장애 발생'},{id:'recover',text:'복구 실행'},{id:'run-before',text:'커밋 내구화 전 장애'},{id:'run-after',text:'커밋 내구화 후 장애'},{id:'run-empty',text:'변경 없는 거래'},{id:'reset',text:'처음부터'}];},
 render(s){return `<div class="wal-live"><div><small>메모리 값</small><strong>${s.memory}</strong></div><div><small>저장된 값</small><strong>${s.disk}</strong></div><div><small>거래 상태</small><strong>${e(s.txn)}</strong></div></div><div class="wal-log"><b>WAL · 앞에서 ${s.durable}개 내구화</b>${s.log.length?s.log.map((x,i)=>`<span class="${i<s.durable?'durable':''}">${i+1}. ${e(x)} <small>${i<s.durable?'내구화':'메모리만'}</small></span>`).join(''):'<span>로그 없음</span>'}</div><p class="small">복구를 다시 실행해도 같은 확정 결과가 유지되어야 해요.</p>`;}
};
})();
