(()=>{
const {escape:e,table}=CS.helpers;
const ipv4=text=>{if(typeof text!=='string'||!/^\d{1,3}(\.\d{1,3}){3}$/.test(text))throw Error('IPv4 주소를 0~255의 네 숫자로 입력해 주세요.');const parts=text.split('.').map(Number);if(parts.some(n=>n<0||n>255))throw Error('IPv4 주소의 각 숫자는0~255여야 해요.');return {parts,value:parts.reduce((v,n)=>(v*256+n)>>>0,0),bits:parts.map(n=>n.toString(2).padStart(8,'0')).join('.')};};
const routes=[{network:'192.0.2.128',prefix:25,next:'R2'},{network:'192.0.2.0',prefix:24,next:'R1'}];
const match=(value,network,prefix)=>prefix===0||((value>>>(32-prefix))===(ipv4(network).value>>>(32-prefix)));
const routeInitial=()=>({address:'192.0.2.130',includeDefault:true,result:null,events:[]});
const routeNow=s=>{const parsed=ipv4(s.address),candidates=routes.map(r=>({...r,match:match(parsed.value,r.network,r.prefix)}));if(s.includeDefault)candidates.push({network:'0.0.0.0',prefix:0,next:'R3',match:true});const chosen=candidates.filter(r=>r.match).sort((a,b)=>b.prefix-a.prefix)[0]||null;return {...structuredClone(s),result:{parsed,candidates,chosen},events:[chosen?`최장 일치 /${chosen.prefix} 경로를 선택해 다음 홉 ${chosen.next}로 보냅니다.`:'일치하는 경로가 없고 기본 경로도 없어 전달할 수 없어요.']};};
CS.labs['ipv4-routing']={custom:true,title:'목적지와 가장 길게 일치하는 경로를 찾으세요',type:'학습용 IPv4 최장 prefix 일치',intro:'192.0.2.130은 /24와 /25에 모두 들어가요. 더 구체적인 /25를 고르는 과정과 기본 경로를 비교해요.',limit:'고정된 단일 라우팅 표를 계산하는 모형이며 실제 네트워크 설정·패킷 전송을 바꾸지 않아요. 정책 라우팅·ECMP·IPv6은 생략했어요.',
 initial:routeInitial,
 action(s,a,data){if(a==='reset')return routeInitial();if(a==='edit')return {...s,address:data};if(a==='route')return routeNow(s);if(a==='to-r2')return routeNow({...routeInitial(),address:'192.0.2.130'});if(a==='to-r1')return routeNow({...routeInitial(),address:'192.0.2.20'});if(a==='to-default')return routeNow({...routeInitial(),address:'203.0.113.7'});if(a==='no-default')return routeNow({...routeInitial(),address:'203.0.113.7',includeDefault:false});if(a==='invalid')return routeNow({...routeInitial(),address:'300.0.0.1'});throw Error('알 수 없는 라우팅 동작이에요.');},
 describe(s){return s.events.at(-1)||'목적지192.0.2.130을 세 경로와 비교해 보세요.';},
 actions(){return [{id:'route',text:'경로 찾기',primary:true},{id:'to-r2',text:'/25와 /24 모두 일치'},{id:'to-r1',text:'/24만 일치'},{id:'to-default',text:'기본 경로 사용'},{id:'no-default',text:'기본 경로 없음'},{id:'invalid',text:'잘못된300 주소'},{id:'reset',text:'처음부터'}];},
 render(s){return `<label class="field route-address">목적지 IPv4<input data-action="edit" value="${e(s.address)}" inputmode="decimal" spellcheck="false"></label>${s.result?`<div class="address-binary"><b>${e(s.address)}</b><span>${e(s.result.parsed.bits)}</span></div>${table(['경로','다음 홉','일치'],s.result.candidates.map(r=>[`${r.network}/${r.prefix}`,r.next,r.match?'예':'아니요']))}<p class="route-choice">선택 · <strong>${s.result.chosen?`${s.result.chosen.network}/${s.result.chosen.prefix} → ${s.result.chosen.next}`:'경로 없음'}</strong></p>`:'<p>아직 경로를 계산하지 않았어요.</p>'}`;}
};

const tcpInitial=()=>({window:3,expected:1,ack:1,buffer:{},app:'',sent:[],retransmissions:0,events:[]});
const receive=(s,seq,data,retrans=false)=>{const n=structuredClone(s);n.sent.push({seq,data,status:'도착',retrans});if(seq<n.expected){n.events.push(`중복 seq${seq}을 앱에 다시 전달하지 않고 ACK${n.ack}를 보냈어요.`);return n;}n.buffer[seq]=data;while(n.buffer[n.expected]){n.app+=n.buffer[n.expected];delete n.buffer[n.expected];n.expected++;}n.ack=n.expected;if(retrans)n.retransmissions++;n.events.push(`seq${seq} 도착 · 누적 ACK${n.ack} · 앱 내용 ${n.app||'없음'}`);return n;};
const tcpAct=(s,a)=>{if(a==='send-a')return receive(s,1,'A');if(a==='lose-b'){const n=structuredClone(s);n.sent.push({seq:2,data:'B',status:'유실',retrans:false});n.events.push(`seq2 B가 유실됐어요. 수신 ACK는 여전히${n.ack}예요.`);return n;}if(a==='send-c')return receive(s,3,'C');if(a==='resend-b')return receive(s,2,'B',true);if(a==='duplicate-b')return receive(s,2,'B',true);throw Error('알 수 없는 TCP 동작이에요.');};
CS.labs['tcp-recovery']={custom:true,title:'B가 빠진 ABC 전송을 누적 ACK로 복구하세요',type:'학습용 TCP 바이트 순서·재전송 모형',intro:'A가 도착하면 ACK2, B가 유실되고 C만 와도 ACK2예요. B를 재전송하면 보관한 C까지 앱에 전달하고 ACK4가 돼요.',limit:'연결 완료 뒤 ASCII1바이트 세 개만 다루는 결정적 모형이에요. 실제 TCP의32비트 순서 공간·MSS·RTO 계산·빠른 재전송·혼잡 알고리즘은 생략했어요.',
 initial:tcpInitial,
 action(s,a,data){if(a==='reset')return tcpInitial();if(a==='window'){const w=Number(data);if(!Number.isInteger(w)||w<1||w>3)throw Error('수신 윈도는1~3에서 선택해 주세요.');return {...tcpInitial(),window:w,events:[`수신 윈도를${w}바이트로 바꿨어요.`]};}if(a==='invalid-window')throw Error('수신 윈도는0보다 커야 해요.');if(a==='run-loss'){let n=tcpInitial();for(const step of ['send-a','lose-b','send-c','resend-b'])n=tcpAct(n,step);return n;}if(a==='run-normal'){let n=tcpInitial();for(const [seq,data] of [[1,'A'],[2,'B'],[3,'C']])n=receive(n,seq,data);return n;}return tcpAct(s,a);},
 describe(s){return s.events.at(-1)||'연결은 ESTABLISHED, 다음 기대 바이트와 ACK는1이에요.';},
 actions(){return [{id:'send-a',text:'A 전송',primary:true},{id:'lose-b',text:'B 유실'},{id:'send-c',text:'C 도착'},{id:'resend-b',text:'B 재전송'},{id:'duplicate-b',text:'B 중복 도착'},{id:'run-loss',text:'유실 복구 끝까지'},{id:'run-normal',text:'유실 없이 끝까지'},{id:'invalid-window',text:'윈도0 시도'},{id:'reset',text:'처음부터'}];},
 render(s){const slots=[1,2,3].map(seq=>{const item=s.sent.findLast(x=>x.seq===seq);return `<div class="${item?.status==='유실'?'lost':seq<s.expected?'delivered':s.buffer[seq]?'buffered':''}"><small>seq ${seq}</small><strong>${['A','B','C'][seq-1]}</strong><span>${seq<s.expected?'전달됨':s.buffer[seq]?'순서 대기':item?.status||'미전송'}</span></div>`;}).join('');return `<label class="field tcp-window">수신 윈도<select data-action="window"><option value="3" ${s.window===3?'selected':''}>3 bytes</option><option value="2" ${s.window===2?'selected':''}>2 bytes</option><option value="1" ${s.window===1?'selected':''}>1 byte</option></select></label><div class="tcp-live">${slots}</div><div class="tcp-score"><span>누적 ACK <b>${s.ack}</b></span><span>앱 전달 <b>${s.app||'없음'}</b></span><span>재전송 <b>${s.retransmissions}회</b></span></div><p class="small">ACK ${s.ack}는 ${s.ack}번 바이트를 다음에 기대한다는 뜻이에요.</p>`;}
};
})();
