(()=>{
const {escape:e}=CS.helpers;
const bytesToBase64=bytes=>{let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);};
const base64ToText=value=>{const binary=atob(value),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes);};
const digest=async text=>{if(!globalThis.crypto?.subtle)throw Error('이 환경에서는 Web Crypto SHA-256을 사용할 수 없어요.');const bytes=new TextEncoder().encode(text),hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('');};
const cryptoInitial=()=>({input:'hello',base64:'',restored:'',hash:'',changed:'',changedHash:'',events:[]});
const checked=s=>{if(typeof s.input!=='string'||s.input.length>100)throw Error('공개 예문을 0~100글자로 입력해 주세요. 실제 비밀번호나 개인 정보는 넣지 마세요.');return s.input;};
CS.labs['crypto-compare']={custom:true,async:true,title:'같은 공개 예문을 Base64와 SHA-256으로 비교하세요',type:'실제 UTF-8·Base64·Web Crypto 실행',intro:'hello를 UTF-8 바이트로 바꾼 뒤 Base64로 표현하고 다시 복원해요. 같은 바이트에 SHA-256을 계산하고 느낌표 한 글자를 붙인 결과와 비교해요.',limit:'학습용 공개 예문만 입력하세요. SHA-256은 암호학적 해시이지만 일반 해시 한 번은 비밀번호 저장 방식이 아니에요. 보안 컨텍스트에서 Web Crypto를 지원하지 않으면 성공처럼 꾸미지 않고 오류를 표시해요.',
 initial:cryptoInitial,
 async action(s,a,data){if(a==='reset')return cryptoInitial();if(a==='edit')return {...s,input:data,base64:'',restored:'',hash:'',changed:'',changedHash:''};if(a==='hello')return {...cryptoInitial(),input:'hello'};if(a==='korean')return {...cryptoInitial(),input:'안녕'};if(a==='empty')return {...cryptoInitial(),input:''};if(a==='too-long')return this.action(s,'edit','가'.repeat(101));if(a==='unsupported')throw Error('Web Crypto를 지원하지 않는 환경에서는 해시 결과를 만들 수 없어요.');const text=checked(s);if(a==='base64'){const encoded=bytesToBase64(new TextEncoder().encode(text));return {...s,base64:encoded,restored:base64ToText(encoded),events:[...s.events,`Base64 변환과 복원 · ${encoded||'(빈 문자열)'}`]};}if(a==='hash'){const hash=await digest(text);return {...s,hash,events:[...s.events,`SHA-256 계산 · ${hash}`]};}if(a==='compare'){const changed=text+'!',hash=await digest(text),changedHash=await digest(changed),base64=bytesToBase64(new TextEncoder().encode(text));return {...s,base64,restored:base64ToText(base64),hash,changed,changedHash,events:[...s.events,`원문과 한 글자 변경 해시 비교 · ${hash===changedHash?'같음':'다름'}`]};}throw Error('알 수 없는 암호 실습 동작이에요.');},
 describe(s){if(s.changedHash)return `원문과 ${s.changed}의 SHA-256은 ${s.hash===s.changedHash?'같아요.':'완전히 달라요.'}`;if(s.hash)return `SHA-256은 ${s.hash.length}자리 16진수예요.`;if(s.base64||s.input==='')return `Base64를 복원하면 원문 ${s.restored===s.input?'그대로예요.':'과 달라요.'}`;return '공개 예문을 고르고 복원 가능한 표현과 해시를 실행해 보세요.';},
 actions(){return [{id:'base64',text:'Base64 변환·복원',primary:true},{id:'hash',text:'SHA-256 계산'},{id:'compare',text:'한 글자 변경 비교'},{id:'hello',text:'hello 예문'},{id:'korean',text:'안녕 예문'},{id:'empty',text:'빈 입력'},{id:'too-long',text:'101글자 경계'},{id:'unsupported',text:'미지원 상황'},{id:'reset',text:'처음부터'}];},
 render(s){return `<label class="field crypto-input">공개 예문<input data-action="edit" value="${e(s.input)}" maxlength="101" autocomplete="off" spellcheck="false"></label><div class="crypto-results"><section><small>Base64</small><strong>${e(s.base64)||'아직 없음'}</strong><span>복원 · ${s.base64||s.input===''?e(s.restored):'—'}</span></section><section><small>SHA-256 · 원문</small><strong>${e(s.hash)||'아직 없음'}</strong><span>${s.hash?`${s.hash.length} hex · 256 bit`:'고정 길이 결과'}</span></section><section><small>SHA-256 · ${e(s.changed)||'한 글자 변경'}</small><strong>${e(s.changedHash)||'아직 없음'}</strong><span>${s.changedHash?(s.changedHash===s.hash?'같음':'다름'):'입력 변화 관찰'}</span></section></div>`;}
};

const users={S1:{role:'학생',classId:'C1'},S2:{role:'학생',classId:'C1'},T1:{role:'교사',classId:'C1'},T2:{role:'교사',classId:'C2'}};
const resources={A1:{owner:'S1',classId:'C1',title:'S1의 과제'},A2:{owner:'S2',classId:'C1',title:'S2의 과제'}};
const accessInitial=()=>({user:'S1',target:'A1',operation:'read',note:'<img src=x onerror=alert(1)>',decision:null,events:[]});
const decide=s=>{const user=users[s.user],resource=resources[s.target];if(!user)return {allow:false,status:401,reason:'로그인 정보가 없어 인증 단계에서 거부했어요.'};if(!resource)return {allow:false,status:404,reason:'대상 규칙을 찾을 수 없어 기본 거부했어요.'};if(user.role==='학생'&&resource.owner===s.user)return {allow:true,status:200,reason:'학생이 자신의 자료를 요청했어요.'};if(user.role==='교사'&&user.classId===resource.classId&&s.operation==='read')return {allow:true,status:200,reason:'담당 수업 교사가 읽기를 요청했어요.'};return {allow:false,status:403,reason:'로그인했지만 이 대상과 행동에 대한 권한이 없어요.'};};
CS.labs['access-control']={custom:true,title:'로그인한 사용자도 요청마다 대상 권한을 확인하세요',type:'가상 서버 인증·인가·출력 인코딩 모형',intro:'S1·S2는 학생, T1은 C1 담당 교사, T2는 다른 수업 교사예요. A1은 S1 소유이고 담당 교사는 읽기만 할 수 있어요.',limit:'외부 서버에 요청하거나 공격 코드를 실행하지 않는 결정적 모형이에요. 실제 시스템은 조직 정책·자원 관계·감사 로그·오류 노출 규칙을 별도로 설계해야 해요.',
 initial:accessInitial,
 action(s,a,data){if(a==='reset')return accessInitial();if(a==='user')return {...s,user:data,decision:null};if(a==='target')return {...s,target:data,decision:null};if(a==='operation')return {...s,operation:data,decision:null};if(a==='note')return {...s,note:data};if(a==='request'||a==='hidden-bypass'){const decision=decide(s);return {...s,decision,events:[...s.events,`${a==='hidden-bypass'?'숨긴 버튼 우회 요청':'권한 요청'} · ${decision.status} · ${decision.reason}`]};}if(a==='own')return this.action({...accessInitial(),user:'S1',target:'A1',operation:'read'},'request');if(a==='other')return this.action({...accessInitial(),user:'S2',target:'A1',operation:'read'},'request');if(a==='teacher')return this.action({...accessInitial(),user:'T1',target:'A1',operation:'read'},'request');if(a==='logged-out')return this.action({...accessInitial(),user:'none',target:'A1',operation:'read'},'request');if(a==='unknown')return this.action({...accessInitial(),user:'S1',target:'Z9',operation:'read'},'request');throw Error('알 수 없는 접근 제어 동작이에요.');},
 describe(s){return s.decision?`${s.decision.status} · ${s.decision.allow?'허용':'거부'} · ${s.decision.reason}`:'사용자·대상·행동을 고르고 서버 권한 검사를 실행하세요.';},
 actions(){return [{id:'request',text:'서버 권한 검사',primary:true},{id:'own',text:'S1 자기 과제'},{id:'other',text:'S2가 A1 요청'},{id:'teacher',text:'담당 교사 읽기'},{id:'logged-out',text:'로그아웃 요청'},{id:'hidden-bypass',text:'숨긴 버튼 우회'},{id:'unknown',text:'없는 대상'},{id:'reset',text:'처음부터'}];},
 render(s){const opts=(items,current)=>items.map(([v,l])=>`<option value="${v}" ${v===current?'selected':''}>${l}</option>`).join('');return `<div class="access-selectors"><label class="field">요청 사용자<select data-action="user">${opts([['S1','S1 · 학생'],['S2','S2 · 학생'],['T1','T1 · C1 교사'],['T2','T2 · C2 교사'],['none','로그아웃']],s.user)}</select></label><label class="field">대상 자료<select data-action="target">${opts([['A1','A1 · S1 과제'],['A2','A2 · S2 과제'],['Z9','Z9 · 없는 대상']],s.target)}</select></label><label class="field">행동<select data-action="operation">${opts([['read','읽기'],['edit','수정']],s.operation)}</select></label></div><div class="access-policy"><section><small>인증</small><strong>${users[s.user]?`${s.user} · ${users[s.user].role}`:'로그인 없음'}</strong></section><section><small>인가 규칙</small><strong>소유자 또는 담당 교사의 읽기</strong></section><section class="${s.decision?.allow?'allowed':s.decision?'denied':''}"><small>서버 판단</small><strong>${s.decision?`${s.decision.status} · ${s.decision.allow?'허용':'거부'}`:'아직 없음'}</strong></section></div><label class="field safe-note">표시할 입력<input data-action="note" value="${e(s.note)}" maxlength="100"></label><p class="safe-output">텍스트로 표시 · <code>${e(s.note)}</code></p>`;}
};
})();
