(()=>{
const {escape:e,table}=CS.helpers;
const programs={
 independent:[{id:'I1',text:'ADD R1,R2,R3',read:['R2','R3'],write:'R1',kind:'alu'},{id:'I2',text:'SUB R4,R5,R6',read:['R5','R6'],write:'R4',kind:'alu'},{id:'I3',text:'AND R7,R8,R9',read:['R8','R9'],write:'R7',kind:'alu'}],
 dependent:[{id:'I1',text:'ADD R1,R2,R3',read:['R2','R3'],write:'R1',kind:'alu'},{id:'I2',text:'SUB R4,R1,R5',read:['R1','R5'],write:'R4',kind:'alu'},{id:'I3',text:'AND R6,R4,R7',read:['R4','R7'],write:'R6',kind:'alu'}],
 load:[{id:'I1',text:'LOAD R1,[A]',read:[],write:'R1',kind:'load'},{id:'I2',text:'ADD R2,R1,R3',read:['R1','R3'],write:'R2',kind:'alu'},{id:'I3',text:'SUB R4,R2,R5',read:['R2','R5'],write:'R4',kind:'alu'}],
 branch:[{id:'I1',text:'CMP R1,0',read:['R1'],write:null,kind:'alu'},{id:'I2',text:'BEQ target',read:[],write:null,kind:'branch'},{id:'I3',text:'ADD R2,R3,R4',read:['R3','R4'],write:'R2',kind:'alu'}]
};
const simulate=(program,forwarding=true,branchPenalty=0)=>{if(!Array.isArray(program)||!program.length||program.length>8)throw Error('명령은 1~8개가 필요해요.');const stages=[null,null,null,null,null],rows=[];let pc=0,stalls=0,guard=0;while(pc<program.length||stages.some(Boolean)){if(++guard>80)throw Error('파이프라인 모형이 안전 한계를 넘었어요.');const next=[null,null,null,stages[2],stages[3]],id=stages[1];let hazard=false,reason='';if(id){const producers=forwarding?[stages[2]?.kind==='load'?stages[2]:null]:[stages[2],stages[3]];const producer=producers.find(p=>p?.write&&id.read.includes(p.write));if(producer){hazard=true;reason=`${id.id}가 ${producer.write} 결과를 기다려요.`;}}if(hazard){next[1]=id;next[0]=stages[0];stalls++;}else{next[2]=id;next[1]=stages[0];if(pc<program.length)next[0]=program[pc++];}if(!next.some(Boolean)&&pc>=program.length)break;rows.push({cycle:rows.length+1,cells:next.map(x=>x?.id||'·'),hazard:hazard?reason:''});for(let i=0;i<5;i++)stages[i]=next[i];}return {program:structuredClone(program),forwarding,rows,stalls,branchPenalty,cycles:rows.length+branchPenalty};};
const pipelineInitial=()=>({preset:'independent',...simulate(programs.independent,true,0),events:[]});
const pipelineRun=(preset,forwarding=true,penalty=0)=>{const result=simulate(programs[preset],forwarding,penalty);return {preset,...result,events:[`${preset==='branch'?'분기':'데이터'} 예제 · ${result.cycles}사이클 · 멈춤 ${result.stalls}회${penalty?` · 잘못 예측 비용 ${penalty}`:''}`]};};
CS.labs['pipeline-hazards']={custom:true,title:'명령 세 개를 5단계 파이프라인에 흘려보내세요',type:'결정적 IF·ID·EX·MEM·WB 파이프라인 모형',intro:'서로 독립인 명령, 바로 앞 결과를 읽는 명령, LOAD 직후 결과를 쓰는 명령의 시간표를 비교해요.',limit:'단일 발행·순서 실행 5단계 교육 모형이에요. 레지스터 쓰기는 같은 사이클의 읽기보다 먼저라고 가정하고, 분기 오예측 비용은 고정 2사이클로 표시해요. 실제 CPU의 단계 수·비순차 실행·캐시 지연은 다를 수 있어요.',
 initial:pipelineInitial,
 action(s,a){if(a==='reset')return pipelineInitial();if(a==='independent')return pipelineRun('independent',true);if(a==='forward')return pipelineRun('dependent',true);if(a==='no-forward')return pipelineRun('dependent',false);if(a==='load-use')return pipelineRun('load',true);if(a==='branch-hit')return pipelineRun('branch',true,0);if(a==='branch-miss')return pipelineRun('branch',true,2);if(a==='invalid')return {...s,...simulate([],true,0)};throw Error('알 수 없는 파이프라인 동작이에요.');},
 describe(s){return `${s.program.length}개 명령 · 총 ${s.cycles}사이클 · 데이터 멈춤 ${s.stalls}회${s.branchPenalty?` · 오예측 비용 ${s.branchPenalty}사이클`:''}`;},
 actions(){return [{id:'independent',text:'서로 독립',primary:true},{id:'forward',text:'의존·전달 있음'},{id:'no-forward',text:'의존·전달 없음'},{id:'load-use',text:'LOAD 직후 사용'},{id:'branch-hit',text:'분기 예측 성공'},{id:'branch-miss',text:'분기 예측 실패'},{id:'invalid',text:'빈 명령 목록'},{id:'reset',text:'처음부터'}];},
 render(s){return `<div class="pipeline-program">${s.program.map(x=>`<span><b>${x.id}</b>${e(x.text)}</span>`).join('')}</div>${table(['사이클','IF','ID','EX','MEM','WB'],s.rows.map(r=>[r.hazard?`${r.cycle} · 멈춤`:r.cycle,...r.cells]))}<div class="pipeline-metrics"><span>기본 흐름 <b>${s.rows.length} cycle</b></span><span>데이터 멈춤 <b>${s.stalls}</b></span><span>분기 비용 <b>+${s.branchPenalty}</b></span><span>총 실행 <b>${s.cycles} cycle</b></span></div>${s.rows.some(r=>r.hazard)?`<p class="pipeline-note">${e(s.rows.filter(r=>r.hazard).map(r=>`C${r.cycle} ${r.hazard}`).join(' · '))}</p>`:''}`;}
};

const amdahl=(parallel,cores)=>{const p=Number(parallel),n=Number(cores);if(!Number.isFinite(p)||p<0||p>100)throw Error('병렬화 비율은 0~100%여야 해요.');if(!Number.isInteger(n)||n<1||n>1000000)throw Error('코어 수는 1~1,000,000의 정수여야 해요.');const fraction=p/100,serial=1-fraction,parallelTime=fraction/n,speedup=1/(serial+parallelTime),limit=p===100?Infinity:100/(100-p);return {parallel:p,cores:n,serialTime:serial,parallelTime,totalTime:serial+parallelTime,speedup,limit,efficiency:speedup/n*100};};
const amdahlState=(parallel=90,cores=8)=>{if(parallel&&typeof parallel==='object'){parallel=90;cores=8;}return {...amdahl(parallel,cores),events:[]};};
CS.labs['amdahl-speedup']={custom:true,title:'병렬화 비율과 코어 수로 속도 향상 상한을 계산하세요',type:'실제 암달의 법칙 계산',intro:'원래 실행 시간을 1로 두고 직렬 구간은 그대로, 병렬 구간만 코어 수로 나눠 이상적인 실행 시간과 속도 향상을 구해요.',limit:'고정 작업 크기와 균등 분배를 가정한 이상적 상한이에요. 통신·동기화·메모리 대역폭·불균형·스케줄링 비용을 제외하므로 실제 성능은 측정해야 해요.',
 initial:amdahlState,
 action(s,a,data){if(a==='reset')return amdahlState();if(a==='parallel')return {...amdahl(data,s.cores),events:[`병렬화 비율 ${data}%로 계산했어요.`]};if(a==='cores')return {...amdahl(s.parallel,data),events:[`코어 ${data}개로 계산했어요.`]};if(a==='calculate')return {...amdahl(s.parallel,s.cores),events:[`속도 향상 ${s.speedup.toFixed(2)}배를 계산했어요.`]};if(a==='half')return {...amdahlState(50,8),events:['50% 병렬·8코어 예제를 계산했어요.']};if(a==='ninety')return {...amdahlState(90,8),events:['90% 병렬·8코어 예제를 계산했어요.']};if(a==='serial')return {...amdahlState(0,64),events:['모두 직렬인 예제를 계산했어요.']};if(a==='full')return {...amdahlState(100,8),events:['모두 병렬인 이상적 예제를 계산했어요.']};if(a==='many')return {...amdahlState(90,1000000),events:['코어가 매우 많을 때 10배 한계에 가까워져요.']};if(a==='invalid')return {...s,...amdahl(s.parallel,0)};throw Error('알 수 없는 암달 계산 동작이에요.');},
 describe(s){return `병렬 ${s.parallel}% · ${s.cores.toLocaleString()}코어 · 이상적 실행 시간 ${s.totalTime.toFixed(4)} · 속도 향상 ${s.speedup.toFixed(2)}배`;},
 actions(){return [{id:'calculate',text:'다시 계산',primary:true},{id:'half',text:'50% · 8코어'},{id:'ninety',text:'90% · 8코어'},{id:'serial',text:'0% · 64코어'},{id:'full',text:'100% · 8코어'},{id:'many',text:'90% · 매우 많은 코어'},{id:'invalid',text:'코어 0 오류'},{id:'reset',text:'처음부터'}];},
 render(s){const percentOptions=[0,25,50,75,90,95,99,100].map(v=>`<option value="${v}" ${s.parallel===v?'selected':''}>${v}%</option>`).join(''),coreValues=[1,2,4,8,16,32,64],coreOptions=(coreValues.includes(s.cores)?coreValues:[...coreValues,s.cores]).map(v=>`<option value="${v}" ${s.cores===v?'selected':''}>${v.toLocaleString()}개</option>`).join('');const serialWidth=Math.max(0,s.serialTime*100),parallelWidth=Math.max(0,s.parallelTime*100);return `<div class="amdahl-inputs"><label class="field">병렬화 가능 구간<select data-action="parallel">${percentOptions}</select></label><label class="field">코어 수<select data-action="cores">${coreOptions}</select></label></div><div class="amdahl-time"><span class="serial" style="width:${serialWidth}%">직렬 ${s.serialTime.toFixed(3)}</span><span class="parallel" style="width:${parallelWidth}%">병렬 ${s.parallelTime.toFixed(3)}</span></div><div class="amdahl-metrics"><section><small>새 실행 시간</small><strong>${s.totalTime.toFixed(4)}</strong></section><section><small>이상적 속도 향상</small><strong>${s.speedup.toFixed(2)}×</strong></section><section><small>코어 효율</small><strong>${s.efficiency.toFixed(1)}%</strong></section><section><small>코어 무한대 상한</small><strong>${Number.isFinite(s.limit)?s.limit.toFixed(2)+'×':'∞'}</strong></section></div>`;}
};
})();
