(()=>{
const {escape:e,table}=CS.helpers;
const replicaInitial=()=>({version:0,nodes:{A:{version:0,value:'old',online:true},B:{version:0,value:'old',online:true},C:{version:0,value:'old',online:true}},pending:[],ack:'아직 쓰기 없음',lastRead:null,events:[]});
const copy=s=>structuredClone(s);
const writeReplica=(s,mode)=>{const n=copy(s),version=n.version+1,value=`v${version}`;n.version=version;n.nodes.A.version=version;n.nodes.A.value=value;const onlineFollowers=['B','C'].filter(id=>n.nodes[id].online);if(mode==='sync'){if(!onlineFollowers.length)throw Error('동기 복제 응답에 필요한 팔로워가 없어요.');const follower=onlineFollowers[0];n.nodes[follower].version=version;n.nodes[follower].value=value;n.pending=['B','C'].filter(id=>id!==follower);n.ack=`과반수 A+${follower} 저장 뒤 v${version} 응답`;}else{n.pending=['B','C'];n.ack=`리더 A만 저장한 뒤 v${version} 응답`;}n.lastRead=null;n.events.push(`${mode==='sync'?'동기':'비동기'} 쓰기 ${value} · ${n.ack}`);return n;};
const deliver=(s,targets)=>{const n=copy(s);for(const id of targets){if(!n.nodes[id])throw Error(`복제 서버 ${id}가 없어요.`);if(!n.nodes[id].online)continue;n.nodes[id].version=n.nodes.A.version;n.nodes[id].value=n.nodes.A.value;n.pending=n.pending.filter(x=>x!==id);}n.events.push(`복제 메시지 전달 · ${targets.filter(id=>n.nodes[id]?.online).join(', ')||'전달 대상 없음'}`);return n;};
const readReplica=(s,id)=>{if(!s.nodes[id])throw Error(`읽을 서버 ${id}가 없어요.`);if(!s.nodes[id].online)throw Error(`${id} 서버는 분리되어 읽을 수 없어요.`);const n=copy(s),node=n.nodes[id];n.lastRead={node:id,value:node.value,version:node.version,stale:n.version-node.version};n.events.push(`${id} 읽기 · ${node.value}${n.lastRead.stale?` · ${n.lastRead.stale}버전 뒤처짐`:' · 최신'}`);return n;};
CS.labs['replica-consistency']={custom:true,title:'복제 지연이 오래된 읽기를 만드는 과정을 확인하세요',type:'결정적 리더·두 복제본 메시지 지연 모형',intro:'A는 쓰기를 받는 리더이고 B·C는 복제본이에요. 비동기 응답 직후 B를 읽으면 아직 old가 보일 수 있어요.',limit:'단일 키와 버전 번호만 다루는 교육 모형이에요. 실제 시스템의 선형화 가능성은 리더 임기·쿼럼·읽기 검증·장애 복구 프로토콜 전체에 달려 있어요.',
 initial:replicaInitial,
 action(s,a){if(a==='reset')return replicaInitial();if(a==='async-write')return writeReplica(s,'async');if(a==='sync-write')return writeReplica(replicaInitial(),'sync');if(a==='read-a')return readReplica(s,'A');if(a==='read-b')return readReplica(s,'B');if(a==='read-c')return readReplica(s,'C');if(a==='deliver-b')return deliver(s,['B']);if(a==='deliver-all')return deliver(s,['B','C']);if(a==='partition-b'){const n=copy(s);n.nodes.B.online=false;n.events.push('B 네트워크 분리');return n;}if(a==='heal-b'){const n=copy(s);n.nodes.B.online=true;n.events.push('B 연결 복구 · 밀린 복제는 아직 전달 전');return n;}if(a==='stale'){return readReplica(writeReplica(replicaInitial(),'async'),'B');}if(a==='eventual'){return readReplica(deliver(writeReplica(replicaInitial(),'async'),['B','C']),'C');}if(a==='missing')return readReplica(s,'Z');throw Error('알 수 없는 복제 실습 동작이에요.');},
 describe(s){return s.lastRead?`${s.lastRead.node}에서 ${s.lastRead.value} 읽기 · ${s.lastRead.stale?`최신보다 ${s.lastRead.stale}버전 뒤처졌어요.`:'현재 최신 버전이에요.'}`:`최신 쓰기 v${s.version} · ${s.ack} · 전달 대기 ${s.pending.join(', ')||'없음'}`;},
 actions(){return [{id:'async-write',text:'A만 저장 후 응답',primary:true},{id:'read-b',text:'B에서 읽기'},{id:'deliver-b',text:'B에 복제 전달'},{id:'deliver-all',text:'모두 전달'},{id:'partition-b',text:'B 네트워크 분리'},{id:'heal-b',text:'B 연결 복구'},{id:'sync-write',text:'과반수 저장 후 응답'},{id:'stale',text:'오래된 읽기 예제'},{id:'eventual',text:'최종 수렴 예제'},{id:'missing',text:'없는 Z 읽기'},{id:'reset',text:'처음부터'}];},
 render(s){return `<div class="replica-write"><small>클라이언트 응답</small><strong>${e(s.ack)}</strong></div><div class="replica-nodes">${Object.entries(s.nodes).map(([id,n])=>`<section class="${n.online?'':'offline'} ${n.version===s.version?'fresh':'stale'}"><b>${id}${id==='A'?' · 리더':''}</b><strong>${e(n.value)}</strong><span>version ${n.version}</span><small>${n.online?(n.version===s.version?'최신':'복제 지연'):'네트워크 분리'}</small></section>`).join('')}</div><div class="replica-pending">전달 대기 · <b>${s.pending.join(', ')||'없음'}</b></div><div class="replica-read"><small>마지막 읽기</small><strong>${s.lastRead?`${s.lastRead.node} → ${e(s.lastRead.value)}`:'아직 없음'}</strong><span>${s.lastRead?(s.lastRead.stale?`${s.lastRead.stale}버전 오래됨`:'최신 버전'):'읽을 서버를 선택하세요.'}</span></div>`;}
};

const quorumInitial=()=>({term:1,leader:'A',online:{A:true,B:true,C:true},nodes:{A:[],B:[],C:[]},entries:[],nextIndex:1,commitIndex:0,effects:0,appliedTokens:[],events:[]});
const appendEntry=(s,token,command='order+1')=>{const n=copy(s);if(!n.leader||!n.online[n.leader])throw Error('현재 요청을 받을 수 있는 리더가 없어요.');const existing=n.entries.find(x=>x.token===token);if(existing){if(existing.command!==command)throw Error(`같은 멱등 키 ${token}에 다른 요청 내용을 사용할 수 없어요.`);n.events.push(`중복 ${token} · 새 로그 없이 기존 index ${existing.index} 반환`);return n;}const entry={index:n.nextIndex++,term:n.term,token,command,committed:false};n.entries.push(entry);n.nodes[n.leader].push(entry.index);n.events.push(`${n.leader}가 ${token}을 index ${entry.index}에 추가 · 아직 미확정`);return n;};
const replicateLog=(s,target)=>{const n=copy(s);if(!n.leader||!n.online[n.leader])throw Error('복제할 리더가 없어요.');if(!n.online[target])throw Error(`${target} 서버가 오프라인이에요.`);if(target===n.leader)throw Error('리더 자신에게 복제할 수 없어요.');n.nodes[target]=[...n.nodes[n.leader]];for(const entry of n.entries){const copies=Object.values(n.nodes).filter(log=>log.includes(entry.index)).length;if(!entry.committed&&copies>=2){entry.committed=true;n.commitIndex=Math.max(n.commitIndex,entry.index);if(!n.appliedTokens.includes(entry.token)){n.appliedTokens.push(entry.token);n.effects++;}}}n.events.push(`${target} 복제 완료 · 과반수 로그를 확정하고 효과 ${n.effects}회 적용`);return n;};
const partitionA=s=>{const n=copy(s);n.online.A=false;if(n.leader==='A')n.leader=null;n.events.push('A 분리 · 리더 없음');return n;};
const electB=s=>{const n=copy(s);if(!n.online.B||!n.online.C)throw Error('B와 C의 두 표가 없어 과반수 선출을 할 수 없어요.');if(n.nodes.B.length<n.nodes.C.length)throw Error('B의 로그가 더 오래되어 리더가 될 수 없어요.');n.term++;n.leader='B';n.events.push(`term ${n.term} · B가 B+C 과반수로 리더 선출`);return n;};
const committedPreset=()=>replicateLog(appendEntry(quorumInitial(),'req-1'),'B');
CS.labs['raft-quorum']={custom:true,title:'세 서버에서 과반수 확정과 멱등 재시도를 실행하세요',type:'단순화한 Raft 로그·쿼럼·멱등 키 모형',intro:'리더가 로그를 혼자 저장한 상태와 두 서버가 저장해 확정된 상태를 구별해요. 응답이 사라져도 같은 req-1로 재시도하면 효과는 한 번만 적용해요.',limit:'고정 3노드·단일 클라이언트 교육 모형이에요. 실제 Raft의 선거 제한·로그 일치 검사·현재 임기 확정 규칙·스냅샷·구성 변경·타이머는 생략했어요.',
 initial:quorumInitial,
 action(s,a){if(a==='reset')return quorumInitial();if(a==='propose')return appendEntry(s,'req-1');if(a==='to-b')return replicateLog(s,'B');if(a==='to-c')return replicateLog(s,'C');if(a==='partition-a')return partitionA(s);if(a==='elect-b')return electB(s);if(a==='second')return appendEntry(s,'req-2');if(a==='retry-same')return appendEntry(s,'req-1');if(a==='heal'){const n=copy(s);if(!n.leader)throw Error('먼저 리더를 선출해 주세요.');n.online={A:true,B:true,C:true};for(const id of ['A','B','C'])n.nodes[id]=[...n.nodes[n.leader]];n.events.push('세 서버 연결 복구·로그 동기화');return n;}if(a==='minority'){let n=quorumInitial();n.online.B=false;n.online.C=false;return appendEntry(n,'req-1');}if(a==='idempotent')return appendEntry(committedPreset(),'req-1');if(a==='new-token'){let n=committedPreset();n=appendEntry(n,'req-2');return replicateLog(n,'B');}if(a==='election'){let n=committedPreset();n=partitionA(n);return electB(n);}if(a==='mismatch')return appendEntry(committedPreset(),'req-1','order+2');throw Error('알 수 없는 합의 실습 동작이에요.');},
 describe(s){const last=s.entries.at(-1);return `term ${s.term} · 리더 ${s.leader||'없음'} · 로그 ${s.entries.length}개 · 확정 index ${s.commitIndex} · 실제 효과 ${s.effects}회${last&&!last.committed?' · 마지막 로그 미확정':''}`;},
 actions(){return [{id:'propose',text:'req-1 제안',primary:true},{id:'to-b',text:'B에 복제'},{id:'to-c',text:'C에 복제'},{id:'partition-a',text:'리더 A 분리'},{id:'elect-b',text:'B 리더 선출'},{id:'second',text:'req-2 제안'},{id:'retry-same',text:'req-1 재시도'},{id:'heal',text:'연결·로그 복구'},{id:'minority',text:'한 서버만 저장'},{id:'idempotent',text:'응답 유실 뒤 같은 키'},{id:'new-token',text:'새 키로 두 번째 요청'},{id:'election',text:'확정 뒤 리더 교체'},{id:'mismatch',text:'같은 키·다른 내용'},{id:'reset',text:'처음부터'}];},
 render(s){const role=id=>s.leader===id?'리더':'팔로워';return `<div class="raft-cluster">${['A','B','C'].map(id=>`<section class="${s.online[id]?'':'offline'} ${s.leader===id?'leader':''}"><b>${id} · ${role(id)}</b><span>${s.online[id]?'온라인':'분리됨'}</span><div>${s.nodes[id].length?s.nodes[id].map(index=>{const item=s.entries.find(x=>x.index===index);return `<i class="${item?.committed?'committed':''}">${index}:${e(item?.token||'?')}</i>`;}).join(''):'<i>빈 로그</i>'}</div></section>`).join('')}</div>${table(['index','term','멱등 키','명령','상태'],s.entries.map(x=>[x.index,x.term,x.token,x.command,x.committed?'확정':'미확정']))}<div class="raft-metrics"><span>현재 term <b>${s.term}</b></span><span>확정 index <b>${s.commitIndex}</b></span><span>고유 요청 <b>${s.appliedTokens.length}</b></span><span>실제 효과 <b>${s.effects}회</b></span></div>`;}
};
})();
