(()=>{
const {escape:e,table}=CS.helpers;
const copy=s=>structuredClone(s);
const sameBag=(a,b)=>{if(a.length!==b.length)return false;const count=new Map;for(const v of a)count.set(v,(count.get(v)||0)+1);for(const v of b){if(!count.has(v))return false;count.set(v,count.get(v)-1);}return [...count.values()].every(v=>v===0);};
const sorted=a=>a.every((v,i)=>i===0||a[i-1]<=v);
const sortWith=(input,implementation)=>implementation==='broken'?[...new Set(input)].sort((a,b)=>a-b):[...input].sort((a,b)=>a-b);
const evaluateSort=(input,implementation='broken')=>{
 if(!Array.isArray(input)||input.some(v=>!Number.isFinite(v)))throw Error('검사 입력은 숫자 배열이어야 해요.');
 const output=sortWith(input,implementation),checks={sorted:sorted(output),preserved:sameBag(input,output),length:input.length===output.length};
 return {input:[...input],output,implementation,checks,suite:[],events:[`${implementation==='broken'?'잘못된':'수정한'} 함수 실행 · [${input}] → [${output}]`,`정렬 ${checks.sorted?'통과':'실패'} · 항목 보존 ${checks.preserved?'통과':'실패'}`]};
};
const sortInitial=()=>evaluateSort([2,1,2]);
const runSuite=implementation=>{const cases=[[2,1,2],[3,3,1],[],[5],[4,2,4,2]],suite=cases.map(input=>{const s=evaluateSort(input,implementation);return {input,output:s.output,pass:s.checks.sorted&&s.checks.preserved};}),state=evaluateSort([2,1,2],implementation);state.suite=suite;state.events.push(`고정 사례 ${suite.length}개 · 통과 ${suite.filter(x=>x.pass).length} · 실패 ${suite.filter(x=>!x.pass).length}`);return state;};
CS.labs['test-invariants']={custom:true,title:'정렬 결과에서 값이 사라지는 버그를 여러 조건으로 찾아보세요',type:'실제 제한 함수·불변조건 검증',intro:'잘못된 함수는 Set으로 중복을 없앤 뒤 정렬해요. 출력이 오름차순이라는 검사만 통과하지만 입력 항목 보존 검사는 실패해요.',limit:'숫자 배열과 결정적 정렬만 다루는 교육 실습이에요. 실제 언어의 정렬 안정성, NaN, 비교 함수 계약, 성능과 국제화 규칙은 별도로 검증해야 해요.',
 initial:sortInitial,
 action(s,a){if(a==='reset')return sortInitial();if(a==='broken')return evaluateSort([2,1,2],'broken');if(a==='fixed')return evaluateSort([2,1,2],'fixed');if(a==='duplicates')return evaluateSort([3,3,1],'broken');if(a==='reverse')return evaluateSort([3,2,1],'broken');if(a==='empty')return evaluateSort([],'broken');if(a==='single')return evaluateSort([7],'broken');if(a==='suite-broken')return runSuite('broken');if(a==='suite-fixed')return runSuite('fixed');if(a==='invalid')return evaluateSort([2,'x',1],'broken');throw Error('알 수 없는 테스트 실습 동작이에요.');},
 describe(s){const passed=Object.values(s.checks).filter(Boolean).length;return `${s.implementation==='broken'?'잘못된 함수':'수정한 함수'} · 입력 [${s.input}] → 출력 [${s.output}] · 조건 ${passed}/3 통과${s.suite.length?` · 사례 ${s.suite.filter(x=>x.pass).length}/${s.suite.length} 통과`:''}`;},
 actions(){return [{id:'broken',text:'버그 함수 실행',primary:true},{id:'fixed',text:'수정 함수 비교'},{id:'duplicates',text:'중복 경계 사례'},{id:'reverse',text:'역순 사례'},{id:'empty',text:'빈 배열'},{id:'single',text:'원소 1개'},{id:'suite-broken',text:'버그 함수 5사례'},{id:'suite-fixed',text:'수정 함수 5사례'},{id:'invalid',text:'잘못된 입력'},{id:'reset',text:'처음부터'}];},
 render(s){return `<div class="sort-compare"><section><b>입력</b><strong>[${s.input.map(e).join(', ')}]</strong><span>길이 ${s.input.length}</span></section><i>sort()</i><section class="${s.checks.preserved?'pass':'fail'}"><b>출력</b><strong>[${s.output.map(e).join(', ')}]</strong><span>길이 ${s.output.length}</span></section></div><div class="invariant-checks"><span class="${s.checks.sorted?'pass':'fail'}">오름차순<b>${s.checks.sorted?'PASS':'FAIL'}</b></span><span class="${s.checks.preserved?'pass':'fail'}">항목·개수 보존<b>${s.checks.preserved?'PASS':'FAIL'}</b></span><span class="${s.checks.length?'pass':'fail'}">길이 보존<b>${s.checks.length?'PASS':'FAIL'}</b></span></div>${s.suite.length?table(['입력','출력','전체 조건'],s.suite.map(x=>[`[${x.input}]`,`[${x.output}]`,x.pass?'통과':'실패'])):''}`;}
};

const shipping=(price,version)=>version==='buggy'?(price>10000?0:3000):(price>=10000?0:3000);
const expected=price=>price>=10000?0:3000;
const evaluatePrice=(price,version='buggy')=>{if(!Number.isInteger(price)||price<0||price>1000000)throw Error('주문 금액은 0부터 1,000,000까지의 정수여야 해요.');const actual=shipping(price,version),want=expected(price);return {version,price,operator:version==='buggy'?'>':'>=',actual,expected:want,comparison:version==='buggy'?price>10000:price>=10000,pass:actual===want,suite:[],stage:'재현',events:[`${price}원 · ${price} ${version==='buggy'?'>':'≥'} 10000 → ${version==='buggy'?price>10000:price>=10000}`,`기대 배송비 ${want}원 · 실제 ${actual}원 · ${actual===want?'통과':'실패'}`]};};
const debugInitial=()=>evaluatePrice(10000);
const shippingSuite=version=>{const cases=[9999,10000,10001],suite=cases.map(price=>{const actual=shipping(price,version),want=expected(price);return {price,actual,expected:want,pass:actual===want};}),state=evaluatePrice(10000,version);state.suite=suite;state.stage=version==='buggy'?'최소 재현 완료':'수정·회귀 확인';state.events.push(`9999·10000·10001 회귀 검사 · ${suite.filter(x=>x.pass).length}/3 통과`);return state;};
CS.labs['boundary-debugging']={custom:true,title:'무료 배송 경계값 오류를 재현하고 수정 뒤 회귀 검사하세요',type:'제한 비교식·디버깅 순환 모형',intro:'요구사항은 10,000원 이상 무료예요. 초기 구현의 > 비교는 정확히 10,000원에서만 실패하므로 경계 양옆을 함께 검사해요.',limit:'고정된 비교식과 배송비 규칙만 실행해요. 사용자가 작성한 코드를 평가하지 않으며 실제 결제·통화 반올림·쿠폰·세금 규칙은 포함하지 않아요.',
 initial:debugInitial,
 action(s,a){if(a==='reset')return debugInitial();if(a==='p9999')return evaluatePrice(9999,s.version);if(a==='p10000')return evaluatePrice(10000,s.version);if(a==='p10001')return evaluatePrice(10001,s.version);if(a==='zero')return evaluatePrice(0,s.version);if(a==='reproduce')return shippingSuite('buggy');if(a==='inspect'){const n=evaluatePrice(10000,'buggy');n.stage='가설·관측';n.events.push('경계값에서 false인 비교 결과를 관측');return n;}if(a==='fix')return shippingSuite('fixed');if(a==='regress')return shippingSuite(s.version);if(a==='empty')throw Error('빈 입력은 숫자 0과 다르므로 실행할 수 없어요.');if(a==='invalid')return evaluatePrice(-1,s.version);throw Error('알 수 없는 디버깅 실습 동작이에요.');},
 describe(s){return `${s.stage} · ${s.version==='buggy'?'버그 식':'수정 식'} price ${s.operator} 10000 · ${s.price}원에서 실제 ${s.actual}원 / 기대 ${s.expected}원 · ${s.pass?'통과':'실패'}${s.suite.length?` · 회귀 ${s.suite.filter(x=>x.pass).length}/3`:''}`;},
 actions(){return [{id:'reproduce',text:'세 경계값 재현',primary:true},{id:'inspect',text:'비교 결과 관측'},{id:'fix',text:'>=로 수정·검사'},{id:'p9999',text:'9,999원'},{id:'p10000',text:'10,000원'},{id:'p10001',text:'10,001원'},{id:'zero',text:'0원'},{id:'regress',text:'회귀 다시 실행'},{id:'empty',text:'빈 입력'},{id:'invalid',text:'-1원 오류'},{id:'reset',text:'처음부터'}];},
 render(s){return `<div class="debug-expression"><span>if (price <b>${e(s.operator)}</b> 10000)</span><strong class="${s.comparison?'true':'false'}">${s.price} ${e(s.operator)} 10000 → ${s.comparison}</strong><i>배송비 ${s.actual}원</i></div><div class="debug-values"><span>입력<b>${s.price}원</b></span><span>기대<b>${s.expected}원</b></span><span>실제<b>${s.actual}원</b></span><span class="${s.pass?'pass':'fail'}">판정<b>${s.pass?'PASS':'FAIL'}</b></span></div>${s.suite.length?table(['금액','기대 배송비','실제 배송비','결과'],s.suite.map(x=>[`${x.price}원`,`${x.expected}원`,`${x.actual}원`,x.pass?'통과':'실패'])):''}<div class="debug-stage"><b>현재 단계</b><span>${e(s.stage)}</span><em>재현 → 가설 → 관측 → 수정 → 회귀</em></div>`;}
};
})();
