(()=>{
const {escape:e,table}=CS.helpers;
const rate=(n,d)=>d===0?null:n/d*100;
const routeVersion=(number,ratio)=>ratio===0?'v1':ratio===100?'v2':ratio===50?(number%2===0?'v2':'v1'):(number%10===0?'v2':'v1');
const deployInitial=()=>({total:0,ratio:10,versions:{v1:{requests:0,errors:0},v2:{requests:0,errors:0}},history:[],status:'카나리 준비',lastBatch:null,events:['v1은 정상, v2는 모든 요청에서 오류가 나는 교육 시나리오']});
const send=(source,count)=>{
 if(!Number.isInteger(count)||count<0||count>100)throw Error('요청 수는 0부터 100까지의 정수여야 해요.');
 const s=structuredClone(source),before={v1:s.versions.v1.errors,v2:s.versions.v2.errors};
 for(let i=0;i<count;i++){const number=s.total+1,version=routeVersion(number,s.ratio),failed=version==='v2';s.total++;s.versions[version].requests++;if(failed)s.versions[version].errors++;s.history.push({number,version,failed});}
 s.history=s.history.slice(-30);s.lastBatch={count,errors:(s.versions.v1.errors-before.v1)+(s.versions.v2.errors-before.v2)};s.status=`${s.ratio}% 경로로 ${count}개 관측`;s.events.push(`${count}개 요청 · 새 오류 ${s.lastBatch.errors}개 · 누적 ${s.total}개`);return s;
};
const ratio=(source,value)=>{if(![0,10,50,100].includes(value))throw Error('배포 비율은 0, 10, 50, 100 중 하나여야 해요.');const s=structuredClone(source);s.ratio=value;s.status=value===0?'v1로 롤백':'배포 비율 변경';s.events.push(`앞으로 보낼 요청의 v2 비율을 ${value}%로 변경`);return s;};
const deploymentStats=s=>({overall:rate(s.versions.v1.errors+s.versions.v2.errors,s.total),v1:rate(s.versions.v1.errors,s.versions.v1.requests),v2:rate(s.versions.v2.errors,s.versions.v2.requests)});
CS.labs['canary-deployment']={custom:true,title:'일부 요청만 v2에 보내 오류율을 관찰하고 롤백하세요',type:'결정적 카나리 라우팅·지표 모형',intro:'v1은 정상이고 v2는 요청마다 오류가 나요. 처음 20개 중 매 10번째 요청만 v2로 보내면 전체 오류율과 버전별 오류율이 얼마나 다른지 확인할 수 있어요.',limit:'10%는 매 10번째, 50%는 짝수 번째 요청을 v2로 보내는 결정적 교육 모형이에요. 실제 배포의 무작위 라우팅, 세션 고정, 상태 저장소, 자동 확장과 통계적 유의성은 포함하지 않아요.',
 initial:deployInitial,
 action(s,a){if(a==='reset')return deployInitial();if(a==='run20')return send(deployInitial(),20);if(a==='one')return send(s,1);if(a==='ten')return send(s,10);if(a==='ratio0')return ratio(s,0);if(a==='ratio10')return ratio(s,10);if(a==='ratio50')return ratio(s,50);if(a==='ratio100')return ratio(s,100);if(a==='rollback'){const next=ratio(s,0);next.status='롤백 후 확인';next.events.push('v2 유입을 멈추고 v1으로 복귀');return send(next,10);}if(a==='zero')return deployInitial();if(a==='invalid')return ratio(s,110);throw Error('알 수 없는 배포 실습 동작이에요.');},
 describe(s){const m=deploymentStats(s),show=v=>v===null?'데이터 없음':`${v.toFixed(1)}%`;return `${s.status} · 누적 ${s.total}개 · v1 ${s.versions.v1.requests}개 / v2 ${s.versions.v2.requests}개 · 전체 오류율 ${show(m.overall)} · v2 오류율 ${show(m.v2)}`;},
 actions(){return [{id:'run20',text:'10%로 20개 보내기',primary:true},{id:'one',text:'요청 1개'},{id:'ten',text:'요청 10개'},{id:'ratio0',text:'v2 0%'},{id:'ratio10',text:'v2 10%'},{id:'ratio50',text:'v2 50%'},{id:'ratio100',text:'v2 100%'},{id:'rollback',text:'롤백 후 10개 확인'},{id:'zero',text:'관측 0개'},{id:'invalid',text:'110% 오류'},{id:'reset',text:'처음부터'}];},
 render(s){const m=deploymentStats(s),show=v=>v===null?'데이터 없음':`${v.toFixed(1)}%`,total=Math.max(1,s.total);return `<div class="deploy-route"><span><b>사용자 요청</b>${s.total}개 관측</span><i>→</i><div><strong>라우터 · v2 ${s.ratio}%</strong><div class="deploy-bar"><em style="width:${s.versions.v1.requests/total*100}%">v1</em><em style="width:${s.versions.v2.requests/total*100}%">v2</em></div></div></div><div class="deploy-versions"><section class="healthy"><b>v1 · 안정 버전</b><strong>${s.versions.v1.requests} 요청</strong><span>${s.versions.v1.errors} 오류 · ${show(m.v1)}</span></section><section class="${s.versions.v2.errors?'unhealthy':''}"><b>v2 · 새 버전</b><strong>${s.versions.v2.requests} 요청</strong><span>${s.versions.v2.errors} 오류 · ${show(m.v2)}</span></section></div><div class="deploy-metrics"><span>전체 요청<b>${s.total}</b></span><span>전체 오류<b>${s.versions.v1.errors+s.versions.v2.errors}</b></span><span>전체 오류율<b>${show(m.overall)}</b></span><span>최근 묶음 오류<b>${s.lastBatch?s.lastBatch.errors:'—'}</b></span></div>${s.history.length?`<div class="request-strip" aria-label="최근 요청의 배포 버전과 성공 실패">${s.history.map(x=>`<i class="${x.failed?'failed':''}" title="요청 ${x.number} · ${x.version} · ${x.failed?'오류':'성공'}">${x.version}</i>`).join('')}</div>`:'<p class="no-observation">아직 보낸 요청이 없어요. 성공률 0%가 아니라 관측 데이터가 없는 상태예요.</p>'}`;}
};

const nearestRank=(values,p)=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.ceil(p*sorted.length)-1];};
const stats=values=>({count:values.length,mean:values.length?values.reduce((a,b)=>a+b,0)/values.length:null,p95:nearestRank(values,.95),max:values.length?Math.max(...values):null});
const minutes=(h,m)=>h*60+m;
const recovery=(backup,incident,recovered,goals={rpo:5,rto:20})=>{if(backup>incident)throw Error('백업 시각은 장애 시각보다 늦을 수 없어요.');if(recovered<incident)throw Error('복구 시각은 장애 시각보다 빠를 수 없어요.');return {backup,incident,recovered,loss:incident-backup,duration:recovered-incident,goals:{...goals}};};
const observeInitial=()=>({latencies:[10,10,10,10,10,10,10,10,10,1000],recovery:recovery(minutes(12,0),minutes(12,10),minutes(12,25)),stage:'발견',signal:'지표: p95 지연 급증',events:['10개 요청 지연을 수집 · 느린 요청 1개 포함','12:10 장애 발견 · 마지막 복구 지점 12:00']});
const setLatency=(source,values,label)=>{const s=structuredClone(source);s.latencies=values;s.signal=label;s.events.push(`${label} · 표본 ${values.length}개`);return s;};
const setGoals=(source,rpo,rto)=>{const s=structuredClone(source);s.recovery.goals={rpo,rto};s.events.push(`목표 RPO ${rpo}분 · RTO ${rto}분`);return s;};
const fmtTime=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
CS.labs['observability-recovery']={custom:true,title:'꼬리 지연을 발견하고 RPO·RTO 목표와 실제 복구를 비교하세요',type:'백분위수·복구 시간 계산 모형',intro:'요청 10개 중 9개는 10ms, 하나는 1000ms예요. 평균과 가장 가까운 순위법 p95를 함께 계산하고 백업·장애·복구 시각에서 실제 데이터 손실 구간과 복구 시간을 구해요.',limit:'고정된 지연 표본과 분 단위 시각을 다루는 교육 모형이에요. 실제 계측 오버헤드, 분산 추적 샘플링, 시계 오차, 백업 무결성 검사와 복구 자동화는 포함하지 않아요.',
 initial:observeInitial,
 action(s,a){if(a==='reset'||a==='baseline')return observeInitial();if(a==='all-fast')return setLatency(s,Array(10).fill(10),'모든 요청이 10ms');if(a==='empty')return setLatency(s,[],'관측 표본 없음');if(a==='slow-spike')return setLatency(s,[10,10,10,10,10,10,10,10,1000,1500],'느린 요청 2개');if(a==='strict')return setGoals(s,5,10);if(a==='relaxed')return setGoals(s,15,20);if(a==='detect'){const n=structuredClone(s);n.stage='발견';n.signal='지표로 p95 급증 발견';n.events.push('발견 · 사용자 영향과 경보 확인');return n;}if(a==='mitigate'){const n=structuredClone(s);n.stage='완화';n.signal='로그·추적으로 느린 DB 경로 확인';n.events.push('완화 · 새 버전 유입 중지');return n;}if(a==='recover'){const n=structuredClone(s);n.stage='복구';n.signal='백업 복원 뒤 핵심 요청 검증';n.events.push('복구 · 서비스 정상화 확인');return n;}if(a==='postmortem'){const n=structuredClone(s);n.stage='회고';n.signal='재발 방지 항목과 담당자 기록';n.events.push('회고 · 비난보다 시스템 개선');return n;}if(a==='contradict') {const n=structuredClone(s);n.recovery=recovery(minutes(12,15),minutes(12,10),minutes(12,25));return n;}if(a==='bad-recovery'){const n=structuredClone(s);n.recovery=recovery(minutes(12,0),minutes(12,10),minutes(12,5));return n;}throw Error('알 수 없는 관측·복구 실습 동작이에요.');},
 describe(s){const m=stats(s.latencies),r=s.recovery,show=v=>v===null?'데이터 없음':`${v.toFixed(0)}ms`;return `${s.stage} · ${s.signal} · 평균 ${show(m.mean)} / p95 ${show(m.p95)} · 실제 손실 구간 ${r.loss}분 / 복구 ${r.duration}분 · RPO ${r.loss<=r.goals.rpo?'충족':'초과'} / RTO ${r.duration<=r.goals.rto?'충족':'초과'}`;},
 actions(){return [{id:'baseline',text:'기본 표본 계산',primary:true},{id:'all-fast',text:'모두 10ms'},{id:'slow-spike',text:'느린 요청 2개'},{id:'empty',text:'표본 0개'},{id:'strict',text:'엄격한 목표'},{id:'relaxed',text:'완화한 목표'},{id:'detect',text:'1 발견'},{id:'mitigate',text:'2 완화'},{id:'recover',text:'3 복구'},{id:'postmortem',text:'4 회고'},{id:'contradict',text:'백업 시각 오류'},{id:'bad-recovery',text:'복구 시각 오류'},{id:'reset',text:'처음부터'}];},
 render(s){const m=stats(s.latencies),r=s.recovery,show=v=>v===null?'데이터 없음':`${v.toFixed(0)}ms`,max=Math.max(1,...s.latencies);return `<div class="latency-samples">${s.latencies.length?s.latencies.map((v,i)=>`<span><i style="height:${Math.max(5,v/max*100)}%"></i><b>${i+1}</b><em>${v}ms</em></span>`).join(''):'<strong>표본이 없어요 · 평균과 p95는 계산하지 않아요.</strong>'}</div><div class="observe-metrics"><span>표본<b>${m.count}</b></span><span>평균<b>${show(m.mean)}</b></span><span>p95<b>${show(m.p95)}</b></span><span>최대<b>${show(m.max)}</b></span></div><div class="recovery-line"><span><b>${fmtTime(r.backup)}</b>마지막 복구 지점</span><i>${r.loss}분</i><strong><b>${fmtTime(r.incident)}</b>장애</strong><i>${r.duration}분</i><span><b>${fmtTime(r.recovered)}</b>서비스 복구</span></div><div class="objective-grid"><span class="${r.loss<=r.goals.rpo?'meet':'miss'}">RPO 목표 ${r.goals.rpo}분<b>실제 ${r.loss}분 · ${r.loss<=r.goals.rpo?'충족':'초과'}</b></span><span class="${r.duration<=r.goals.rto?'meet':'miss'}">RTO 목표 ${r.goals.rto}분<b>실제 ${r.duration}분 · ${r.duration<=r.goals.rto?'충족':'초과'}</b></span></div><div class="incident-stage"><b>${e(s.stage)}</b><span>${e(s.signal)}</span><em>발견 → 완화 → 복구 → 회고</em></div>`;}
};
CS.helpers.ch24={rate,routeVersion,deploymentStats,nearestRank,stats,recovery};
})();
