const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const ctx=vm.createContext({structuredClone,URL});ctx.window=ctx;for(const file of ['src/core.js','src/labs/ch06.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),ctx);const labs=ctx.CS.labs;
const finish=(l,p)=>{let s=l.initial(p),guard=0;while(!s.done&&guard++<100)s=l.step(s,p);return s;};

test('layer model restores normal and empty messages',()=>{const l=labs['layer-message'];for(const message of ['HI','']){const p=l.validate({message,destination:'B'}),s=finish(l,p);assert.equal(s.done,true);assert.equal(s.failed,false);assert.equal(s.restored,message);assert.equal(s.phase,9);}});
test('layer model stops without a fake received message for unknown destinations',()=>{const l=labs['layer-message'],p=l.validate({message:'HI',destination:'unknown'}),s=finish(l,p);assert.equal(s.failed,true);assert.equal(s.done,true);assert.equal(s.phase,3);assert.equal(s.restored,null);});
test('segment model reorders complete arrivals and recovers a missing part',()=>{const l=labs['segment-order'];let s=l.initial();for(let i=0;i<3;i++)s=l.action(s,'receive');assert.equal(s.complete,true);assert.deepEqual(Array.from(s.received),[2,1,3]);assert.match(l.describe(s),/1 → 2 → 3/);s=l.action(l.initial(),'missing');s=l.action(s,'receive');s=l.action(s,'receive');assert.match(l.describe(s),/빠짐 2번/);s=l.action(s,'retry');s=l.action(s,'receive');assert.equal(s.complete,true);});

test('HTTP model parses URL and returns 200 or 404 by id',()=>{const l=labs['http-library'];for(const [id,status] of [['B01',200],['B99',404]]){const p=l.validate({url:`https://library.example/books?id=${id}`,scenario:'normal'}),s=finish(l,p);assert.equal(p.host,'library.example');assert.equal(p.id,id);assert.equal(s.connected,true);assert.equal(s.status,status);assert.equal(s.done,true);}});
test('HTTP model distinguishes 204 body absence, 500 response and connection failure',()=>{const l=labs['http-library'],url='https://library.example/books?id=B01';for(const [scenario,status,connected,hasBody] of [['empty',204,true,false],['server',500,true,true],['connection',null,false,false]]){const p=l.validate({url,scenario}),s=finish(l,p);assert.equal(s.status,status);assert.equal(s.connected,connected);assert.equal(!!s.body,hasBody);}});
test('HTTP model rejects malformed or out-of-scope URLs before starting',()=>{const l=labs['http-library'];for(const url of ['not a url','https://other.example/books?id=B01','https://library.example/other?id=B01','https://library.example/books'])assert.throws(()=>l.validate({url,scenario:'normal'}));});

test('TLS model completes valid certificate and blocks expired or mismatched certificates',()=>{const l=labs['tls-handshake'];let valid=finish(l,l.validate({certificate:'valid'}));assert.equal(valid.done,true);assert.equal(valid.failed,false);for(const certificate of ['expired','mismatch']){const s=finish(l,l.validate({certificate}));assert.equal(s.done,true);assert.equal(s.failed,true);assert.equal(s.phase,2);}});
test('CH06 lessons include four separate teaching figures each',()=>{const lessonCtx=vm.createContext({CS:ctx.CS});lessonCtx.window=lessonCtx;vm.runInContext(fs.readFileSync(path.join(__dirname,'..','content/ch06.js'),'utf8'),lessonCtx);for(const id of ['ch06-l01','ch06-l02']){const html=lessonCtx.CS.lessons[id].sections.map(s=>s.html||'').join('');assert.equal((html.match(/<figure /g)||[]).length,4);assert.equal(lessonCtx.CS.lessons[id].questions.length,3);}});
