const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const ctx=vm.createContext({structuredClone});ctx.window=ctx;
for(const file of ['src/core.js','src/labs/ch20.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),ctx);
const labs=ctx.CS.labs;
test('asynchronous write can produce a stale follower read',()=>{const l=labs['replica-consistency'],s=l.action(l.initial(),'stale');assert.equal(s.nodes.A.value,'v1');assert.equal(s.lastRead.value,'old');assert.equal(s.lastRead.stale,1);});
test('delivering all pending replicas converges every node',()=>{const l=labs['replica-consistency'];let s=l.action(l.initial(),'async-write');s=l.action(s,'deliver-all');assert.ok(Object.values(s.nodes).every(n=>n.value==='v1'));assert.equal(s.pending.length,0);});
test('network partition blocks delivery until heal and a later delivery',()=>{const l=labs['replica-consistency'];let s=l.action(l.initial(),'async-write');s=l.action(s,'partition-b');s=l.action(s,'deliver-all');assert.equal(s.nodes.B.value,'old');s=l.action(s,'heal-b');s=l.action(s,'deliver-b');assert.equal(s.nodes.B.value,'v1');});
test('synchronous preset acknowledges after two copies',()=>{const l=labs['replica-consistency'],s=l.action(l.initial(),'sync-write');assert.equal(Object.values(s.nodes).filter(n=>n.version===1).length,2);assert.match(s.ack,/과반수/);});
test('read from a missing replica is rejected',()=>{const l=labs['replica-consistency'];assert.throws(()=>l.action(l.initial(),'missing'),/서버 Z/);});
test('leader-only Raft entry stays uncommitted',()=>{const l=labs['raft-quorum'],s=l.action(l.initial(),'propose');assert.equal(s.entries[0].committed,false);assert.equal(s.effects,0);});
test('replication to one follower reaches majority and applies once',()=>{const l=labs['raft-quorum'];let s=l.action(l.initial(),'propose');s=l.action(s,'to-b');assert.equal(s.commitIndex,1);assert.equal(s.effects,1);});
test('same idempotency key does not append or apply twice',()=>{const l=labs['raft-quorum'],s=l.action(l.initial(),'idempotent');assert.equal(s.entries.length,1);assert.equal(s.effects,1);});
test('new token creates a second committed effect',()=>{const l=labs['raft-quorum'],s=l.action(l.initial(),'new-token');assert.equal(s.entries.length,2);assert.equal(s.commitIndex,2);assert.equal(s.effects,2);});
test('B can be elected by B and C after committed leader A is partitioned',()=>{const l=labs['raft-quorum'],s=l.action(l.initial(),'election');assert.equal(s.leader,'B');assert.equal(s.term,2);assert.equal(s.commitIndex,1);});
test('one server cannot commit and mismatched retry is rejected',()=>{const l=labs['raft-quorum'],minor=l.action(l.initial(),'minority');assert.equal(minor.commitIndex,0);assert.throws(()=>l.action(l.initial(),'mismatch'),/다른 요청 내용/);});
test('CH20 lessons include four figures and three questions each',()=>{const lessonCtx=vm.createContext({CS:ctx.CS});lessonCtx.window=lessonCtx;vm.runInContext(fs.readFileSync(path.join(__dirname,'..','content/ch20.js'),'utf8'),lessonCtx);for(const id of ['ch20-l01','ch20-l02']){const lesson=lessonCtx.CS.lessons[id],html=lesson.sections.map(s=>s.html||'').join('');assert.equal((html.match(/<figure /g)||[]).length,4);assert.equal(lesson.sections.length,6);assert.equal(lesson.questions.length,3);assert.ok(lesson.sources.length>=3);}});
