const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const ctx=vm.createContext({structuredClone});ctx.window=ctx;
for(const file of ['src/core.js','src/labs/ch21.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),ctx);
const labs=ctx.CS.labs;
test('baseline capacity overflows forty requests',()=>{const s=labs['scaling-distribution'].initial();assert.equal(s.overflow,40);assert.deepEqual(Array.from(s.loads),[60,60]);});
test('scale-out handles all requests',()=>{const l=labs['scaling-distribution'],s=l.action(l.initial(),'scale-out');assert.equal(s.overflow,0);assert.equal(s.processed,120);});
test('cache offloads half of requests',()=>{const l=labs['scaling-distribution'],s=l.action(l.initial(),'cache');assert.equal(s.cacheServed,60);assert.equal(s.originRequests,60);assert.equal(s.overflow,0);});
test('sticky sessions overload one server despite enough total capacity',()=>{const l=labs['scaling-distribution'],s=l.action(l.initial(),'sticky');assert.equal(s.loads.reduce((a,b)=>a+b,0),120);assert.ok(s.overflow>0);assert.ok(s.config.servers*s.config.capacity>=120);});
test('splitting a hot key removes deterministic skew',()=>{const l=labs['scaling-distribution'];const hot=l.action(l.initial(),'hot'),split=l.action(hot,'split-hot');assert.ok(hot.overflow>0);assert.equal(split.overflow,0);});
test('zero traffic works and zero servers is rejected',()=>{const l=labs['scaling-distribution'];assert.equal(l.action(l.initial(),'zero').processed,0);assert.throws(()=>l.action(l.initial(),'invalid'),/서버 수/);});
test('balanced producer and consumer leave no backlog',()=>{const l=labs['bounded-queue'],s=l.action(l.initial(),'balanced');assert.equal(s.queue,0);assert.equal(s.processed,25);});
test('unbounded overload accumulates twenty five jobs',()=>{const l=labs['bounded-queue'],s=l.action(l.initial(),'overload');assert.equal(s.queue,25);assert.equal(s.rejected,0);});
test('bounded queue caps backlog and exposes rejection',()=>{const l=labs['bounded-queue'],s=l.action(l.initial(),'bounded');assert.ok(s.queue<=10);assert.ok(s.rejected>0);});
test('backpressure delays upstream work without rejection',()=>{const l=labs['bounded-queue'],s=l.action(l.initial(),'backpressure');assert.ok(s.queue<=10);assert.ok(s.delayed>0);assert.equal(s.rejected,0);});
test('consumer expansion drains an overloaded queue and invalid limit is rejected',()=>{const l=labs['bounded-queue'];const overloaded=l.action(l.initial(),'overload'),expanded=l.action(overloaded,'add-consumer');assert.ok(expanded.queue<overloaded.queue);assert.throws(()=>l.action(l.initial(),'invalid'),/큐 한도/);});
test('CH21 lessons include four figures and three questions each',()=>{const lessonCtx=vm.createContext({CS:ctx.CS});lessonCtx.window=lessonCtx;vm.runInContext(fs.readFileSync(path.join(__dirname,'..','content/ch21.js'),'utf8'),lessonCtx);for(const id of ['ch21-l01','ch21-l02']){const lesson=lessonCtx.CS.lessons[id],html=lesson.sections.map(s=>s.html||'').join('');assert.equal((html.match(/<figure /g)||[]).length,4);assert.equal(lesson.sections.length,6);assert.equal(lesson.questions.length,3);assert.ok(lesson.sources.length>=3);}});
