const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const ctx=vm.createContext({structuredClone});ctx.window=ctx;
for(const file of ['src/core.js','src/labs/ch22.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),ctx);
const labs=ctx.CS.labs;
test('tangled notification change affects business storage and notification roles',()=>{const l=labs['module-boundary'],s=l.action(l.initial(),'tangled-sms');assert.equal(s.loan.saved,true);assert.equal(s.notifications[0].channel,'sms');assert.equal(s.affected.length,3);});
test('separated notification change preserves loan and narrows change roles',()=>{const l=labs['module-boundary'],s=l.action(l.initial(),'separated-sms'),t=l.action(l.initial(),'tangled-sms');assert.equal(s.loan.saved,true);assert.equal(s.notifications.length,1);assert.ok(s.affected.length<t.affected.length);});
test('zero subscribers follows explicit no-notification policy',()=>{const l=labs['module-boundary'],s=l.action(l.initial(),'no-subscriber');assert.equal(s.loan.saved,true);assert.equal(s.notifications.length,0);assert.match(s.policy,/구독자 없음/);});
test('direct state mutation is visible and layer violation is rejected',()=>{const l=labs['module-boundary'];assert.throws(()=>l.action(l.initial(),'mutate'),/먼저/);const changed=l.action(l.action(l.initial(),'separated-sms'),'mutate');assert.match(l.describe(changed),/외부에서 변경됨/);assert.throws(()=>l.action(l.initial(),'invalid-layer'),/계층 규칙/);});
test('normal monolith and services produce same business result with different remote boundaries',()=>{const l=labs['architecture-tradeoff'],m=l.action(l.initial(),'mono-normal'),s=l.action(l.initial(),'service-normal');assert.equal(m.order,'완료');assert.equal(s.order,'완료');assert.equal(m.remoteBoundaries,0);assert.equal(s.remoteBoundaries,2);});
test('inventory failure is never reported as order success',()=>{const l=labs['architecture-tradeoff'],s=l.action(l.initial(),'inventory-fail');assert.equal(s.order,'실패');assert.equal(s.inventory,'오류');assert.throws(()=>l.action(s,'false-success'),/성공/);});
test('required notification failure leaves compensation work',()=>{const l=labs['architecture-tradeoff'],s=l.action(l.initial(),'notify-required');assert.equal(s.inventory,'예약됨');assert.equal(s.order,'보상 필요');});
test('best effort notification policy completes core order and schedules retry',()=>{const l=labs['architecture-tradeoff'],s=l.action(l.initial(),'notify-best');assert.equal(s.order,'완료');assert.equal(s.notification,'재시도 대기');});
test('delayed event consumer can recover to a completed result',()=>{const l=labs['architecture-tradeoff'];let s=l.action(l.initial(),'event-delay');assert.equal(s.order,'접수됨');s=l.action(s,'recover');assert.equal(s.order,'완료');assert.equal(s.notification,'전송됨');});
test('recovery without pending notification is rejected',()=>{const l=labs['architecture-tradeoff'];assert.throws(()=>l.action(l.initial(),'recover'),/다시 처리/);});
test('CH22 lessons include four figures and three questions each',()=>{const lessonCtx=vm.createContext({CS:ctx.CS});lessonCtx.window=lessonCtx;vm.runInContext(fs.readFileSync(path.join(__dirname,'..','content/ch22.js'),'utf8'),lessonCtx);for(const id of ['ch22-l01','ch22-l02']){const lesson=lessonCtx.CS.lessons[id],html=lesson.sections.map(s=>s.html||'').join('');assert.equal((html.match(/<figure /g)||[]).length,4);assert.equal(lesson.sections.length,6);assert.equal(lesson.questions.length,3);assert.ok(lesson.sources.length>=3);}});
