const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const ctx=vm.createContext({structuredClone});ctx.window=ctx;
for(const file of ['src/core.js','src/labs/ch24.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),ctx);
const labs=ctx.CS.labs;
test('10 percent canary sends 18 requests to v1 and 2 to failing v2',()=>{const l=labs['canary-deployment'],s=l.action(l.initial(),'run20'),m=ctx.CS.helpers.ch24.deploymentStats(s);assert.equal(s.versions.v1.requests,18);assert.equal(s.versions.v2.requests,2);assert.equal(s.versions.v2.errors,2);assert.equal(m.overall,10);assert.equal(m.v2,100);});
test('zero observations have no rate instead of a false zero percent',()=>{const s=labs['canary-deployment'].initial(),m=ctx.CS.helpers.ch24.deploymentStats(s);assert.equal(m.overall,null);assert.equal(m.v1,null);assert.equal(m.v2,null);});
test('rollback sends every future request to v1 without new errors',()=>{const l=labs['canary-deployment'],before=l.action(l.initial(),'run20'),after=l.action(before,'rollback');assert.equal(after.ratio,0);assert.equal(after.versions.v1.requests,28);assert.equal(after.versions.v2.requests,2);assert.equal(after.versions.v2.errors,2);assert.equal(after.lastBatch.errors,0);});
test('50 percent route deterministically splits ten requests',()=>{const l=labs['canary-deployment'];let s=l.action(l.initial(),'ratio50');s=l.action(s,'ten');assert.equal(s.versions.v1.requests,5);assert.equal(s.versions.v2.requests,5);});
test('invalid deployment percentage is rejected',()=>{const l=labs['canary-deployment'];assert.throws(()=>l.action(l.initial(),'invalid'),/0, 10, 50, 100/);});
test('latency baseline calculates mean 109 and nearest-rank p95 1000',()=>{const s=labs['observability-recovery'].initial(),m=ctx.CS.helpers.ch24.stats(s.latencies);assert.equal(m.count,10);assert.equal(m.mean,109);assert.equal(m.p95,1000);});
test('identical latencies have equal mean and p95',()=>{const l=labs['observability-recovery'],s=l.action(l.initial(),'all-fast'),m=ctx.CS.helpers.ch24.stats(s.latencies);assert.equal(m.mean,10);assert.equal(m.p95,10);});
test('empty latency sample returns no data',()=>{const l=labs['observability-recovery'],s=l.action(l.initial(),'empty'),m=ctx.CS.helpers.ch24.stats(s.latencies);assert.equal(m.count,0);assert.equal(m.mean,null);assert.equal(m.p95,null);assert.equal(m.max,null);});
test('RPO and RTO goals are compared independently with actual values',()=>{const l=labs['observability-recovery'];const strict=l.action(l.initial(),'strict');assert.ok(strict.recovery.loss>strict.recovery.goals.rpo);assert.ok(strict.recovery.duration>strict.recovery.goals.rto);const relaxed=l.action(strict,'relaxed');assert.ok(relaxed.recovery.loss<=relaxed.recovery.goals.rpo);assert.ok(relaxed.recovery.duration<=relaxed.recovery.goals.rto);});
test('contradictory recovery times are rejected',()=>{const l=labs['observability-recovery'];assert.throws(()=>l.action(l.initial(),'contradict'),/백업 시각/);assert.throws(()=>l.action(l.initial(),'bad-recovery'),/복구 시각/);});
test('CH24 lessons include four figures and three questions each',()=>{const lessonCtx=vm.createContext({CS:ctx.CS});lessonCtx.window=lessonCtx;vm.runInContext(fs.readFileSync(path.join(__dirname,'..','content/ch24.js'),'utf8'),lessonCtx);for(const id of ['ch24-l01','ch24-l02']){const lesson=lessonCtx.CS.lessons[id],html=lesson.sections.map(s=>s.html||'').join('');assert.equal((html.match(/<figure /g)||[]).length,4);assert.equal(lesson.sections.length,6);assert.equal(lesson.questions.length,3);assert.ok(lesson.sources.length>=3);}});
